NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "ToggleUnknownBools.pak",
["MOD_AUTHOR"]				= "Mjjstral",
["NMS_VERSION"]				= "2.2+",
["MODIFICATIONS"] 			= 
	{
		{
			["PAK_FILE_SOURCE"] 	= "NMSARC.59B126E2.pak",
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= 
					{
						-- "GCAISPACESHIPGLOBALS.GLOBAL.MBIN",
						-- "GCATLASGLOBALS.GLOBAL.MBIN",
						-- "GCAUDIOGLOBALS.GLOBAL.MBIN",
						-- "GCBUILDINGGLOBALS.GLOBAL.MBIN",
						-- "GCCAMERAGLOBALS.GLOBAL.MBIN",
						-- "GCCHARACTERGLOBALS.GLOBAL.MBIN",
						-- "GCCREATUREGLOBALS.MBIN",
						-- "GCDEBUGOPTIONS.GLOBAL.MBIN",
						-- "GCENVIRONMENTGLOBALS.GLOBAL.MBIN",
						-- "GCFLEETGLOBALS.GLOBAL.MBIN",
						-- "GCGALAXYGLOBALS.GLOBAL.MBIN",
						-- "GCGAMEPLAYGLOBALS.GLOBAL.MBIN",
						-- "GCGRAPHICSGLOBALS.GLOBAL.MBIN",
						-- "GCMULTIPLAYERGLOBALS.GLOBAL.MBIN",
						-- "GCPLACEMENTGLOBALS.MBIN",
						-- "GCPLAYERGLOBALS.GLOBAL.MBIN",
						-- "GCRICHPRESENCEGLOBALS.MBIN",
						-- "GCROBOTGLOBALS.MBIN",
						-- "GCSCENEOPTIONS.GLOBAL.MBIN",
						-- "GCSCRATCHPADGLOBALS.GLOBAL.MBIN",
						-- "GCSIMULATIONGLOBALS.GLOBAL.MBIN",
						-- "GCSKYGLOBALS.GLOBALS.MBIN",
						-- "GCSMOKETESTOPTIONS.GLOBAL.MBIN",
						-- "GCSOLARGENERATIONGLOBALS.GLOBAL.MBIN",
						-- "GCSPACESHIPGLOBALS.GLOBAL.MBIN",
						-- "GCTERRAINGLOBALS.GLOBAL.MBIN",
						"GCUIGLOBALS.GLOBAL.MBIN",
						-- "GCVEHICLEGLOBALS.GLOBAL.MBIN",
						-- "GCWATERGLOBALS.GLOBAL.MBIN",
						
						-- "METADATA\REALITY\TABLES\BASEBUILDINGCOSTSTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\BASEBUILDINGTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\CONSUMABLEITEMTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\COSTTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\DAMAGETABLE.MBIN",
						-- "METADATA\REALITY\TABLES\DISCOVERYREWARDLOOKUPTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\EXPEDITIONEVENTTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\EXPEDITIONREWARDTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\FRIGATETRAITTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\INVENTORYTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\LEGACYBASEBUILDINGTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\LEGACYITEMTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\MAINTENANCEGROUPSTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\PROCEDURALPRODUCTTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\PROCEDURALTECHNOLOGYTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\PURCHASEABLEBUILDINGBLUEPRINTS.MBIN",
						-- "METADATA\REALITY\TABLES\PURCHASEABLESPECIALS.MBIN",
						-- "METADATA\REALITY\TABLES\REWARDTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\TRADINGCLASSDATATABLE.MBIN",
						-- "METADATA\REALITY\TABLES\TRADINGCOSTTABLE.MBIN",
						-- "METADATA\REALITY\TABLES\UNLOCKABLEITEMTREES.MBIN",
						-- "METADATA\SIMULATION\AMBIENT\AMBIENTMODECAMERAS.MBIN",
						-- "METADATA\SIMULATION\ECOSYSTEM\CREATUREAUDIOTABLE.MBIN",
						-- "METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN",
						-- "METADATA\SIMULATION\ECOSYSTEM\CREATUREFILENAMETABLE.MBIN",
						-- "METADATA\SIMULATION\ECOSYSTEM\CREATUREROLEDESCRIPTIONTABLE.MBIN",
						-- "METADATA\SIMULATION\ECOSYSTEM\DEPRECATEDASSETSTABLE.MBIN",
						-- "METADATA\SIMULATION\ECOSYSTEM\ROBOTDATATABLE.MBIN",
					},
					["REGEXBEFORE"] 		= 
					{ 
						{ [[((.*Unknown.*)(True))|((True)(.*Unknown.*))]], 		[[\2UNIQUE_PLACEHOLDER\6]] }, 
						{ [[((.*Unknown.*)(False))|((False)(.*Unknown.*))]], 	[[\2True\6]] },
						{ [[((.*Unknown.*)(UNIQUE_PLACEHOLDER))|((UNIQUE_PLACEHOLDER)(.*Unknown.*))]], 		[[\2False\6]] }, 
					}
				}
			}
		}
	}	
}