NORMAL = "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.OVERLAY.NORMALX.DDS"
DIFFUSEP2 = "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.PAINT2.PAINTEDX.DDS"
DIFFUSEP1X = "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.PAINT1X.DDS"

NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"]	= "_hF_FreighterRetexture_0.6.pak",
["MOD_AUTHOR"]		= "hemis FEAR",
["LUA_AUTHOR"]		= "Lowkie",
["NMS_VERSION"]		= "0.6",
["MOD_DESCRIPTION"]	= "Fixes the chipped paint look of the Freighter",
["MODIFICATIONS"]	= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.TEXTURE.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name", "PAINT2", "Name", "PAINTED"},
							--["PRECEDING_KEY_WORDS"]	= {"PAINTED"},
							["VALUE_CHANGE_TABLE"]	= {
								{ "Diffuse", DIFFUSEP2 }, --Original "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.PAINT2.PAINTED.DDS"
								{ "Normal",  NORMAL }, --Original "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.OVERLAY.NORMAL.DDS"								
							}
						},
						{								
							["SPECIAL_KEY_WORDS"] = {"Name", "PAINT2", "Name", "UNPAINTED"},
							["VALUE_CHANGE_TABLE"]	= {
								{ "Normal",  NORMAL }, --Original "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.OVERLAY.NORMAL.DDS"								
							}
						},
						{
							["SPECIAL_KEY_WORDS"]	= {"Name", "PAINT1"},
							["VALUE_CHANGE_TABLE"]	= {
								{ "Diffuse", DIFFUSEP1X }, --Original "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.PAINT1X.DDS"
								{ "Normal",  NORMAL }, --Original "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.OVERLAY.NORMAL.DDS"								
							}
						},
						{		
							["SPECIAL_KEY_WORDS"] = {"Name", "BASE", "Name", "PAINTED"},						
							["PRECEDING_KEY_WORDS"]	= {"PAINTED"},
							["VALUE_CHANGE_TABLE"]	= {
								{ "Normal",  NORMAL }, --Original "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.OVERLAY.NORMAL.DDS"								
							}
						},
						{								
							["SPECIAL_KEY_WORDS"] = {"Name", "BASE", "Name", "UNPAINTED"},
							["VALUE_CHANGE_TABLE"]	= {
								{ "Normal",  NORMAL }, --Original "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.OVERLAY.NORMAL.DDS"								
							}
						},
					}
				}
			}
		}
	}	
}	
