BONUSOBJECTS_DENSITY_MULTIPLIER = 1/5 --We're decreasing density so make this a fraction
BONUSOBJECTS_COVERAGE_MULTIPLIER = 1/5 --We're decreasing density so make this a fraction
IMPOSTER_RADIUS_MULTIPLIER = 500
GLOBAL_MINSCALE_MULTIPLIER = 1
GLOBAL_MAXSCALE_MULTIPLIER = 1
LANDMARKS_MAXSCALE_MULTIPLIER = 1.5
GRASS_MINSCALE_MULTIPLIER = 1.25
GRASS_MAXSCALE_MULTIPLIER = 1.25
GRASS_DENSITY_MULTIPLIER = GRASS_MINSCALE_MULTIPLIER
OGTREES_FADE_OUT_RADIUS_MULTIPLIER = 2
FLOWERY_SCALE_MULTIPLIER = 1.1
FLOWERY_DENSITY_MULTIPLIER = 4
FLOWERY_COVERAGE_MULTIPLIER = 0.75
DISTANTOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DISTANTOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="0.1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGELUSH/DISTANTOBJECTS/HUGEOGLUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGELUSH/DISTANTOBJECTS/HUGELUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGERING/DISTANTOBJECTS/HUGERINGOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEROCK/DISTANTOBJECTS/HUGEROCKOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/DISTANTOBJECTS/SWAMPOBJECTSFULL.MBIN" />
		</Property>
	  </Property>
	</Property>]]
LANDMARKS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="LANDMARKS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGELUSH/LANDMARKS/HUGELUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGELUSH/LANDMARKS/HUGEOGLUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/ALPINEHQOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/ALPINEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/ALPINEOBJECTSFULLTINYDENSE.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/ALPINEOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/ALPINEOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHBIGPROPSOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHBUBBLEOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHHQTENTACLEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHINFESTEDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHOBJECTSFULLTINYDENSE.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHROCKYOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHROCKYWEIRDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHROOMAOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/LUSHROOMBOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/OGLUSHHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/OGLUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/OGLUSHOBJECTSFULLTINYDENSE.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/OGLUSHOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/OGLUSHOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/TREELODALPINEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LANDMARKS/TREELODLUSHOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/LANDMARKS/SWAMPOBJECTSFULL.MBIN" />
		</Property>
	  </Property>
	</Property>]]
OBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="OBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGELUSH/OBJECTS/HUGELUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGERING/OBJECTS/HUGERINGOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/ALPINEOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/ALPINEOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/ALPINEOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/ALPINEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHOBJECTSLOWWEIRDMEDIUMBUSH.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHOBJECTSMIDWEIRDMEDIUMBUSH.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHOBJECTSFULLWEIRDMEDIUMBUSH.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHHQOBJECTSFULLWEIRDMEDIUMBUSH.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/ALPINEHQOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHBIGPROPSOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHBUBBLEOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHHQTENTACLEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHINFESTEDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHROCKYOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHROCKYWEIRDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHROOMAOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/OBJECTS/LUSHROOMBOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/OBJECTS/SWAMPOBJECTSFULL.MBIN" />
		</Property>
	  </Property>
	</Property>]]
DETAILOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DETAILOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGELUSH/DETAILOBJECTS/HUGELUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGERING/DETAILOBJECTS/HUGERINGOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/ALPINEHQOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/ALPINEOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/ALPINEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/ALPINEOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/ALPINEOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/FLOWERYLUSHHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/FLOWERYLUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/LUSHHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/LUSHOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/LUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/LUSHOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/LUSHOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/DETAILOBJECTS/SWAMPOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HYDROGARDEN/DETAILOBJECTS/HYDROGARDENOBJECTSDEAD.MBIN" />
		</Property>
	  </Property>
	</Property>]]
GRASS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="GRASS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/NEWLUSHGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/NEWCROSSGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/BUBBLELUSHGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/TALLNEWLUSHGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/TALLNEWCROSSGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/TALLBUBBLELUSHGRASS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
NMS_MOD_DEFINITION_CONTAINER = --WARNING: Most, if not all, biomes in this mod are co-dependent (They use object lists generated by other biomes). These scripts won't work unless all of them are used together.
{
["MOD_FILENAME"] 			= "_CodenameAwesome.MishMashBiomes-LUSH.pak",
["MOD_AUTHOR"]				= "CodenameAwesome",
["NMS_VERSION"]				= "",
["MODIFICATIONS"] 			=
	{
		{
			["MBIN_CHANGE_TABLE"] 	=
				{
					{-- ~~LUSH BIOME~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHHQOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHHQOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSDEAD.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSLOW.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSMID.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSDEAD.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSLOW.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSMID.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEHQOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEHQOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEHQOBJECTSMID.MBIN","REMOVE"},
							--ORIGINS Files
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\SWAMPOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\DISTANTOBJECTS\SWAMPOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\SWAMPOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\LANDMARKS\SWAMPOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIGPROPSOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHBIGPROPSOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLEOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHBUBBLEOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQTENTACLEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHHQTENTACLEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHINFESTEDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHINFESTEDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYWEIRDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMAOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROOMAOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROOMBOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\SWAMPOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\OBJECTS\SWAMPOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\SWAMPOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\DETAILOBJECTS\SWAMPOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIGPROPSOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHBIGPROPSOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLEOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHBUBBLEOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQTENTACLEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHHQTENTACLEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHINFESTEDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHINFESTEDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYWEIRDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMAOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHROOMAOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHROOMBOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIGPROPSOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHBIGPROPSOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLEOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHBUBBLEOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQTENTACLEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQTENTACLEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHINFESTEDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHINFESTEDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYWEIRDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMAOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROOMAOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROOMBOBJECTS.MBIN"},
						},
					},
					-- Remove any irrelevant parts of these files
					{--Fix up Landmarks files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\LANDMARKS\SWAMPOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHBIGPROPSOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHBUBBLEOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHHQTENTACLEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHINFESTEDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROCKYWEIRDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROOMAOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROOMBOBJECTS.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Landmarks
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks & Big things
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								  { "MaxScale", LANDMARKS_MAXSCALE_MULTIPLIER },
								},
							},
						},
					},
					{--Fix up Objects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\OBJECTS\SWAMPOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHBIGPROPSOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHBUBBLEOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHHQTENTACLEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHINFESTEDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHROCKYWEIRDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHROOMAOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHROOMBOBJECTS.MBIN",
						},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Big Things
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MinScale", GLOBAL_MINSCALE_MULTIPLIER },
								  { "MaxScale", GLOBAL_MAXSCALE_MULTIPLIER },
								},
							},
							{--Increasing the imposter radius of objects

								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								},
							},
						},
					},
					{--Fix up DetailObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\DETAILOBJECTS\SWAMPOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHBIGPROPSOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHBUBBLEOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQTENTACLEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHINFESTEDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROCKYWEIRDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROOMAOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROOMBOBJECTS.MBIN",
						},

						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							},
						},
					},--[[Commenting this out. This decision kind of muddies the water unfortunately but now non-Huge biomes have DistantObjects which I'm treating as part of the Landmarks.
					{--Remove DistantObjects from Landmarks files that have them
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\LANDMARKS\SWAMPOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\OBJECTS\SWAMPOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\DETAILOBJECTS\SWAMPOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHBIGPROPSOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHBIGPROPSOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHBIGPROPSOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Landmarks
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DistantObjects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							}
						},
					},]]
					--GRASS
					--I want to handle grass entirely separately
					{
						["MBIN_FILE_SOURCE"] = {
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWLUSHGRASS.MBIN"},
						},
					},
					{
						["MBIN_FILE_SOURCE"] = {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWLUSHGRASS.MBIN"
						},
						["EXML_CHANGE_TABLE"] = {
							--[[{--(1) Save grass to a variable
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWLUSHGRASS.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["SAVE_SECTION_TO"] = "NEWLUSHGRASS",
								["REMOVE"] = "SECTION",
							},
							{--(2) Delete all objects in the object list
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["REMOVE"] = "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
							{--(3) Add the grass back in
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects"},
								["USE_SECTION"] = "NEWLUSHGRASS",
							},]]-- This feature isn't fully implemented yet so I'm going to be doing it the hard way for now. Eventually I'll need to switch back to ensure future-proofing.
							{--temp
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SMALLROCK.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["REMOVE"] = "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
							{--temp
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/HQLUSH/SMALLPROPS/SMALLROCK.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["REMOVE"] = "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
							{--temp
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/HQLUSH/SMALLPROPS/SMALLBOULDER.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["REMOVE"] = "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
							{--temp
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/FLOWERS/BUTTERCUP.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["REMOVE"] = "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
							{--temp
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/FLOWERS/SCABIOUS.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["REMOVE"] = "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
							{--temp
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/PLANTS/FERN.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["REMOVE"] = "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
							{--temp
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/FLOWERS/YARROW.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["REMOVE"] = "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
						},
					},
					{
						["MBIN_FILE_SOURCE"] = {
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWLUSHGRASS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWCROSSGRASS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWLUSHGRASS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\SCRUBGRASS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWLUSHGRASS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\BUBBLELUSHGRASS.MBIN"},
						},
					},
					{
						["MBIN_FILE_SOURCE"] = {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWCROSSGRASS.MBIN"
						},
						["EXML_CHANGE_TABLE"] = {
							{
								["REPLACE_TYPE"] = "ALL",
								["VALUE_CHANGE_TABLE"] = {
									{"Filename","MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWCROSSGRASS.SCENE.MBIN"},
								},
							},
						},
					},
					{
						["MBIN_FILE_SOURCE"] = {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\SCRUBGRASS.MBIN"
						},
						["EXML_CHANGE_TABLE"] = {
							{
								["REPLACE_TYPE"] = "ALL",
								["VALUE_CHANGE_TABLE"] = {
									{"Filename","MODELS/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS_MATCHGROUND.SCENE.MBIN"},
								},
							},
							{--It seems that the scrubgrass model is skinnier than the usual grass so let's increase the density to make sure it's not too patchy
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "FlatDensity", 1.5 },
								  { "SlopeDensity", 1.5 },
								},
							},
						},
					},
					{
						["MBIN_FILE_SOURCE"] = {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\BUBBLELUSHGRASS.MBIN"
						},
						["EXML_CHANGE_TABLE"] = {
							{
								["REPLACE_TYPE"] = "ALL",
								["VALUE_CHANGE_TABLE"] = {
									{"Filename","MODELS/PLANETS/BIOMES/COMMON/GRASS/BUBBLELUSHGRASS.SCENE.MBIN"},
								},
							},
							{--It seems that the scrubgrass model is skinnier than the usual grass so let's increase the density to make sure it's not too patchy
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "FlatDensity", 1.5 },
								  { "SlopeDensity", 1.5 },
								},
							},
						},
					},
					{--Tall Grass
						["MBIN_FILE_SOURCE"] = {
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWLUSHGRASS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\TALLNEWLUSHGRASS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\NEWCROSSGRASS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\TALLNEWCROSSGRASS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\SCRUBGRASS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\TALLSCRUBGRASS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\BUBBLELUSHGRASS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\TALLBUBBLELUSHGRASS.MBIN"},
						},
					},
					{--Tall Grass
						["MBIN_FILE_SOURCE"] = {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\TALLNEWLUSHGRASS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\TALLNEWCROSSGRASS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\TALLSCRUBGRASS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\GRASS\TALLBUBBLELUSHGRASS.MBIN"
						},
						["EXML_CHANGE_TABLE"] = {
							{--Scale
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MinScale", 2 },
								  { "MaxScale", 2 },
								  { "FlatDensity", 1/2 },
								  { "SlopeDensity", 1/2 },
								},
							},
						},
					},
					{--Delete grass from existing files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHBIGPROPSOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQTENTACLEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROCKYWEIRDOBJECTS.MBIN",
						},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWCROSSGRASS.SCENE.MBIN",},
								["SECTION_UP"] = 1,
								["REMOVE"] 	= "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
						},
					},
					{--Delete grass from existing files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHINFESTEDOBJECTS.MBIN",
						},

						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWLUSHGRASS.SCENE.MBIN",},
								["SECTION_UP"] = 1,
								["REMOVE"] 	= "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
						},
					},
					{--Delete grass from existing files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHBUBBLEOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROOMAOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHROOMBOBJECTS.MBIN",
						},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/GRASS/BUBBLELUSHGRASS.SCENE.MBIN",},
								["SECTION_UP"] = 1,
								["REMOVE"] 	= "SECTION",
								["REPLACE_TYPE"] = "ALL"
							},
						},
					},
					{--OG TREES
						["MBIN_FILE_SOURCE"] 	= { --First create the object lists
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHHQOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSMID.MBIN"},
							},
					},
					{--Now replace the model and increase the scale by x1.5 because the old models were just smaller
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSMID.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Replace the new model with the old one
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]],[["MODELS/PLANETS/BIOMES/COMMON/TREES/MEDIUMTREE1.SCENE.MBIN"]] },
								},
							},
							{--Scale
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MinScale", 1.5 },
								  { "MaxScale", 1.5 },
								},
							},
						},
					},
					{--LARGETREE1 TREES
						["MBIN_FILE_SOURCE"] 	= { --First create the object lists
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LARGETREE1LUSHHQOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LARGETREE1LUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LARGETREE1LUSHOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LARGETREE1LUSHOBJECTSMID.MBIN"},
							},
					},
					{--Now replace the model
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LARGETREE1LUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LARGETREE1LUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LARGETREE1LUSHOBJECTSMID.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Replace the new model with the old one
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [["MODELS/PLANETS/BIOMES/COMMON/TREES/MEDIUMTREE1.SCENE.MBIN"]],[["MODELS/PLANETS/BIOMES/COMMON/TREES/LARGETREE1.SCENE.MBIN"]] },
								},
							},
						},
					},
					{--Copy for Flowery detailobjects
						["MBIN_FILE_SOURCE"] 	= {
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\FLOWERYLUSHHQOBJECTSFULL.MBIN"},
						},
					},
					{--Flowery detailobjects HQ
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\FLOWERYLUSHHQOBJECTSFULL.MBIN"
						},
						["EXML_CHANGE_TABLE"] 	= --Double the COVERAGE value of the flowers
						{
							{
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/FLOWERS/BUTTERCUP.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "Coverage", FLOWERY_COVERAGE_MULTIPLIER },
								  { "FlatDensity", FLOWERY_DENSITY_MULTIPLIER },
								  { "SlopeDensity", FLOWERY_DENSITY_MULTIPLIER },
								  { "MaxScale", FLOWERY_SCALE_MULTIPLIER },
								  { "MinScale", FLOWERY_SCALE_MULTIPLIER },
								  { "MaxScale", FLOWERY_SCALE_MULTIPLIER },
								},
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/FLOWERS/SCABIOUS.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "Coverage", FLOWERY_COVERAGE_MULTIPLIER },
								  { "FlatDensity", FLOWERY_DENSITY_MULTIPLIER },
								  { "SlopeDensity", FLOWERY_DENSITY_MULTIPLIER },
								  { "MaxScale", FLOWERY_SCALE_MULTIPLIER },
								  { "MinScale", FLOWERY_SCALE_MULTIPLIER },
								  { "MaxScale", FLOWERY_SCALE_MULTIPLIER },
								},
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/COMMON/FLOWERS/YARROW.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "Coverage", FLOWERY_COVERAGE_MULTIPLIER },
								  { "FlatDensity", FLOWERY_DENSITY_MULTIPLIER },
								  { "SlopeDensity", FLOWERY_DENSITY_MULTIPLIER },
								  { "MaxScale", FLOWERY_SCALE_MULTIPLIER },
								  { "MinScale", FLOWERY_SCALE_MULTIPLIER },
								  { "MaxScale", FLOWERY_SCALE_MULTIPLIER },
								},
							},
						},
					},
					{--Replace models in Alpine Objects
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEOBJECTSMID.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Replace the new model with the old one
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [[/FROZEN/]],[[/HQALPINE/]] },
								},
							},
						},
					},
					{--Replace models in AlpineHQ Objects
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\ALPINEHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\ALPINEHQOBJECTSMID.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Replace the new model with the old one
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [[/HQFROZEN/]],[[/HQALPINE/HQ/]] },
								},
							},
						},
					},
					{--TREELOD TREES
						["MBIN_FILE_SOURCE"] 	= { --First create the object lists
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\TREELODLUSHOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\TREELODALPINEOBJECTSFULL.MBIN"},
							},
					},
					{
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\TREELODLUSHOBJECTSLOW.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Replace the new model with the old one
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]],[["MODELS/PLANETS/BIOMES/COMMON/TREES/TREELOD.SCENE.MBIN"]] },
								},
							},
							{--Scale & Density
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxScale", 1.25 },
								  { "SlopeDensity", 0.9 },
								  { "FlatDensity", 0.9 },
								},
							},
						},
					},
					{--The original object list here have been scaled by 1.5 so there's no need here
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\TREELODALPINEOBJECTSFULL.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Replace the new model with the old one
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [["MODELS/PLANETS/BIOMES/HQALPINE/LARGEPROPS/LARGETREE.SCENE.MBIN"]],[["MODELS/PLANETS/BIOMES/COMMON/TREES/TREELOD.SCENE.MBIN"]] },
								},
							},
						},
					},
					{-- ~~TINYDENSE ~~
						["MBIN_FILE_SOURCE"] 	= {
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSFULLTINYDENSE.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSFULLTINYDENSE.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSFULLTINYDENSE.MBIN"},
						},
					},
					{-- Tiny dense trees
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSFULLTINYDENSE.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSFULLTINYDENSE.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSFULLTINYDENSE.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Landmarks
						{
							{--Tiny Things
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MinScale", 1/2 },
								  { "MaxScale", 1/2 },
								  { "Coverage", 1/2 },
								  { "FlatDensity", 2},
								  { "SlopeDensity", 2},
								},
							},
						},
					},
					{-- Hydro WEIRDMEDIUMBUSH - Create the object lists
						["MBIN_FILE_SOURCE"] 	= { --First create the object lists
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHHQOBJECTSFULLWEIRDMEDIUMBUSH.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSFULLWEIRDMEDIUMBUSH.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSLOWWEIRDMEDIUMBUSH.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSMIDWEIRDMEDIUMBUSH.MBIN"},
						},
					},
					{-- Hydro WEIRDMEDIUMBUSH - swap the model
						["MBIN_FILE_SOURCE"] 	= { --First create the object lists
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHHQOBJECTSFULLWEIRDMEDIUMBUSH.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSFULLWEIRDMEDIUMBUSH.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSLOWWEIRDMEDIUMBUSH.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\OBJECTS\LUSHOBJECTSMIDWEIRDMEDIUMBUSH.MBIN"
						},
						["EXML_CHANGE_TABLE"] = {
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [[MODELS/PLANETS/BIOMES/COMMON/PLANTS/MEDIUMBUSH.SCENE.MBIN]],[[MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/WEIRDMEDIUMBUSH.SCENE.MBIN]] },
								},
							},
							{ --Tweak the distribution a bit
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/WEIRDMEDIUMBUSH.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{"FlatDensity", 1/4},
									{"SlopeDensity", 1/4},
									{"MaxScale", 1.5},
								},
							},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\OGLUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\OGLUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\ALPINEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\ALPINEHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\ALPINEHQOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\LANDMARKS\SWAMPOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\SWAMPOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHHQTENTACLEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHHQTENTACLEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHINFESTEDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHINFESTEDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROCKYOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROCKYWEIRDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROOMAOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROOMAOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROOMBOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROOMBOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\LANDMARKS\SWAMPOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\SWAMPOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHBIGPROPSOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHBIGPROPSOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHBUBBLEOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHBUBBLEOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHHQTENTACLEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHHQTENTACLEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHINFESTEDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHINFESTEDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROCKYOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROCKYWEIRDOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROOMAOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROOMAOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LANDMARKS\LUSHROOMBOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROOMBOBJECTS.MBIN"},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\OGLUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\ALPINEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\ALPINEHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\SWAMPOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHHQTENTACLEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHINFESTEDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROCKYWEIRDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROOMAOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\LUSHROOMBOBJECTS.MBIN",
						},
						["EXML_CHANGE_TABLE"] =
						{
							{--Increasing the imposter radius of Landmarks & Big things & Drastically decrease density
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["MATH_OPERATION"] 		= "*",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "FlatDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "SlopeDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "Coverage", BONUSOBJECTS_COVERAGE_MULTIPLIER},
								},
							},
						},
					},
					{--Create Mish Mash LUSH Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME.MBIN","REMOVE"},},
					},
					{--Update Object Lists
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{--Make storms less frequent
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{"Clear",	"1"},
								},
							},
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"

							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = GRASS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = LANDMARKS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},--Adding these now but with a low chance.
								["ADD"] = DISTANTOBJECTS,
							},
							{--Remove the original object lists
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"
							},
							{--Remove the original object lists
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN_ULTRA"},
								["REMOVE"] = "SECTION"
							},
						},
					},
					{--Create a copies that use custom palettes
						["MBIN_FILE_SOURCE"] 	= {
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-HQPALETTE.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-ULTRAPALETTE.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-LUSHROOMAPALETTE.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-LUSHROOMBPALETTE.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-LUSHBUBBLESPALETTE.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-SWAMPPALETTE.MBIN"},
						},
					},
					{
						["MBIN_FILE_SOURCE"] 	= "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-HQPALETTE.MBIN",
						["EXML_CHANGE_TABLE"]	=
						{
							{
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ "ColourPaletteFile",	"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQCOLOURPALETTE.MBIN" },
								},
							},
						},
					},
					{
						["MBIN_FILE_SOURCE"] 	= "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-ULTRAPALETTE.MBIN",
						["EXML_CHANGE_TABLE"]	=
						{
							{
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ "ColourPaletteFile",	"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHULTRACOLOURPALETTES.MBIN" },
								},
							},
						},
					},
					{
						["MBIN_FILE_SOURCE"] 	= "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-LUSHROOMAPALETTE.MBIN",
						["EXML_CHANGE_TABLE"]	=
						{
							{
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ "ColourPaletteFile",	"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMACOLOURPALETTE.MBIN" },
								},
							},
						},
					},
					{
						["MBIN_FILE_SOURCE"] 	= "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-LUSHROOMBPALETTE.MBIN",
						["EXML_CHANGE_TABLE"]	=
						{
							{
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ "ColourPaletteFile",	"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBCOLOURPALETTE.MBIN" },
								},
							},
						},
					},
					{
						["MBIN_FILE_SOURCE"] 	= "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-LUSHBUBBLESPALETTE.MBIN",
						["EXML_CHANGE_TABLE"]	=
						{
							{
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ "ColourPaletteFile",	"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLESCOLOURPALETTE.MBIN" },
								},
							},
						},
					},
					{
						["MBIN_FILE_SOURCE"] 	= "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\MISHMASHLUSHBIOME-SWAMPPALETTE.MBIN",
						["EXML_CHANGE_TABLE"]	=
						{
							{
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ "ColourPaletteFile",	"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\SWAMPCOLOURPALETTES.MBIN" },
								},
							},
						},
					},
					{-- ~~HUGELUSH BIOME~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects). There's no Landmarks in Huge Biomes so just 3 folders.
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\DISTANTOBJECTS\HUGELUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\HUGERINGOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\DISTANTOBJECTS\HUGERINGOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\LANDMARKS\HUGELUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\OBJECTS\HUGELUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\HUGERINGOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\OBJECTS\HUGERINGOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\DETAILOBJECTS\HUGELUSHOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\HUGERINGOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\DETAILOBJECTS\HUGERINGOBJECTSFULL.MBIN","REMOVE"},
						},
					},
					-- Remove any irrelevant parts of these files
					{--Fix up DistantObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\DISTANTOBJECTS\SWAMPOBJECTSFULL.MBIN",--Not adding the biglushobjects because i already made a better one
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\DISTANTOBJECTS\HUGELUSHOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DistantObjects. No need to remove Landmarks because there aren't any.
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks

								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								},
							},
						},
					},
					{--Fix up DistantObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\DISTANTOBJECTS\HUGERINGOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DistantObjects. No need to remove Landmarks because there aren't any.
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius

								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								},
							},
						},
					},
					{--Fix up Landmark files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\LANDMARKS\HUGELUSHOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Landmarks. No need to remove Landmarks because there aren't any.
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DistantObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks

								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								},
							},
						},
					},
					{--Replace the trees for variety
						["MBIN_FILE_SOURCE"] = {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\DISTANTOBJECTS\HUGELUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\LANDMARKS\HUGELUSHOBJECTSFULL.MBIN"
						},
						["EXML_CHANGE_TABLE"] =
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE17.SCENE.MBIN"]],	[["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE10.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE21.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE63.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HUGEPROPS/HUGERING/HUGERINGTREE.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]] },
								},
							},
						},
					},
					{--HUGE OG TREES
						["MBIN_FILE_SOURCE"] 	= { --First create the object lists
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\DISTANTOBJECTS\HUGELUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\DISTANTOBJECTS\HUGEOGLUSHOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\LANDMARKS\HUGELUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\LANDMARKS\HUGEOGLUSHOBJECTSFULL.MBIN"},
							},
					},
					{--Now replace the model and increase the scale by x1.5 because the old models were just smaller
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\DISTANTOBJECTS\HUGEOGLUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\LANDMARKS\HUGEOGLUSHOBJECTSFULL.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Replace the new model with the old one
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	=
								{
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]],[["MODELS/PLANETS/BIOMES/COMMON/TREES/MEDIUMTREE1.SCENE.MBIN"]] },
								},
							},
							{--Scale up and fix the LOD distance because holy shit it's bad
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxRegionRadius", OGTREES_FADE_OUT_RADIUS_MULTIPLIER },
								  { "MinScale", 2 },
								  { "MaxScale", 2 },
								},
							},
						},
					},
					{--Fix up Objects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\OBJECTS\HUGELUSHOBJECTSFULL.MBIN",
						},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DistantObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks

								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								},
							},
						},
					},
					{--Fix up Objects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\OBJECTS\HUGERINGOBJECTSFULL.MBIN"
						},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DistantObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks

								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								},
							},
						},
					},
					{--Fix up DetailObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\DETAILOBJECTS\HUGELUSHOBJECTSFULL.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DistantObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							},
						},
					},
					{--Fix up DetailObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\DETAILOBJECTS\HUGERINGOBJECTSFULL.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DistantObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\DISTANTOBJECTS\HUGERINGOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGERINGOBJECTSFULL.MBIN"},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGERINGOBJECTSFULL.MBIN",
						},
						["EXML_CHANGE_TABLE"] =
						{
							{--Increasing the imposter radius of Landmarks & Big things & Drastically decrease density
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["MATH_OPERATION"] 		= "*",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	=
								{
								  { "FlatDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "SlopeDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "Coverage", BONUSOBJECTS_COVERAGE_MULTIPLIER},
								},
							},
						},
					},
					{--Create Mish Mash Huge Lush Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\MISHMASHHUGELUSHBIOME.MBIN","REMOVE"},},
					},
					{--Update Object Lists
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\MISHMASHHUGELUSHBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"

							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"

							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = GRASS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = LANDMARKS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DISTANTOBJECTS,
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","DISTANTOBJECTS"},
								["VALUE_CHANGE_TABLE"] = {
									{"Probability", 1}
								}
							},
						},
					},
				},
		},
	},
}

--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE
