--see also StandardSchemeExtended.lua

NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] 			= "zzAssets-Defrosted.pak",     --the name of the pak created (if not combined) - REQUIRED
  ["MOD_DESCRIPTION"]		= "",         --optional, for reference
  ["MOD_AUTHOR"]				= "",         --optional, for reference
  ["NMS_VERSION"]				= "2.0",     --optional, for reference
  ["MODIFICATIONS"] 		=             --REQUIRED SECTION
	{
		{
			["MBIN_CHANGE_TABLE"] = 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= {
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.ANIM.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE.ANIM.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\FROZENLARGETREE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\FROZENLEAF1_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\ICE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\ICE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\IMPOSTER_IMPOSTERMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\IMPOSTER_IMPOSTERMAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\LAMBERT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\LAMBERT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\LARGETILINGROCK_A.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\LARGETILINGROCK_A.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\MEDIUMPLANT_FROZENLARGETREE_MAT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\MEDIUMPLANT_FROZENLARGETREE_MAT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\SMALLPLANT_FROZENLEAF1_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\SMALLPLANT_FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\SMOOTHROCKTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\SMOOTHROCKTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\ENTITIES\_LARGEROCK_A.ENTITY.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\ENTITIES\_LARGEROCK_A.ENTITY.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\BARK1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\BILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENLARGETREE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\IMPOSTERMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\IMPOSTERMAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\LAMBERT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\LAMBERT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_A2.ENTITY.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_A2.ENTITY.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_C.ENTITY.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_C.ENTITY.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_C2.ENTITY.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_C2.ENTITY.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\FROZENLARGETREE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\HANGINGICESOLID_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\HANGINGICESOLID_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\HANGINGICE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\HANGINGICE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\IMPOSTERMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\IMPOSTERMAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\LAMBERT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\LAMBERT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\SNOWTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\ICE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS\ICE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\SNOWTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\BARK2.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\BARK2.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\FROND2.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\FROND2.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\FROZENLARGETREE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\IMPOSTERMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\IMPOSTERMAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\LAMBERT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\LAMBERT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\ENTITIES\_MEDPLANT_D.ENTITY.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\ENTITIES\_MEDPLANT_D.ENTITY.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\FLATROCKS_SNOWTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\FLATROCKS_SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENLARGETREE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENLEAF1_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENMEDROCK_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\FROZENMEDROCK_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\LAMBERT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\LAMBERT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\LARGEROCKS_FROZENLEAF1_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\LARGEROCKS_FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\ROCKTEMPLATWE_SMOOTHROCKTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\ROCKTEMPLATWE_SMOOTHROCKTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLICEFORMATION.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLICEFORMATION.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLICEFORMATION.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLICEFORMATION.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SNOWFRAGMENTS.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SNOWFRAGMENTS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SNOWFRAGMENTS.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS.SCENE.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SNOWFRAGMENTS.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION\ICEFORMATION_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLICEFORMATION\ICEFORMATION_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\FLOWERHEAD_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT\FLOWERHEAD_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\LAMBERT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT\LAMBERT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\LEAVESB_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT\LEAVESB_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\LEAVES_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT\LEAVES_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\MEDIUMPLANT_FROZENLARGETREE_MAT2.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT\MEDIUMPLANT_FROZENLARGETREE_MAT2.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\ENTITIES\_SMALLPLANT_A.ENTITY.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT\ENTITIES\_SMALLPLANT_A.ENTITY.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\ICE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\ICE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\LAMBERT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\LAMBERT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\ROCKBASE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\ROCKBASE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\SNOWTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\TILINGROCKFROZEN_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\TILINGROCKFROZEN_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKBASE_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKBASE_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKS_SNOWTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKS_SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS\SNOWTILING_MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS\TINYSLATEMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SNOWFRAGMENTS\TINYSLATEMAT.MATERIAL.MBIN","REMOVE"},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLICEFORMATION.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SNOWFRAGMENTS.SCENE.MBIN",
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] 		= "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ [[\FROZEN\]],[[\HQALPINE\]] }
							}
						}
					}
				},
				{--Delete icicle and snow geometry from trees
					["MBIN_FILE_SOURCE"] 	= {
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE.SCENE.MBIN"
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Value","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\HANGINGICE_MAT.MATERIAL.MBIN"},
							["SECTION_UP"] = 2,
							["REMOVE"] = "SECTION"
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Value","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\HANGINGICESOLID_MAT.MATERIAL.MBIN"},
							["SECTION_UP"] = 2,
							["REMOVE"] = "SECTION"
						}
					}
				},
				{--Delete icicle and snow geometry from trees
					["MBIN_FILE_SOURCE"] 	= {
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE.SCENE.MBIN"
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Value","MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN"},
							["SECTION_UP"] = 2,
							["REMOVE"] = "SECTION"
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\FROZENLARGETREE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\FROZENLEAF1_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\ICE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\LARGETILINGROCK_A.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\MEDIUMPLANT_FROZENLARGETREE_MAT1.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\SMALLPLANT_FROZENLEAF1_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGEROCKS\SMOOTHROCKTILING_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\BARK1.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\BILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\FROZENLARGETREE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\FROZENLARGETREE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\HANGINGICESOLID_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\HANGINGICE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\LARGEPROPS\LARGETREEBARE\SNOWTILING_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS\ICE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMICEDRIFTS\SNOWTILING_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\BARK2.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\FROND2.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\FROZENLARGETREE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\FLATROCKS_SNOWTILING_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\FROZENLARGETREE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\FROZENLEAF1_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\FROZENMEDROCK_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\LARGEROCKS_FROZENLEAF1_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\ROCKTEMPLATWE_SMOOTHROCKTILING_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLICEFORMATION\ICEFORMATION_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLPLANT\MEDIUMPLANT_FROZENLARGETREE_MAT2.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\ICE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\ROCKBASE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\SNOWTILING_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKS\TILINGROCKFROZEN_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKBASE_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKS_SNOWTILING_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HQALPINE\SMALLPROPS\SMALLROCKSSHARDS\SNOWTILING_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["REPLACE_TYPE"] 		= "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ [[/FROZEN/]],[[/HQALPINE/]] },
							}
						}
					}
				},
				{ --HQ Tree Colors Fix
					["MBIN_FILE_SOURCE"] 	= {
					{"TEXTURES\PLANETS\BIOMES\COMMON\LEAVES\HQLEAVES\HQFROND1.TEXTURE.MBIN","TEXTURES\PLANETS\BIOMES\HQFROZEN\TREES\PINELEAF.TEXTURE.MBIN","REMOVE"},
					}
				},
				{ --HQ Tree Colors Fix
					["MBIN_FILE_SOURCE"] 	= {
					"TEXTURES\PLANETS\BIOMES\HQFROZEN\TREES\PINELEAF.TEXTURE.MBIN"
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["REPLACE_TYPE"] 		= "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ [[TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND1.]],[[TEXTURES/PLANETS/BIOMES/HQFROZEN/TREES/PINELEAF.]] }
							}
						}
					}
				}
			}
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE