BONUSOBJECTS_DENSITY_MULTIPLIER = 1/5 --We're decreasing density so make this a fraction
BONUSOBJECTS_COVERAGE_MULTIPLIER = 1/5 --We're decreasing density so make this a fraction
IMPOSTER_RADIUS_MULTIPLIER = 500
GLOBAL_MINSCALE_MULTIPLIER = 1
GLOBAL_MAXSCALE_MULTIPLIER = 1
LANDMARKS_MAXSCALE_MULTIPLIER = 1.5
DISTANTOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DISTANTOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGERADIO/DISTANTOBJECTS/HUGERADIOOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGERADIO/DISTANTOBJECTS/HUGERADIORINGOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUWCRYSTALSOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCRYSTALS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCUCUMBERLIGHTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCURVECORAL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERGASBAGS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERMONOLITHS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
LANDMARKS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="LANDMARKS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/LANDMARKS/RADIOACTIVEOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/LANDMARKS/RADIOACTIVEOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/LANDMARKS/RADIOACTIVEOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/LANDMARKS/RADIOACTIVEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/LANDMARKS/RADIOACTIVEALIENOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/LANDMARKS/RADIOACTIVEGLOWOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/LANDMARKS/RADIOSPIKECRYSTALSOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/LANDMARKS/RADIOSPIKEPOTATOOBJECTS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
OBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="OBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/OBJECTS/RADIOACTIVEOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/OBJECTS/RADIOACTIVEOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/OBJECTS/RADIOACTIVEOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/OBJECTS/RADIOACTIVEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/OBJECTS/SCORCHEDOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/OBJECTS/SCORCHEDOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/OBJECTS/SCORCHEDOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/OBJECTS/SCORCHEDOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/OBJECTS/TOXICOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/OBJECTS/TOXICOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/OBJECTS/TOXICOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/OBJECTS/TOXICOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/OBJECTS/RADIOACTIVEALIENOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/OBJECTS/RADIOACTIVEGLOWOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/OBJECTS/RADIOSPIKECRYSTALSOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/OBJECTS/RADIOSPIKEPOTATOOBJECTS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
DETAILOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DETAILOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\DETAILOBJECTS\HUGEROCKOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGESCORCHED\DETAILOBJECTS\HUGESCORCHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGETOXIC\DETAILOBJECTS\HUGETOXICOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DETAILOBJECTS\HUGEUWPLANTOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\DETAILOBJECTS\LUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\DETAILOBJECTS\SCORCHEDOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\DETAILOBJECTS\SCORCHEDOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\DETAILOBJECTS\SCORCHEDOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\DETAILOBJECTS\SCORCHEDOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\DETAILOBJECTS\TOXICOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\DETAILOBJECTS\TOXICOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\DETAILOBJECTS\TOXICOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\DETAILOBJECTS\TOXICOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
          <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\CAVE\DETAILOBJECTS\CAVEBIOMESPARSETOXIC.MBIN" />
        </Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/DETAILOBJECTS/RADIOACTIVEALIENOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/DETAILOBJECTS/RADIOACTIVEGLOWOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/DETAILOBJECTS/RADIOSPIKECRYSTALSOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/DETAILOBJECTS/RADIOSPIKEPOTATOOBJECTS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
GRASS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="GRASS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="0.1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/NEWLUSHGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/NEWCROSSGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/TALLNEWLUSHGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/TALLNEWCROSSGRASS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
NMS_MOD_DEFINITION_CONTAINER = --WARNING: Most, if not all, biomes in this mod are co-dependent (They use object lists generated by other biomes). These scripts won't work unless all of them are used together.
{
["MOD_FILENAME"] 			= "_CodenameAwesome.MishMashBiomes-RADIOACTIVE.pak",
["MOD_AUTHOR"]				= "CodenameAwesome",
["NMS_VERSION"]				= "",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
				{
					{-- ~~RADIOACTIVE BIOME~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEALIENOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEALIENOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEALIENOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEALIENOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEALIENOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEALIENOBJECTS.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEGLOWOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEGLOWOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEGLOWOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEGLOWOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEGLOWOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEGLOWOBJECTS.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKECRYSTALSOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOSPIKECRYSTALSOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKECRYSTALSOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOSPIKECRYSTALSOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKECRYSTALSOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOSPIKECRYSTALSOBJECTS.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKEPOTATOOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOSPIKEPOTATOOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKEPOTATOOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOSPIKEPOTATOOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKEPOTATOOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOSPIKEPOTATOOBJECTS.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSDEAD.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSLOW.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSMID.MBIN","REMOVE"},
						},
					},
					-- Remove any irrelevant parts of these files
					{--Fix up Landmarks files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEALIENOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEGLOWOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOSPIKECRYSTALSOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOSPIKEPOTATOOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSMID.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Landmarks
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks & Big things
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								  { "MaxScale", LANDMARKS_MAXSCALE_MULTIPLIER }
								}
							}
						}
					},
					{--Fix up Objects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEALIENOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOACTIVEGLOWOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOSPIKECRYSTALSOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\OBJECTS\RADIOSPIKEPOTATOOBJECTS.MBIN",
						},
		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER }
								}
							},
							{--Big Things
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MinScale", GLOBAL_MINSCALE_MULTIPLIER },
								  { "MaxScale", GLOBAL_MAXSCALE_MULTIPLIER }
								}
							}
						}
					},
					{--Fix up DetailObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEALIENOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOACTIVEGLOWOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOSPIKECRYSTALSOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\DETAILOBJECTS\RADIOSPIKEPOTATOOBJECTS.MBIN",
						},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							}
						}
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\LANDMARKS\RADIOACTIVEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\RADIOACTIVEOBJECTSFULL.MBIN"},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\RADIOACTIVEOBJECTSFULL.MBIN",
						},
						["EXML_CHANGE_TABLE"] =
						{
							{--Increasing the imposter radius of Landmarks & Big things & Drastically decrease density
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["MATH_OPERATION"] 		= "*",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "FlatDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "SlopeDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "Coverage", BONUSOBJECTS_COVERAGE_MULTIPLIER},
								}
							},
						},
					},
					{--Create Mish Mash RADIOACTIVE Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\MISHMASHRADIOACTIVEBIOME.MBIN","REMOVE"}}
					},
					{--Update Object Lists
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\MISHMASHRADIOACTIVEBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = GRASS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = LANDMARKS,
							},
						}
					},
										{
						["MBIN_FILE_SOURCE"] 	= {
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERADIO\DISTANTOBJECTS\HUGERADIOOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\HUGERINGOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERADIO\DISTANTOBJECTS\HUGERADIORINGOBJECTSFULL.MBIN","REMOVE"},
						},
					},
					{-- Create Frozen Distant Objects
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERADIO\DISTANTOBJECTS\HUGERADIOOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERADIO\DISTANTOBJECTS\HUGERADIORINGOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DistantObjects. No need to remove Landmarks because there aren't any.
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of DistantObjects
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER }
								}
							},
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE17.SCENE.MBIN"]],	[["MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE10.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE21.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE63.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HUGEPROPS/HUGERING/HUGERINGTREE.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN"]] }
								}
							}
						}
					},
					{-- Let's scale up those trees
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERADIO\DISTANTOBJECTS\HUGERADIOOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERADIO\DISTANTOBJECTS\HUGERADIORINGOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= 
						{
							{--Let's scale up those trees a bit
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MinScale", 1.5 },
								  { "MaxScale", 1.5 }
								}
							}
						}
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERADIO\DISTANTOBJECTS\HUGERADIOOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGERADIOOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERADIO\DISTANTOBJECTS\HUGERADIOOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGERADIORINGOBJECTSFULL.MBIN"},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGERADIOOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGERADIORINGOBJECTSFULL.MBIN",
						},
						["EXML_CHANGE_TABLE"] =
						{
							{--Increasing the imposter radius of Landmarks & Big things & Drastically decrease density
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["MATH_OPERATION"] 		= "*",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "FlatDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "SlopeDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "Coverage", BONUSOBJECTS_COVERAGE_MULTIPLIER},
								}
							},
						},
					},
					{--Create Mish Mash Huge Frozen Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\MISHMASHHUGERADIOBIOME.MBIN","REMOVE"}}
					},
					{--Update Object Lists --NO LANDMARKS
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\MISHMASHHUGERADIOBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{---Change ground texture to snow
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{[["METADATA/SIMULATION/SOLARSYSTEM/TEXTURES/LUSH.MBIN"]],[["METADATA/SIMULATION/SOLARSYSTEM/TEXTURES/RADIOACTIVE.MBIN"]]}
								}
							},
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = GRASS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DISTANTOBJECTS,
							},
							{--Set the weather to Snow since this is originally a Lush biome file.
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{"Humid",	"0"},
									{"Radioactive",	"1"},
								}	
							}
						}
					}
				}
		}
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE