BONUSOBJECTS_DENSITY_MULTIPLIER = 1/5 --We're decreasing density so make this a fraction
BONUSOBJECTS_COVERAGE_MULTIPLIER = 1/5 --We're decreasing density so make this a fraction
IMPOSTER_RADIUS_MULTIPLIER = 500
GLOBAL_MINSCALE_MULTIPLIER = 1
GLOBAL_MAXSCALE_MULTIPLIER = 1
LANDMARKS_MAXSCALE_MULTIPLIER = 1.5
DISTANTOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DISTANTOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="0.1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DISTANTOBJECTS/BARRENBIGPROPSOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEROCK/DISTANTOBJECTS/HUGEROCKOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCRYSTALS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCUCUMBERLIGHTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCURVECORAL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERGASBAGS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERMONOLITHS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUWPLANTOBJECTS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
LANDMARKS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="LANDMARKS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENCORALOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENHIVESOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENINFESTEDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENROCKYOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/BARRENROCKYWEIRDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/DRIEDLUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/DRIEDLUSHOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/LANDMARKS/DRIEDLUSHOBJECTSMID.MBIN" />
		</Property>
	  </Property>
	</Property>]]
OBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="OBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENCORALOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENHIVESOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENINFESTEDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENROCKYOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/OBJECTS/BARRENROCKYWEIRDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEROCK/OBJECTS/HUGEROCKOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/OBJECTS/HUGEUWPLANTOBJECTS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
DETAILOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DETAILOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENCORALOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENHIVESOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENHQOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENINFESTEDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENROCKYOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/DETAILOBJECTS/BARRENROCKYWEIRDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEROCK/DETAILOBJECTS/HUGEROCKOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DETAILOBJECTS/HUGEUWPLANTOBJECTS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
NMS_MOD_DEFINITION_CONTAINER = --WARNING: Most, if not all, biomes in this mod are co-dependent (They use object lists generated by other biomes). These scripts won't work unless all of them are used together.
{
["MOD_FILENAME"] 			= "_CodenameAwesome.MishMashBiomes-BARREN.pak",
["MOD_AUTHOR"]				= "CodenameAwesome",
["NMS_VERSION"]				= "",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
				{
					{-- ~~BARREN BIOME~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENBIGPROPSOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DISTANTOBJECTS\BARRENBIGPROPSOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENCORALOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENHIVESOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENINFESTEDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENCORALOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENHIVESOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENINFESTEDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENCORALOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENHIVESOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENINFESTEDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENHQOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENHQOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENHQOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENOBJECTSDEAD.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENOBJECTSLOW.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENOBJECTSMID.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHHQOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSLOW.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSMID.MBIN","REMOVE"},
						},
					},
					-- Remove any irrelevant parts of these files
					{--Fix up Landmarks files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENCORALOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENHIVESOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENINFESTEDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENROCKYWEIRDOBJECTS.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Landmarks
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks & Big things
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								  { "MaxScale", LANDMARKS_MAXSCALE_MULTIPLIER }
								}
							}
						}
					},
					{--Fix up Objects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENCORALOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENHIVESOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENINFESTEDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\OBJECTS\BARRENROCKYWEIRDOBJECTS.MBIN",
						},
		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER }
								}
							},
							{--Big Things
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MinScale", GLOBAL_MINSCALE_MULTIPLIER },
								  { "MaxScale", GLOBAL_MAXSCALE_MULTIPLIER }
								}
							}
						}
					},
					{--Fix up DetailObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENCORALOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENHIVESOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENINFESTEDOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DETAILOBJECTS\BARRENROCKYWEIRDOBJECTS.MBIN",
						},
		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							}
						}
					},
					{--DRIED LUSH - Replace trees with dead trees.
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSMID.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Replace the new model with the old one
						{
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"]],[["MODELS/PLANETS/BIOMES/HQALPINE/LARGEPROPS/LARGETREEBARE.SCENE.MBIN"]] }
								}
							}
						}
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\BARRENOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\BARRENHQOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\BARRENHQOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\LANDMARKS\DRIEDLUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\DRIEDLUSHOBJECTSFULL.MBIN"},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\BARRENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\BARRENHQOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\DRIEDLUSHOBJECTSFULL.MBIN",
						},
						["EXML_CHANGE_TABLE"] =
						{
							{--Increasing the imposter radius of Landmarks & Big things & Drastically decrease density
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["MATH_OPERATION"] 		= "*",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "FlatDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "SlopeDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "Coverage", BONUSOBJECTS_COVERAGE_MULTIPLIER},
								}
							},
						},
					},
					{--Create Mish Mash Barren Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\MISHMASHBARRENBIOME.MBIN","REMOVE"}}
					},
					{--Update Object Lists
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\MISHMASHBARRENBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = LANDMARKS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DISTANTOBJECTS,
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"
	
							},
						}
					},
					{--Create a copy of the file that uses the HQ palette
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\MISHMASHBARRENBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\MISHMASHBARRENHQBIOME.MBIN"}}
					},
					{
						["MBIN_FILE_SOURCE"] 	= "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\MISHMASHBARRENHQBIOME.MBIN",
						["EXML_CHANGE_TABLE"]	= 
						{
							{
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{ "ColourPaletteFile",	"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENHQCOLOURPALETTES.MBIN" }
								}	
							}
						}
					},
					{-- ~~HUGEBARREN BIOME~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects). There's no Landmarks in Huge Biomes so just 3 folders.
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\HUGEROCKOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\DISTANTOBJECTS\HUGEROCKOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\HUGEUWPLANTOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DISTANTOBJECTS\HUGEUWPLANTOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\UNDERWATERCRYSTALS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DISTANTOBJECTS\HUGEUNDERWATERCRYSTALS.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\UNDERWATERCUCUMBERLIGHTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DISTANTOBJECTS\HUGEUNDERWATERCUCUMBERLIGHTS.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\UNDERWATERCURVECORAL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DISTANTOBJECTS\HUGEUNDERWATERCURVECORAL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\UNDERWATERGASBAGS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DISTANTOBJECTS\HUGEUNDERWATERGASBAGS.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\UNDERWATERMONOLITHS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DISTANTOBJECTS\HUGEUNDERWATERMONOLITHS.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\HUGEROCKOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\OBJECTS\HUGEROCKOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\HUGEUWPLANTOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\OBJECTS\HUGEUWPLANTOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\HUGEROCKOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\DETAILOBJECTS\HUGEROCKOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\HUGEUWPLANTOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DETAILOBJECTS\HUGEUWPLANTOBJECTS.MBIN","REMOVE"},
						},
					},
					-- Remove any irrelevant parts of these files
					{--Fix up DistantObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\DISTANTOBJECTS\HUGEROCKOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DISTANTOBJECTS\HUGEUWPLANTOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\DISTANTOBJECTS\BARRENBIGPROPSOBJECTSFULL.MBIN"
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DistantObjects. No need to remove Landmarks because there aren't any.
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER }
								}
							}
						}
					},
					{--Fix up Objects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\OBJECTS\HUGEROCKOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\OBJECTS\HUGEUWPLANTOBJECTS.MBIN",
						},		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DistantObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER }
								}
							}
						}
					},
					{--Fix up Objects files for extra underwater objects
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCRYSTALS.MBIN",
							"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCUCUMBERLIGHTS.MBIN",
							"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERCURVECORAL.MBIN",
							"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERGASBAGS.MBIN",
							"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/DISTANTOBJECTS/HUGEUNDERWATERMONOLITHS.MBIN"
						},		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increase scale
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MinScale", 4 },
								  { "MinScale", 4 },
								  { "FlatDensity", 1/6},
								  { "SlopeDensity", 1/6},
								}
							},
							{--Fix spawn heights
								
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MinHeight", -1 },
								  { "MaxHeight", 128 },
								  { "MaxImposterRadius", 9999}
								}
							},
							{--Fix LOD distances
								["PRECEDING_KEY_WORDS"] = {"LodDistances"},
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "IGNORE", 6 },
								}
							}
						}
					},
					{--Fix up DetailObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\DETAILOBJECTS\HUGEROCKOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DETAILOBJECTS\HUGEUWPLANTOBJECTS.MBIN",
							},		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DistantObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							}
						}
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\DISTANTOBJECTS\HUGEROCKOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEROCKOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\DISTANTOBJECTS\HUGEUWPLANTOBJECTS.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEUWPLANTOBJECTS.MBIN"},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEROCKOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEUWPLANTOBJECTS.MBIN",
						},
						["EXML_CHANGE_TABLE"] =
						{
							{--Increasing the imposter radius of Landmarks & Big things & Drastically decrease density
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["MATH_OPERATION"] 		= "*",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "FlatDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "SlopeDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "Coverage", BONUSOBJECTS_COVERAGE_MULTIPLIER},
								}
							},
						},
					},
					{--Create Mish Mash Huge Barren Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\HUGEROCKBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\MISHMASHHUGEBARRENBIOME.MBIN","REMOVE"}}
					},
					{--Update Object Lists --NO LANDMARKS
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\MISHMASHHUGEBARRENBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DISTANTOBJECTS,
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","DISTANTOBJECTS"},
								["VALUE_CHANGE_TABLE"] = {
									{"Probability",1}
								},
							},
						}
					}
				}
		}
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE