--see also StandardSchemeExtended.lua

NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] 			= "zzAssets_IceSpikes.pak",     --the name of the pak created (if not combined) - REQUIRED
  ["MOD_DESCRIPTION"]		= "",         --optional, for reference
  ["MOD_AUTHOR"]				= "",         --optional, for reference
  ["NMS_VERSION"]				= "2.0",     --optional, for reference
  ["MODIFICATIONS"] 		=             --REQUIRED SECTION
	{
		{
			["MBIN_CHANGE_TABLE"] = 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= {
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGEPLATFORMROCK.DESCRIPTOR.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGEPLATFORMROCK.GEOMETRY.DATA.MBIN.PC",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGEPLATFORMROCK.GEOMETRY.MBIN.PC",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGEPLATFORMROCK.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGESPIKEROCK.DESCRIPTOR.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK.DESCRIPTOR.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGESPIKEROCK.GEOMETRY.DATA.MBIN.PC",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK.GEOMETRY.DATA.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGESPIKEROCK.GEOMETRY.MBIN.PC",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK.GEOMETRY.MBIN.PC","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGESPIKEROCK.SCENE.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK.SCENE.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGEPLATFORMROCK\PHONG19.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK\PHONG19.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGEPLATFORMROCK\PLATFORMROCKPLATES_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK\PLATFORMROCKPLATES_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGEPLATFORMROCK\PLATFORMROCK_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK\PLATFORMROCK_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGESPIKEROCK\LAMBERT1.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK\LAMBERT1.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGESPIKEROCK\LARGESPIKEROCK_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK\LARGESPIKEROCK_MAT.MATERIAL.MBIN","REMOVE"},
					{"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGESPIKEROCK\SMALLGROWTHATTACHMENT_MAT.MATERIAL.MBIN",
					"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK\SMALLGROWTHATTACHMENT_MAT.MATERIAL.MBIN","REMOVE"},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK.SCENE.MBIN"
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] 		= "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ [[\HUGEROCK\]],[[\HUGEICESPIKE\]] }
							}
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGESPIKEROCK\LARGESPIKEROCK_MAT.MATERIAL.MBIN"
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["REPLACE_TYPE"] 		= "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ [[TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGESPIKEROCK.BASE.1.]],[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ICETILING.]] }
							}
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEICESPIKE\HUGEPLATFORMROCK\PLATFORMROCK_MAT.MATERIAL.MBIN"
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["REPLACE_TYPE"] 		= "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ [[TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGEPLATFORMROCK.BASE.1.]],[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ICETILING.]] }
							}
						}
					}
				},
			}
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE