BONUSOBJECTS_DENSITY_MULTIPLIER = 1/5 --We're decreasing density so make this a fraction
BONUSOBJECTS_COVERAGE_MULTIPLIER = 1/5 --We're decreasing density so make this a fraction
IMPOSTER_RADIUS_MULTIPLIER = 500
GLOBAL_MINSCALE_MULTIPLIER = 1
GLOBAL_MAXSCALE_MULTIPLIER = 1
LANDMARKS_MAXSCALE_MULTIPLIER = 1.5
DISTANTOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DISTANTOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEFROZEN/DISTANTOBJECTS/HUGEFROZENOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEFROZEN/DISTANTOBJECTS/HUGEFROZENRINGOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEFROZEN/DISTANTOBJECTS/HUGEICESPIKEOBJECTSFULL.MBIN" />
		</Property>
	  </Property>
	</Property>]]
LANDMARKS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="LANDMARKS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENALIENOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENBIGPROPSOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENHQOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENPILLAROBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENROCKYOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENROCKYWEIRDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/LANDMARKS/FROSTEDLUSHOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/LANDMARKS/FROSTEDLUSHOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/LANDMARKS/FROSTEDLUSHOBJECTSFULL.MBIN" />
		</Property>
	  </Property>
	</Property>]]
OBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="OBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENALIENOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENHQOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENPILLAROBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENROCKYOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENROCKYWEIRDOBJECTS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
DETAILOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DETAILOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENALIENOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENHQOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSDEAD.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSFULL.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSLOW.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSMID.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENPILLAROBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENROCKYOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENROCKYWEIRDOBJECTS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/DETAILOBJECTS/LUSHHQOBJECTSFULL.MBIN" />
		</Property>
	  </Property>
	</Property>]]
GRASS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="GRASS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="0.1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/NEWLUSHGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/NEWCROSSGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/TALLNEWLUSHGRASS.MBIN" />
		</Property>
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/GRASS/TALLNEWCROSSGRASS.MBIN" />
		</Property>
	  </Property>
	</Property>]]
NMS_MOD_DEFINITION_CONTAINER = --WARNING: Most, if not all, biomes in this mod are co-dependent (They use object lists generated by other biomes). These scripts won't work unless all of them are used together.
{
["MOD_FILENAME"] 			= "_CodenameAwesome.MishMashBiomes-FROZEN.pak",
["MOD_AUTHOR"]				= "CodenameAwesome",
["NMS_VERSION"]				= "",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
				{
					{-- ~~FROZEN BIOME~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENALIENOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENBIGPROPSOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENPILLAROBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENALIENOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENPILLAROBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENALIENOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENPILLAROBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENROCKYOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENROCKYWEIRDOBJECTS.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENHQOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENHQOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSLOW.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSMID.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENHQOBJECTSMID.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSDEAD.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSLOW.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSMID.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSLOW.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSLOW.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSMID.MBIN","REMOVE"},
						},
					},
					-- Remove any irrelevant parts of these files
					{--Fix up Landmarks files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENALIENOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENBIGPROPSOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENPILLAROBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENROCKYWEIRDOBJECTS.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Landmarks
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks & Big things
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER },
								  { "MaxScale", LANDMARKS_MAXSCALE_MULTIPLIER }
								}
							}
						}
					},
					{--Fix up Objects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENALIENOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENPILLAROBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\OBJECTS\FROZENROCKYWEIRDOBJECTS.MBIN",
						},
		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of landmarks
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER }
								}
							},
							{--Big Things
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MinScale", GLOBAL_MINSCALE_MULTIPLIER },
								  { "MaxScale", GLOBAL_MAXSCALE_MULTIPLIER }
								}
							}
						}
					},
					{--Fix up DetailObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENHQOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSDEAD.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENOBJECTSMID.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENALIENOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENPILLAROBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENROCKYOBJECTS.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\DETAILOBJECTS\FROZENROCKYWEIRDOBJECTS.MBIN",
						},
		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Landmarks",},
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							}
						}
					},
					{--FROSTED LUSH
						["MBIN_FILE_SOURCE"] = {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSLOW.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROSTEDLUSHOBJECTSMID.MBIN",
						},
						["EXML_CHANGE_TABLE"] = {
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	= {
									{ [[/HQLUSH/HQTREES/]] , [[/FROSTEDHQLUSH/HQTREES/]] }
								}
							}
						}
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\FROZENOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\LANDMARKS\FROZENHQOBJECTSMID.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\FROZENHQOBJECTSMID.MBIN"},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\FROZENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\FROZENHQOBJECTSMID.MBIN",
						},
						["EXML_CHANGE_TABLE"] =
						{
							{--Increasing the imposter radius of Landmarks & Big things & Drastically decrease density
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["MATH_OPERATION"] 		= "*",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "FlatDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "SlopeDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "Coverage", BONUSOBJECTS_COVERAGE_MULTIPLIER},
								}
							},
						},
					},
					{--Create Mish Mash FROZEN Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\MISHMASHFROZENBIOME.MBIN","REMOVE"}}
					},
					{--Update Object Lists
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\MISHMASHFROZENBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = GRASS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = LANDMARKS,
							},
						}
					},
					{--Create a copy of the file that uses the HQ palette
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\MISHMASHFROZENBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\MISHMASHFROZENHQBIOME.MBIN"}}
					},
					{
						["MBIN_FILE_SOURCE"] 	= "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\MISHMASHFROZENHQBIOME.MBIN",
						["EXML_CHANGE_TABLE"]	= 
						{
							{
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{ "ColourPaletteFile",	"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQCOLOURPALETTES.MBIN" }
								}	
							}
						}
					},
					{ -- HUGE FROZEN
						["MBIN_FILE_SOURCE"] 	= {
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEFROZENOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\HUGERINGOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEFROZENRINGOBJECTSFULL.MBIN","REMOVE"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\HUGEROCKOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEICESPIKEOBJECTSFULL.MBIN","REMOVE"},
						},
					},
					{-- Create Frozen Distant Objects
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEFROZENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEFROZENRINGOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DistantObjects. No need to remove Landmarks because there aren't any.
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of DistantObjects
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER }
								}
							},
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE17.SCENE.MBIN"]],	[["MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE10.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE21.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE63.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN"]] },
									{ [["MODELS/PLANETS/BIOMES/HUGEPROPS/HUGERING/HUGERINGTREE.SCENE.MBIN"]], [["MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN"]] }
								}
							}
						}
					},
					{-- Let's scale up those trees
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEFROZENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEFROZENRINGOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= 
						{
							{--Let's scale up those trees a bit
								["SPECIAL_KEY_WORDS"] = {"Filename","MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN"},
								["SECTION_UP"] = 1,
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MinScale", 1.5 },
								  { "MaxScale", 1.5 }
								}
							}
						}
					},
					{--  Swap in Ice Spikes
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEICESPIKEOBJECTSFULL.MBIN",
							},
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DistantObjects. No need to remove Landmarks because there aren't any.
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},----Change all of this
								["REMOVE"] 	= "SECTION"
							},
							{--Increasing the imposter radius of DistantObjects
								
								["MATH_OPERATION"] 		= "*",
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "MaxImposterRadius", IMPOSTER_RADIUS_MULTIPLIER }
								}
							},
							{
								["REPLACE_TYPE"] 		= "RAW",
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{ [[/HUGEROCK/]],	[[/HUGEICESPIKE/]] },
								}
							}
						}
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEFROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEFROZENOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEFROZENOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEFROZENRINGOBJECTSFULL.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEFROZEN\DISTANTOBJECTS\HUGEICESPIKEOBJECTSFULL.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEICESPIKEOBJECTSFULL.MBIN"},
						},
					},
					{-- ~~BONUS OBJECTS~~
						["MBIN_FILE_SOURCE"] 	= {--First copy all the files into three or four different folders (DistantObjects,Landmarks,Objects,DetailObjects).
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEFROZENOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEFROZENRINGOBJECTSFULL.MBIN",
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BONUSOBJECTS\HUGEICESPIKEOBJECTSFULL.MBIN",
						},
						["EXML_CHANGE_TABLE"] =
						{
							{--Increasing the imposter radius of Landmarks & Big things & Drastically decrease density
								["PRECEDING_KEY_WORDS"] = {"GcObjectSpawnData.xml"},
								["VALUE_MATCH_TYPE"] 	= "NUMBER",
								["MATH_OPERATION"] 		= "*",
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
								  { "FlatDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "SlopeDensity", BONUSOBJECTS_DENSITY_MULTIPLIER},
								  { "Coverage", BONUSOBJECTS_COVERAGE_MULTIPLIER},
								}
							},
						},
					},
					{--Create Mish Mash Huge Frozen Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\MISHMASHHUGEFROZENBIOME.MBIN","REMOVE"}}
					},
					{--Update Object Lists
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\MISHMASHHUGEFROZENBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{---Change ground texture to snow
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{"TextureFile","METADATA/SIMULATION/SOLARSYSTEM/TEXTURES/FROZEN.MBIN"},
									{"TileTypesFile","METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENTILETYPES.MBIN"},
									{"ColourPaletteFile","METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENCOLOURPALETTES.MBIN"},
								}
							},
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = GRASS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DISTANTOBJECTS,
							},
							{--Set the weather to Snow since this is originally a Lush biome file.
								["REPLACE_TYPE"] 		= "ALL",
								["VALUE_CHANGE_TABLE"] 	= 
								{
									{"Humid",	"0"},
									{"Frozen",	"1"},
								}	
							}
						}
					}
				}
		}
	},
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE