NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] 			= "zzAssets-E3Crystals.pak",     --the name of the pak created (if not combined) - REQUIRED
  ["MOD_DESCRIPTION"]		= "",         --optional, for reference
  ["MOD_AUTHOR"]				= "",         --optional, for reference
  ["NMS_VERSION"]				= "2.0",     --optional, for reference
  ["MODIFICATIONS"] 		=             --REQUIRED SECTION
	{
		{
			["MBIN_CHANGE_TABLE"] = 
			{ 
				{	
					["MBIN_FILE_SOURCE"] 	= 
					{
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_UNDERWATER.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_RED.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_MOUNTAIN.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_CAVE.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_UNDERWATER.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_RED.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_MOUNTAIN.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_CAVE.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_UNDERWATER.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_RED.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_MOUNTAIN.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_CAVE.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_UNDERWATER.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_RED.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_MOUNTAIN.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_CAVE.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_UNDERWATER.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_RED.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_MOUNTAIN.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_CAVE.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_UNDERWATER.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_RED.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_MOUNTAIN.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCEFRAGMENTS_CAVE.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_UNDERWATER.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_RED.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_MOUNTAIN.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_CAVE.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_UNDERWATER.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_RED.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_MOUNTAIN.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_CAVE.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_UNDERWATER.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_RED.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_MOUNTAIN.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_CAVE.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_UNDERWATER.MATERIAL.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_RED.MATERIAL.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_MOUNTAIN.MATERIAL.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_CAVE.MATERIAL.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_UNDERWATER.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_RED.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_MOUNTAIN.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_CAVE.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_UNDERWATER.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_RED.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_MOUNTAIN.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_CAVE.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_UNDERWATER.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_RED.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_MOUNTAIN.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_CAVE.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_UNDERWATER.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_RED.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_MOUNTAIN.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.SCENE.MBIN","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_CAVE.SCENE.MBIN"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_UNDERWATER.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_RED.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_MOUNTAIN.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_CAVE.GEOMETRY.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_UNDERWATER.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_RED.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_MOUNTAIN.GEOMETRY.DATA.MBIN.PC"},
						{"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_CAVE.GEOMETRY.DATA.MBIN.PC"}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_RED.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_RED.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_RED.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_RED.SCENE.MBIN",
					},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_RED.MATERIAL.MBIN"},
							}	
						},
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","ATTACHMENT"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value","MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTAL_LARGE\ENTITIES\CRYSTAL_LARGE.ENTITY.MBIN"},
							}	
						},
					},
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_RED.MATERIAL.MBIN"},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{[[SUBSTANCE.BASE.DDS]],[[SUBSTANCEALT_RED.DDS]]},
							}	
						},
					},
				},
				{-- CAVE = GREEN
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_CAVE.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_CAVE.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_CAVE.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_CAVE.SCENE.MBIN",
					},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_CAVE.MATERIAL.MBIN"},
							}	
						},
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","ATTACHMENT"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value","MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTAL_LARGE_CAVE\ENTITIES\CRYSTAL_LARGE_CAVE.ENTITY.MBIN"},
							}	
						},
					},
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_CAVE.MATERIAL.MBIN"},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{[[SUBSTANCE.BASE.DDS]],[[SUBSTANCEALT_GREEN.DDS]]},
							}	
						},
					},
				},
				{-- MOUNTAIN = BLUE
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_MOUNTAIN.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_MOUNTAIN.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_MOUNTAIN.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_MOUNTAIN.SCENE.MBIN",
					},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_MOUNTAIN.MATERIAL.MBIN"},
							}	
						},
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","ATTACHMENT"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value","MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTAL_LARGE_MOUNTAIN\ENTITIES\CRYSTAL_LARGE_MOUNTAIN.ENTITY.MBIN"},
							}	
						},
					},
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_MOUNTAIN.MATERIAL.MBIN"},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{[[SUBSTANCE.BASE.DDS]],[[SUBSTANCEALT_BLUE.DDS]]},
							}	
						},
					},
				},
				{-- UNDERWATER = YELLOW
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_UNDERWATER.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_UNDERWATER.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD_UNDERWATER.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE_UNDERWATER.SCENE.MBIN",
					},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value","MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_UNDERWATER.MATERIAL.MBIN"},
							}	
						},
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","ATTACHMENT"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value","MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTAL_LARGE_UNDERWATER\ENTITIES\CRYSTAL_LARGE_UNDERWATER.ENTITY.MBIN"},
							}	
						},
					},
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\MINERALMAT_UNDERWATER.MATERIAL.MBIN"},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{[[SUBSTANCE.BASE.DDS]],[[SUBSTANCEALT_YELLOW.DDS]]},
							}	
						},
					},
				},
				{--Medium entities
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_UNDERWATER.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_RED.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_MOUNTAIN.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK_CAVE.SCENE.MBIN",
					},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","ATTACHMENT"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{[[_LARGE]],[[_MEDIUM]]},
							}	
						},
					},
				},
				{--Small entities
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_UNDERWATER.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_RED.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_MOUNTAIN.SCENE.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL_CAVE.SCENE.MBIN"
					},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["REPLACE_TYPE"] = "ALL",
							["SPECIAL_KEY_WORDS"] = {"Name","ATTACHMENT"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{[[_LARGE]],[[_SMALL]]},
							}	
						},
					},
				},
			},
		},
	},
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE