--see also StandardSchemeExtended.lua

NMS_MOD_DEFINITION_CONTAINER =
{
  ["MOD_FILENAME"] 			= "_CodenameAwesome.ActivatedColourPalettes.pak",     --the name of the pak created (if not combined) - REQUIRED
  ["MOD_DESCRIPTION"]		= "Reactivates old color palettes that were disabled in the game with the NEXT update.",         --optional, for reference
  ["MOD_AUTHOR"]				= "",         --optional, for reference
  ["NMS_VERSION"]				= "2.0",     --optional, for reference
  ["MODIFICATIONS"] 		=             --REQUIRED SECTION
	{
		{
			["MBIN_CHANGE_TABLE"] =
			{
				{
					["MBIN_FILE_SOURCE"] = {
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQCOLOURPALETTE.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQCOLOURPALETTE-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DEADCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DEADCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\BEAMSTONE\BEAMSCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\BEAMSTONE\BEAMSCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\BONESPIRE\BONESPIRECOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\BONESPIRE\BONESPIRECOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\CONTOUR\CONTOURCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\CONTOUR\CONTOURCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\ELBUBBLE\ELBUBBLECOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\ELBUBBLE\ELBUBBLECOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\FRACTALCUBE\FRACTCUBECOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\FRACTALCUBE\FRACTCUBECOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HEXAGON\HEXAGONCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HEXAGON\HEXAGONCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HYDROGARDEN\HYDROGARDENCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HYDROGARDEN\HYDROGARDENCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\IRRISHELLS\IRRISHELLSCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\IRRISHELLS\IRRISHELLSCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\MSTRUCTURES\MSTRUCTCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\MSTRUCTURES\MSTRUCTCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\SHARDS\SHARDSCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\SHARDS\SHARDSCOLOURPALETTES-ACTIVATED.MBIN"},
						{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\WIRECELLS\WIRECELLSCOLOURPALETTES.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\WIRECELLS\WIRECELLSCOLOURPALETTES-ACTIVATED.MBIN"},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQCOLOURPALETTE-ACTIVATED.MBIN",
					},
					["EXML_CHANGE_TABLE"] =
					{
						{
							["PRECEDING_KEY_WORDS"] = {"Grass"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"All"},
							}
						},
						{
							["PRECEDING_KEY_WORDS"] = {"Leaf"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"All"},
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DEADCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\BEAMSTONE\BEAMSCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\BONESPIRE\BONESPIRECOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\CONTOUR\CONTOURCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\ELBUBBLE\ELBUBBLECOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\FRACTALCUBE\FRACTCUBECOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HEXAGON\HEXAGONCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HYDROGARDEN\HYDROGARDENCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\IRRISHELLS\IRRISHELLSCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\MSTRUCTURES\MSTRUCTCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\SHARDS\SHARDSCOLOURPALETTES-ACTIVATED.MBIN",
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\WIRECELLS\WIRECELLSCOLOURPALETTES-ACTIVATED.MBIN",
					},
					["EXML_CHANGE_TABLE"] =
					{
						{
							["PRECEDING_KEY_WORDS"] = {"Grass"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"All"},
							}
						},
						--[[{
							["PRECEDING_KEY_WORDS"] = {"GrassAlt"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"All"},
							}
						},]]
						{
							["PRECEDING_KEY_WORDS"] = {"Plant"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"All"},
							}
						},
						{
							["PRECEDING_KEY_WORDS"] = {"Leaf"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"All"},
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQCOLOURPALETTES-ACTIVATED.MBIN",
					},
					["EXML_CHANGE_TABLE"] =
					{
						{
							["PRECEDING_KEY_WORDS"] = {"RockSaturated"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"Inactive"},
							}
						},
						{
							["PRECEDING_KEY_WORDS"] = {"RockSaturated"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"Inactive"},
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQCOLOURPALETTE-ACTIVATED.MBIN",
					},
					["EXML_CHANGE_TABLE"] =
					{
						{
							["PRECEDING_KEY_WORDS"] = {"Sand"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"NumColours",	"Inactive"},
							}
						},
					}
				},
			}
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE
