Author = "Exosolar"
ModName = "Exosolars Glass Fix"
ModNameSub = ""
BaseDescription = ""
GameVersion = "336"
ModVersion = "a"
FileSource1 = {
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\CONCRETE\BASIC_GFLOOR\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\CONCRETE\BASIC_GFLOOR_LOD\GLASS_MAT2.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\CONCRETE\BASIC_WALL_DOORWINDOWL\GLASS_MAT1.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\CONCRETE\BASIC_WALL_DOORWINDOWL_LOD\GLASS_MAT1.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\CONCRETE\BASIC_WALL_WINDOW\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\CONCRETE\BASIC_WALL_WINDOW_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\METAL\BASIC_GFLOOR\BASIC_WALL_WINDOW_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\METAL\BASIC_GFLOOR_LOD\BASIC_WALL_WINDOW2_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\METAL\BASIC_WALL_DOORWINDOWL\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\METAL\BASIC_WALL_DOORWINDOWL_LOD\BASIC_WALL_WINDOW2_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\METAL\BASIC_WALL_WINDOW\BASIC_WALL_WINDOW_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\METAL\BASIC_WALL_WINDOW_LOD\BASIC_WALL_WINDOW1_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\WOOD\BASIC_GFLOOR\BASIC_WALL_WINDOW_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\WOOD\BASIC_GFLOOR_LOD\BASIC_WALL_WINDOW3_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\WOOD\BASIC_WALL_DOORWINDOWL\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\WOOD\BASIC_WALL_DOORWINDOWL_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\WOOD\BASIC_WALL_WINDOW\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BASICPARTS\MESHES\WOOD\BASIC_WALL_WINDOW_LOD\GLASS_MAT2.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIOROOM_CENTRE_LOD\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIOROOM_CORE\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIOROOM_CORE\DEFAULTROOM_DOOR_GLASS_MAT1.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIOROOM_CORE_LOD\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIOROOM_DOOR\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIOROOM_DOOR_LOD\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIOROOM_WALL\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIOROOM_WALL_LOD\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIORPANEL_TRANSFORMER\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\BIORPANEL_TRANSFORMER_LOD\DEFAULTROOM_DOOR_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDORCAP_VIEWINGSPHERE\CUBEROOM_CORRIDORHATCH_GLASS_MAT1.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDORCAP_VIEWINGSPHERE\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDORCAP_VIEWINGSPHERE_LOD\CUBEROOM_CORRIDORHATCH_GLASS_MAT1.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDORCAP_VIEWINGSPHERE_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDOR_CURVED\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDOR_CURVED_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDOR_CURVED_LOD\GLASS_MAT1.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDOR_JOIN\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDOR_SIDEWINDOW\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDOR_STRAIGHT_GLASS\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDOR_STRAIGHT_GLASS_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CORRIDOR_TOPWINDOW\CORRIDOR_SIDEWINDOW_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CUBEROOM_CURVEDROOF\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CUBEROOM_CURVEDROOF_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CUBEROOM_GLASS\GLASS\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CUBEROOM_GLASS\GLASSWALL_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CUBEROOM_WINDOW\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CUBEROOM_WINDOWCIRCLE\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\CUBEROOM_WINDOWSMALL\GLASS_MAT1.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DOORNOSNAP_LOD\TKDEREF_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\PANELCORNER_DEFAULT\GLASS_MAT1.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\PANEL_GLASS_MAIN\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\PANEL_GLASS_MAIN_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\ROOMCUBE_WINDOW\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\ROOM_ROOF\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\ROOM_ROOF_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\ROOM_WINDOW\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\SNAPGROUP_PARTS\CORRIDOR_STRAIGHT_GLASS\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\SNAPGROUP_PARTS\WINDOWMODULE\CORRIDOR_SIDEWINDOW_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_CAP\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_CAP_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_CURVED\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_LSHAPE\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_STRAIGHT\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_STRAIGHT_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_TSHAPE\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_TSHAPE_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_VERTICAL\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_XSHAPE\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\CORRIDOR_XSHAPE_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\MAINROOMCUBE_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\SURVIVALPOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UNDERWATERBASE\SURVIVALPOD_LOD\GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\WINDOWMODULE\CORRIDOR_SIDEWINDOW_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\WINDOWMODULE_LOD\CORRIDOR_SIDEWINDOW_GLASS_MAT.MATERIAL.MBIN",
"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\COMMONPARTS\GANTRY\CORRIDORGLASSSTRAIGHT_2\GLASS_MAT1.MATERIAL.MBIN",
}


NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= ModName.." "..ModNameSub.." "..GameVersion..ModVersion..".pak",
["MOD_DESCRIPTION"]	= BaseDescription,
["MOD_AUTHOR"]		= Author,
["NMS_VERSION"]		= GameVersion,
["MODIFICATIONS"]	= {{
["MBIN_CHANGE_TABLE"] = {
{["MBIN_FILE_SOURCE"] = FileSource1,
["EXML_CHANGE_TABLE"] = {

--Change DerelictAbandCrateChance
	{
		["PRECEDING_KEY_WORDS"] = {"Uniforms"},
		["SECTION_UP"] = 1,
		["VALUE_CHANGE_TABLE"] = {
			{"x", 0.1},
			{"y", 0.1},
			{"z", 0.16},
			{"t", 0.6},
		}
	},

}},
}},}}