cd ..\..\_ENGINE\RGOG
copy SRC\REDMASPARAMS\PLAYER_GAMEPLAY_REVISION_PRESET.lua USERPARAMS\PLAYER_GAMEPLAY_REVISION_PRESET.lua

cd LITE
start  lite.exe ..\USERPARAMS\PLAYER_GAMEPLAY_REVISION_PRESET.lua
