cd ..\..\_ENGINE\RGOG
copy SRC\REDMASPARAMS\REDMAS_SPAWNER_FOR_CONSTRUCTS_BY_MSSP_PRESET.lua USERPARAMS\REDMAS_SPAWNER_FOR_CONSTRUCTS_BY_MSSP_PRESET.lua

cd LITE
start  lite.exe ..\USERPARAMS\REDMAS_SPAWNER_FOR_CONSTRUCTS_BY_MSSP_PRESET.lua
