LightFOV = 360
LightFalloff = "linear"					--"quadratic" ; use linear if your lights are dim, quadratic if they are really bright
LightMultiplier = 0.5						--1
LightRedOf1 = 1.0
LightGreenOf1 = 1.0
LightBlueOf1 = 1.0

NMS_MOD_DEFINITION_CONTAINER = {
MOD_FILENAME		= "GLight 234a Freighter Frigate.pak",
MOD_DESCRIPTION		= "Freighter and Frigate light modifications",
MOD_AUTHOR			= "Gumsk",
NMS_VERSION			= "2.3.4",
MODIFICATIONS		= {{ MBIN_CHANGE_TABLE = {{ MBIN_FILE_SOURCE = {

--Freighter and Frigate
		"MODELS\COMMON\SPACECRAFT\COMMONPARTS\HANGARINTERIORPARTS\BRIDGE.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\COMMONPARTS\HANGARINTERIORPARTS\BRIDGETERMINAL.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\COMMONPARTS\HANGARINTERIORPARTS\CENTRESUPPORT.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\COMMONPARTS\HANGARINTERIORPARTS\DOORSBACK.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\COMMONPARTS\HANGARINTERIORPARTS\DOORSFRONT.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\COMMONPARTS\HANGARINTERIORPARTS\HANGARLAYOUT.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\INDUSTRIAL\TURRET\TURRETA.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\INDUSTRIAL\HULL\HULL_A.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\INDUSTRIAL\HULL\HULL_B.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\INDUSTRIAL\ACCESSORIES\BRIDGEA.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\INDUSTRIAL\ACCESSORIES\HANGARA_EXTERIOR.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\INDUSTRIAL\ACCESSORIES\LANDINGPAD_HANGAR.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\INDUSTRIAL\ACCESSORIES\SPOTLIGHT\SPOTLIGHT.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\INDUSTRIAL\ACCESSORIES\SPOTLIGHT\SPOTLIGHT_2.SCENE.MBIN",		
		"MODELS\COMMON\SPACECRAFT\FRIGATES\COMBATFRIGATELOD0.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\FRIGATES\DIPLOMATICFRIGATELOD0.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\FRIGATES\DIPLOMATICLODNODE.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\FRIGATES\INDUSTRIALFRIGATELOD0.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\FRIGATES\INDUSTRIALFRIGATELOD1.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\FRIGATES\INDUSTRIALLODNODE.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\FRIGATES\SCIENCEFRIGATELOD0.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\FRIGATES\SCIENCELODNODE.SCENE.MBIN",
		"MODELS\COMMON\SPACECRAFT\FRIGATES\SUPPORTFRIGATELOD0.SCENE.MBIN",
		},
		
EXML_CHANGE_TABLE = {
	-- {SPECIAL_KEY_WORDS		= {"Name","FOV"},
		-- REPLACE_TYPE 		= "ALL",
		-- VALUE_CHANGE_TABLE	= {
			-- {"Value", LightFOV}}},
	{SPECIAL_KEY_WORDS 		= {"Name","FALLOFF"},
		REPLACE_TYPE 		= "ALL",
		VALUE_CHANGE_TABLE	= {
			{"Value", LightFalloff}}},
	{SPECIAL_KEY_WORDS 		= {"Name","INTENSITY","Value","IGNORE"},
		["MATH_OPERATION"]		= "*",
		REPLACE_TYPE 		= "ALL",
		VALUE_CHANGE_TABLE	= {
			{"IGNORE", LightMultiplier}}},
	-- {SPECIAL_KEY_WORDS = {"Name","COL_R"},
		-- REPLACE_TYPE 		= "ALL",
		-- VALUE_CHANGE_TABLE	= {
			-- {"Value", LightRedOf1}}},
	-- {SPECIAL_KEY_WORDS = {"Name","COL_G"},
		-- REPLACE_TYPE 		= "ALL",
		-- VALUE_CHANGE_TABLE	= {
			-- {"Value", LightGreenOf1}}},
	-- {SPECIAL_KEY_WORDS = {"Name","COL_B"},	
	-- REPLACE_TYPE 		= "ALL",
		-- VALUE_CHANGE_TABLE	= {
			-- {"Value", LightBlueOf1}}}
}}}}}}