LightFOV = 360
LightFalloff = "linear"						--"quadratic" ; use linear if your lights are dim, quadratic if they are really bright
LightMultiplier = 0.5						--1
LightRedOf1 = 1.0
LightGreenOf1 = 1.0
LightBlueOf1 = 1.0

NMS_MOD_DEFINITION_CONTAINER = {
MOD_FILENAME		= "GLights 234a Nexus.pak",
MOD_DESCRIPTION		= "Nexus light modifications",
MOD_AUTHOR			= "Gumsk",
NMS_VERSION			= "2.3.4",
MODIFICATIONS		= {{ MBIN_CHANGE_TABLE = {{ MBIN_FILE_SOURCE = {

--Anomaly/Nexus
		"MODELS\SPACE\NEXUS\NEXUS.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\NEXUSCORE.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\NEXUSEXTERIOR.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\TERMINALS\NEXUSBLUEPRINTANALYSER.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\SECTIONS\HEAVYPILLAR.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\SECTIONS\VISTALARGEPROP5.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\SECTIONS\VISTALARGEPROP6.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\RIGHTSECTION\SHOPBIG.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\RIGHTSECTION\SHOPSMALL.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\RIGHTSECTION\RIGHTSECTION.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\RIGHTSECTION\BALCONYVISTA.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\NADAPOLOROOM\CONTROLROOM.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\NADAPOLOROOM\PARTS\FAN.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\MAINHALLWAY\ROBOARM.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\MAINHALLWAY\HALLWAY.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\MAINHALLWAY\PARTS\WALLDETAIL.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\MAINHALLWAY\PARTS\SUPPORT.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\LIGHTING\SMALLSIDELIGHT.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\LIGHTING\LIGHTCOLLUMN.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\LIGHTING\SMALLLIGHTCOLLUMN.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\LEFTAREA\LEFTAREA.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\LANDINGPAD\LANDINGPAD.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\LANDINGBAYS\LANDINGLIGHT.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\LANDINGBAYS\LANDINGBAYS.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\DOORS\FORWARDDOOR.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\DOORS\LEFTDOOR.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\DOORS\MAINAIRLOCK.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\DOORS\MARKETDOOR.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\DOORS\ROOMDOOR.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\CORRIDOR\CORRIDOR.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\BUILDINGFRONT\BUILDINGFRONT.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\BRIDGE\BRIDGEROOM.SCENE.MBIN",
		"MODELS\SPACE\NEXUS\PARTS\BRIDGE\LARGETERMINAL.SCENE.MBIN",

--Anomaly (old?)
		"MODELS\SPACE\ANOMALY\ANOMALY.SCENE.MBIN",
		"MODELS\SPACE\ANOMALY\PARTS\CORE\CENTRALCORE_1.SCENE.MBIN",
		"MODELS\SPACE\ANOMALY\PARTS\DOORS\FORWARDDOOR.SCENE.MBIN",
		"MODELS\SPACE\ANOMALY\PARTS\DOORS\LEFTDOOR.SCENE.MBIN",
		"MODELS\SPACE\ANOMALY\PARTS\DOORS\MAINAIRLOCK.SCENE.MBIN",
		"MODELS\SPACE\ANOMALY\PARTS\DOORS\ROOMDOOR.SCENE.MBIN"
		},
		
EXML_CHANGE_TABLE = {
	-- {SPECIAL_KEY_WORDS		= {"Name","FOV"},
		-- REPLACE_TYPE 		= "ALL",
		-- VALUE_CHANGE_TABLE	= {
			-- {"Value", LightFOV}}},
	{SPECIAL_KEY_WORDS 		= {"Name","FALLOFF"},
		REPLACE_TYPE 		= "ALL",
		VALUE_CHANGE_TABLE	= {
			{"Value", LightFalloff}}},
	{SPECIAL_KEY_WORDS 		= {"Name","INTENSITY","Value","IGNORE"},
		["MATH_OPERATION"]		= "*",
		REPLACE_TYPE 		= "ALL",
		VALUE_CHANGE_TABLE	= {
			{"IGNORE", LightMultiplier}}},
	-- {SPECIAL_KEY_WORDS = {"Name","COL_R"},
		-- REPLACE_TYPE 		= "ALL",
		-- VALUE_CHANGE_TABLE	= {
			-- {"Value", LightRedOf1}}},
	-- {SPECIAL_KEY_WORDS = {"Name","COL_G"},
		-- REPLACE_TYPE 		= "ALL",
		-- VALUE_CHANGE_TABLE	= {
			-- {"Value", LightGreenOf1}}},
	-- {SPECIAL_KEY_WORDS = {"Name","COL_B"},	
	-- REPLACE_TYPE 		= "ALL",
		-- VALUE_CHANGE_TABLE	= {
			-- {"Value", LightBlueOf1}}}
}}}}}}