MainDiffuse = "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/COMMON/HFBACKPLATE_GOLDSUBTILIS.DDS" -- MAIN DIFFUSE MAP
MainMasks = "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/COMMON/HFBACKPLATE_GOLDSUBTILIS.MASKS.DDS" -- MAIN MASKS MAP
MainNormal = "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/COMMON/HFBACKPLATE_GOLDSUBTILIS.NORMAL.DDS" -- MAIN NORMAL MAP

TileDiffuse = "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/BUILDABLEBUILDINGS/INTERIORFREIGHTERTILE_HFBACKPLATE_GOLDSUBTILIS.DDS" -- TILING DIFFUSE MAP
TileMasks = "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/BUILDABLEBUILDINGS/INTERIORFREIGHTERTILE_HFBACKPLATE_GOLDSUBTILIS.MASKS.DDS" -- TILING MASKS MAP
TileNormal = "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/BUILDABLEBUILDINGS/INTERIORFREIGHTERTILE_HFBACKPLATE_GOLDSUBTILIS.NORMAL.DDS" -- TILING NORMAL MAP

MetalDiffuse = "TEXTURES/SPACE/SPACESTATION/INTERIOR/METALHORIZONTALPATTERN_HFBACKPLATE_GOLDSUBTILIS.DDS" -- METAL DIFFUSE
MetalMasks = "TEXTURES/SPACE/SPACESTATION/INTERIOR/METALHORIZONTALPATTERN_HFBACKPLATE_GOLDSUBTILIS.MASKS.DDS" -- METAL MASKS MAP
MetalNormal = "TEXTURES/SPACE/SPACESTATION/INTERIOR/METALHORIZONTALPATTERN_HFBACKPLATE_GOLDSUBTILIS.NORMAL.DDS" -- METAL NORMAL MAP

Version = "1.0"
Game_Version = "4.23"
Mod_Author = "hemis FEAR"
Lua_Author = "hemis FEAR"

NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"]	= "_hF_fBackplate_GoldSubtilis_"..Version..".pak",
["MOD_AUTHOR"]		= Mod_Author,
["LUA_AUTHOR"]		= Lua_Author,
["NMS_VERSION"]		= Game_Version,
["MOD_VERSION"] 	= Version,
["MOD_DESCRIPTION"]	= "fBackplate: Gold Subtilis Freighter Back Wall & Doors",
["MODIFICATIONS"]	= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	=	
					{
					"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSFRONT/HANGARCOMMON_MAT12.MATERIAL.MBIN",
					"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSBACK/HANGARCOMMON_MAT12.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gDiffuseMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", MainDiffuse } --Original "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/COMMON/COMMONTILLED.DDS" 
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gMasksMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", MainMasks } --Original "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/COMMON/COMMONTILLED.MASKS.DDS" 
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gNormalMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", MainNormal } --Original "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/COMMON/COMMONTILLED.NORMAL.DDS"
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name", "gMaterialParamsVec4"},	
							["INTEGER_TO_FLOAT"]    = "FORCE",							
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"x",	"0"}-- Original "0.9"
							}
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	=	"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSFRONT/INTERIORFREIGHTERTILE_MAT12.MATERIAL.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gDiffuseMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", TileDiffuse } --Original "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/BUILDABLEBUILDINGS/INTERIORFREIGHTERTILE.DDS" 
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gMasksMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", TileMasks } --Original "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/BUILDABLEBUILDINGS/INTERIORFREIGHTERTILE.MASKS.DDS" 
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gNormalMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", TileNormal } --Original "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/BUILDABLEBUILDINGS/INTERIORFREIGHTERTILE.NORMAL.DDS"
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name", "gMaterialParamsVec4"},	
							["INTEGER_TO_FLOAT"]    = "FORCE",							
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"x",	"0"}-- Original "0.9"
							}
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	=	
					{
					"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSFRONT/METALHORZ_MAT2.MATERIAL.MBIN",
					"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSBACK/METALHORZ_MAT2.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gDiffuseMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", MetalDiffuse } --Original "TEXTURES/SPACE/SPACESTATION/INTERIOR/METALHORIZONTALPATTERN.DDS" 
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gMasksMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", MetalMasks } --Original "TEXTURES/SPACE/SPACESTATION/INTERIOR/METALHORIZONTALPATTERN.MASKS.DDS" 
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","gNormalMap",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Map", MetalNormal } --Original "TEXTURES/SPACE/SPACESTATION/INTERIOR/METALHORIZONTALPATTERN.NORMAL.DDS"
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name", "gMaterialParamsVec4"},	
							["INTEGER_TO_FLOAT"]    = "FORCE",							
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"x",	"0"}-- Original "0.9"
							}
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= 
					{
						"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSBACK/GLOW_MAT19.MATERIAL.MBIN",
						"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSBACK/GLOW_MAT13.MATERIAL.MBIN",
						"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSFRONT/GLOW_MAT13.MATERIAL.MBIN",
						"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSFRONT/GLOW_MAT6.MATERIAL.MBIN",
						"MODELS/COMMON/SPACECRAFT/COMMONPARTS/HANGARINTERIORPARTS/DOORSFRONT/PHONG153.MATERIAL.MBIN",
					},	
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name", "gMaterialColourVec4"},
							["INTEGER_TO_FLOAT"]    = "FORCE",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"x",		"0.100000"}, 	
								{"y",		"0.800000"},
								{"z",		"0.875000"},
							}
						}
					}
				}
			}
		}
	}	
}