CODES_NMS_LOC6_ENGLISH = {
{"WEATHER_SWAMP1", "Tropical Storms"},
{"WEATHER_SWAMP2", "Occasional Boiling Fog"},
{"WEATHER_SWAMP3", "Superheated Mists"},
{"WEATHER_SWAMP4", "Painful Mist"},
{"WEATHER_SWAMP5", "Infrequent Torrents"},
{"WEATHER_SWAMP6", "Oppressive"},
{"WEATHER_SWAMP7", "Soggy Danger"},
{"WEATHER_SWAMP8", "Sticky Heat"},
{"WEATHER_SWAMP9", "Clammy Menace"},
{"WEATHER_SWAMP10", "Hazardous Moisture"},
{"WEATHER_SWAMP_CLEAR1", "Gentle Mist"},
{"WEATHER_SWAMP_CLEAR2", "Humid"},
{"WEATHER_SWAMP_CLEAR3", "Tropical Winds"},
{"WEATHER_SWAMP_CLEAR4", "Warm Fog"},
{"WEATHER_SWAMP_CLEAR5", "Temperate Murk"},
{"WEATHER_SWAMP_CLEAR6", "Mild Damp"},
{"WEATHER_SWAMP_CLEAR7", "Warm Dewdrops"},
{"WEATHER_SWAMP_CLEAR8", "Tepid Damp"},
{"WEATHER_SWAMP_CLEAR9", "Sweaty Drizzle"},
{"WEATHER_SWAMP_CLEAR10", "Muggy Haze"},
{"WEATHER_SWAMP_EXTREME1", "Death Fog"},
{"WEATHER_SWAMP_EXTREME2", "Sultry Disaster"},
{"WEATHER_SWAMP_EXTREME3", "Cataclysmic Monsoons"},
{"WEATHER_SWAMP_EXTREME4", "Mists of Annihilation"},
{"WEATHER_SWAMP_EXTREME5", "All-Consuming Fog"},
{"WEATHER_SWAMP_EXTREME6", "Liquid Hell"},
{"WEATHER_SWAMP_EXTREME7", "Storms of Desolation"},
{"WEATHER_SWAMP_EXTREME8", "Melting Deluges"},
{"WEATHER_SWAMP_EXTREME9", "Boiling Catastrophe"},
{"WEATHER_SWAMP_EXTREME10", "Damp Misery"},
{"WEATHER_LAVA1", "Heated Gas Pockets"},
{"WEATHER_LAVA2", "Occasional Firestorms"},
{"WEATHER_LAVA3", "Incendiary Winds"},
{"WEATHER_LAVA4", "Unpredictable Conflagrations"},
{"WEATHER_LAVA5", "Drifting Firestorms"},
{"WEATHER_LAVA6", "Pillars of Flame"},
{"WEATHER_LAVA7", "Magma Geysers"},
{"WEATHER_LAVA8", "Plumes of Fire"},
{"WEATHER_LAVA9", "Molten Rain"},
{"WEATHER_LAVA10", "Tectonic Storms"},
{"WEATHER_LAVA11", "Smothering Ash"},
{"WEATHER_LAVA_CLEAR1", "Sulphurous Haze"},
{"WEATHER_LAVA_CLEAR2", "Ash Wisps"},
{"WEATHER_LAVA_CLEAR3", "Drifting Smog"},
{"WEATHER_LAVA_CLEAR4", "Cinderfalls"},
{"WEATHER_LAVA_CLEAR5", "Ash Plumes"},
{"WEATHER_LAVA_CLEAR6", "Choking Ash"},
{"WEATHER_LAVA_CLEAR7", "Burning Mists"},
{"WEATHER_LAVA_CLEAR8", "Sulfur Fumes"},
{"WEATHER_LAVA_CLEAR9", "Enveloping Ash"},
{"WEATHER_LAVA_CLEAR10", "Ashen Winds"},
{"WEATHER_LAVA_EXTREME1", "Frequent Firestorms"},
{"WEATHER_LAVA_EXTREME2", "Walls of Flame"},
{"WEATHER_LAVA_EXTREME3", "Clouds of Fire"},
{"WEATHER_LAVA_EXTREME4", "Ashen Destruction"},
{"WEATHER_LAVA_EXTREME5", "Magma Rain"},
{"WEATHER_LAVA_EXTREME6", "Basalt Hail"},
{"WEATHER_LAVA_EXTREME7", "Explosive Gas Eruptions"},
{"WEATHER_LAVA_EXTREME8", "Lethal Ash Storms"},
{"WEATHER_LAVA_EXTREME9", "Sulphurous Inferno"},
{"WEATHER_LAVA_EXTREME10", "Colossal Firestorms"},
{"WEATHER_LAVA_EXTREME11", "Obsidian Doom"},
{"WEATHER_WATERWORLD1", "Coastal Storms"},
}

CODES_NMS_UPDATE3_ENGLISH = {
{"WEATHER_HEAT1", "Infrequent Heat Storms"},
{"WEATHER_HEAT2", "Rare Firestorms"},
{"WEATHER_HEAT3", "Superheated Gas Pockets"},
{"WEATHER_HEAT4", "Wandering Hot Spots"},
{"WEATHER_HEAT5", "Atmospheric Heat Instabilities"},
{"WEATHER_HEAT6", "Direct Sunlight"},
{"WEATHER_HEAT7", "Heated Atmosphere"},
{"WEATHER_HEAT8", "Occasional Ash Storms"},
{"WEATHER_HEAT9", "Dangerously Hot"},
{"WEATHER_HEAT10", "Burning Air"},
{"WEATHER_HEAT_CLEAR1", "Parched"},
{"WEATHER_HEAT_CLEAR2", "Overly Warm"},
{"WEATHER_HEAT_CLEAR3", "Sunny"},
{"WEATHER_HEAT_CLEAR4", "Dehydrated"},
{"WEATHER_HEAT_CLEAR5", "Unending Sunlight"},
{"WEATHER_HEAT_CLEAR6", "Direct Sunlight"},
{"WEATHER_HEAT_CLEAR7", "Heated Atmosphere"},
{"WEATHER_HEAT_CLEAR8", "Sweltering"},
{"WEATHER_HEATEXTREME1", "Extreme Heat"},
{"WEATHER_HEATEXTREME2", "Burning Gas Clouds"},
{"WEATHER_HEATEXTREME3", "Intense Heat"},
{"WEATHER_HEATEXTREME4", "Superheated Air"},
{"WEATHER_HEATEXTREME5", "Scalding Heat"},
{"WEATHER_HEATEXTREME6", "Inferno Winds"},
{"WEATHER_HEATEXTREME7", "Firestorms"},
{"WEATHER_HEATEXTREME8", "Combustible Dust"},
{"WEATHER_HEATEXTREME9", "Incendiary Dust"},
{"WEATHER_HEATEXTREME10", "Self-Igniting Storms"},
{"WEATHER_COLDEXTREME1", "Howling Blizzards"},
{"WEATHER_COLDEXTREME2", "Intense Cold"},
{"WEATHER_COLDEXTREME3", "Icy Tempests"},
{"WEATHER_COLDEXTREME4", "Supercooled Storms"},
{"WEATHER_COLDEXTREME5", "Raging Snowstorms"},
{"WEATHER_COLDEXTREME6", "Ice Storms"},
{"WEATHER_COLDEXTREME7", "Deep Freeze"},
{"WEATHER_COLDEXTREME8", "Roaring Ice Storms"},
{"WEATHER_COLDEXTREME9", "Frequent Blizzards"},
{"WEATHER_COLDEXTREME10", "Hazardous Whiteouts"},
{"WEATHER_COLD1", "Frozen Clouds"},
{"WEATHER_COLD2", "Occasional Snowfall"},
{"WEATHER_COLD3", "Infrequent Blizzards"},
{"WEATHER_COLD4", "Outbreaks of Frozen Rain"},
{"WEATHER_COLD5", "Harsh, Icy Winds"},
{"WEATHER_COLD6", "Drifting Snowstorms"},
{"WEATHER_COLD7", "Ice Storms"},
{"WEATHER_COLD8", "Migratory Blizzards"},
{"WEATHER_COLD9", "Icy Blasts"},
{"WEATHER_COLD10", "Wandering Frosts"},
{"WEATHER_COLD_CLEAR1", "Powder Snow"},
{"WEATHER_COLD_CLEAR2", "Wintry"},
{"WEATHER_COLD_CLEAR3", "Snowy"},
{"WEATHER_COLD_CLEAR4", "Icy"},
{"WEATHER_COLD_CLEAR5", "Crisp"},
{"WEATHER_COLD_CLEAR6", "Frost"},
{"WEATHER_COLD_CLEAR7", "Freezing"},
{"WEATHER_COLD_CLEAR8", "Permafrost"},
{"WEATHER_TOXICEXTREME1", "Frequent Toxic Floods"},
{"WEATHER_TOXICEXTREME2", "Toxic Superstorms"},
{"WEATHER_TOXICEXTREME3", "Acidic Deluges"},
{"WEATHER_TOXICEXTREME4", "Corrosive Cyclones"},
{"WEATHER_TOXICEXTREME5", "Caustic Floods"},
{"WEATHER_TOXICEXTREME6", "Corrosive Storms"},
{"WEATHER_TOXICEXTREME7", "Torrential Acid"},
{"WEATHER_TOXICEXTREME8", "Noxious Gas Storms"},
{"WEATHER_TOXICEXTREME9", "Toxic Monsoons"},
{"WEATHER_TOXICEXTREME10", "Bone-Stripping Acid Storms"},
{"WEATHER_TOXICEXTREME11", "Corrosive Rainstorms"},
{"WEATHER_TOXICEXTREME12", "Pouring Toxic Rain"},
{"WEATHER_TOXIC1", "Occasional Acid Storms"},
{"WEATHER_TOXIC2", "Atmospheric Corruption"},
{"WEATHER_TOXIC3", "Poison Flurries"},
{"WEATHER_TOXIC4", "Toxic Outbreaks"},
{"WEATHER_TOXIC5", "Acidic Dust Pockets"},
{"WEATHER_TOXIC6", "Passing Toxic Fronts"},
{"WEATHER_TOXIC7", "Caustic Winds"},
{"WEATHER_TOXIC8", "Alkaline Cloudbursts"},
{"WEATHER_TOXIC9", "Dangerously Toxic Rain"},
{"WEATHER_TOXIC10", "Corrosive Sleet Storms"},
{"WEATHER_TOXIC11", "Lethal Atmosphere"},
{"WEATHER_TOXIC12", "Infrequent Toxic Drizzle"},
{"WEATHER_TOXIC_CLEAR1", "Acid Rain"},
{"WEATHER_TOXIC_CLEAR2", "Toxic Clouds"},
{"WEATHER_TOXIC_CLEAR3", "Poison Rain"},
{"WEATHER_TOXIC_CLEAR4", "Choking Clouds"},
{"WEATHER_TOXIC_CLEAR5", "Caustic Moisture"},
{"WEATHER_TOXIC_CLEAR6", "Poisonous Gas"},
{"WEATHER_TOXIC_CLEAR7", "Stinging Atmosphere"},
{"WEATHER_TOXIC_CLEAR8", "Toxic Damp"},
{"WEATHER_TOXIC_CLEAR9", "Corrosive Damp"},
{"WEATHER_TOXIC_CLEAR10", "Stinging Puddles"},
{"WEATHER_RADIOEXTREME1", "Extreme Radioactivity"},
{"WEATHER_RADIOEXTREME2", "Irradiated Thunderstorms"},
{"WEATHER_RADIOEXTREME3", "Planet-Wide Radiation Storms"},
{"WEATHER_RADIOEXTREME4", "Extreme Atmospheric Decay"},
{"WEATHER_RADIOEXTREME5", "Roaring Nuclear Wind"},
{"WEATHER_RADIOEXTREME6", "Gamma Cyclones"},
{"WEATHER_RADIOEXTREME7", "Contaminated Squalls"},
{"WEATHER_RADIOEXTREME8", "Extreme Thermonuclear Fog"},
{"WEATHER_RADIOEXTREME9", "Frequent Particle Eruptions"},
{"WEATHER_RADIOEXTREME10", "Enormous Nuclear Storms"},
{"WEATHER_RADIO1", "Particulate Winds"},
{"WEATHER_RADIO2", "Energetic Storms"},
{"WEATHER_RADIO3", "Irradiated Downpours"},
{"WEATHER_RADIO4", "Radioactive Dust Storms"},
{"WEATHER_RADIO5", "Volatile Windstorms"},
{"WEATHER_RADIO6", "Occasional Radiation Outbursts"},
{"WEATHER_RADIO7", "Irradiated Storms"},
{"WEATHER_RADIO8", "Unstable Fog"},
{"WEATHER_RADIO9", "Reactive Rain"},
{"WEATHER_RADIO10", "Radioactive Dust Storms"},
{"WEATHER_RADIO_CLEAR1", "Radioactive Humidity"},
{"WEATHER_RADIO_CLEAR2", "Radioactive Damp"},
{"WEATHER_RADIO_CLEAR3", "Irradiated Winds"},
{"WEATHER_RADIO_CLEAR4", "Contaminated Puddles"},
{"WEATHER_RADIO_CLEAR5", "Volatile Winds"},
{"WEATHER_RADIO_CLEAR6", "Unstable Atmosphere"},
{"WEATHER_RADIO_CLEAR7", "Gamma Dust"},
{"WEATHER_RADIO_CLEAR8", "Nuclidic Atmosphere"},
{"WEATHER_LUSHEXTREME1", "Boiling Superstorms"},
{"WEATHER_LUSHEXTREME2", "Intense Heatbursts"},
{"WEATHER_LUSHEXTREME3", "Superheated Rain"},
{"WEATHER_LUSHEXTREME4", "Boiling Monsoons"},
{"WEATHER_LUSHEXTREME5", "Broiling Humidity"},
{"WEATHER_LUSHEXTREME6", "Painfully Hot Rain"},
{"WEATHER_LUSHEXTREME7", "Torrential Heat"},
{"WEATHER_LUSHEXTREME8", "Blistering Floods"},
{"WEATHER_LUSHEXTREME9", "Scalding Rainstorms"},
{"WEATHER_LUSHEXTREME10", "Torrid Deluges"},
{"WEATHER_LUSH1", "Boiling Puddles"},
{"WEATHER_LUSH2", "Sweltering Damp"},
{"WEATHER_LUSH3", "Superheated Drizzle"},
{"WEATHER_LUSH4", "Dangerously Hot Fog"},
{"WEATHER_LUSH5", "Choking Humidity"},
{"WEATHER_LUSH6", "Mostly Calm"},
{"WEATHER_LUSH7", "Occasional Scalding Cloudbursts"},
{"WEATHER_LUSH8", "Usually Mild"},
{"WEATHER_LUSH9", "Blistering Damp"},
{"WEATHER_LUSH10", "Lethal Humidity Outbreaks"},
{"WEATHER_LUSH_CLEAR1", "Temperate"},
{"WEATHER_LUSH_CLEAR2", "Light Showers"},
{"WEATHER_LUSH_CLEAR3", "Mild Rain"},
{"WEATHER_LUSH_CLEAR4", "Refreshing Breeze"},
{"WEATHER_LUSH_CLEAR5", "Humid"},
{"WEATHER_LUSH_CLEAR6", "Pleasant"},
{"WEATHER_LUSH_CLEAR7", "Balmy"},
{"WEATHER_LUSH_CLEAR8", "Mellow"},
{"WEATHER_LUSH_CLEAR9", "Beautiful"},
{"WEATHER_LUSH_CLEAR10", "Blissful"},
{"WEATHER_BARRENEXTREME1", "Billowing Dust Storms"},
{"WEATHER_BARRENEXTREME2", "Choking Sandstorms"},
{"WEATHER_BARRENEXTREME3", "Hazardous Temperature Extremes"},
{"WEATHER_BARRENEXTREME4", "Lung-Burning Night Wind"},
{"WEATHER_BARRENEXTREME5", "Extreme Wind Blasting"},
{"WEATHER_BARRENEXTREME6", "Planetwide Desiccation"},
{"WEATHER_BARRENEXTREME7", "Sand Blizzards"},
{"WEATHER_BARRENEXTREME8", "Howling Gales"},
{"WEATHER_BARRENEXTREME9", "Dead Wastes"},
{"WEATHER_BARRENEXTREME10", "Blasted Atmosphere"},
{"WEATHER_BARREN1", "Occasional Sandstorms"},
{"WEATHER_BARREN2", "Infrequent Dust Storms"},
{"WEATHER_BARREN3", "Intermittent Wind Blasting"},
{"WEATHER_BARREN4", "Parched Sands"},
{"WEATHER_BARREN5", "Sporadic Grit Storms"},
{"WEATHER_BARREN6", "Dust-Choked Winds"},
{"WEATHER_BARREN7", "Highly Variable Temperatures"},
{"WEATHER_BARREN8", "Blasted Atmosphere"},
{"WEATHER_BARREN9", "Freezing Night Winds"},
{"WEATHER_BARREN10", "Ceaseless Drought"},
{"WEATHER_BARREN_CLEAR1", "Moistureless"},
{"WEATHER_BARREN_CLEAR2", "Baked"},
{"WEATHER_BARREN_CLEAR3", "Sterile"},
{"WEATHER_BARREN_CLEAR4", "Clear"},
{"WEATHER_BARREN_CLEAR5", "Unclouded Skies"},
{"WEATHER_BARREN_CLEAR6", "Dry Gusts"},
{"WEATHER_BARREN_CLEAR7", "Withered"},
{"WEATHER_BARREN_CLEAR8", "Icy Nights"},
{"WEATHER_DEAD1", "Perfectly Clear"},
{"WEATHER_DEAD2", "Absent"},
{"WEATHER_DEAD3", "No Atmosphere"},
{"WEATHER_DEAD4", "Utterly Still"},
{"WEATHER_DEAD5", "Peaceful"},
{"WEATHER_DEAD6", "Eerily Calm"},
{"WEATHER_DEAD7", "Airless"},
{"WEATHER_DEAD8", "Silent"},
{"WEATHER_DEAD9", "Inert"},
{"WEATHER_DEAD10", "Clear"},
{"WEATHER_CLEAR1", "Clear"},
{"WEATHER_CLEAR2", "Unclouded Skies"},
{"WEATHER_CLEAR3", "Fair"},
{"WEATHER_CLEAR4", "Fine"},
{"WEATHER_CLEAR5", "Moderate"},
{"WEATHER_CLEAR6", "Peaceful Climate"},
{"WEATHER_CLEAR7", "Tempered"},
{"WEATHER_CLEAR8", "Emollient"},
{"WEATHER_CLEAR9", "Fine"},
{"WEATHER_CLEAR10", "Moderate"},
{"WEATHER_GLITCH1", "Invisible Mist"},
{"WEATHER_GLITCH2", "Internal Rain"},
{"WEATHER_GLITCH3", "Lost Clouds"},
{"WEATHER_GLITCH4", "Crimson Heat"},
{"WEATHER_GLITCH5", "Winds of Glass"},
{"WEATHER_GLITCH6", "Thirsty Clouds"},
{"WEATHER_GLITCH7", "Obsidian Heat"},
{"WEATHER_GLITCH8", "Memories of Frost"},
{"WEATHER_GLITCH9", "Haunted Frost"},
{"WEATHER_GLITCH10", "Indetectable Burning"},
{"WEATHER_GLITCH11", "[REDACTED]"},
{"WEATHER_GLITCH12", "Anomalous"},
{"WEATHER_RED1", "Burning Crimson"},
{"WEATHER_RED2", "Scarlet Rain"},
{"WEATHER_RED3", "Fevered Clouds"},
{"WEATHER_RED4", "Carmine Winds"},
{"WEATHER_RED5", "Red Mist"},
{"WEATHER_RED6", "Flaming Hail"},
{"WEATHER_RED7", "Vermillion Storms"},
{"WEATHER_RED8", "Rain of Atlas"},
{"WEATHER_RED9", "Angered Clouds"},
{"WEATHER_RED10", "Blood Rain"},
{"WEATHER_GREEN1", "Bilious Storms"},
{"WEATHER_GREEN2", "Deadly Pressure Variations"},
{"WEATHER_GREEN3", "Harsh Toxic Wind"},
{"WEATHER_GREEN4", "Corrupted Blood"},
{"WEATHER_GREEN5", "Infinite Toxic Mist"},
{"WEATHER_GREEN6", "Echoes of Acid"},
{"WEATHER_GREEN7", "Poison Cyclones"},
{"WEATHER_GREEN8", "Inescapable Toxins"},
{"WEATHER_GREEN9", "Clouds of Haunted Green"},
{"WEATHER_GREEN10", "Invisible Jade Winds"},
{"WEATHER_BLUE1", "Frozen Mists"},
{"WEATHER_BLUE2", "Electric Rain"},
{"WEATHER_BLUE3", "Azure Storms"},
{"WEATHER_BLUE4", "Extreme Low Pressure"},
{"WEATHER_BLUE5", "All-Consuming Cold"},
{"WEATHER_BLUE6", "Winds from Beyond"},
{"WEATHER_BLUE7", "Unfathomable Storms"},
{"WEATHER_BLUE8", "Unimaginable Blue"},
{"WEATHER_BLUE9", "Ultramarine Wind"},
{"WEATHER_BLUE10", "Inverted Superstorms"},
}

function getChangeTable(codes)
ChangeTable = {}
for i=1,#codes do
	local value = codes[i]
        local prefix = "Test"

	ChangeTable[#ChangeTable+1] = 
						{
							["SPECIAL_KEY_WORDS"] = {"Id", value[1]},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Value", prefix.." - "..value[2]},
							}
						}
end
return ChangeTable
end

NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "ClimateCodes.pak",
["MOD_AUTHOR"]				= "Traj",
["NMS_VERSION"]				= "3.96",
["MODIFICATIONS"] 			= 
	{
		{
			["PAK_FILE_SOURCE"] 	= "NMSARC.86055253.pak",
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= "LANGUAGE\NMS_LOC6_ENGLISH.MBIN",
					["EXML_CHANGE_TABLE"] 	= getChangeTable(CODES_NMS_LOC6_ENGLISH)
				},
				{
					["MBIN_FILE_SOURCE"] 	= "LANGUAGE\NMS_UPDATE3_ENGLISH.MBIN",
					["EXML_CHANGE_TABLE"] 	= getChangeTable(CODES_NMS_UPDATE3_ENGLISH)
				}
			}
		}
	}	
}

--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE