----------------------------------------------------------------------------------------------------
-- mod description
----------------------------------------------------------------------------------------------------

METADATA_MOD_NAME       = "BetterPassiveLootFromFrigates"
METADATA_MOD_AUTHOR     = "FriendlyFirePL"
METADATA_LUA_AUTHOR     = "FriendlyFirePL"
METADATA_NMS_VERSION    = "422"
METADATA_MOD_DESC       = "This mod changes the passive loot generated by different frigate types to items better suited for mid- and late gameplay."



----------------------------------------------------------------------------------------------------
-- loot data structure
----------------------------------------------------------------------------------------------------

-- for each of the 3 frigate types the following variables have been used:
--
-- xF - frigate type
-- xI - loot item
-- xT - loot type
-- xA - amount per stat point, acts as nominator
-- xP - some kind of parameter, acts as denominator
-- xG - message for getting the loot instance
-- xW - message for waiting for the next loot instance

-- formula:
-- [Loot in single instace] = [Floor Of ( [Frigate Stat Score] * [Amount Per Stat Point] / [Parameter] )]

-- assuming max stat of 50 for given frigate type, the parameters have been adjusted for maximum loot of:
--
-- industrial       50 * (1/5) = 10         Salvaged Data
-- trading          50 * (2/5) = 20         Tainted Metal
-- support          50 * (1/10) = 5         Warp Cell
--
-- per frigate per instance



----------------------------------------------------------------------------------------------------
-- loot data
----------------------------------------------------------------------------------------------------

-- industrial frigates
IF = "Mining"
II = "BP_SALVAGE"
IT = "Product"
IA = 1
IP = 5
IG = "%CAP_RACE%, the crew have been busy recovering the technology modules from planetary excavations. We will deposit the &lt;DARK_TECH&gt;Salvaged Data&lt;&gt; in your cargo inventory."
IW = "Welcome aboard %CAP_RACE%. The planetary scavenging crew are currently deployed on mission. I hope to receive news of a successful operation very soon."

-- trading frigates
TF = "Diplomacy"
TI = "AF_METAL"
TT = "Substance"       
TA = 2
TP = 5
TG = "Welcome aboard %CAP_RACE%. I am pleased to report local trade scouts have secured favourable deals across the system. The collected &lt;TITLE&gt;Tainted Metal&lt;&gt; will be transfered to your storage."
TW = "Welcome, %CAP_RACE%. The scouts are currently deployed on trade missions across the local system. I shall report any profitable news as I have it."

-- support frigates
SF = "Support"
SI = "HYPERFUEL1"
ST = "Product"
SA = 1
SP = 10
SG = "A status report, %CAP_RACE%. The generator units are at optimal load and the supply tanks are full. We have prepared the surplus &lt;FUEL&gt;Warp Cells&lt;&gt; for your own personal use."
SW = "Warp fuel generators are running at maximum efficiency, %CAP_RACE%! The supply tanks will soon be full, ready for deployment to your fleet."



----------------------------------------------------------------------------------------------------
-- other variables (not recommended to change)
----------------------------------------------------------------------------------------------------

-- file to be changed
PATH_FRIGATES = "GCFLEETGLOBALS.GLOBAL.MBIN"
PATH_LANGUAGE = "LANGUAGE\\NMS_LOC4_ENGLISH.MBIN"

-- time to generate loot instance in seconds
TIME = 600

-- new text on the button to collect loot
TEXT_COLLECT = "Collect Items"

-- list of strings ID to be changed
LIST_ID =
{
    "FLEET_LOOT_MINING_LANG",
    "FLEET_LOOT_TRADE_LANG",
    "FLEET_LOOT_FUEL_LANG",
    "FLEET_LOOT_MINING_WAIT_LANG",
    "FLEET_LOOT_TRADE_WAIT_LANG",
    "FLEET_LOOT_FUEL_WAIT_LANG",
    "FLEET_LOOT_COLLECT_OPT_A",
    "FLEET_LOOT_COLLECT_UNITS_OPT_A",
}

-- list of new strings
LIST_TEXT =
{
    IG,
    TG,
    SG,
    IW,
    TW,
    SW,
    TEXT_COLLECT,
    TEXT_COLLECT,
}



----------------------------------------------------------------------------------------------------
-- mod container
----------------------------------------------------------------------------------------------------

NMS_MOD_DEFINITION_CONTAINER = 
{
    ["MOD_FILENAME"] 	    = "FF_"..METADATA_MOD_NAME.."_"..METADATA_NMS_VERSION..".pak", 
    ["MOD_AUTHOR"]		    = METADATA_MOD_AUTHOR,
    ["LUA_AUTHOR"]		    = METADATA_LUA_AUTHOR,
    ["NMS_VERSION"]		    = METADATA_NMS_VERSION,
    ["MOD_DESCRIPTION"]     = METADATA_MOD_DESC,
    
    ["MODIFICATIONS"]   =
    {
        {
            ["MBIN_CHANGE_TABLE"] =
            {
                {
                    ["MBIN_FILE_SOURCE"] = PATH_FRIGATES,
                    ["EXML_CHANGE_TABLE"] = 
                    {
                        {
                            ["VCT"] = {{"TimeBetweenPassiveIncomeTicks",TIME,},}
                        },
                    }
                },

                {
                    ["MBIN_FILE_SOURCE"] = PATH_LANGUAGE,
                    ["EXML_CHANGE_TABLE"] = {{},},
                }
            }
        }
    }
}



----------------------------------------------------------------------------------------------------
-- functions to modify the files (definetely do not change)
----------------------------------------------------------------------------------------------------

local EXML_LOOT = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][1]["EXML_CHANGE_TABLE"]
local EXML_TEXT = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][2]["EXML_CHANGE_TABLE"]

function MODIFY_LOOT(Frigate,Loot,Type,Amount,Param)
    if Frigate~=nil and Loot~=nil and Type~=nil and Amount~=nil and Param~=nil then
        local CHANGE = 
        {
            ["SKW"] = {Frigate,"GcPassiveFrigateIncome.xml",},
            ["VCT"] = 
            {
                {"IncomeId",Loot},
                {"InventoryType",Type},
                {"AmountOfIncomeRewarded",Amount},
                {"ForEveryXAmountOfTheStat",Param},
            },
        }
        EXML_LOOT[#EXML_LOOT+1] = CHANGE
    end
end

function MODIFY_TEXT(ListID,ListText)
    if ListID~=nil and ListText~=nil and #ListID==#ListText then
        for i=1,#ListID do
            local CHANGE = 
            {
                ["SKW"] = {"Id",ListID[i],},
                ["VCT"] = {{"Value",ListText[i]},},
            }
            EXML_TEXT[#EXML_TEXT+1] = CHANGE
        end
    end
end

MODIFY_LOOT(IF,II,IT,IA,IP)
MODIFY_LOOT(TF,TI,TT,TA,TP)
MODIFY_LOOT(SF,SI,ST,SA,SP)

MODIFY_TEXT(LIST_ID, LIST_TEXT)



----------------------------------------------------------------------------------------------------
-- end of file
----------------------------------------------------------------------------------------------------