-- ============================================================
--  Grass Draw Distance - by kuborr
--  NMS 6.24
-- ============================================================
--
--  What this does:
--    Multiplies FadeOutStartDistance and FadeOutEndDistance on
--    grass objects only. Rocks, flora, props, trees untouched.
--
--  Only grass models are targeted via SPECIAL_KEY_WORDS. 
--  It won't accidentally catch anything else
--  sharing the same biome files.
--
--  Caps are in place so nothing explodes if a biome already has
--  unusually high values (some do, found out the hard way).
--
--  File list per model was verified against REPORT.lua, each
--  model only targets the biome files it actually appears in,
--  which keeps the log clean with zero warnings.
--
--  GRASSVARIATION01 and BONEGRASS are intentionally absent.
--  They produced zero matches against 6.24 game files so they are either
--  removed by HG or renamed at some point.
-- ============================================================


-- ── Tweak these if you want a different multiplier or caps but I would not recommend that ───
local MULTIPLIER    = 2      
local MAX_CAP_LOW   = 999     
local MAX_CAP_HIGH  = 9999    
local VALUE_CEILING = 4999    
-- ─────────────────────────────────────────────────────────────


-- called for FadeOutStartDistance and FadeOutEndDistance
-- multiplies the current value then clamps it so we don't write nonsense into the files
function GrassDistMulCap(_, currentValue)
    local val = tonumber(currentValue)
    if not val then return currentValue end  -- shouldn't happen but just in case

    local result = val * MULTIPLIER

    -- tiered cap - some vanilla values are already in the hundreds so after
    -- multiplying they'd blow past 999 but not necessarily 9999
    if     result > MAX_CAP_HIGH then return tostring(MAX_CAP_HIGH)
    elseif result > MAX_CAP_LOW  then return tostring(MAX_CAP_LOW)
    end

    return tostring(result)
end

-- called for FadeOutOffsetDistance only
function GrassFixOffset(_, currentValue)
    if tonumber(currentValue) == 0 then return "10" end
    return currentValue
end


-- ── Grass model list with their actual biome files ───────────
--
-- Each entry maps one grass model to the biome MBINs it actually
-- lives in.
--
local GRASS_ENTRIES =
{
    -- ── Barren planet grass ──────────────────────────────────

    {   
        
        model = "MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/BARRENGRASSLARGE.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHIVESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQTENTACLEOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMAOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\OBJECTS\MOUNTAIN\MOUNTAINROCKSCRUB.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\OBJECTS\ROCK\BUILDINGDRESSING.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKECRYSTALSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKEPOTATOOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\ROCKY\ROCKOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICSPORESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICTENTACLESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDCRYSTALSOBJECTS.MBIN",
        },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/BARRENGRASSPROC.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOCEANOBJECTSA.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOCEANOBJECTSB.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOCEANOBJECTSC.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENPEACOCKOBJECTS.MBIN",
        },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/BARRENGRASSSMALL.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHIVESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOCEANOBJECTSA.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOCEANOBJECTSB.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOCEANOBJECTSC.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENPEACOCKOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENRUINSOBJECTS.MBIN",
        },
    },
    {   
        
        model = "MODELS/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENCORALOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\FROZENDEADOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LAVA\LAVAISLANDSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LAVA\LAVAOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\OBJECTS\ROCK\BUILDINGDRESSING.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\OBJECTS\ROCK\BUILDINGDRESSINGGLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOBIGPROPSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHCORALOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDSHIELDTREEOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHOCEANOBJECTSA.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHOCEANOBJECTSB.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHOCEANOBJECTSC.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICEGGSMOONOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICEGGSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDCORALOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDFROZENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDHOTOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\CONTOUR\CONTOUROBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\ELBUBBLE\ELBUBBLEOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\FRACTALCUBE\FRACTCUBEOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HYDROGARDEN\HYDROGARDENOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\MSTRUCTURES\MSTRUCTOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\SHARDS\SHARDSOBJECTSDEAD.MBIN",
        },
    },

    -- ── Burnt / scorched grass ───────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/BURNT/BURNTREMIX/BURNTREMIXTALLGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BURNT\BURNTREMIX\BURNTREMIXOBJECTSFULL.MBIN" },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/BURNT/DETAIL/BURNTTALLGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BURNT\BURNTOBJECTSFULL.MBIN" },
    },

    -- ── Cave grass ───────────────────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/NEWCROSSGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\CAVE\CAVEBIOMEGRASSBUSHES.MBIN" },
    },

    -- ── Common/shared grass types ────────────────────────────
    -- These are the ones HG reuses across many different biome types

    {   
        model = "MODELS/PLANETS/BIOMES/COMMON/GRASS/BUBBLELUSHGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLEOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMAOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\OBJECTS\ROCK\BUILDINGDRESSINGGLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKECRYSTALSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKEPOTATOOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICSPORESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICTENTACLESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDCRYSTALSOBJECTS.MBIN",
        },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/COMMON/GRASS/LONGALTGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYWEIRDOBJECTS.MBIN",
        },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWCROSSGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FLORAL\FLORALOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENALIENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENPILLAROBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\HUGERINGOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\HUGEROCKOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGESCORCHED\HUGESCORCHOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\HUGEUWPLANTOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQTENTACLEOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVERUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\ROCKY\ROCKOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\SWAMPISLANDSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\SWAMPOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HYDROGARDEN\HYDROGARDENOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\IRRISHELLS\IRRISHELLSOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\WIRECELLS\WIRECELLSOBJECTSDEAD.MBIN",
        },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWLUSHGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FLORAL\FLORALOBJECTSGRASS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHRUINSOBJECTS.MBIN",
        },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWSCRUBGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHIVESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\OBJECTS\MOUNTAIN\MOUNTAINROCKSCRUB.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\OBJECTS\ROCK\BUILDINGDRESSING.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\OBJECTS\ROCK\BUILDINGDRESSINGGLOW.MBIN",
        },
    },
    {   
        
        model = "MODELS/PLANETS/BIOMES/COMMON/GRASS/TALLGRASSBILLBOARD.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENCORALOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHIVESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENPEACOCKOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\FROZENDEADOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENPILLAROBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGERING\HUGERINGOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEROCK\HUGEROCKOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGESCORCHED\HUGESCORCHOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGETOXIC\HUGETOXICOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGEUWPLANT\HUGEUWPLANTOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LAVA\LAVAISLANDSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LAVA\LAVAOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLEOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEALIENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEGLOWOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVERUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOBIGPROPSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKECRYSTALSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKEPOTATOOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHCORALOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDALIENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDSHIELDTREEOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHOCEANOBJECTSA.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHOCEANOBJECTSB.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHOCEANOBJECTSC.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICEGGSMOONOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICEGGSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOCEANOBJECTSA.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOCEANOBJECTSB.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOCEANOBJECTSC.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICSPORESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICTENTACLESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDCORALOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDCRYSTALSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDFROZENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDHOTOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HYDROGARDEN\HYDROGARDENOBJECTSDEAD.MBIN",
        },
    },

    -- ── Desolate grass ───────────────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/DESOLATE/DETAIL/DESOLATETALLGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DESOLATE\DESOLATEOBJECTSFULL.MBIN" },
    },

    -- ── Frozen/snow planet grass ─────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/HQFROZEN/FOLIAGE/FROZENBUSHYGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\FROZENDEADOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\FROZENDEADWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENALIENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENPILLAROBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDDEADFROZENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDFROZENOBJECTS.MBIN",
        },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/HQFROZEN/FOLIAGE/FROZENGRASSLARGE.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENALIENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENPILLAROBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDFROZENOBJECTS.MBIN",
        },
    },

    -- ── Irradiated / radioactive grass ──────────────────────

    {  
        model = "MODELS/PLANETS/BIOMES/IRRADIATED/DETAIL/IRRADIATEDTALLGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\IRRADIATED\IRRADIATEDOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\IRRADIATED\IRRADREMIX\IRRADREMIXOBJECTSFULL.MBIN",
        },
    },

    -- ── Jungle grass ────────────────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/JUNGLE/DETAIL/JUNGLETALLGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\JUNGLE\JUNGLEOBJECTSFULL.MBIN" },
    },

    -- ── Alien grass ────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/LIVINGSHIP/SMALL/GLOWGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEALIENOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDALIENOBJECTS.MBIN",
        },
    },

    -- ── Noxious / toxic grass ────────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/NOXIOUS/DETAIL/NOXIOUSGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BURNT\BURNTOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BURNT\BURNTREMIX\BURNTREMIXOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DESOLATE\DESOLATEOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\IRRADIATED\IRRADIATEDOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\IRRADIATED\IRRADREMIX\IRRADREMIXOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\JUNGLE\JUNGLEOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\NOXIOUS\NOXIOUSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\NOXIOUS\NOXREMIX\NOXREMIXOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SUBZERO\SUBZEROOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SUBZERO\SUBZREMIX\SUBZREMIXOBJECTSFULL.MBIN",
        },
    },
    {   -- noxious TALL grass
        model = "MODELS/PLANETS/BIOMES/NOXIOUS/DETAIL/NOXIOUSTALLGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\NOXIOUS\NOXIOUSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\NOXIOUS\NOXREMIX\NOXREMIXOBJECTSFULL.MBIN",
        },
    },

    -- ── Subzero grass ────────────────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/SUBZERO/DETAIL/SUBZEROTALLGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SUBZERO\SUBZEROOBJECTSFULL.MBIN" },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/SUBZERO/REMIX/SUBZREMIXTALLGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SUBZERO\SUBZREMIX\SUBZREMIXOBJECTSFULL.MBIN" },
    },

    -- ── Toxic planet grass ───────────────────────────────────

    {   
        
        model = "MODELS/PLANETS/BIOMES/TOXIC/SMALL/TOXICGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGETOXIC\HUGETOXICOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLEOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQTENTACLEOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYWEIRDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMAOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEGLOWOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVEOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOACTIVERUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOBIGPROPSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKECRYSTALSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOSPIKEPOTATOOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICBIGPROPSOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICEGGSMOONOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICEGGSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICINFESTEDOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICISLANDSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOBJECTSDEAD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOBJECTSFULL.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOBJECTSLOW.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOBJECTSMID.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOCEANOBJECTSA.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOCEANOBJECTSB.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICOCEANOBJECTSC.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICRUINSOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICSPORESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICTENTACLESOBJECTS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WATERWORLD\WATERWORLDCRYSTALSOBJECTS.MBIN",
        },
    },

    -- ── Underwater grass ─────────────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/UNDERWATER/DEEPWATER/SMALL/DEEPFLOATGLOWGRASS.SCENE.MBIN",
        files =
        {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\DEEPWATERCOLUMNBLOBS.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\DEEPWATERCOLUMNDENSE.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\DEEPWATERCOLUMNROCKS.MBIN",
        },
    },
    {   -- deep glow grass, only the deepwater glow biome
        model = "MODELS/PLANETS/BIOMES/UNDERWATER/DEEPWATER/SMALL/DEEPGLOWGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\UNDERWATER\DEEPWATERGLOW.MBIN" },
    },

    -- ── Weird planet grass ───────────────────────────────────

    {   
        model = "MODELS/PLANETS/BIOMES/WEIRD/IRRISHELLS/SHELLGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\IRRISHELLS\IRRISHELLSOBJECTSDEAD.MBIN" },
    },
    {   
        model = "MODELS/PLANETS/BIOMES/WEIRD/WIRECELLS/WIRECELLGRASS.SCENE.MBIN",
        files = { "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\WIRECELLS\WIRECELLSOBJECTSDEAD.MBIN" },
    },
}


-- build one MBIN_CHANGE_TABLE entry per model at runtime so we don't have to
-- repeat the same SECTION_UP/REPLACE_TYPE/etc block 28 times by hand
local MBIN_CT = {}
local VCT = {
    {"FadeOutStartDistance",  "GrassDistMulCap()"},
    {"FadeOutEndDistance",    "GrassDistMulCap()"},
    {"FadeOutOffsetDistance", "GrassFixOffset()"},  -- fix 0s, leave 10s alone
}
for _, entry in ipairs(GRASS_ENTRIES) do
    MBIN_CT[#MBIN_CT + 1] =
    {
        ["MBIN_FILE_SOURCE"]  = entry.files,
        ["MXML_CHANGE_TABLE"] =
        {
            {
                ["SPECIAL_KEY_WORDS"]   = {"Filename", entry.model},
                ["SECTION_UP"]          = 2,      -- go up 2 levels from the Filename line to get the object section
                ["REPLACE_TYPE"]        = "ALL",  -- hit every instance in the file, not just the first
                ["VALUE_MATCH"]         = VALUE_CEILING,
                ["VALUE_MATCH_OPTIONS"] = "<",    -- only touch values below VALUE_CEILING
                ["VALUE_CHANGE_TABLE"]  = VCT,
            },
        },
    }
end


NMS_MOD_DEFINITION_CONTAINER =
{
    ["MOD_FILENAME"]    = "_GrassDrawDistance",
    ["MOD_AUTHOR"]      = "kuborr",
    ["LUA_AUTHOR"]      = "kuborr",
    ["NMS_VERSION"]     = "6.24",
    ["MOD_DESCRIPTION"] = "Increases grass draw distance by 2x (grass only, no rocks/flora/props)",

    ["AMUMSS_SUPPRESS_MSG"] = "UNUSED_VARIABLE",

    ["MODIFICATIONS"] = {{ ["MBIN_CHANGE_TABLE"] = MBIN_CT }},
}