-- Escala el coste de materiales (Requirements -> Amount) de todas las piezas de base.
--   1) global xMULT
--   2) piezas estructurales (T_/S_/M_/F_) xMULT_STRUCT  [solo si difiere]
--   3) ids criticos de early-game de vuelta a vanilla
local MULT        = 35
local MULT_STRUCT = 1

local MOD_NAME     = "HardcoreSky_BaseBuildCost"
local GAME_VERSION = "7.02"
local SUFFIX       = "x35_struct1"

-- >>> STRUCT_IDS (generado por extras/gen_structs.py) >>>
local STRUCT_IDS = {
  "CORRIDOR", "CORRIDORC", "CORRIDORL", "CORRIDORL_SPACE", "CORRIDORL_WATER", "CORRIDORT",
  "CORRIDORT_SPACE", "CORRIDORT_WATER", "CORRIDORV_WATER", "CORRIDORX", "CORRIDORX_SPACE", "CORRIDORX_WATER",
  "CORRIDOR_S", "CORRIDOR_SPACE", "CORRIDOR_WATER", "CORRIDOR_WINDOW", "CORSTAIRS_SPACE", "CUBEROOM",
  "CUBEROOMB_SPACE", "CUBEROOMCURVED", "CUBEROOMC_SPACE", "CUBEROOM_SPACE", "CUBEWALL", "CUBEWALL_SPACE",
  "FRE_CORR_A", "FRE_CORR_A_GLAS", "FRE_CORR_A_L", "FRE_CORR_A_STR", "FRE_CORR_A_T", "FRE_CORR_B",
  "FRE_CORR_B_L", "FRE_CORR_B_STR", "FRE_CORR_B_T", "FRE_CORR_GLA_L", "FRE_CORR_GLA_ST", "FRE_CORR_GLA_T",
  "FRE_CORR_G_STA", "FRE_CORR_STA", "FRE_CORR_STA_B", "FRE_EXT_PLATFOR", "FRE_EXT_WALKWAY", "FRE_EXT_W_STA",
  "FRE_FACE_DOOR_A", "FRE_FACE_WALL", "FRE_FACE_WINDOW", "FRE_ROOM_B", "FRE_ROOM_BIO", "FRE_ROOM_COOK",
  "FRE_ROOM_DRESS", "FRE_ROOM_EXTR", "FRE_ROOM_FLEET", "FRE_ROOM_IND", "FRE_ROOM_IND1", "FRE_ROOM_LADDER",
  "FRE_ROOM_NPCBUI", "FRE_ROOM_NPCFAR", "FRE_ROOM_NPCSCI", "FRE_ROOM_NPCVEH", "FRE_ROOM_NPCWEA", "FRE_ROOM_PLANT0",
  "FRE_ROOM_PLANT1", "FRE_ROOM_REFINE", "FRE_ROOM_ROCLOC", "FRE_ROOM_SCAN", "FRE_ROOM_SHOP", "FRE_ROOM_STORE0",
  "FRE_ROOM_STORE1", "FRE_ROOM_STORE2", "FRE_ROOM_STORE3", "FRE_ROOM_STORE4", "FRE_ROOM_STORE5", "FRE_ROOM_STORE6",
  "FRE_ROOM_STORE7", "FRE_ROOM_STORE8", "FRE_ROOM_STORE9", "FRE_ROOM_TECH", "FRE_ROOM_TELEPO", "FRE_ROOM_VEHICL",
  "F_ARCH", "F_ARCHB", "F_ARCHB_H", "F_ARCHM", "F_ARCHM_H", "F_ARCHT",
  "F_ARCHT_H", "F_ARCH_H", "F_CHEV_DOOR", "F_CHEV_WALL", "F_CHEV_WALL_H_C", "F_CHEV_WIN0",
  "F_CHEV_WIN1", "F_CHEV_WIN2", "F_DOOR", "F_DOOR1", "F_DOORB0", "F_DOORB0_H",
  "F_DOORB1", "F_DOORM0", "F_DOORM0_H", "F_DOORM1", "F_DOORT0", "F_DOORT0_H",
  "F_DOORT1", "F_DOORWINB0", "F_DOORWINDOW", "F_DOORWINM0", "F_DOORWINT0", "F_DOOR_H",
  "F_FLOOR", "F_FLOOR_Q", "F_GDOOR", "F_GDOORB0", "F_GDOORM0", "F_GDOORT0",
  "F_GFLOOR", "F_RAMP", "F_RAMP_H", "F_RAMP_Q_TOP", "F_ROOF0", "F_ROOF1",
  "F_ROOF2", "F_ROOF3", "F_ROOF4", "F_ROOF5", "F_ROOF6", "F_ROOF7",
  "F_ROOF8", "F_ROOF_C", "F_ROOF_E_CAP", "F_ROOF_E_Q", "F_ROOF_IC", "F_ROOF_M",
  "F_ROOF_M_CAP", "F_ROOF_M_Q", "F_ROOF_M_WIN", "F_TRIFLOOR", "F_TRIFLOOR_Q", "F_WALL",
  "F_WALLB", "F_WALLB_DIAGONA", "F_WALLB_H", "F_WALLB_WIN0", "F_WALLB_WIN1", "F_WALLB_WIN2",
  "F_WALLB_WIN3", "F_WALLDIAGONAL", "F_WALLM", "F_WALLM_DIAGONA", "F_WALLM_H", "F_WALLM_WIN0",
  "F_WALLM_WIN1", "F_WALLM_WIN2", "F_WALLM_WIN3", "F_WALLT", "F_WALLT_DIAGONA", "F_WALLT_H",
  "F_WALLT_WIN0", "F_WALLT_WIN1", "F_WALLT_WIN2", "F_WALLT_WIN3", "F_WALL_H", "F_WALL_Q",
  "F_WALL_Q1", "F_WALL_Q_H", "F_WALL_Q_H1", "F_WALL_WIN1", "F_WALL_WIN2", "F_WALL_WIN3",
  "F_WALL_WINDOW", "GARAGE_B", "GARAGE_FLOAT", "GARAGE_FREIGHT", "GARAGE_L", "GARAGE_M",
  "GARAGE_MECH", "GARAGE_S", "GARAGE_SUB", "MAINROOM", "MAINROOMCUBE", "MAINROOMCUBEF",
  "MAINROOMCUBE_W", "MAINROOMFRAME", "MAINROOM_WATER", "M_ARCH", "M_ARCH_H", "M_DOOR",
  "M_DOORWINDOW", "M_DOOR_H", "M_FLOOR", "M_FLOOR_Q", "M_GDOOR", "M_GDOOR_D",
  "M_GFLOOR", "M_RAMP", "M_RAMP_H", "M_ROOF", "M_ROOF_C", "M_ROOF_IC",
  "M_ROOF_M", "M_SDOOR", "M_TRIFLOOR", "M_TRIFLOOR_Q", "M_WALL", "M_WALLDIAGONAL",
  "M_WALL_H", "M_WALL_Q", "M_WALL_Q_H", "M_WALL_WINDOW", "S_ARCH", "S_ARCHB",
  "S_ARCHB_H", "S_ARCHM", "S_ARCHM_H", "S_ARCHT", "S_ARCHT_H", "S_ARCH_H",
  "S_CHEV_DOOR", "S_CHEV_WALL", "S_CHEV_WALL_H_C", "S_CHEV_WIN0", "S_CHEV_WIN1", "S_CHEV_WIN2",
  "S_CONTAINER0", "S_CONTAINER1", "S_CONTAINER2", "S_CONTAINER3", "S_CONTAINER4", "S_CONTAINER5",
  "S_CONTAINER6", "S_CONTAINER7", "S_CONTAINER8", "S_CONTAINER9", "S_DOOR", "S_DOOR1",
  "S_DOORB0", "S_DOORB0_H", "S_DOORB1", "S_DOORM0", "S_DOORM0_H", "S_DOORM1",
  "S_DOORT0", "S_DOORT0_H", "S_DOORT1", "S_DOORWINB0", "S_DOORWINDOW", "S_DOORWINM0",
  "S_DOORWINT0", "S_DOOR_H", "S_FLOOR", "S_FLOOR_Q", "S_GDOOR", "S_GDOORB0",
  "S_GDOORM0", "S_GDOORT0", "S_GFLOOR", "S_LANDINGZONE", "S_RAMP", "S_RAMP_H",
  "S_RAMP_Q_TOP", "S_ROOF0", "S_ROOF1", "S_ROOF2", "S_ROOF3", "S_ROOF4",
  "S_ROOF5", "S_ROOF_C", "S_ROOF_E_CAP", "S_ROOF_E_Q", "S_ROOF_IC", "S_ROOF_M",
  "S_ROOF_M_CAP", "S_ROOF_M_Q", "S_ROOF_M_WIN", "S_S_WALL", "S_TOWER", "S_TOWER_B",
  "S_TOWER_B_FA", "S_TOWER_C", "S_TOWER_FA", "S_TRIFLOOR", "S_TRIFLOOR_Q", "S_WALL",
  "S_WALLB", "S_WALLB_DIAGONA", "S_WALLB_H", "S_WALLB_WIN0", "S_WALLB_WIN1", "S_WALLB_WIN2",
  "S_WALLB_WIN3", "S_WALLDIAGONAL", "S_WALLM", "S_WALLM_DIAGONA", "S_WALLM_H", "S_WALLM_WIN0",
  "S_WALLM_WIN1", "S_WALLM_WIN2", "S_WALLM_WIN3", "S_WALLT", "S_WALLT_DIAGONA", "S_WALLT_H",
  "S_WALLT_WIN0", "S_WALLT_WIN1", "S_WALLT_WIN2", "S_WALLT_WIN3", "S_WALL_H", "S_WALL_Q",
  "S_WALL_Q1", "S_WALL_Q_H", "S_WALL_Q_H1", "S_WALL_SUPPORTS", "S_WALL_WIN1", "S_WALL_WIN2",
  "S_WALL_WIN3", "S_WALL_WINDOW", "T_ARCH", "T_ARCHB", "T_ARCHB_H", "T_ARCHM",
  "T_ARCHM_H", "T_ARCHT", "T_ARCHT_H", "T_ARCH_H", "T_CHEV_DOOR", "T_CHEV_WALL",
  "T_CHEV_WALL_H_C", "T_CHEV_WIN0", "T_CHEV_WIN1", "T_CHEV_WIN2", "T_DOOR", "T_DOOR1",
  "T_DOORB0", "T_DOORB0_H", "T_DOORB1", "T_DOORM0", "T_DOORM0_H", "T_DOORM1",
  "T_DOORT0", "T_DOORT0_H", "T_DOORT1", "T_DOORWINB0", "T_DOORWINDOW", "T_DOORWINM0",
  "T_DOORWINT0", "T_DOOR_H", "T_FLOOR", "T_FLOOR_Q", "T_GDOOR", "T_GDOORB0",
  "T_GDOORM0", "T_GDOORT0", "T_GFLOOR", "T_RAMP", "T_RAMP_H", "T_RAMP_Q_TOP",
  "T_ROOF0", "T_ROOF1", "T_ROOF2", "T_ROOF3", "T_ROOF4", "T_ROOF5",
  "T_ROOF6", "T_ROOF7", "T_ROOF_C", "T_ROOF_E_CAP", "T_ROOF_E_Q", "T_ROOF_IC",
  "T_ROOF_M", "T_ROOF_M_CAP", "T_ROOF_M_Q", "T_ROOF_M_WIN", "T_TRIFLOOR", "T_TRIFLOOR_Q",
  "T_WALL", "T_WALLB", "T_WALLB_DIAGONA", "T_WALLB_H", "T_WALLB_WIN0", "T_WALLB_WIN1",
  "T_WALLB_WIN2", "T_WALLB_WIN3", "T_WALLDIAGONAL", "T_WALLM", "T_WALLM_DIAGONA", "T_WALLM_H",
  "T_WALLM_WIN0", "T_WALLM_WIN1", "T_WALLM_WIN2", "T_WALLM_WIN3", "T_WALLT", "T_WALLT_DIAGONA",
  "T_WALLT_H", "T_WALLT_WIN0", "T_WALLT_WIN1", "T_WALLT_WIN2", "T_WALLT_WIN3", "T_WALL_H",
  "T_WALL_Q", "T_WALL_Q1", "T_WALL_Q_H", "T_WALL_Q_H1", "T_WALL_WIN1", "T_WALL_WIN2",
  "T_WALL_WIN3", "T_WALL_WINDOW",
}
-- <<< STRUCT_IDS (generado por extras/gen_structs.py) <<<

local EARLY_EXEMPT_IDS = {
  "BASE_FLAG", "BUILDSAVE", "BUILDTERMINAL", "TELEPORTER", "BUILDLANDINGPAD",
  "NPCSCIENCETERM", "NPCWEAPONTERM", "NPCFARMTERM", "NPCVEHICLETERM", "NPCBUILDERTERM", "NPCFRIGTERM"
}

local function MakeSKW(ids)
  local t = {}
  for _, id in ipairs(ids) do
    t[#t + 1] = { "ID", id }
  end
  return t
end

local CHANGES = {
  {
    PRECEDING_KEY_WORDS = { "Requirements" },
    REPLACE_TYPE        = "ALL",
    INTEGER_TO_FLOAT    = "PRESERVE",
    MATH_OPERATION      = "*",
    VALUE_CHANGE_TABLE  = { { "Amount", MULT } }
  },
}

if MULT_STRUCT ~= MULT then
  table.insert(CHANGES, {
    FOREACH_SKW_GROUP   = MakeSKW(STRUCT_IDS),
    PRECEDING_KEY_WORDS = { "Requirements" },
    REPLACE_TYPE        = "ALL",
    INTEGER_TO_FLOAT    = "PRESERVE",
    MATH_OPERATION      = "*",
    VALUE_CHANGE_TABLE  = { { "Amount", MULT_STRUCT / MULT } }
  })
end

table.insert(CHANGES, {
  FOREACH_SKW_GROUP   = MakeSKW(EARLY_EXEMPT_IDS),
  PRECEDING_KEY_WORDS = { "Requirements" },
  REPLACE_TYPE        = "ALL",
  INTEGER_TO_FLOAT    = "PRESERVE",
  MATH_OPERATION      = "*",
  VALUE_CHANGE_TABLE  = { { "Amount", 1 / MULT } }
})

NMS_MOD_DEFINITION_CONTAINER = {
  MOD_FILENAME    = MOD_NAME .. "_" .. SUFFIX .. ".zip",
  MOD_AUTHOR      = "Azunain",
  LUA_AUTHOR      = "Azunain",
  NMS_VERSION     = GAME_VERSION,
  MOD_DESCRIPTION = string.format(
    "Base part material costs x%d (structural pieces x%d); early-game items stay vanilla",
    MULT, MULT_STRUCT
  ),
  MODIFICATIONS   = {{
    MBIN_CHANGE_TABLE = {{
      MBIN_FILE_SOURCE  = "METADATA/REALITY/TABLES/NMS_BASEPARTPRODUCTS.MBIN",
      MXML_CHANGE_TABLE = CHANGES
    }}
  }}
}