local MOD_NAME     = "HardcoreSky_Fauna_Glitch"
local GAME_VERSION = "7.02"
local MOD_FILENAME = MOD_NAME..".zip"

local DO_ARCH    = 1
local DO_SAND    = 0
local ROLE_VALUE = ""

local GROUND_ARCHS = "WRDFLOAT,WRDROLL,WRDCRYSTAL,WRDBUTTERFLY,WRDROLLPRED,WRDCRYSTALPRED"
local AIR_ARCHS    = ""
local WATER_ARCHS  = ""
local CAVE_ARCHS   = ""

local GEN_FILE = "METADATA/SIMULATION/ECOSYSTEM/CREATUREGENERATIONDATA.MBIN"

local GROUND_TABLES = {
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEALIEN.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEARTHROPODHERB.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEARTHROPODPRED.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEARTHROPODWORLD.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEBONE.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEBUTTERFLY.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEHERBIVOREGIANT.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEHERBIVORELARGE.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEHERBIVOREMED.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEHERBIVORESMALL.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEHERDMED.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEMAYBEBUTTERFLY.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEPLANTCATHERB.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEPLANTCATPRED.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEPLANTCATWORLD.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEPLAYERPREDATORLARGE.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEPLAYERPREDATORMED.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEPREDATORLARGE.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEPREDATORMED.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEROBOT.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/GROUNDTABLEWALKINGBUILDING.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEARTHROPOD.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEBUTTERFLOCK.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEBUTTERFLY.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEDIGGER.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEDRILL.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEFLOATER.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEFLYINGBEETLE.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEHERMITCRAB.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEMOLE.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEPETS.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEPLANTCAT.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEPLOW.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEROLLER.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLESMALLBIRD.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/TEST/GROUNDTABLEWALKINGBUILDING.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDBUTTERFLY.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDCRYSTAL.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDCRYSTALPREDATOR.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDFLOAT.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDGLOWSTRIDERS.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDPURPLE.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDPURPLEBONES.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDROLL.MBIN",
  "METADATA/SIMULATION/ECOSYSTEM/GROUND/WEIRD/GROUNDTABLEWEIRDROLLPREDATOR.MBIN"
}

local function split(s)
  local t = {}
  for w in string.gmatch(s or "", "[^,]+") do
    t[#t + 1] = w
  end
  return t
end

local function domain_block(name, list_text)
  local archs = split(list_text)
  local out = {}
  out[#out + 1] = ('      <Property name="%s">'):format(name)
  if #archs > 0 then
    local w = 1.0 / #archs
    for _, a in ipairs(archs) do
      out[#out + 1] = ('        <Property name="%s" value="GcCreatureGenerationWeightedListDomainEntry">'):format(name)
      out[#out + 1] = ('          <Property name="Weight" value="%0.6f" />'):format(w)
      out[#out + 1] = ('          <Property name="Archetype" value="%s" />'):format(a)
      out[#out + 1] = "        </Property>"
    end
  end
  out[#out + 1] = "      </Property>"
  return table.concat(out, "\n")
end

local ARCHETYPES_BLOCK =
  '    <Property name="Archetypes" value="GcCreatureGenerationWeightedList">\n' ..
  domain_block("Ground", GROUND_ARCHS) .. "\n" ..
  domain_block("Air", AIR_ARCHS) .. "\n" ..
  domain_block("Cave", CAVE_ARCHS) .. "\n" ..
  domain_block("Water", WATER_ARCHS) .. "\n" ..
  "    </Property>"

local SANDWORM_BLOCK = [[
    <Property name="SandwormPresenceChance">
      <Property name="Lush" value="1.000000" />
      <Property name="Toxic" value="1.000000" />
      <Property name="Scorched" value="1.000000" />
      <Property name="Radioactive" value="1.000000" />
      <Property name="Frozen" value="1.000000" />
      <Property name="Barren" value="1.000000" />
      <Property name="Dead" value="1.000000" />
      <Property name="Weird" value="1.000000" />
      <Property name="Red" value="1.000000" />
      <Property name="Green" value="1.000000" />
      <Property name="Blue" value="1.000000" />
      <Property name="Test" value="1.000000" />
      <Property name="Swamp" value="1.000000" />
      <Property name="Lava" value="1.000000" />
      <Property name="Waterworld" value="1.000000" />
      <Property name="GasGiant" value="1.000000" />
      <Property name="All" value="1.000000" />
    </Property>
]]

local GEN_CHANGES = {}

if DO_ARCH == 1 or DO_SAND == 1 then
  GEN_CHANGES[#GEN_CHANGES + 1] = {
    SPECIAL_KEY_WORDS  = {"AbandonedSystemSpecific", "GcCreatureGenerationOptionalWeightedList"},
    VALUE_CHANGE_TABLE = {{"Probability", "1"}, {"OverrideAllDomains", "true"}}
  }
  GEN_CHANGES[#GEN_CHANGES + 1] = {
    SPECIAL_KEY_WORDS  = {"EmptySystemSpecific", "GcCreatureGenerationOptionalWeightedList"},
    VALUE_CHANGE_TABLE = {{"Probability", "1"}, {"OverrideAllDomains", "true"}}
  }
end

if DO_ARCH == 1 then
  GEN_CHANGES[#GEN_CHANGES + 1] = {
    PRECEDING_KEY_WORDS = {"Archetypes"},
    REPLACE_TYPE        = "ALL",
    ADD_OPTION          = "REPLACEwholeSECTION",
    ADD                 = ARCHETYPES_BLOCK
  }
end

if DO_SAND == 1 then
  GEN_CHANGES[#GEN_CHANGES + 1] = {
    PRECEDING_KEY_WORDS = {"SandwormPresenceChance"},
    REPLACE_TYPE        = "ALL",
    ADD_OPTION          = "REPLACEwholeSECTION",
    ADD                 = SANDWORM_BLOCK
  }
end

local MBIN_CHANGE_TABLE = {}

if #GEN_CHANGES > 0 then
  MBIN_CHANGE_TABLE[#MBIN_CHANGE_TABLE + 1] = {
    MBIN_FILE_SOURCE  = GEN_FILE,
    MXML_CHANGE_TABLE = GEN_CHANGES
  }
end

if ROLE_VALUE ~= "" then
  for _, path in ipairs(GROUND_TABLES) do
    MBIN_CHANGE_TABLE[#MBIN_CHANGE_TABLE + 1] = {
      MBIN_FILE_SOURCE  = path,
      MXML_CHANGE_TABLE = {
        { REPLACE_TYPE = "ALL", VALUE_CHANGE_TABLE = {{"CreatureRole", ROLE_VALUE}} }
      }
    }
  end
end

NMS_MOD_DEFINITION_CONTAINER = {
  MOD_FILENAME    = MOD_FILENAME,
  MOD_AUTHOR      = "Azunain",
  LUA_AUTHOR      = "Azunain",
  NMS_VERSION     = GAME_VERSION,
  MOD_DESCRIPTION = "Fauna overhaul: every system spawns glitch (WRD*) ground creatures only.",
  MODIFICATIONS   = {{
    MBIN_CHANGE_TABLE = MBIN_CHANGE_TABLE
  }}
}