---------------------------------------------------------------------------------------
local mod_desc = [[
  Ramp Control Switch Part v1.1 - a standalone buildable part reusing the existing ramp
  control switch mesh (RAMPCONTROL.SCENE.MBIN). Interaction now directly attaches the real
  vanilla AIRLOCK_NESW_B_RAMPCONTROLS.ENTITY.MBIN (the same shared entity the exterior ramp
  switches and cockpit buttons reuse) instead of a custom JANK7_RAMPOPEN/JANK7_RAMPCLOSE
  broadcast entity - this makes the part work on its own, independent of the separate
  Corvette_Ramp_Manual_Control mod's RAMPDATA trigger-state edit.

  CONFIRMED WORKING IN-GAME as of this version's prior build: places on the corvette,
  shows in the build menu, and functions correctly. This round is a polish pass on
  top of that confirmed baseline, not a re-fix of the menu-visibility bug.

  Registers new rows cloned field-for-field from the Shovel's own CURRENT game-version
  entries in BASEBUILDINGOBJECTSTABLE.MBIN (Object "S_JANK7_RAMPSW") and
  BASEBUILDINGPARTSTABLE.MBIN (Part "_JANK7_RAMPSW"), plus BASEBUILDINGAUTOGENERATEDPARTSDATA/
  BASEBUILDINGCOSTSTABLE/DEFAULTSAVEDATA.KnownProducts entries and a Product row in
  NMS_REALITY_GCPRODUCTTABLE.MBIN - all copied from a real, current, working reference
  mod's exact method rather than guessed. Custom files live under a real MODELS\...
  root (MODELS\CUSTOM\PROPS\...), matching actual on-disk/PAK convention.

  This round's changes:
  1. Display name is now real text: "Ramp Control Switch" (Name/NameLower fields take a
     literal string fine, confirmed via the reference mod's own GetProduct()).
  2. Icon is now a custom texture (TEXTURES/UI/FRONTEND/ICONS/PRODUCTS/
     PRODUCT.JANK7RAMPSWITCH.DDS), converted from a user-supplied render with its
     background removed, replacing the placeholder Shovel icon.
  3. Placement-ghost fixed with real evidence instead of a guess: the user pulled
     SWITCH_WALL_PLACEMENT.SCENE/.GEOMETRY.MBIN from a vanilla wall switch "roughly the
     same size" as ours. That confirmed vanilla ghosts commonly aren't low-poly replicas
     of the real mesh at all - they're a plain box, sized to match the collision Box
     exactly. JANK7_RAMPSWITCH_PLACEMENT.SCENE.MXML now copies that real box geometry
     file directly (via a vanilla-file-copy MBIN_CHANGE_TABLE entry, same idiom the
     reference mod uses) instead of the old REFERENCE-to-full-mesh + guessed Sphere.
     Box dimensions and AutoPartData's MagicData bounds were updated to match this real,
     evidence-based footprint instead of the earlier guessed sphere-derived numbers.
]]-------------------------------------------------------------------------------------

-- Cloned from BASEBUILDINGOBJECTSTABLE.MBIN's real S_SHOVEL entry (current game version),
-- field-for-field, except ID and PlacementScene.
local OBJECT_ADD = [[
		<Property name="Objects" value="GcBaseBuildingEntry" _id="S_JANK7_RAMPSW">
			<Property name="ID" value="S_JANK7_RAMPSW" />
			<Property name="IsTemporary" value="false" />
			<Property name="IsFromModFolder" value="true" />
			<Property name="Style" value="GcBaseBuildingPartStyle">
				<Property name="Style" value="None" />
			</Property>
			<Property name="PlacementScene" value="TkModelResource">
				<Property name="Filename" value="MODELS\CUSTOM\PROPS\JANK7_RAMPSWITCH_PLACEMENT.SCENE.MBIN" />
				<Property name="Seed" value="0" />
			</Property>
			<Property name="SinglePartID" value="" />
			<Property name="DecorationType" value="GcBaseBuildingObjectDecorationTypes">
				<Property name="BaseBuildingDecorationType" value="SurfaceNormal" />
			</Property>
			<Property name="IsPlaceable" value="true" />
			<Property name="IsPlaceableFloatingInSpace" value="false" />
			<Property name="IsDecoration" value="true" />
			<Property name="Biome" value="GcBiomeType">
				<Property name="Biome" value="Lush" />
			</Property>
			<Property name="BuildableOnPlanetBase" value="false" />
			<Property name="BuildableOnSpaceBase" value="false" />
			<Property name="BuildableOnFreighter" value="false" />
			<Property name="BuildableInShipStructural" value="false" />
			<Property name="BuildableInShipDecorative" value="true" />
			<Property name="BuildableOnPlanet" value="false" />
			<Property name="BuildableOnPlanetWithProduct" value="false" />
			<Property name="BuildableUnderwater" value="false" />
			<Property name="BuildableAboveWater" value="true" />
			<Property name="BuildableOnSpaceStationBase" value="false" />
			<Property name="BuildableOnSpaceStationBackSection" value="false" />
			<Property name="BuildableOnSpaceStationExterior" value="false" />
			<Property name="PlanetLimit" value="0" />
			<Property name="RegionLimit" value="0" />
			<Property name="PlanetBaseLimit" value="0" />
			<Property name="FreighterBaseLimit" value="0" />
			<Property name="CorvetteBaseLimit" value="0" />
			<Property name="DoesNotCountTowardsComplexity" value="false" />
			<Property name="CheckPlaceholderCollision" value="false" />
			<Property name="CheckPlayerCollision" value="true" />
			<Property name="CanStack" value="true" />
			<Property name="SnapRotateBlocked" value="false" />
			<Property name="CanRotate3D" value="true" />
			<Property name="CanScale" value="false" />
			<Property name="Groups">
				<Property name="Groups" value="GcBaseBuildingEntryGroup" _index="0">
					<Property name="Group" value="BASE_TECH" />
					<Property name="SubGroupName" value="TECHTECH" />
					<Property name="SubGroup" value="0" />
				</Property>
			</Property>
			<Property name="StorageContainerIndex" value="-1" />
			<Property name="ColourPaletteGroupId" value="" />
			<Property name="StationColourPaletteGroupId" value="" />
			<Property name="DefaultColourPaletteId" value="" />
			<Property name="MaterialGroupId" value="" />
			<Property name="DefaultMaterialId" value="" />
			<Property name="CanChangeColour" value="false" />
			<Property name="CanChangeMaterial" value="false" />
			<Property name="CanPickUp" value="false" />
			<Property name="ShowInBuildMenu" value="true" />
			<Property name="CompositePartObjectIDs" />
			<Property name="FamilyIDs" />
			<Property name="BuildEffectAccelerator" value="1.000000" />
			<Property name="IconOverrideProductID" value="" />
			<Property name="RemovesAttachedDecoration" value="false" />
			<Property name="RemovesWhenUnsnapped" value="false" />
			<Property name="EditsTerrain" value="false" />
			<Property name="BaseTerrainEditShape" value="Cube" />
			<Property name="MinimumDeleteDistance" value="1.000000" />
			<Property name="IsSealed" value="false" />
			<Property name="HasGravity" value="false" />
			<Property name="GravityStrength" value="0.500000" />
			<Property name="GravityFalloff" value="2.000000" />
			<Property name="CloseMenuAfterBuild" value="false" />
			<Property name="Tag" value="" />
			<Property name="LinkGridData" value="GcBaseLinkGridData">
				<Property name="Connection" value="GcBaseLinkGridConnectionData">
					<Property name="Network" value="GcLinkNetworkTypes">
						<Property name="LinkNetworkType" value="Power" />
					</Property>
					<Property name="NetworkSubGroup" value="0" />
					<Property name="NetworkMask" value="0" />
					<Property name="ConnectionDistance" value="0.100000" />
					<Property name="UseMinDistance" value="false" />
					<Property name="LinkSocketPositions" />
					<Property name="LinkSocketSubGroups" />
				</Property>
				<Property name="Rate" value="0" />
				<Property name="Storage" value="0" />
				<Property name="DependsOnEnvironment" value="None" />
				<Property name="DependsOnHotspots" value="None" />
				<Property name="DependentConnections" />
			</Property>
			<Property name="GhostsCountOverride" value="0" />
			<Property name="ShowGhosts" value="true" />
			<Property name="SnappingDistanceOverride" value="0.000000" />
			<Property name="RegionSpawnLOD" value="1" />
			<Property name="NPCInteractionScene" value="TkModelResource">
				<Property name="Filename" value="" />
				<Property name="Seed" value="0" />
			</Property>
			<Property name="IsModularCustomisation" value="false" />
			<Property name="ModularCustomisationBaseID" value="" />
			<Property name="HasDescriptor" value="false" />
			<Property name="DescriptorID" value="" />
			<Property name="FossilDisplayID" value="" />
			<Property name="UseProductIDOverride" value="false" />
			<Property name="UseProductIDOverrideInSpace" value="false" />
			<Property name="OverrideProductID" value="" />
		</Property>
]]

-- Cloned from BASEBUILDINGPARTSTABLE.MBIN's real _SHOVEL entry. Model and Inactive both
-- point at the same new custom scene - no separate LOD variant exists yet.
local PART_ADD = [[
		<Property name="Parts" value="GcBaseBuildingPart" _id="_JANK7_RAMPSW">
			<Property name="ID" value="_JANK7_RAMPSW" />
			<Property name="StyleModels">
				<Property name="StyleModels" value="GcBaseBuildingPartStyleModel" _index="0">
					<Property name="Style" value="GcBaseBuildingPartStyle">
						<Property name="Style" value="None" />
					</Property>
					<Property name="Model" value="TkModelResource">
						<Property name="Filename" value="MODELS\CUSTOM\PROPS\JANK7_RAMPSWITCH.SCENE.MBIN" />
						<Property name="Seed" value="0" />
					</Property>
					<Property name="Inactive" value="TkModelResource">
						<Property name="Filename" value="MODELS\CUSTOM\PROPS\JANK7_RAMPSWITCH.SCENE.MBIN" />
						<Property name="Seed" value="0" />
					</Property>
				</Property>
			</Property>
		</Property>
]]

-- Field content cloned from NMS_BASEPARTPRODUCTS.MBIN's real S_SHOVEL entry (schema is
-- identical GcProductData either way), but the MBIN_CHANGE_TABLE entry below now targets
-- NMS_REALITY_GCPRODUCTTABLE.MBIN instead, matching the reference mod's proven method -
-- see that table entry for why. ID matches the OBJECT table's ID (S_JANK7_RAMPSW), not the
-- Part's. Name/NameLower are now real display text ("Ramp Control Switch") - a literal
-- string works fine here without touching localization tables, confirmed by the reference
-- mod's own GetProduct() passing a plain name straight into these fields. Icon now points at
-- our own custom texture (converted from a user-supplied render, background removed).
-- Subtitle and Description are now real literal text (same as Name/NameLower, no
-- localization table needed).
local PRODUCT_ADD = [[
		<Property name="Table" value="GcProductData" _id="S_JANK7_RAMPSW">
			<Property name="ID" value="S_JANK7_RAMPSW" />
			<Property name="Name" value="Landing Bay Actuator" />
			<Property name="NameLower" value="Landing Bay Actuator" />
			<Property name="Subtitle" value="Control System" />
			<Property name="Description" value="A remote actuator unit that controls the opening and closing of landing bays onboard corvette class spacecraft." />
			<Property name="AltDescription" value="" />
			<Property name="Hint" value="" />
			<Property name="BuildableShipTechID" value="" />
			<Property name="GroupID" value="" />
			<Property name="DebrisFile" value="TkModelResource">
				<Property name="Filename" value="MODELS/EFFECTS/DEBRIS/TERRAINDEBRIS/TERRAINDEBRIS4.SCENE.MBIN" />
				<Property name="Seed" value="0" />
			</Property>
			<Property name="BaseValue" value="1" />
			<Property name="Level" value="0" />
			<Property name="Icon" value="TkTextureResource">
				<Property name="Filename" value="TEXTURES/UI/FRONTEND/ICONS/PRODUCTS/PRODUCT.JANK7RAMPSWITCH.DDS" />
			</Property>
			<Property name="HeroIcon" value="TkTextureResource">
				<Property name="Filename" value="" />
			</Property>
			<Property name="Colour">
				<Property name="R" value="0.172549024" />
				<Property name="G" value="0.486274511" />
				<Property name="B" value="0.623529434" />
				<Property name="A" value="1.000000" />
			</Property>
			<Property name="Category" value="GcRealitySubstanceCategory">
				<Property name="SubstanceCategory" value="BuildingPart" />
			</Property>
			<Property name="Type" value="GcProductCategory">
				<Property name="ProductCategory" value="BuildingPart" />
			</Property>
			<Property name="Rarity" value="GcRarity">
				<Property name="Rarity" value="Common" />
			</Property>
			<Property name="Legality" value="GcLegality">
				<Property name="Legality" value="Legal" />
			</Property>
			<Property name="Consumable" value="false" />
			<Property name="ChargeValue" value="0" />
			<Property name="StackMultiplier" value="1" />
			<Property name="DefaultCraftAmount" value="1" />
			<Property name="CraftAmountStepSize" value="1" />
			<Property name="CraftAmountMultiplier" value="1" />
			<Property name="Requirements">
				<Property name="Requirements" value="GcTechnologyRequirement" _id="FUEL1">
					<Property name="ID" value="FUEL1" />
					<Property name="Type" value="GcInventoryType">
						<Property name="InventoryType" value="Substance" />
					</Property>
					<Property name="Amount" value="25" />
				</Property>
			</Property>
			<Property name="AltRequirements" />
			<Property name="Cost" value="GcItemPriceModifiers">
				<Property name="SpaceStationMarkup" value="0.000000" />
				<Property name="LowPriceMod" value="0.000000" />
				<Property name="HighPriceMod" value="0.000000" />
				<Property name="BuyBaseMarkup" value="0.000000" />
				<Property name="BuyMarkupMod" value="0.000000" />
			</Property>
			<Property name="RecipeCost" value="1" />
			<Property name="SpecificChargeOnly" value="false" />
			<Property name="NormalisedValueOnWorld" value="0.000000" />
			<Property name="NormalisedValueOffWorld" value="0.000000" />
			<Property name="TradeCategory" value="GcTradeCategory">
				<Property name="TradeCategory" value="None" />
			</Property>
			<Property name="WikiCategory" value="Construction" />
			<Property name="FossilCategory" value="GcFossilCategory">
				<Property name="FossilCategory" value="None" />
			</Property>
			<Property name="CorvettePartCategory" value="GcCorvettePartCategory">
				<Property name="CorvettePartCategory" value="None" />
			</Property>
			<Property name="CorvetteRewardFrequency" value="0.000000" />
			<Property name="IsCraftable" value="true" />
			<Property name="DeploysInto" value="" />
			<Property name="EconomyInfluenceMultiplier" value="0.000000" />
			<Property name="PinObjective" value="" />
			<Property name="PinObjectiveTip" value="" />
			<Property name="PinObjectiveMessage" value="" />
			<Property name="PinObjectiveScannableType" value="GcScannerIconTypes">
				<Property name="ScanIconType" value="None" />
			</Property>
			<Property name="PinObjectiveEasyToRefine" value="false" />
			<Property name="NeverPinnable" value="false" />
			<Property name="CookingIngredient" value="false" />
			<Property name="CookingValue" value="0.000000" />
			<Property name="FoodBonusStat" value="GcStatsTypes">
				<Property name="StatsType" value="Unspecified" />
			</Property>
			<Property name="FoodBonusStatAmount" value="0.000000" />
			<Property name="GoodForSelling" value="false" />
			<Property name="GiveRewardOnSpecialPurchase" value="" />
			<Property name="EggModifierIngredient" value="false" />
			<Property name="IsTechbox" value="false" />
			<Property name="CanSendToOtherPlayers" value="true" />
		</Property>
]]

-- NEW (from reading the real "Build Custom Freighter Console" reference mod): that mod's
-- own newly-added part has entries in BOTH of these tables even though Shovel itself has
-- neither (confirmed no Shovel row in BASEBUILDINGCOSTSTABLE via grep, and none ever found
-- in BASEBUILDINGAUTOGENERATEDPARTSDATA either). Shovel evidently doesn't NEED them, but
-- since the reference mod includes them for its own new part and they're cheap/inert
-- placeholder data (bounding box + fake profiling numbers), adding them removes one more
-- variable rather than leaving it as an untested assumption.
local AUTOPARTDATA_ADD = [[
		<Property name="PartsData" value="GcBaseBuildingPartData">
			<Property name="PartID" value="_JANK7_RAMPSW" />
			<Property name="Style" value="GcBaseBuildingPartStyle">
				<Property name="Style" value="None" />
			</Property>
			<Property name="MagicData" value="TkMagicModelData">
				<Property name="Vertices">
					<Property value="Vertices">
						<Property name="X" value="-0.180496" />
						<Property name="Y" value="0.370919" />
						<Property name="Z" value="-0.167622" />
					</Property>
					<Property value="Vertices">
						<Property name="X" value="-0.180496" />
						<Property name="Y" value="0.370919" />
						<Property name="Z" value="0.167622" />
					</Property>
					<Property value="Vertices">
						<Property name="X" value="0.180496" />
						<Property name="Y" value="0.370919" />
						<Property name="Z" value="-0.167622" />
					</Property>
					<Property value="Vertices">
						<Property name="X" value="0.180496" />
						<Property name="Y" value="0.370919" />
						<Property name="Z" value="0.167622" />
					</Property>
					<Property value="Vertices">
						<Property name="X" value="-0.180496" />
						<Property name="Y" value="0.000000" />
						<Property name="Z" value="-0.167622" />
					</Property>
					<Property value="Vertices">
						<Property name="X" value="-0.180496" />
						<Property name="Y" value="0.000000" />
						<Property name="Z" value="0.167622" />
					</Property>
					<Property value="Vertices">
						<Property name="X" value="0.180496" />
						<Property name="Y" value="0.000000" />
						<Property name="Z" value="-0.167622" />
					</Property>
					<Property value="Vertices">
						<Property name="X" value="0.180496" />
						<Property name="Y" value="0.000000" />
						<Property name="Z" value="0.167622" />
					</Property>
				</Property>
				<Property name="Centre">
					<Property name="X" value="0.000000" />
					<Property name="Y" value="0.185459" />
					<Property name="Z" value="0.000000" />
				</Property>
				<Property name="Radius" value="0.308326" />
			</Property>
			<Property name="NodesCost" value="3" />
			<Property name="TimeCost" value="5000" />
			<Property name="PhysicsCost" value="1" />
			<Property name="MeshesCost" value="1" />
			<Property name="InstanceNodesCost" value="3" />
			<Property name="InstanceTimeCost" value="5000" />
			<Property name="InstanceMeshesCost" value="1" />
			<Property name="LastProfiledTimestamp" value="1757700000" />
			<Property name="InstanceLastProfiledTimestamp" value="1757700000" />
		</Property>
]]

local COST_ADD = [[
		<Property name="ObjectCosts" value="GcBaseBuildingEntryCosts">
			<Property name="ID" value="S_JANK7_RAMPSW" />
			<Property name="Active0AverageFrameTimeCost" value="0.001000" />
			<Property name="Active1AverageFrameTimeCost" value="0.001000" />
			<Property name="ActiveTotalNodes" value="6" />
			<Property name="ActivePhysicsComponents" value="2" />
			<Property name="Inactive0AverageFrameTimeCost" value="0.000500" />
			<Property name="Inactive1AverageFrameTimeCost" value="0.000500" />
			<Property name="InactiveTotalNodes" value="6" />
			<Property name="InactivePhysicsComponents" value="2" />
		</Property>
]]

-- NEW (from the reference mod's GetKnownProduct()): registers the product ID directly into
-- the default save data's KnownProducts list. Untested hypothesis, but it fits the symptom
-- exactly - clean compile, no crash, part simply never appears in the build menu. A product
-- that isn't "known" may never surface in the menu regardless of every other table being
-- correct, the same way vanilla technologies/blueprints must be unlocked/known before they
-- list. Shovel doesn't need this because it ships already known by default.
local KNOWNPRODUCT_ADD = [[
		<Property name="KnownProducts" value="S_JANK7_RAMPSW" />
]]

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= 'Jank7.Ramp_Control_Switch_Part_v1.1',
	MOD_BATCHNAME 		= 'Jank7_Ultimate_Landing_Bays_Part',
	MOD_AUTHOR			= 'Jank7',
	NMS_VERSION			= '7.03',
	MOD_DESCRIPTION		= mod_desc,
	AMUMSS_SUPPRESS_MSG	= 'MULTIPLE_STATEMENTS,MIXED_TABLE',
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{--	|New buildable object entry, cloned from vanilla S_SHOVEL|
		MBIN_FILE_SOURCE	= 'METADATA/REALITY/TABLES/BASEBUILDINGOBJECTSTABLE.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'ID', 'S_SHOVEL'},
				ADD_OPTION			= 'ADDafterSECTION',
				ADD					= OBJECT_ADD
			},
		}
	},
	{--	|New buildable part entry, cloned from vanilla _SHOVEL|
		MBIN_FILE_SOURCE	= 'METADATA/REALITY/TABLES/BASEBUILDINGPARTSTABLE.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'ID', '_SHOVEL'},
				ADD_OPTION			= 'ADDafterSECTION',
				ADD					= PART_ADD
			},
		}
	},
	{--	|New Product entry - registered in NMS_REALITY_GCPRODUCTTABLE.MBIN, matching the reference mod's proven method exactly (not NMS_BASEPARTPRODUCTS.MBIN, which only proves a vanilla Shovel row lives there). PRECEDING_KEY_WORDS unanchored, same as the reference mod - Shovel has no entry in this table to anchor to.|
		MBIN_FILE_SOURCE	= 'METADATA/REALITY/TABLES/NMS_REALITY_GCPRODUCTTABLE.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				PRECEDING_KEY_WORDS	= {'Table'},
				ADD					= PRODUCT_ADD
			},
		}
	},
	{--	|AutoGenerated bounding/perf data - present on the reference mod's new part, absent for Shovel; cheap to add, removes it as a variable|
		MBIN_FILE_SOURCE	= 'METADATA/REALITY/TABLES/BASEBUILDINGAUTOGENERATEDPARTSDATA.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				PRECEDING_KEY_WORDS	= {'PartsData'},
				ADD					= AUTOPARTDATA_ADD
			},
		}
	},
	{--	|Perf-cost table row - same rationale as AutoGeneratedPartsData above|
		MBIN_FILE_SOURCE	= 'METADATA/REALITY/TABLES/BASEBUILDINGCOSTSTABLE.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				PRECEDING_KEY_WORDS	= {'ObjectCosts'},
				ADD					= COST_ADD
			},
		}
	},
	{--	|Registers the product as already-known in the default save data - candidate fix for "compiles clean, doesn't crash, never shows in the build menu"|
		MBIN_FILE_SOURCE	= 'METADATA/GAMESTATE/DEFAULTSAVEDATA.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				PRECEDING_KEY_WORDS	= {'KnownProducts'},
				ADD					= KNOWNPRODUCT_ADD
			},
		}
	},
	{--	|Seeds our placement-ghost geometry from a REAL vanilla file (a similarly-sized wall switch's own plain-box ghost) instead of hand-authored guesswork - same "copy vanilla file as new file" idiom the reference mod uses|
		MBIN_FILE_SOURCE	=
		{
			{'MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UTILITYPARTS\SWITCH_WALL_PLACEMENT.GEOMETRY.MBIN', 'MODELS\CUSTOM\PROPS\JANK7_RAMPSWITCH_PLACEMENT.GEOMETRY.MBIN', 'REMOVE'},
		},
	},
	{--	|Companion stream-data file for the geometry above - copied alongside it since the two always ship as a matched pair for a given base filename|
		MBIN_FILE_SOURCE	=
		{
			{'MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UTILITYPARTS\SWITCH_WALL_PLACEMENT.GEOMETRY.DATA.MBIN', 'MODELS\CUSTOM\PROPS\JANK7_RAMPSWITCH_PLACEMENT.GEOMETRY.DATA.MBIN', 'REMOVE'},
		},
	},
}}}}