NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]  = "_PM_modulSX.pak",
["MOD_AUTHOR"]    = "Phantom",
["LUA_AUTHOR"]    = "Phantom",
["NMS_VERSION"]   = "7.3",
["MODIFICATIONS"] =
    {
        {
            ["MBIN_CHANGE_TABLE"] =
            {
                {
                    ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN",
                    ["MXML_CHANGE_TABLE"] =
                    {
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "SCRAP_TECH"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BaseValue", "5650"} -- Original 200
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "SCRAP_WEAP"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BaseValue", "5610"} -- Original 350
                            }							
                        },					
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_LASER2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_LASER3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_LASER4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_LASERX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SCANNER2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SCANNER3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SCANNER4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SCANNERX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_BOLT2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_BOLT3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_BOLT4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_BOLTX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_GRENADE2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_GRENADE3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_GRENADE4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_GRENADEX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_TGRENADE2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_TGRENADE3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_TGRENADE4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_TGRENADEX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_RAIL2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_RAIL3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_RAIL4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_RAILX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHOTGUN2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_SHOTGUN3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHOTGUN4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHOTGUNX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SMG2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SMG3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SMG4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SMGX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_CANNON2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_CANNON3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_CANNON4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_CANNONX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
						    ["SPECIAL_KEY_WORDS"] = {"ID", "U_SENTGUN"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
							    {"BaseValue", "200"},
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
						    ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHOTX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_ENERGY1"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_ENERGY2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_ENERGY3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},		
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_ENERGYX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
						},	
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_HAZARDX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
						},									
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_JETBOOST2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_JETBOOST3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_JETBOOST4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_JETBOOSTX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIELDBOOST2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIELDBOOST3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIELDBOOST4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIELDBOOSTX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_UNW1"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_UNW2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_UNW3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_RAD1"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_RAD2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_RAD3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_TOX1"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_TOX2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_TOX3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_COLDPROT1"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_COLDPROT2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_COLDPROT3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_HOTPROT1"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_HOTPROT2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_HOTPROT3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},	
                        {
						    ["SPECIAL_KEY_WORDS"] = {"ID", "U_SENTSUIT"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BaseValue", "200"}, 
								{"BuyMarkupMod", "20.000000"} 
                            }
						},	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_PULSE2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_PULSE3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_PULSE4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_PULSEX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_LAUNCH2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_LAUNCH3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_LAUNCH4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_LAUNCHX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_HYPER2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_HYPER3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_HYPER4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_HYPERX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHIELD2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHIELD3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHIELD4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHIELDX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPGUN2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPGUN3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPGUN4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPGUNX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPLAS2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPLAS3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPLAS4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPLASX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },			
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHOT2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHOT3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHOT4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPSHOTX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPMINI2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPMINI3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPMINI4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPMINIX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPBLOB2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"} 
                            }
                        },
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPBLOB3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPBLOB4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
						},						
						{
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_SHIPBLOBX"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "20.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOGUN2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOGUN3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOGUN4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOBOOST2"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "2.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOBOOST3"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "3.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOBOOST4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },	
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_ENG2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_ENG3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_ENG4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_ENG2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_ENG3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_ENG4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },	
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_SUB2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_SUB3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_SUB4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_SUBGUN2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_SUBGUN3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXO_SUBGUN4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },	
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_MECH_ENG2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_MECH_ENG3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_MECH_ENG4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },	
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHLAS2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHLAS3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHLAS4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"}
                            }
                        },
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHFLAME2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHFLAME3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHFLAME4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },		
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHGUN2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHGUN3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_MECHGUN4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },	
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOLAS2"},
							["VALUE_CHANGE_TABLE"] =
							{
								{"BuyMarkupMod", "2.000000"} 
                            }							
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOLAS3"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "3.000000"} 
                            }
                        },	
                        {
                            ["SPECIAL_KEY_WORDS"] = {"ID", "U_EXOLAS4"},
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuyMarkupMod", "4.000000"} 
                            }
                        },						
                    }						
                },
            }
        }
    }
}