NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "No Rainbow Particles.pak",
["MOD_AUTHOR"]				= "Andarius",
["NMS_VERSION"]				= "3.10",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= 
					{
						"MODELS\EFFECTS\SPACECRAFT\RAINBOWTRAILSPARKLE\EMITTERS\SPARKLEREMITTER.PARTICLE.MBIN",
						"MODELS\EFFECTS\SPACECRAFT\RAINBOWTRAILSPARKLE\EMITTERS\SPARKLEGEMITTER.PARTICLE.MBIN",
						"MODELS\EFFECTS\SPACECRAFT\RAINBOWTRAILSPARKLE\EMITTERS\SPARKLEBEMITTER.PARTICLE.MBIN",
					},
					["EXML_CHANGE_TABLE"] 	= 
					{						
						{
							["REPLACE_TYPE"] 		= "ALL",
							["VALUE_CHANGE_TABLE"] 	= 
								{
									{ "EmissionRate", 							"0" }, 		--Original "50"
								}
						},
					}
				},				
			}
		},
	}	 --3 global replacements
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE