NMS_MOD_DEFINITION_CONTAINER =
{
	["MOD_FILENAME"] = "RemoveMiningParticles",
	["MOD_AUTHOR"] = "Flugelwulff",
	["LUA_AUTHOR"] = "Flugelwulff",
	["NMS_VERSION"] = "6.17",
	["MODIFICATIONS"] =
	{
		{
			["MBIN_CHANGE_TABLE"] 	=
			{
				{
					["MBIN_FILE_SOURCE"] =
					{
						"MODELS\EFFECTS\DEBRIS\LARGERESOURCEDEBRIS.SCENE.MBIN",
						"MODELS\EFFECTS\DEBRIS\RESOURCEDEBRIS.SCENE.MBIN",
						"MODELS\EFFECTS\DEBRIS\TERRAINDEBRIS\TERRAINDEBRIS1.SCENE.MBIN",
						"MODELS\EFFECTS\DEBRIS\TERRAINDEBRIS\TERRAINDEBRIS2.SCENE.MBIN",
						"MODELS\EFFECTS\DEBRIS\TERRAINDEBRIS\TERRAINDEBRIS3.SCENE.MBIN",
						"MODELS\EFFECTS\DEBRIS\TERRAINDEBRIS\TERRAINDEBRIS4.SCENE.MBIN",
					},
					["MXML_CHANGE_TABLE"] 	=
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Type", "MESH"},
							["REPLACE_TYPE"] = "ALL",
							["REMOVE"] = "SECTION",
						}
					}
				}
			}
		}
	}
}