local mod_filename           = "ScannerBiome"
local lua_author             = "Strollker"
local mod_author             = "Strollker"
local lua_Internalversion    = "0.0.9"
local lua_version            = "0.0.1"
local nms_version            = "Voyagers"
local mod_description        = [[]]

local mxml_changes           = {}
local mxml_changes_time      = {}
local MBIN_Changes           = {}
local Modifications          = {}

local FileSource             = {
    "MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/SPECIALSHOP/ENTITIES/SPECIALSHOPORB.ENTITY.MXML",
    "MODELS/PLANETS/SNOW/WRECKS/GIANTWRECKEDSHIP/ENTITIES/GIANTWRECK.ENTITY.MXML",
    "MODELS/PLANETS/CREATURES/SANDWORMMINI/SANDWORMMINI/ENTITIES/DATA.ENTITY.MXML",
    "MODELS/PLANETS/CREATURES/SANDWORMMINI/GROUNDWORMSPAWNER/ENTITIES/GROUNDWORMSPAWNER.ENTITY.MXML",
    "MODELS/PLANETS/CREATURES/FISH/GRABBYPLANT/ENTITIES/GRABBYPLANT.ENTITY.MXML",
    "MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/ROBOTHEADS/ENTITIES/_DATA_ROBOT.ENTITY.MXML",
    "MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/ROBOTBASE/ENTITIES/TERMINAL.ENTITY.MXML",
    "MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/ROBOTTERMINALSMALL/ENTITIES/ROBOTTERMINAL.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/DIPLODOCUS/DIPLODOCUS/ENTITIES/DIPLO.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/LAVA/LARGEPROPS/LARGEVOLCANO/ENTITIES/DATA.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/INAIR/GASBAGPARTS/FLOATINGRESOURCE/ENTITIES/FLOATINGRESOURCE.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/INAIR/FLOATINGGASBAGS/ENTITIES/FLOATINGGASBAG.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/UNDERGROUNDLUMP/ENTITIES/UNDERGROUNDLUMP.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SPOREBAG/ENTITIES/SPOREBAG.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAP/ENTITIES/SCRAPCORE.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/ROBOTHEADSCAMPSITE/ENTITIES/_DATA_ROBOT.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/ROBOTHEADS/ENTITIES/DATA.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/METALFORMATION/ENTITIES/METALFORMATION.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/GROUNDRESOURCE/ENTITIES/_GEMSTONE_1.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/FIENDEGG/ENTITIES/FIENDEGG.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/CORRUPTDRONEPILLAR/ENTITIES/DATA.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/CLAMSHELL/ENTITIES/MAIN1.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/BONEPILE/ENTITIES/BONEPILE.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/CRYSTALS/UNDERGROUNDCRYSTALS/ENTITIES/UNDERGROUNDCRYSTAL.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/CRYSTALS/SENTINELCRYSTAL/ENTITIES/DATA.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/CRYSTALS/NPCROBOTCRYSTALS/ENTITIES/NPCROBOTCRYSTAL.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/PLANTS/MONSTERPLANT/ENTITIES/MONSTERPLANT.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/VENUSFLYTRAP/ENTITIES/VENUSFLYTRAP.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TENTACLEPLANT/ENTITIES/TENTACLEPLANTSIDE.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TENTACLEPLANT/ENTITIES/TENTACLEPLANTFLAT.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TENTACLEPLANT/ENTITIES/TENTACLEPLANT.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/ROLLINGPLANT/ENTITIES/ROLLINGPROP.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARDPLANTSPIKEY/ENTITIES/DATA.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARDPLANTSPIKEY/ENTITIES/_DATA_3.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARDPLANTSPIKEY/ENTITIES/_DATA_2.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FLOATINGPLANTS/ENTITIES/_FLOAT_1.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/INTERACTIVE/SPOREVENT/ENTITIES/SPOREVENT.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/TERRAINRESOURCE/TERRAINRESOURCE/ENTITIES/SCANLOCATOR.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SIGNALSCANNER/ENTITIES/SIGNAL.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SETTLEMENT/SUMMARY_TERMINAL/ENTITIES/SUMMARYTERMINALDATA.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/PARTS/CRATELOCK/ENTITIES/CRATELOCK.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/INTERACTIVE/WEAPONTECHSTATION/ENTITIES/WEAPONTECHSTATION.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/WARRIORPARTS/DESTRUCTIBLEDOORSTRONG/ENTITIES/DESTRUCTIBLEDOORSTRONG.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/WARRIORPARTS/DESTRUCTIBLEDOOR/ENTITIES/DESTRUCTIBLEDOOR.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/TRADERPARTS/DESTRUCTIBLEDOORSTRONG/ENTITIES/DESTRUCTIBLEDOORSTRONG.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/TRADERPARTS/DESTRUCTIBLEDOOR/ENTITIES/DESTRUCTIBLEDOOR.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/SCIENTIFICPARTS/DOORROUND_DESTRUCTIBLESTRONG/ENTITIES/DOORDESTRUCTIBLE_STRONG.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/FISHINGPLATFORM/ENTITIES/FISHINGPLATFORM.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/WORDSTONE/ENTITIES/WORDSTONE.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/SPACEBASE/MESHES/ANIMATEDDOOR/ENTITIES/ANIMATEDDOOR.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/SPACEBASE/FIENDEGG/ENTITIES/FIENDEGG.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/NPCROOMS/NPC_ABANDFRIGATECAPTAIN/ENTITIES/ABANFRIGATETERMINALFINAL.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/NPCROOMS/NPC_ABANDFRIGATECAPTAIN/ENTITIES/ABANFRIGATETERMINALCREW.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/NPCROOMS/NPC_ABANDFRIGATECAPTAIN/ENTITIES/ABANFRIGATETERMINALCAPTAIN.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/NPCROOMS/NPC_ABANDFRIGATECAPTAIN/ENTITIES/ABANFRIGATETERMINALAIRLOCK.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/DECORATION/BUILDERS/STAFFBUILDER/ENTITIES/STAFFBUILDER.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MINERALROCK/MINERALROCK_SMALL_RARE/ENTITIES/MINERALROCK_SMALL_RARE.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MINERALROCK/MINERALROCK_SMALL/ENTITIES/MINERALROCK_SMALL.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MINERALROCK/MINERALROCK_MEDIUM_RARE/ENTITIES/MINERALROCK_MEDIUM.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MINERALROCK/MINERALROCK_MEDIUM/ENTITIES/MINERALROCK_MEDIUM.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/GRAVEINCAVE/GRAVEINCAVE/ENTITIES/GRAVEINCAVE.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/FACTORY/FACTORYWARRIOR/ENTITIES/FACTORYDOOR.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/DEPOT/PARTS/DEPOTSCIENTIFICBASE/ENTITIES/SCIENTIFICDEPOTBASE.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/DEBRIS/PARTS/DEBRILARGECONTAINER/ENTITIES/TECHDEBRIS.ENTITY.MXML",
    "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/CRATE/CRATE_TUTORIALSUPPLY/ENTITIES/CRATE_TUTORIALSUPPLY.ENTITY.MXML",
    "MODELS/EFFECTS/WEATHER/TOXICCLOUDHAZARD/ENTITIES/TOXICCLOUDHAZARDDATA.ENTITY.MXML",
    "MODELS/EFFECTS/WEATHER/RADIOACTIVEANOMALYHAZARD/ENTITIES/RADIOACTIVELANOMALYHAZARDDATA.ENTITY.MXML",
    "MODELS/EFFECTS/WEATHER/LAVAVENTHAZARD/ENTITIES/LAVAHAZARDDATA.ENTITY.MXML",
    "MODELS/EFFECTS/WEATHER/GEOTHERMALHAZARD/ENTITIES/GEOTHERMALHAZARDDATA.ENTITY.MXML",
    "MODELS/EFFECTS/WEATHER/ELECTRICALANOMALYHAZARD/ENTITIES/ELECTRICALANOMALYHAZARDDATA.ENTITY.MXML",
    "MODELS/EFFECTS/EXPLOSION/SNAKEEMERGE/ROCKDEBRIS/ENTITIES/ROCK03.ENTITY.MXML",
    "MODELS/COMMON/SPACECRAFT/INDUSTRIAL/DESTRUCTIBLEPARTS/SHIELDGENERATOR0/ENTITIES/PROXIMITYDESTRUCTABLE.ENTITY.MXML",
    "MODELS/COMMON/SPACECRAFT/BIGGS/TELEWATER/ENTITIES/TELEWATER.ENTITY.MXML",
    "MODELS/COMMON/SPACECRAFT/BIGGS/TELEPORTER/ENTITIES/TELEPORTER.ENTITY.MXML",
    "MODELS/COMMON/ROBOTS/FRIENDLYDRONE/ENTITIES/FRIENDLYDRONE.ENTITY.MXML",
    "MODELS/COMMON/ROBOTS/DRONESUMMONER/ENTITIES/SUMDRONE.ENTITY.MXML",
    "MODELS/COMMON/ROBOTS/DRONEMEDIC/ENTITIES/MEDICDRONE.ENTITY.MXML",
    "MODELS/COMMON/ROBOTS/DRONEARMOURED/ENTITIES/DRONEARMOURED.ENTITY.MXML",
    "MODELS/COMMON/ROBOTS/DRONE/ENTITIES/DRONE.ENTITY.MXML",
    "MODELS/COMMON/ROBOTS/CORRUPTEDDRONE/ENTITIES/CORRUPTEDDRONE.ENTITY.MXML",
    "MODELS/COMMON/DEMOS/E32015/MODELS/SCANNABLEOBJECT2/ENTITIES/SCANOBJECT2.ENTITY.MXML",
    "MODELS/COMMON/DEMOS/E32015/MODELS/SCANNABLEOBJECT/ENTITIES/SCANOBJECT.ENTITY.MXML",
}

local function AddChange(tbl, cfg)
    local entry = {
        ["REPLACE_TYPE"] = cfg.replace_type,
        ["VALUE_CHANGE_TABLE"] = cfg.values
    }
    if cfg.keywords then entry["SPECIAL_KEY_WORDS"] = cfg.keywords end
    if cfg.preceding then entry["PRECEDING_KEY_WORDS"] = cfg.preceding end
    if cfg.section_up then entry["SECTION_UP"] = cfg.section_up end
    if cfg.add then
        entry["ADD_OPTION"] = cfg.add_option
        entry["ADD"] = cfg.add
    end
    table.insert(tbl, entry)
end

AddChange(mxml_changes, {
     replace_type = "ALL",
    keywords = { { "ScannableType", "Binoculars" } },
    values = {
        { "ScannableType",                "Scanner" },
    }
})

AddChange(mxml_changes_time, {
    replace_type = "ALL",
    values = {
        { "CreatureMinScanTime",                           "0" },
        { "BinocMinScanTime",                              "0" },
        { "BinocCreatureScanTime",                         "0" },
        { "BinocScanTime",                                 "0" },
    }
})

-- =================================================================================================
-- SAFE FALLBACK
-- =================================================================================================
function NMS_LOG(message)
    print(string.format("[MOD:%s] %s", mod_filename, tostring(message)))
end

for _, FileSource in ipairs(FileSource) do
    if mxml_changes and next(mxml_changes) then
        table.insert(MBIN_Changes, {
            COMMENT = " ",
            MBIN_FILE_SOURCE = FileSource,
            MXML_CHANGE_TABLE = mxml_changes
        })
    end
end

if mxml_changes_time and next(mxml_changes_time) then
    table.insert(MBIN_Changes, {
        COMMENT = " ",
        MBIN_FILE_SOURCE = "GLOBALS/GCGAMEPLAYGLOBALS.GLOBAL.MXML",
        MXML_CHANGE_TABLE = mxml_changes_time
    })
end

if next(MBIN_Changes) then
    table.insert(Modifications, {
        MBIN_CHANGE_TABLE = MBIN_Changes
    })
    NMS_LOG("[INFO] Active modification. ")
else
    NMS_LOG("[INFO] No active MBIN modifications detected. The script will compile without changes to the game.")
end

NMS_MOD_DEFINITION_CONTAINER = {
    MOD_FILENAME = string.format("%s v%s %s", mod_filename, lua_version, nms_version, lua_Internalversion),
    LUA_AUTHOR = lua_author,
    MOD_AUTHOR = mod_author,
    NMS_VERSION = nms_version,
    MOD_DESCRIPTION = mod_description,
    MODIFICATIONS = Modifications,
}

return NMS_MOD_DEFINITION_CONTAINER