--------------------------------------------------------------------------------
--  SClassMaxMe
--  * The ambient freighter that warps into a system is a Capital freighter.
--  * Every ship and freighter generated by the game is S-class.
--  * Every ship/freighter type gets max cargo and tech slots.
--
--  Capital System Freighter lua by potatiustotalis, updated by dudemiustotalis
--  (permission to include and enhance given by dudemiustotalis).
--  Combined mod by Unclejuju. Modernized for NMS 6.45 / AMUMSS 5.6.2.
--
--  HOW IT WORKS
--    * EXPERIENCESPAWNTABLE.MBIN -> the "AmbientSpawns" freighter entry is
--      told to WarpIn and to use the CapitalFreighter AI role.
--    * INVENTORYTABLE.MBIN -> ClassProbabilities set to 100% S,
--      MaxInventoryCapacity raised, and every size-class entry gets the
--      slot counts below.
--------------------------------------------------------------------------------

-------------------------------- SETTINGS --------------------------------------
-- Class roll: weights out of 100. Vanilla spreads these across C/B/A/S.
local ClassProbability = { C = "0", B = "0", A = "0", S = "100" }

-- Hard cap on inventory capacity, per class.
local MaxInventoryCapacity = "120"

-- Slot counts applied to every ship & freighter size entry listed below.
local CargoSlots = "120"   -- MinSlots / MaxSlots
local TechSlots  = "60"    -- MinTechSlots / MaxTechSlots

-- Which INVENTORYTABLE size entries to touch.
local SizeEntries = {
  "SciSmall",  "SciMedium",  "SciLarge",     -- Explorers
  "FgtSmall",  "FgtMedium",  "FgtLarge",     -- Fighters
  "ShuSmall",  "ShtMedium",  "ShtLarge",     -- Shuttles (yes, the game spells them this way)
  "DrpSmall",  "DrpMedium",  "DrpLarge",     -- Haulers
  "RoySmall",  "RoyMedium",  "RoyLarge",     -- Exotics
  "AlienSmall","AlienMedium","AlienLarge",   -- Living ships
  "SailSmall", "SailMedium", "SailLarge",    -- Solar ships
  "RobotSmall","RobotMedium","RobotLarge",   -- Sentinel interceptors
  "FreighterSmall","FreighterMedium","FreighterLarge",
}
------------------------------ END SETTINGS ------------------------------------

-- Build the PRECEDING_KEY_WORDS table AMUMSS expects: one {name} per entry.
local SizeEntryKeys = {}
for _, name in ipairs(SizeEntries) do
  table.insert(SizeEntryKeys, { name })
end

NMS_MOD_DEFINITION_CONTAINER = {
  ["MOD_FILENAME"]    = "SClassMaxMe",
  ["MOD_AUTHOR"]      = "Unclejuju",
  ["LUA_AUTHOR"]      = "potatiustotalis / dudemiustotalis / Unclejuju (modernized by Julian)",
  ["NMS_VERSION"]     = "6.45",
  ["MOD_DESCRIPTION"] = "S Class Capital Freighter with max slots will spawn in the system and all Ships and Regular Freighters are also S Class with max slots",
  ["MODIFICATIONS"]   = {
    {
      ["MBIN_CHANGE_TABLE"] = {

        ---------------------------------------------------------------- Capital freighter spawn
        {
          ["MBIN_FILE_SOURCE"] = "METADATA\SIMULATION\SCENE\EXPERIENCESPAWNTABLE.MBIN",
          ["MXML_CHANGE_TABLE"] = {
            {
              ["COMMENT"]             = "Ambient system freighter warps in and is a Capital freighter",
              ["PRECEDING_KEY_WORDS"] = "AmbientSpawns",
              ["VALUE_CHANGE_TABLE"]  = {
                {"WarpIn",     "True"},              -- vanilla: False
                {"AIShipRole", "CapitalFreighter"},  -- vanilla: Freighter
              },
            },
          },
        },

        ---------------------------------------------------------------- Everything S-class, max slots
        {
          ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\INVENTORYTABLE.MBIN",
          ["MXML_CHANGE_TABLE"] = {
            {
              ["COMMENT"]             = "Class roll is always S",
              ["PRECEDING_KEY_WORDS"] = "ClassProbabilities",
              ["REPLACE_TYPE"]        = "ALL",
              ["VALUE_CHANGE_TABLE"]  = {
                {"C", ClassProbability.C},
                {"B", ClassProbability.B},
                {"A", ClassProbability.A},
                {"S", ClassProbability.S},
              },
            },
            {
              ["COMMENT"]             = "Raise the per-class inventory cap",
              ["PRECEDING_KEY_WORDS"] = "MaxInventoryCapacity",
              ["REPLACE_TYPE"]        = "ALL",
              ["VALUE_CHANGE_TABLE"]  = {
                {"C", MaxInventoryCapacity},
                {"B", MaxInventoryCapacity},
                {"A", MaxInventoryCapacity},
                {"S", MaxInventoryCapacity},
              },
            },
            {
              ["COMMENT"]             = "Max cargo/tech slots for every ship & freighter size",
              ["PRECEDING_KEY_WORDS"] = SizeEntryKeys,
              ["VALUE_CHANGE_TABLE"]  = {
                {"MinSlots",     CargoSlots},
                {"MaxSlots",     CargoSlots},
                {"MinTechSlots", TechSlots},
                {"MaxTechSlots", TechSlots},
              },
            },
          },
        },
      },
    },
  },
}