NMS_MOD_DEFINITION_CONTAINER = 
{
	["MOD_FILENAME"]	= "SIR - ShipHUD - CombatHUD.pak",
	["MOD_AUTHOR"]		= "VirtualVoyager",
	["MOD_DESCRIPTION"]	= "This mod makes ship space map cleaner",
	["LUA_AUTHOR"]      = "Lowkie",
	["NMS_VERSION"]		= "4.08",	
	["MODIFICATIONS"]	= 
	{
		{
			["MBIN_CHANGE_TABLE"] = 
			{
				{
					["MBIN_FILE_SOURCE"] = {
						"MODELS\HUD\SPACEMAPHORIZON\HORZVAO_MAT.MATERIAL.MBIN",
						"MODELS\HUD\SPACEMAPHORIZON\HORZ_MAT.MATERIAL.MBIN",
						"MODELS\COMMON\SPACECRAFT\DROPSHIPS\COCKPIT\COCKPITA_INTERIOR\GLOWGRADIENTORANGE_MAT.MATERIAL.MBIN",
						"MODELS\COMMON\SPACECRAFT\DROPSHIPS\COCKPIT\COCKPITB_INTERIOR\GLOWGRADIENTORANGE_MAT.MATERIAL.MBIN",
						"MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPITCOMMON_INTERIOR\GLOWGRADIENTORANGE_MAT.MATERIAL.MBIN",
						"MODELS\COMMON\SPACECRAFT\SCIENTIFIC\INTERIORS\CANOPYA_INTERIOR\GLOWGRADIENTORANGE_MAT.MATERIAL.MBIN",
						"MODELS\COMMON\SPACECRAFT\SHUTTLE\INTERIORS\CANOPYA_INTERIOR\CANOPYA_INTERIOR\GLOWGRADIENTORANGE_MAT.MATERIAL.MBIN",
						},
					["EXML_CHANGE_TABLE"] = 
					{				
						{
							["PRECEDING_KEY_WORDS"] = {"Samplers"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Map",	"TEXTURES/EFFECTS/GRADIENT_LONGFALLOFFVVHUD.DDS"},
							},
						},
					},
				},
			},
		},
	},
}