-- SoftPortal
-- Dims teleporter tunnels, ancient portal tunnels, and the misty active face on teleporters.
-- Hyperdrive system warp (WARPTUNNEL) is left alone.

-- Brightness vs vanilla (~half of the previous SoftPortal pass again):
local COLOUR   = "0.08"   -- was 0.16
local PARAM2X  = "0.125"  -- was 0.25 (* of vanilla)
local LIGHTI   = "0.09"   -- was 0.18 (* of vanilla)
local LIGHTCOL = "0.175"  -- was 0.35 (* of vanilla)

local function MaterialDarken()
  return
  {
    {
      ["SPECIAL_KEY_WORDS"] = {"Name", "gMaterialColourVec4"},
      ["INTEGER_TO_FLOAT"]  = "FORCE",
      ["VALUE_CHANGE_TABLE"] =
      {
        {"X", COLOUR},
        {"Y", COLOUR},
        {"Z", COLOUR},
      }
    },
    {
      ["SPECIAL_KEY_WORDS"] = {"Name", "gMaterialParams2Vec4"},
      ["INTEGER_TO_FLOAT"]  = "FORCE",
      ["MATH_OPERATION"]    = "*",
      ["VALUE_CHANGE_TABLE"] =
      {
        {"X", PARAM2X},
      }
    },
  }
end

local function SceneLightDarken()
  return
  {
    {
      ["SPECIAL_KEY_WORDS"] = {"Name", "INTENSITY"},
      ["REPLACE_TYPE"]      = "ALL",
      ["INTEGER_TO_FLOAT"]  = "FORCE",
      ["MATH_OPERATION"]    = "*",
      ["VALUE_CHANGE_TABLE"] =
      {
        {"Value", LIGHTI},
      }
    },
    {
      ["SPECIAL_KEY_WORDS"] = {"Name", "COL_R"},
      ["REPLACE_TYPE"]      = "ALL",
      ["INTEGER_TO_FLOAT"]  = "FORCE",
      ["MATH_OPERATION"]    = "*",
      ["VALUE_CHANGE_TABLE"] =
      {
        {"Value", LIGHTCOL},
      }
    },
    {
      ["SPECIAL_KEY_WORDS"] = {"Name", "COL_G"},
      ["REPLACE_TYPE"]      = "ALL",
      ["INTEGER_TO_FLOAT"]  = "FORCE",
      ["MATH_OPERATION"]    = "*",
      ["VALUE_CHANGE_TABLE"] =
      {
        {"Value", LIGHTCOL},
      }
    },
    {
      ["SPECIAL_KEY_WORDS"] = {"Name", "COL_B"},
      ["REPLACE_TYPE"]      = "ALL",
      ["INTEGER_TO_FLOAT"]  = "FORCE",
      ["MATH_OPERATION"]    = "*",
      ["VALUE_CHANGE_TABLE"] =
      {
        {"Value", LIGHTCOL},
      }
    },
  }
end

local function ParticleColourDarken()
  -- Dim particle RGB; also cut mid-life alpha so mist is thinner
  local t = {}
  for _, key in ipairs({"ColourStart", "ColourMiddle", "ColourEnd"}) do
    local vct =
    {
      {"R", COLOUR},
      {"G", COLOUR},
      {"B", COLOUR},
    }
    if key == "ColourMiddle" then
      table.insert(vct, {"A", COLOUR})
    end
    table.insert(t,
    {
      ["PRECEDING_KEY_WORDS"] = {key},
      ["INTEGER_TO_FLOAT"]    = "FORCE",
      ["MATH_OPERATION"]      = "*",
      ["VALUE_CHANGE_TABLE"]  = vct,
    })
  end
  return t
end

local WARPPORTAL_MATERIALS =
{
  "MODELS/EFFECTS/WARP/WARPPORTAL/TUNNELMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/ENDGLOWMAT4.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/ENGGLOWCAPMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/FARLIGHTMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/GRADIENTCLOUDMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/GRADIENTCLOUDALTGMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/LIGHTARMSGREENMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/LIGHTSTREAKSMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/LIGHTSTREAKSLARGEMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/LIGHTSTREAKSSMALLMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/SCROLLINGWAVESALTGMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/SCROLLINGWAVESALTG2MAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/SCROLLINGWAVESALTG3MAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/WARPBGMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/WARPCLOUD.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPPORTAL/WARPSCROLLWMAT.MATERIAL.MBIN",
}

local WARPLARGEPORTAL_MATERIALS =
{
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/TUNNELMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/ENDGLOWMAT3.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/ENGGLOWCAPMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/GRADIENTCLOUDMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/GRADIENTCLOUDALTRMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/LIGHTARMSREDMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/LIGHTSTREAKSMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/LIGHTSTREAKSSMALLMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/SCROLLINGWAVESALTRMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/WARPBGMAT.MATERIAL.MBIN",
  "MODELS/EFFECTS/WARP/WARPLARGEPORTAL/WARPSCROLLWMAT.MATERIAL.MBIN",
}

-- Misty scrolling face on active teleporters / portal effect mesh
local DEVICE_MIST_MATERIALS =
{
  "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PORTAL/PORTALEFFECT/PORTALEFFECT/PORTALSCROLL_MAT.MATERIAL.MBIN",
  "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/COMMONPARTS/TELEPORTER/TRAILLIGHT_MAT.MATERIAL.MBIN",
  "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/COMMONPARTS/TELEPORTER_STATION/TRAILLIGHT_MAT.MATERIAL.MBIN",
  "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/COMMONPARTS/TELEPORTER_NEXUS/TRAILLIGHT_MAT.MATERIAL.MBIN",
}

local PORTAL_PARTICLES =
{
  "MODELS/EFFECTS/PORTAL/PORTALEFFECT/MIST.PARTICLE.MBIN",
  "MODELS/EFFECTS/PORTAL/PORTALEFFECT/MISTSUCK.PARTICLE.MBIN",
  "MODELS/EFFECTS/PORTAL/PORTALEFFECT/GLOW.PARTICLE.MBIN",
  "MODELS/EFFECTS/PORTAL/PORTALEFFECT/EMBERBITS.PARTICLE.MBIN",
  "MODELS/EFFECTS/PORTAL/PORTALEFFECT/ENERGYSPIN.PARTICLE.MBIN",
  "MODELS/EFFECTS/PORTAL/PORTALEFFECT/DISTORTIONRINGS.PARTICLE.MBIN",
  "MODELS/EFFECTS/PORTAL/STATIONPORTALGROUNDEFFECT/MIST.PARTICLE.MBIN",
  "MODELS/EFFECTS/PORTAL/STATIONPORTALGROUNDEFFECT/GLOW.PARTICLE.MBIN",
  "MODELS/EFFECTS/PORTAL/STATIONPORTALGROUNDEFFECT/EMBERBITS.PARTICLE.MBIN",
}

NMS_MOD_DEFINITION_CONTAINER =
{
  ["MOD_FILENAME"]    = "SoftPortal",
  ["MOD_AUTHOR"]      = "calma",
  ["LUA_AUTHOR"]      = "Cursor",
  ["NMS_VERSION"]     = "6.45",
  ["MOD_DESCRIPTION"] = "Much softer teleporter/ancient-portal tunnels and dimmer active portal mist",
  ["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] = WARPPORTAL_MATERIALS,
          ["MXML_CHANGE_TABLE"] = MaterialDarken(),
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS/EFFECTS/WARP/WARPPORTAL.SCENE.MBIN",
          ["MXML_CHANGE_TABLE"] = SceneLightDarken(),
        },
        {
          ["MBIN_FILE_SOURCE"] = WARPLARGEPORTAL_MATERIALS,
          ["MXML_CHANGE_TABLE"] = MaterialDarken(),
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS/EFFECTS/WARP/WARPLARGEPORTAL.SCENE.MBIN",
          ["MXML_CHANGE_TABLE"] = SceneLightDarken(),
        },
        {
          ["MBIN_FILE_SOURCE"] = DEVICE_MIST_MATERIALS,
          ["MXML_CHANGE_TABLE"] = MaterialDarken(),
        },
        {
          ["MBIN_FILE_SOURCE"] = PORTAL_PARTICLES,
          ["MXML_CHANGE_TABLE"] = ParticleColourDarken(),
        },
      }
    },
  }
}