ModName = "AL_PimpMyShip_Starborn_Runner"
ModNameSub = "zzz"
GameVersion = "5.12"
ModVersion = "1.0.0"
ModVersion = "SHADOW_WEAVER"

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME	= ModNameSub.."_"..ModName.."_"..ModVersion,
	MOD_DESCRIPTION	= "Starborn Runner Paintjob",
	MOD_AUTHOR		= "AL",
	LUA_AUTHOR		= "AL",
	NMS_VERSION		= GameVersion,
	ADD_FILES = {
		{
			FILE_DESTINATION 		= "TEXTURES\COMMON\SPACECRAFT\FIGHTERS\WRACERTRIM.DDS",
			EXTERNAL_FILE_SOURCE 	= "WRACERTRIM.DDS"
		},
		{
			FILE_DESTINATION 		= "TEXTURES\COMMON\SPACECRAFT\FIGHTERS\WRACERTRIM.MASKS.DDS",
			EXTERNAL_FILE_SOURCE 	= "WRACERTRIM.MASKS.DDS"
		},
		{
			FILE_DESTINATION 		= "TEXTURES\COMMON\SPACECRAFT\FIGHTERS\WRACERTRIM.NORMAL.DDS",
			EXTERNAL_FILE_SOURCE 	= "WRACERTRIM.NORMAL.DDS"
		},
		{
			FILE_DESTINATION 		= "TEXTURES\COMMON\SPACECRAFT\FIGHTERS\WRACERTRIM.PARALLAX.DDS",
			EXTERNAL_FILE_SOURCE 	= "WRACERTRIM.PARALLAX.DDS"
		},
		{
			FILE_DESTINATION 		= "TEXTURES\COMMON\SPACECRAFT\FIGHTERS\WRACERDECALS.DDS",
			EXTERNAL_FILE_SOURCE 	= "WRACERDECALS.DDS"
		},
		{
			FILE_DESTINATION 		= "TEXTURES\COMMON\SPACECRAFT\FIGHTERS\WRACERDECALS.NORMAL.DDS",
			EXTERNAL_FILE_SOURCE 	= "WRACERDECALS.NORMAL.DDS"
		},
		{
			FILE_DESTINATION 		= "TEXTURES\COMMON\SPACECRAFT\FIGHTERS\WRACERDECALS.PARALLAX.DDS",
			EXTERNAL_FILE_SOURCE 	= "WRACERDECALS.PARALLAX.DDS"
		}
	},
	MODIFICATIONS	= {
		{
			MBIN_CHANGE_TABLE = {
				{
					MBIN_FILE_SOURCE = "MODELS\COMMON\SPACECRAFT\FIGHTERS\WRACER\RACERPAINTMAT.MATERIAL.MBIN",
					EXML_CHANGE_TABLE = {
						{
							VALUE_CHANGE_TABLE = {
								{"Shader","SHADERS/UBERSHADER.SHADER.BIN"},
								{"ShaderMillDataHash","0"}
							}	
						}
					}
				}
			}
		}
	}
}