Author = "Gumsk"
ModName = "GShip Texture"
ModNameSub = "Fighter"
BaseDescription = "Increases normal masks on fighters"
GameVersion = "315"
ModVersion = "a"
FileSource1 = "MODELS\EFFECTS\LINES\SHIPLASERLINE.MATERIAL.MBIN"
FileSource2 = "MODELS\EFFECTS\LINES\SHIPLASERLINECORE.MATERIAL.MBIN"

NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= ModName.." "..ModNameSub.." "..GameVersion..ModVersion..".pak",
["MOD_DESCRIPTION"]	= BaseDescription,
["MOD_AUTHOR"]		= Author,
["NMS_VERSION"]		= GameVersion,
["ADD_FILES"] = {
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/SHARED/HQTRIM_METAL.TRIMMETAL.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/SHARED/GUMSK_HQTRIM_METAL.TRIMMETAL.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/SHARED/HQTRIM_PRIMARY.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/SHARED/GUMSK_HQTRIM_PRIMARY.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/SHARED/HQTRIM_SECONDARY.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/SHARED/GUMSK_HQTRIM_SECONDARY.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_A.BASE.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/COCKPIT/GUMSK_COCKPIT_A.BASE.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_A.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/COCKPIT/GUMSK_COCKPIT_A.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_A_NOSEB.BASE.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/COCKPIT/GUMSK_COCKPIT_A_NOSEB.BASE.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_B.BASE.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/COCKPIT/GUMSK_COCKPIT_B.BASE.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_B_NOSEA.BASE.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/COCKPIT/GUMSK_COCKPIT_B_NOSEA.BASE.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPITACC_TOPFIN_A.BASE.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/COCKPIT/GUMSK_COCKPITACC_TOPFIN_A.BASE.NORMAL.DDS",
	},
	{
		["FILE_DESTINATION"] 		= "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPITACC_TOPFIN_B.BASE.NORMAL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "FIGHTERS/COCKPIT/GUMSK_COCKPITACC_TOPFIN_B.BASE.NORMAL.DDS",
	},

},

["MODIFICATIONS"]	= {{
["MBIN_CHANGE_TABLE"] = {
-- {["MBIN_FILE_SOURCE"] = {FileSource1},

	-- ["EXML_CHANGE_TABLE"] = {
		-- {["PRECEDING_KEY_WORDS"] = {"Samplers"},
			-- ["VALUE_CHANGE_TABLE"] = {
				-- {"Map", "GUMSK/GUMSKLASER"..Color..".DDS"}
			-- }},
	-- }
-- },
-- {["MBIN_FILE_SOURCE"] = {FileSource2},

	-- ["EXML_CHANGE_TABLE"] = {
		-- {["PRECEDING_KEY_WORDS"] = {"Samplers"},
			-- ["VALUE_CHANGE_TABLE"] = {
				-- {"Map", "GUMSK/GUMSKLASERCORE"..ColorCore..".DDS"}
			-- }},
	-- }
-- },
}},}}