NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "FixKorvaxMonolith.pak",
["MOD_AUTHOR"]				= "Lenni",
["NMS_VERSION"]				= "4.26",
["MOD_DESCRIPTION"]			= "Fix Korvax Monoliths",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= {{[[MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/MONOLITH.SCENE.MBIN]], [[MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/MONOLITH_KORVAX.SCENE.MBIN]], "REMOVE"}},
				},
			}
		}
	}	
}