NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "NoStandingLoss.pak",
["MOD_AUTHOR"]				= "Lenni",
["NMS_VERSION"]				= "4.43",
["MOD_DESCRIPTION"]			= "You don't lose standing anymore",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	=
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= "METADATA/REALITY/TABLES/REWARDTABLE.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["FSKWG"]  = {
								{"Id", "KILLED_CIV"},
								{"Id", "STD_DEC_EXP"},
								{"Id", "STD_DEC_TRA"},
								{"Id", "STD_DEC_WAR"},
								{"Id", "MB_STAND_NEG"},
								{"Id", "STD_DEC_BUI"},
							},
							["REMOVE"] = "SECTION",
						},
					},
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CONTAINER/CONTAINERA/ENTITIES/CONTAINER_A.ENTITY.MBIN",
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CONTAINER/CONTAINERB/ENTITIES/CONTAINER_B.ENTITY.MBIN",
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CONTAINER/CONTAINERC/ENTITIES/CONTAINER_C.ENTITY.MBIN",
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CONTAINER/CONTAINERE/ENTITIES/CONTAINER_E.ENTITY.MBIN",
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CONTAINER/CONTAINERF/ENTITIES/CONTAINER_F.ENTITY.MBIN",
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CONTAINER/CONTAINERG/ENTITIES/CONTAINER_G.ENTITY.MBIN",
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CONTAINER/CONTAINERH/ENTITIES/CONTAINER_H.ENTITY.MBIN",
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTERSMALL_PROC/ENTITIES/SMALLFREIGHTER.ENTITY.MBIN",
						"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTERTINY_PROC/ENTITIES/_TINY_FREIGHTER.ENTITY.MBIN",
					},
					["EXML_CHANGE_TABLE"] 	=
					{
						{
							["PKW"]  = "StandingChangeOnDeath",
							["VCT"] = {
								{"None", "0"},
							},
						},
					},
				},
			}
		}
	}	
}
