-----------------------------------------------------------
local desc = [[
  Remove ambient audio from decorations and building parts
]]---------------------------------------------------------

local path = 'MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/'

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '__MODEL remove ambient sounds.pak',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= 3.75,
	MOD_BATCHNAME		= '_MODELS ~@~collection.pak',
	MOD_DESCRIPTION		= desc,
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE	= {
			path..'DECORATION/AQUARIUM/ENTITIES/AQUARIUM.ENTITY.MBIN',
			path..'DECORATION/LARGEDESK/ENTITIES/AUDIOLARGEDESK.ENTITY.MBIN',
			path..'DECORATION/ENCASEDMONITOR/ENTITIES/AUDIOMONITOR.ENTITY.MBIN',
			path..'DECORATION/MONITORDESK/ENTITIES/AUDIOSCREENSTAND.ENTITY.MBIN',
			path..'DECORATION/SERVERSTACK/ENTITIES/AUDIOSERVER.ENTITY.MBIN',
			path..'DECORATION/TERRARIUM/ENTITIES/TERRARIUM.ENTITY.MBIN',
			path..'DECORATION/TOY_CORE/ENTITIES/AUDIOTOYCORE.ENTITY.MBIN',
			path..'FOLIAGE/HYDROPOD/ENTITIES/PODGROWING.ENTITY.MBIN',
			path..'FOLIAGE/WEIRDCUBE/ENTITIES/CUBOIDSMALL.ENTITY.MBIN',
			path..'NPCROOMS/NPC_CONSTRUCTION/ENTITIES/WORKSTATION.ENTITY.MBIN',
			path..'NPCROOMS/NPC_FARMING/ENTITIES/WORKSTATION.ENTITY.MBIN',
			path..'NPCROOMS/NPC_SCIENCE/ENTITIES/WORKDESK.ENTITY.MBIN',
			path..'NPCROOMS/NPC_WEAPONS/ENTITIES/WORKSTATION.ENTITY.MBIN',
			path..'TERMINAL_CUBECRATE/ENTITIES/TERMINALCHAR.ENTITY.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				VALUE_CHANGE_TABLE 	= {
					{'Ambient', ''}
				}
			}
		}
	}
}}}}
