--[[┎──────────────────────────────────────────────────────────
	┃ 				EXCLUDED FROM BATCH
	┠──────────────────────────────────────────────────────
	┃ Remove ambient audio from decorations and building parts
────┸──────────────────────────────────────────────────────--]]
File_Path = 'MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/'

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '__MODEL remove ambient sounds.pak',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= '3.53',
	MOD_BATCHNAME		= '_MODELS ~@~collection.pak',
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE	= {
			File_Path..'BUILDABLEPARTS/TERMINAL_CUBECRATE/ENTITIES/TERMINALCHAR.ENTITY.MBIN',
			File_Path..'BUILDABLEPARTS/DECORATION/AQUARIUM/ENTITIES/AQUARIUM.ENTITY.MBIN',
			File_Path..'BUILDABLEPARTS/DECORATION/LARGEDESK/ENTITIES/AUDIOLARGEDESK.ENTITY.MBIN',
			File_Path..'BUILDABLEPARTS/DECORATION/ENCASEDMONITOR/ENTITIES/AUDIOMONITOR.ENTITY.MBIN',
			File_Path..'BUILDABLEPARTS/DECORATION/MONITORDESK/ENTITIES/AUDIOSCREENSTAND.ENTITY.MBIN',
			-- File_Path..'BUILDABLEPARTS/FOLIAGE/HYDROPOD/ENTITIES/PODGROWING.ENTITY.MBIN',
			-- File_Path..'BUILDABLEPARTS/FOLIAGE/WEIRDCUBE/ENTITIES/CUBOIDSMALL.ENTITY.MBIN',
			File_Path..'BUILDABLEPARTS/DECORATION/SERVERSTACK/ENTITIES/AUDIOSERVER.ENTITY.MBIN',
			File_Path..'BUILDABLEPARTS/DECORATION/TERRARIUM/ENTITIES/TERRARIUM.ENTITY.MBIN',
			File_Path..'COMMONPARTS/TELEPORTER_NEXUS/ENTITIES/TELEPORTERNEXUSINTERACTION.ENTITY.MBIN'
		},
		EXML_CHANGE_TABLE	= {
			{
				VALUE_CHANGE_TABLE 	= {
					{'Ambient', ''}
				}
			}
		}
	}
}}}}
