NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]  = "_____ZV4X.GrassNOT.pak",
["MOD_AUTHOR"]    = "ZV4X",
["LUA_AUTHOR"]    = "Babscoole",
["NMS_VERSION"]   = "3.37",
["MODIFICATIONS"] =
    {
        {
            ["MBIN_CHANGE_TABLE"] =
            {
                {
                    ["MBIN_FILE_SOURCE"] = 
                    {
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\BLOBBYGRASS01\BLOBBYGRASSMAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\BLOBBYGRASS01\BLOBBYGRASSMAT2.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\BUBBLELUSHGRASS\BUBBLEGRASSGLOWMAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CHEESEPLANT\PHONG12.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CLOVER01\CLOVERMAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CROSSGRASS\LUSHGRASS1MAT1.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CROSSGRASS\LUSHGRASS2MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CROSSGRASS\LUSHGRASS3MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CROSSGRASS\LUSHGRASS4MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CROSSGRASS\LUSHGRASS5MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CROSSGRASS\LUSHGRASS6MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CROSSGRASS\LUSHGRASS7MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\CROSSGRASS\VOLUMEBUSHMAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSBILLBOARD\LUSHGRASS1MAT1.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSBILLBOARD\LUSHGRASS2MAT1.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSBILLBOARD\LUSHGRASS3MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSBILLBOARD\LUSHGRASS4MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSBILLBOARD\LUSHGRASS5MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSBILLBOARD\LUSHGRASS6MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSBILLBOARD\LUSHGRASS7MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSBILLBOARD\LUSHGRASS8MAT1.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSCLUMP01\GRASSLUSHMAT1.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSLUSH\BLOBBYGRASSMAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\GRASSVARIATION01\THINGRASS01MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\LONGALTGRASS\LONGALTGRASSMAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\BLOBBYGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\CROSSGRASS_LUSHGRASS3MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\CROSSGRASS_LUSHGRASS4MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\CROSSGRASS_LUSHGRASS5MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\CROSSGRASS_LUSHGRASS6MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\CURLYGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\DANDEGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\GRASSSEAWEED_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWCROSSGRASS\TENTACLEGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWLUSHGRASS\LUSHNEW_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\BLOBBYGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\CROSSGRASS_LUSHGRASS3MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\CROSSGRASS_LUSHGRASS4MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\CROSSGRASS_LUSHGRASS5MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\CROSSGRASS_LUSHGRASS6MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\CURLYGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\DANDEGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\GRASSSEAWEED_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\SMLBGRASSNEW_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\TENTACLEGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWPROCGRASS\ENTITIES\_GRASS_SAMPHIRE.ENTITY.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWSCRUBGRASS\CHEESEGRASS_1EXP_PHONG13.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\NEWSCRUBGRASS\NEWSCRUBGRASS_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\PROCGRASSCLUMP\PROCGRASS4MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\PROCGRASSCLUMP\SMALL_WEED_MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\TALLGRASSBILLBOARD\TALLGRASSHIMAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\TALLGRASSBILLBOARD\TALLGRASSMAT2.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\TALLGRASSBILLBOARD\TALLGRASSMAT3.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\TALLGRASSBILLBOARD\TALLGRASSMAT4.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\TALLGRASSBILLBOARD\TALLGRASSMAT6.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\THINGRASS01\THINGRASS01MAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\WILDGRASS01\WILDGRASSMAT.MATERIAL.MBIN",
                        "MODELS\PLANETS\BIOMES\COMMON\GRASS\WILDGRASS02\WILDGRASS_01.MATERIAL.MBIN",
                    },
                    ["EXML_CHANGE_TABLE"] =
                    {
                        {
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"Shader", "SHADERS/BASIC.SHADER.BIN"},
                            }
                        },
                    }
                },
            }
        },
    }
}