NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME = "bSilent Refiners",
	MOD_AUTHOR = "Bladehawke",
	LUA_AUTHOR = "Bladehawke",
	NMS_VERSION = "6.0",
	MOD_DESCRIPTION = "This mod silences refiners",
	MODIFICATIONS = {
		{
			MBIN_CHANGE_TABLE = {
				{
					MBIN_FILE_SOURCE = {
						"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/REFINER/ENTITIES/REFINER1.ENTITY.MBIN",
						"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/REFINER/ENTITIES/REFINER2.ENTITY.MBIN",
						"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/REFINER/ENTITIES/REFINER3.ENTITY.MBIN",
						"MODELS/COMMON/PLAYER/PLAYERCHARACTER/PLAYERCHARACTER/ENTITIES/PLAYERCHARACTER.ENTITY.MBIN"},
					MXML_CHANGE_TABLE = {
						{
							SPECIAL_KEY_WORDS = {"StateID", "REFINE_START", "Action", "GcPlayAudioAction"},
							VALUE_CHANGE_TABLE = {
								{"Sound", ""}
							}
						}
					}
				}
			}
		}
	}
}