NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Engine Trails Disabler",
["MOD_AUTHOR"]      = "JinxM0D",
["LUA_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "7.01",
["MOD_DESCRIPTION"] = "This mod disables all engine trails and their particle effects in the entire game",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\EFFECTS\MODULES\PLASMAENGINE\FLARE.PARTICLE.MBIN",
            "MODELS\EFFECTS\MODULES\PLASMAENGINE\FLATMIST.PARTICLE.MBIN",
            "MODELS\EFFECTS\MODULES\PLASMAENGINE\GLOW.PARTICLE.MBIN",
            "MODELS\EFFECTS\MODULES\PLASMAENGINE\MIST.PARTICLE.MBIN",
            "MODELS\EFFECTS\MODULES\PLASMAENGINE\MOTES.PARTICLE.MBIN",
            "MODELS\EFFECTS\MODULES\PLASMAENGINE\RINGS.PARTICLE.MBIN",
            "MODELS\EFFECTS\MODULES\PLASMAENGINE\ROOFMIST.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\ATLASSHIPTRAIL\ELECFACING.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\ATLASSHIPTRAIL\FLARE.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\ATLASSHIPTRAIL\GLOW.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\ATLASSHIPTRAIL\LONGFLARE.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\ATLASSHIPTRAIL\REFRACTION.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\ATLASSHIPTRAIL\RINGS.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\RAINBOWTRAILSPARKLE\EMITTERS\SPARKLEBEMITTER.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\RAINBOWTRAILSPARKLE\EMITTERS\SPARKLEGEMITTER.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\RAINBOWTRAILSPARKLE\EMITTERS\SPARKLEREMITTER.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPSPLUTTERINGTRAIL\BANG.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPSPLUTTERINGTRAIL\DISTORTION.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPSPLUTTERINGTRAIL\JETFIRE.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPSPLUTTERINGTRAIL\SMOKE.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPSPLUTTERINGTRAIL\SPARKS.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPTIMELOOPTRAIL\BLACKHOLE.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPTIMELOOPTRAIL\DISTORTION.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPTIMELOOPTRAIL\FLARE.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPTIMELOOPTRAIL\RINGSPARKS.PARTICLE.MBIN",
            "MODELS\EFFECTS\SPACECRAFT\SHIPTIMELOOPTRAIL\WARPBASE.PARTICLE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"MaxCount", "0"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\EFFECTS\TRAILS\SPACECRAFT\HOT\HOTTRAIL.TRAIL.MBIN",
            "MODELS\EFFECTS\TRAILS\SPACECRAFT\HOT\PLASMATRAIL.TRAIL.MBIN",
            "MODELS\EFFECTS\TRAILS\SPACECRAFT\HOT\RAINBOWTRAIL.TRAIL.MBIN",
            "MODELS\EFFECTS\TRAILS\SPACECRAFT\HOT\SPLUTTERINGTRAIL.TRAIL.MBIN",
            "MODELS\EFFECTS\TRAILS\SPACECRAFT\HOT\SWARMDRONETRAIL.TRAIL.MBIN",
            "MODELS\EFFECTS\TRAILS\SPACECRAFT\HOT\TIMELOOPTRAIL.TRAIL.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"MaxPointsPerFrame", "0"},
              }
            },
          }
        },
      }
    }
  }
}