NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Mission Hints Stay Forever",
["MOD_AUTHOR"]      = "",
["LUA_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "6.45",
["MOD_DESCRIPTION"] = "Mission hints stay forever",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "METADATA\SIMULATION\MISSIONS\TABLES\ATLASPATHTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\BASECOMPUTERMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\COMMUNITYMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\COREMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\CORVETTEMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\DEBUGMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\DEPRECATEDMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\FLEETMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\MISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\MULTIPLAYERMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\NPCMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\PIRATEMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\PLANETPROCMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\RECURRINGMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\SEASONALBESPOKEMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\SEASONALMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\SENTINELSETTLEMENTMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\SPACEPOIMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\STARTEDONUSEMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\STATSTORIESMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\TUTORIALMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\WATERMISSIONTABLE.MBIN",
            "METADATA\SIMULATION\MISSIONS\TABLES\WIKIMISSIONTABLE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"CustomNotifyTimers", "GcCustomNotifyTimerOptions"},
              ["REPLACE_TYPE"] = "ALL",
              ["VALUE_CHANGE_TABLE"] =
              {
                {"HasCustomNotifyTimer", "true"},
                {"NotifyDisplayTime",    "50000000.000000"},
                {"NotifyPauseTime",      "100000000.000000"},
              },
            },
          }
        },
      }
    },
  }
}