NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Waterless Deserts",
["MOD_AUTHOR"]      = "camus",
["LUA_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "6.45",
["MOD_DESCRIPTION"] = "Removes chance for water on barren/desert and frozen biomes",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENBIGPROPSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENCORALBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHIVESBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENINFESTEDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOCEANBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENPEACOCKBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENROCKYBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENROCKYWEIRDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENRUINSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DESOLATE\DESOLATEBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENBIGPROPSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENINFESTEDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENISLANDSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENPILLARBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENROCKYWEIRDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENRUINSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SUBZERO\SUBZEROBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SUBZERO\SUBZREMIX\SUBZREMIXBIOME.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"Terrain", "GcTerrainControls"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"WaterActiveFrequency",     "0.000000"},
                {"HighWaterActiveFrequency", "0.000000"},
              },
            },
          }
        },
      }
    },
  }
}