cd ..\..\_ENGINE\RGOG
copy SRC\REDMASPARAMS\REDMAS_SANDWORM_OVERHAUL_PRESET.lua USERPARAMS\REDMAS_SANDWORM_OVERHAUL_PRESET.lua

cd LITE
start  lite.exe ..\USERPARAMS\REDMAS_SANDWORM_OVERHAUL_PRESET.lua
