dofile([[OBE_methods.lua]])

SETTINGS = {
	["PREFIX"] = "DT",
	["SECTIONS"] = {
		"MAIN_LMK"
	},
	["REPLACEMENTS"] = {
		{
			["OLD_MODEL"] = "MODELS/PLANETS/BIOMES/BARREN/PLANTS/LARGECACTUS.SCENE.MBIN",
			["NEW_MODEL"] = "CUSTOMMODELS/CODENAMEAWESOME/PLANETS/BIOMES/UNFROZEN/LARGEPROPS/LARGETREEBARE.SCENE.MBIN",
			["FIRST_ONLY"] = true
		},
		{
			["OLD_MODEL"] = "MODELS/PLANETS/BIOMES/SCORCHED/LARGE/LARGESPIRE.SCENE.MBIN",
			["NEW_MODEL"] = "CUSTOMMODELS/CODENAMEAWESOME/PLANETS/BIOMES/UNFROZEN/LARGEPROPS/LARGETREEBARE.SCENE.MBIN",
			["FIRST_ONLY"] = true
		},
		{
			["OLD_MODEL"] = "MODELS/PLANETS/BIOMES/LAVA/LARGEPROPS/DEADTREE.SCENE.MBIN",
			["NEW_MODEL"] = "CUSTOMMODELS/CODENAMEAWESOME/PLANETS/BIOMES/UNFROZEN/LARGEPROPS/LARGETREEBARE.SCENE.MBIN"
		},
		{
			["OLD_MODEL"] = "MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN",
			["NEW_MODEL"] = "CUSTOMMODELS/CODENAMEAWESOME/PLANETS/BIOMES/UNFROZEN/LARGEPROPS/LARGETREEBARE.SCENE.MBIN",
			["FIRST_ONLY"] = true
		},
		{
			["OLD_MODEL"] = "MODELS/PLANETS/BIOMES/TOXIC/LARGE/FUNGALTREE.SCENE.MBIN",
			["NEW_MODEL"] = "CUSTOMMODELS/CODENAMEAWESOME/PLANETS/BIOMES/UNFROZEN/LARGEPROPS/LARGETREEBARE.SCENE.MBIN",
			["FIRST_ONLY"] = true,
			["MULTIPLIERS"] = {
				["MinScale"] = 0.75,
				["MaxScale"] = 0.75,
			}
		}
	}
}

MBIN_CHANGE_TABLE = create_model_swap_table(SETTINGS)

NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] = "Must be combined.pak",
  ["MOD_BATCHNAME"] = "OpenBiomeExtender.pak",
  ["MOD_AUTHOR"] = "CodenameAwesome",
  ["MODIFICATIONS"] =
	{
		{
			["MBIN_CHANGE_TABLE"] = MBIN_CHANGE_TABLE
		},
	}
}