NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "PU_ClearStorms",
["MOD_AUTHOR"]      = "Trevix",
["LUA_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "6.30",
["MOD_DESCRIPTION"] = "ClearStorms",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\BLUEWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\BUBBLEWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\CLEARCOLD.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\CLEARWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\DUSTWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\FIRESTORMWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\GASGIANTWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\GRAVITYSTORMWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\GREENWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\HUMIDWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\LAVAWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\RADIOACTIVE.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\RAINWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\REDWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\SCORCHED.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\SNOWWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\SWAMPWEATHER.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\TOXIC.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\WEATHER\WEIRDWEATHER.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Weighting",         "1.000000"},
                {"FogStrength",       "1.500000"},
                {"FogMax",            "1.000000"},
                {"FogColourStrength", "1.200000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "SkyColour", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.250000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "SkyUpperColour", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.250000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "HorizonColour", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.50000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "SunColour", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.250000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "FogColour", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.50000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "HeightFogColour", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.50000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "LightColour", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.250000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "CloudColour1", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.250000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Storms", "GcStormProperties", "CloudColour2", "GcColourModifier"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"OffsetSaturation",   "0.000000"},
                {"OffsetValue",        "-0.250000"},
                {"MultiplySaturation", "0.750000"},
                {"MultiplyValue",      "1.000000"},
              },
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENBIGPROPSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENCORALBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENHIVESBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENHQBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENINFESTEDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENOCEANBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENPEACOCKBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENROCKYBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENROCKYWEIRDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENRUINSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DESOLATE/DESOLATEBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FLORAL/FLORALBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENBIGPROPSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENINFESTEDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENISLANDSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENPILLARBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENROCKYBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENROCKYWEIRDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENRUINSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGELUSH/HUGELUSHBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGERING/HUGERINGBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEROCK/HUGEROCKBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGESCORCHED/HUGESCORCHBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGETOXIC/HUGETOXICBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/HUGEUVWPLANTBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/IRRADIATED/IRRADIATEDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/IRRADIATED/IRRADREMIX/IRRADREMIXBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/JUNGLE/JUNGLEBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LAVA/LAVABIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LAVA/LAVAISLANDSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHBIGPROPSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHBUBBLESBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHHQBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHHQTENTACLEBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHINFESTEDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROCKYBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROCKYWEIRDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROOMABIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROOMBBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHRUINSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHULTRABIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/NOXIOUS/NOXIOUSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/NOXIOUS/NOXREMIX/NOXREMIXBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEGLOWBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEISLANDSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVERUINSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEVARIANTBBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOBIGPROPSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOINFESTEDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOSPIKECRYSTALSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/ROCKY/ROCKBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHBIGPROPSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHCORALBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHEDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHEDRUINSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHEDSHIELDTREEBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHINFESTEDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHOCEANBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SUBZERO/SUBZEROBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SUBZERO/SUBZREMIX/SUBZREMIXBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/SWAMPBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/SWAMPISLANDSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICBIGPROPSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICEGGSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICINFESTEDBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICISLANDSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICOCEANBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICROCKYBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICRUINSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICSPORESBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICTENTACLESBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WATERWORLD/WATERWORLDCORALBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WATERWORLD/WATERWORLDCRYSTALSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WATERWORLD/WATERWORLDFROZENBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WATERWORLD/WATERWORLDHOTBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WATERWORLD/WATERWORLDROCKYBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/BEAMSTONE/BEAMSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/BONESPIRE/BONESPIREBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/CONTOUR/CONTOURBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/ELBUBBLE/ELBUBBLEBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/FRACTALCUBE/FRACTCUBEBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HEXAGON/HEXAGONBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HOUDINIPROPS/HOUDINIPROPSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HYDROGARDEN/HYDROGARDENBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/IRRISHELLS/IRRISHELLSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/MSTRUCTURES/MSTRUCTBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/SHARDS/SHARDSBIOME.MBIN"
            "METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/WIRECELLS/WIRECELLSBIOME.MBIN"
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"CloudSettings", "GcBiomeCloudSettings"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"MinCoverage",         "0.0150000"},
                {"MaxCoverage",         "0.400000"},
                {"MinCoverageVariance", "0.000000"},
                {"MaxCoverageVariance", "0.150000"},
                {"MinCover",            "-0.900000"},
                {"MaxCover",            "0.600000"},
                {"MinVariance",         "0.000000"},
                {"MaxVariance",         "0.400000"},
                {"MinRatio",            "0.2000000"},
                {"MaxRatio",            "0.800000"},
              }
            },
          }
        },
      }
    },
  }
}