local FishID = {
"F_ALL_COM_S1",
"F_ALL_COM_S2",
"F_ALL_COM_S3",
"F_ALL_COM_M1",
"F_ALL_COM_M2",
"F_ALL_COM_L1",
"F_ALL_COM_XL",
"F_ALL_RARE_S1",
"F_ALL_RARE_S2",
"F_ALL_RARE_M1",
"F_ALL_RARE_M2",
"F_ALL_RARE_L1",
"F_ALL_RARE_XL",
"F_ALL_EPIC_S1",
"F_ALL_EPIC_M1",
"F_ALL_EPIC_L1",
"F_ALL_EPIC_XL",
"F_ALL_LEG_S1",
"F_ALL_LEG_M1",
"F_ALL_LEG_L1",
"F_ALL_LEG_XL",
"F_TOX_COM_S1",
"F_TOX_COM_S2",
"F_TOX_COM_S3",
"F_TOX_COM_M1",
"F_TOX_COM_M2",
"F_TOX_COM_L1",
"F_TOX_COM_XL",
"F_TOX_RARE_S1",
"F_TOX_RARE_S2",
"F_TOX_RARE_M1",
"F_TOX_RARE_M2",
"F_TOX_RARE_L1",
"F_TOX_RARE_XL",
"F_TOX_EPIC_S1",
"F_TOX_EPIC_M1",
"F_TOX_EPIC_L1",
"F_TOX_EPIC_XL",
"F_TOX_LEG_S1",
"F_TOX_LEG_M1",
"F_TOX_LEG_L1",
"F_TOX_LEG_XL",
"F_RAD_COM_S1",
"F_RAD_COM_S2",
"F_RAD_COM_S3",
"F_RAD_COM_M1",
"F_RAD_COM_M2",
"F_RAD_COM_L1",
"F_RAD_COM_XL",
"F_RAD_RARE_S1",
"F_RAD_RARE_S2",
"F_RAD_RARE_M1",
"F_RAD_RARE_M2",
"F_RAD_RARE_L1",
"F_RAD_RARE_XL",
"F_RAD_EPIC_S1",
"F_RAD_EPIC_M1",
"F_RAD_EPIC_L1",
"F_RAD_EPIC_XL",
"F_RAD_LEG_S1",
"F_RAD_LEG_M1",
"F_RAD_LEG_L1",
"F_RAD_LEG_XL",
"F_HOT_COM_S1",
"F_HOT_COM_S2",
"F_HOT_COM_S3",
"F_HOT_COM_M1",
"F_HOT_COM_M2",
"F_HOT_COM_L1",
"F_HOT_COM_XL",
"F_HOT_RARE_S1",
"F_HOT_RARE_S2",
"F_HOT_RARE_M1",
"F_HOT_RARE_M2",
"F_HOT_RARE_L1",
"F_HOT_RARE_XL",
"F_HOT_EPIC_S1",
"F_HOT_EPIC_M1",
"F_HOT_EPIC_L1",
"F_HOT_EPIC_XL",
"F_HOT_LEG_S1",
"F_HOT_LEG_M1",
"F_HOT_LEG_L1",
"F_HOT_LEG_XL",
"F_DUST_COM_S1",
"F_DUST_COM_S2",
"F_DUST_COM_S3",
"F_DUST_COM_M1",
"F_DUST_COM_M2",
"F_DUST_COM_L1",
"F_DUST_COM_XL",
"F_DUST_RARE_S1",
"F_DUST_RARE_S2",
"F_DUST_RARE_M1",
"F_DUST_RARE_M2",
"F_DUST_RARE_L1",
"F_DUST_RARE_XL",
"F_DUST_EPIC_S1",
"F_DUST_EPIC_M1",
"F_DUST_EPIC_L1",
"F_DUST_EPIC_XL",
"F_DUST_LEG_S1",
"F_DUST_LEG_M1",
"F_DUST_LEG_L1",
"F_DUST_LEG_XL",
"F_ODD_COM_S1",
"F_ODD_COM_S2",
"F_ODD_COM_S3",
"F_ODD_COM_M1",
"F_ODD_COM_M2",
"F_ODD_COM_L1",
"F_ODD_COM_XL",
"F_ODD_RARE_S1",
"F_ODD_RARE_S2",
"F_ODD_RARE_M1",
"F_ODD_RARE_M2",
"F_ODD_RARE_L1",
"F_ODD_RARE_XL",
"F_ODD_EPIC_S1",
"F_ODD_EPIC_M1",
"F_ODD_EPIC_L1",
"F_ODD_EPIC_XL",
"F_ODD_LEG_S1",
"F_ODD_LEG_M1",
"F_ODD_LEG_L1",
"F_ODD_LEG_XL"
}

local function CreateShopID(NewID)
    return [[
        <Property value="NMSString0x10.xml">
            <Property name="Value" value="]] .. NewID .. [[" />
        </Property>
    ]]
end

local ADDFishID = {}
for i=1,#FishID do
    ADDFishID[#ADDFishID + 1] = CreateShopID(FishID[i])
end

local ADDFishID = table.concat(ADDFishID,"\n")

NMS_MOD_DEFINITION_CONTAINER = {
    ["MOD_FILENAME"] = "AltF4_AddFishToShop.pak",
    ["MOD_AUTHOR"] = "AltF4",
    ["LUA_AUTHOR"] = "AltF4",
    ["NMS_VERSION"] = "5.10",
    ["MOD_DESCRIPTION"] = "Add Fish to space station shop.",
    ["MODIFICATIONS"] = {
        {
            ["MBIN_CHANGE_TABLE"] = {
                {
                    ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\DEFAULTREALITY.MBIN",
                    ["EXML_CHANGE_TABLE"] = {
                        {
                            ["PRECEDING_KEY_WORDS"] = {
                                {"TradeSettings", "SpaceStation", "AlwaysPresentProducts"},
                                {"TradeSettings", "Shop", "AlwaysPresentProducts"},
                            },
                            ["ADD"] = ADDFishID
                        },
                    }
                },
            },
        },
    }
}