
STD 	 = {R=0.48, G=0.59, B=0.67};
LOWVALUE = {R=0.54, G=0.5, B=0.447};
GAZ 	 = {R=0.23, G=0.55, B=0.89};
PLANT 	 = {R=0.22, G=0.55, B=0.21};
DARK	 = {R=0.28, G=0.28, B=0.28};
VALUABLE = {R=0.88, G=0.82, B=0.60};
GOLD	 = {R=0.86, G=0.58, B=0.0};
BLUE	 = {R=0.11, G=0.26, B=0.41};
PURPLE	 = {R=0.38, G=0.07, B=0.27};
RACE	 = {R=0.19, G=0.26, B=0.20};

PRODUCTS =
{
 {"AMMO", DARK}, 
 {"HEXCORE", DARK}, 
 {"FARMPROD3", STD}, 
 {"JELLY", STD}, 
 {"POWERCELL", STD}, 
 {"PRODFUEL2", STD}, 
 {"SCRAP_GOODS", DARK}, 
 {"SCRAP_TECH", DARK}, 
 {"PRODFUEL1", STD}, 
 {"LAUNCHFUEL", STD}, 
 {"SCRAP_WEAP", DARK}, 
 {"NANOTUBES", STD}, 
 {"POWERCELL2", STD}, 
 {"SHIPCHARGE", STD}, 
 {"OXY_CRAFT", STD}, 
 {"CARBON_SEAL", STD}, 
 {"CASING", STD}, 
 {"ACCESS1", DARK}, 
 {"ATLAS_SEED_1", DARK}, 
 {"ATLAS_SEED_10", DARK}, 
 {"ATLAS_SEED_2", DARK}, 
 {"ATLAS_SEED_3", DARK}, 
 {"ATLAS_SEED_4", DARK}, 
 {"ATLAS_SEED_5", DARK}, 
 {"ATLAS_SEED_6", DARK}, 
 {"ATLAS_SEED_7", DARK}, 
 {"ATLAS_SEED_8", DARK}, 
 {"ATLAS_SEED_9", DARK}, 
 {"NAV_DATA", DARK}, 
 {"ACCESS2", DARK}, 
 {"MICROCHIP", STD}, 
 {"ACCESS3", DARK}, 
 {"GEODE_LAND", STD}, 
 {"GEODE_CAVE", STD}, 
 {"GEODE_CRYSTAL", STD}, 
 {"GEODE_SPACE", STD}, 
 {"GEODE_ASTEROID", STD}, 
 {"GEODE_RARE", STD}, 
 {"CATA_CRAFT", STD}, 
 {"HYDRALIC", STD}, 
 {"FUELPROD3", LOWVALUE}, 
 {"LANDPROD3", LOWVALUE}, 
 {"COMPUTER", STD}, 
 {"CLAMPEARL", LOWVALUE}, 
 {"OXYPROD3", LOWVALUE}, 
 {"ANTIMATTER", STD}, 
 {"GRENFUEL1", STD}, 
 {"CAVECUBE", LOWVALUE}, 
 {"MAGNET", STD},
 {"MIRROR", STD},
 {"CAVEPROD3", LOWVALUE}, 
 {"WATERPROD3", LOWVALUE}, 
 {"AM_HOUSING", STD}, 
 {"SUBFUEL", STD}, 
 {"VENTGEM", LOWVALUE}, 
 {"ALBUMENPEARL", LOWVALUE}, 
 {"POLICE_TOKEN", DARK}, 
 {"WAR_CURIO2", RACE}, 
 {"REPAIRKIT", DARK}, 
 {"BIO", STD}, 
 {"CATAPROD3", LOWVALUE}, 
 {"SACVENOM", VALUABLE}, 
 {"EXP_CURIO2", RACE}, 
 {"GRAVBALL", VALUABLE}, 
 {"NIPNIPBUDS", PLANT}, 
 {"QUAD_PROD", VALUABLE}, 
 {"FRIGATE_FUEL_1", STD}, 
 {"CAVE_CRAFT", STD}, 
 {"TRA_CURIO2", RACE}, 
 {"EXP_CURIO1", RACE}, 
 {"TRA_CURIO1", RACE}, 
 {"WAR_CURIO1", RACE}, 
 {"TECH_COMP", DARK}, 
 {"ALLOY1", VALUABLE}, 
 {"ALLOY2", VALUABLE}, 
 {"ALLOY3", VALUABLE}, 
 {"ALLOY4", VALUABLE}, 
 {"ALLOY5", VALUABLE}, 
 {"ALLOY6", VALUABLE}, 
 {"WATER_CRAFT", VALUABLE}, 
 {"WALKER_PROD", VALUABLE}, 
 {"FRIGATE_FUEL_2", STD}, 
 {"HYPERFUEL1", STD}, 
 {"HYPERFUEL2", STD}, 
 {"BP_SALVAGE", DARK}, 
 {"FACT_TOKEN", DARK}, 
 {"FARMPROD6", VALUABLE}, 
 {"REACTION1", VALUABLE}, 
 {"REACTION2", VALUABLE}, 
 {"REACTION3", VALUABLE}, 
 {"EYEBALL", GOLD}, 
 {"FIENDCORE", GOLD}, 
 {"FRIGATE_FUEL_3", STD}, 
 {"NAV_DATA_DROP", DARK}, 
 {"FRIG_TOKEN", DARK}, 
 {"FREI_INV_TOKEN", DARK}, 
 {"WEAP_INV_TOKEN", DARK}, 
 {"SHIP_INV_TOKEN", DARK}, 
 {"SUIT_INV_TOKEN", DARK}, 
 {"FISHCORE", GOLD}, 
 {"FARMPROD2", GOLD}, 
 {"FARMPROD5", GOLD}, 
 {"STORM_CRYSTAL", GOLD}, 
 {"ALLOY7", GOLD}, 
 {"ALLOY8", GOLD}, 
 {"FARMPROD4", GOLD}, 
 {"FARMPROD1", GOLD}, 
 {"COMPOUND1", GOLD}, 
 {"COMPOUND2", GOLD}, 
 {"COMPOUND3", GOLD}, 
 {"FARMPROD8", GOLD}, 
 {"FARMPROD7", BLUE}, 
 {"FARMPROD9", BLUE}, 
 {"COMPOUND4", BLUE}, 
 {"COMPOUND5", BLUE}, 
 {"COMPOUND6", BLUE}, 
 {"MEGAPROD3", BLUE}, 
 {"MEGAPROD1", BLUE}, 
 {"MEGAPROD2", BLUE}, 
 {"ULTRAPROD1", PURPLE}, 
 {"ULTRAPROD2", PURPLE}, 
}

SUBSTANCES = 
{
	{"UI_AF_METAL_NAME", LOWVALUE}, 
	{"UI_FUEL_1_NAME", STD}, 
	{"UI_FUEL_2_NAME", STD},
	{"UI_AIR1_NAME", STD}, 
	{"UI_LAUNCHSUB_NAME", STD}, 
	{"UI_LAUNCHSUB2_NAME", STD}, 
	{"UI_ROCKETFUEL_NAME", STD}, 
	{"UI_LAND1_NAME", STD}, 
	{"UI_LAND2_NAME", STD}, 
	{"UI_LAND3_NAME", STD}, 
	{"UI_SAND1_NAME", STD}, 
	{"UI_WATER2_NAME", STD}, 
	{"UI_NEWCATA2_NAME", STD}, 
	{"UI_CAVE1_NAME", LOWVALUE}, 
	{"UI_CAVE2_NAME", LOWVALUE}, 
	{"UI_WATER1_NAME", LOWVALUE}, 
	{"UI_NEWWATER2_NAME", LOWVALUE}, 
	{"UI_WATERPLANT_NAME", LOWVALUE}, 
	{"UI_YELLOW2_NAME", LOWVALUE}, 
	--{"UI_RED2_NAME", STD}, 
	--{"UI_GREEN2_NAME", STD}, 
	--{"UI_BLUE2_NAME", STD}, 
	{"UI_STELLAR2_NAME", LOWVALUE}, 
	{"UI_LAVA1_NAME", STD}, 
	{"UI_LUSH1_NAME", STD}, 
	{"UI_DUSTY1_NAME", STD}, 
	{"UI_TOXIC1_NAME", STD}, 
	{"UI_RADIO1_NAME", STD}, 
	{"UI_COLD1_NAME", STD}, 
	{"UI_HOT1_NAME", STD}, 
	{"UI_PLANTSUB_DEADCREATURE_NAME", STD}, 
	{"SUB_DEADDRONE_NAME", LOWVALUE}, 
	{"UI_ASTEROID1_NAME", LOWVALUE}, 
	{"UI_ASTEROID2_NAME", LOWVALUE}, 
	{"UI_ASTEROID3_NAME", LOWVALUE}, 
	{"UI_GAS_1_NAME", GAZ}, 
	{"UI_GAS_2_NAME", GAZ}, 
	{"UI_GAS_3_NAME", GAZ}, 
	--{"UI_EX_YELLOW_NAME", STD}, 
	--{"UI_EX_RED_NAME", STD}, 
	--{"UI_EX_GREEN_NAME", STD}, 
	--{"UI_EX_BLUE_NAME", STD}, 
	{"UI_PLANTSUB_TOXIC_NAME", PLANT}, 
	{"UI_PLANTSUB_SNOW_NAME", PLANT}, 
	{"UI_PLANTSUB_RADIO_NAME", PLANT}, 
	{"UI_PLANTSUB_BARREN_NAME", PLANT}, 
	{"UI_PLANTSUB_SCORCHED_NAME", PLANT}, 
	{"UI_PLANTSUB_LUSH_NAME", PLANT}, 
	{"UI_PLANTSUB_CAVE_NAME", PLANT}, 
	{"UI_PLANTSUB_WATER_NAME", PLANT}, 
	{"UI_PLANTSUB_CREATUREPOOP_NAME", PLANT}, 
	{"UI_MAINTAIN_SUB1_NAME", STD}, 
	{"UI_MAINTAIN_SUB2_NAME", STD}, 
	{"UI_MAINTAIN_SUB3_NAME", STD}, 
	{"UI_MAINTAIN_SUB4_NAME", STD}, 
	{"UI_MAINTAIN_SUB5_NAME", STD}, 
};


local change_product_table = {}

for i = 1,#PRODUCTS do
  local current_change =
  {
	["SPECIAL_KEY_WORDS"] = {"Id", PRODUCTS[i][1]},
	["PRECEDING_KEY_WORDS"] = {"Colour"},
	["INTEGER_TO_FLOAT"] = "FORCE",
	["VALUE_CHANGE_TABLE"] 	= 
	{
		{"R",	PRODUCTS[i][2].R}; 
		{"G",	PRODUCTS[i][2].G};
		{"B",	PRODUCTS[i][2].B};
	}
  }
  table.insert(change_product_table, current_change)
end


local change_substance_table = {}

for i = 1,#SUBSTANCES do
  local current_change =
  {
	["SPECIAL_KEY_WORDS"] = {"Name", SUBSTANCES[i][1]},
	["PRECEDING_KEY_WORDS"] = {"Colour"},
	["INTEGER_TO_FLOAT"] = "FORCE",
	["VALUE_CHANGE_TABLE"] 	= 
	{
		{"R",	SUBSTANCES[i][2].R}; 
		{"G",	SUBSTANCES[i][2].G};
		{"B",	SUBSTANCES[i][2].B};
	}
  }
  table.insert(change_substance_table, current_change)
end


NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] 		= "Colorless Inventory 4.1.pak", 
  ["MOD_AUTHOR"]		= "Lo2k",
  ["NMS_VERSION"]		= "3.84",
  ["MOD_DESCRIPTION"]	= "This mods changes background of most items",
  ["MODIFICATIONS"] = 
  {
    {
    ["MBIN_CHANGE_TABLE"] = 
      {
        {
          ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN",
          ["EXML_CHANGE_TABLE"] = change_product_table
        },
		{
          ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\NMS_REALITY_GCSUBSTANCETABLE.MBIN",
          ["EXML_CHANGE_TABLE"] = change_substance_table
        },
      }
    },
  }
}