NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "No Damaged Machineries in Abandoned Buildings.pak", 
["MOD_AUTHOR"]				= "Lo2k",
["NMS_VERSION"]				= "2.61.1",
["MOD_DESCRIPTION"]			= "This mod removes damaged machineries in abandoned buildings",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= {
					"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\ABANDONED\ABANDONDEDSCIENTIFIC.LSYSTEM.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\ABANDONED\ABANDONDEDTRADER.LSYSTEM.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\ABANDONED\ABANDONDEDWARRIOR.LSYSTEM.MBIN",
					"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\ABANDONED\UNDERWATER_ABANDONDEDSCIENTIFIC.LSYSTEM.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\ABANDONED\UNDERWATER_ABANDONDEDTRADER.LSYSTEM.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\ABANDONED\UNDERWATER_ABANDONDEDWARRIOR.LSYSTEM.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Model", "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/DEBRIS/DEBRISLARGE_COMMON.SCENE.MBIN",},
							["REMOVE"] 	= "SECTION",
						},
						{
							["SPECIAL_KEY_WORDS"] = {"LocatorType", "TECHBOX_",},
							["REPLACE_TYPE"] = "ALL",
							["REMOVE"] 	= "SECTION",
						},
					},
				}	
			}
		}
	}	
}