NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "No Glowing Plants 1.2.pak", 
["MOD_AUTHOR"]				= "Lo2k",
["LUA_AUTHOR"]				= "Lo2k",
["NMS_VERSION"]				= "4.03",
["MOD_DESCRIPTION"]			= "This mod removes light from common red, blue and yellow plants",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= 
					{
					  "MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\COMMODITYPLANT.SCENE.MBIN", 
					  "MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\COMMODITYPLANT1.SCENE.MBIN", 
					  "MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FUELPLANT.SCENE.MBIN", 
					  "MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FUELPLANT1.SCENE.MBIN", 
					  "MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FUELPLANTSTARTSCENE.SCENE.MBIN", 
					  "MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\TECHPLANT1.SCENE.MBIN", 
					},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{  
							["SPECIAL_KEY_WORDS"] = {"Type", "LIGHT",},
							["REMOVE"] 	= "SECTION",
						},	
					},
				}	
			}
		}
	}	
}
