NMS_MOD_DEFINITION_CONTAINER = 
{
MOD_FILENAME = "Smokeless Stations - Full.pak", 
MOD_AUTHOR	 = "Lo2k",
LUA_AUTHOR	 = "Lo2k",
NMS_VERSION  = "5.73",
MOD_DESCRIPTION = "Removes smokes effects from Stations",
MODIFICATIONS= 
	{
		{
			MBIN_CHANGE_TABLE = 
			{ 
				{
					MBIN_FILE_SOURCE = {				
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONCORRIDORMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONELEC.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONEXTERIORDAMAGEMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONFLOORMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONTUNNELMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDVOLUMELIGHT.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/PIRATECENTRALORBEMBERS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/PIRATECENTRALORBMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/PIRATEFLOORMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/PIRATEFRIGATEHANGERVOLUMELIGHT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/PIRATEROOFMIST.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/CENTRALORBBEAMSPARKS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/CENTRALORBCOOLANT.MBIN",
					--"MODELS/EFFECTS/STATION/CENTRALORBCOOLANT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/CENTRALORBDUSTSPARKS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/CENTRALORBFOG.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ORBEYE.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ORBLOWERMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ORBVOLUMELIGHT.SCENE.MBIN",
									
					--"MODELS/EFFECTS/STATION/STATIONBILLBOARDGLOW.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONCLOUDS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONEXHAUSTVENT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONEXTERIORLIGHTGLOW.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/ENTRANCESMOKE.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LANDINGPADSMOKEBURST.SCENE.MBIN",
				    --"MODELS/EFFECTS/STATION/GENERALFLOATINGSMOKE.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LANDINGPADSMOKELOOP.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LAUNCHTUBEFILLMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LAUNCHTUBEPIPESTEAM.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LAUNCHTUBESTEAM.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/STATIONGLOWLINEMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONGROUNDMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONTOWERCLOUDS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONTUNNELFOG.SCENE.MBIN",		
					--"MODELS/EFFECTS/STATION/STATIONLARGEVOLUMELIGHT.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/STATIONPADVOLUMELIGHT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONPITVOLUMELIGHT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONSTAIRGLOW.SCENE.MBIN",					
					--"MODELS/EFFECTS/STATION/STATIONVOLUMELIGHT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/TOWERLIGHTGLOW.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/WATERDRIPS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/WATERSPLASH.SCENE.MBIN",
					
					"MODELS/EFFECTS/STATION/STATIONORBVENTMIST.SCENE.MBIN",		-- orb lateral steam vents
					--"MODELS/EFFECTS/STATION/STATIONORBTOP.SCENE.MBIN",  -- orb top blue rings
					"MODELS/EFFECTS/STATION/STATIONORBPITMIST.SCENE.MBIN",  --mist at the bottom of the orb pit
				    "MODELS/EFFECTS/STATION/STATIONLARGEFOG.SCENE.MBIN", --big white mist on top of the orb pit							
					"MODELS/EFFECTS/STATION/STATIONORBLARGEFOG.SCENE.MBIN",  --big white glow around the orb
					"MODELS/EFFECTS/STATION/STATIONORBMIST.SCENE.MBIN",  --mist folling from the orb
					"MODELS/EFFECTS/STATION/STATIONAREAMIST.SCENE.MBIN",  --Containers treatment smoke
					"MODELS/EFFECTS/STATION/STATIONORBEYE.SCENE.MBIN",  --eye streak effect			
					--"MODELS/EFFECTS/STATION/STATIONENERGYBEAM.SCENE.MBIN",  --energy beam smoke trail + electric effect
					--"MODELS/EFFECTS/STATION/STATIONENERGYBEAMSTART.SCENE.MBIN",  --blue energy ball
							
					"MODELS/EFFECTS/STATION/STATIONLIGHTGLOW.SCENE.MBIN",  --Whole station haze
					"MODELS/EFFECTS/STATION/STATIONLIGHTGLOWSMALL.SCENE.MBIN",	--Floor0 light haze
					"MODELS/EFFECTS/STATION/STATIONLAUNCHTUBELIGHTGLOW.SCENE.MBIN",  -- entry distance panels big white billboards
					"MODELS/EFFECTS/STATION/STATIONGRILLGLOW.SCENE.MBIN",  -- landing area vertical white lights
					"MODELS/EFFECTS/STATION/STATIONLANDPADBURST.SCENE.MBIN",  --landing pad smoke when poping in or out
					"MODELS/EFFECTS/STATION/STATIONLANDPADSMOKELOOP.SCENE.MBIN",  --landing pad ship smoke
					"MODELS/EFFECTS/STATION/STATIONVENTMIST.SCENE.MBIN",  --Smoke raising from every wall corner
					"MODELS/EFFECTS/STATION/STATIONVENTMISTLARGE.SCENE.MBIN",  -- falling smoke from ceiling large vents
					"MODELS/EFFECTS/STATION/STATIONFLOORMIST.SCENE.MBIN",  -- Floor0 mist
					"MODELS/EFFECTS/STATION/STATIONTOPFLOORMIST.SCENE.MBIN",  -- 1st floor mist
					},
					MXML_CHANGE_TABLE = 
					{
						{
							PKW = "Children",
							REMOVE = "SECTION",
						},
					}
				},
			}
		}
	}
}