NMS_MOD_DEFINITION_CONTAINER = 
{
MOD_FILENAME = "Smokeless Stations 1.4 - Full.pak", 
MOD_AUTHOR	 = "Lo2k",
LUA_AUTHOR	 = "Lo2k",
NMS_VERSION  = "6.04",
MOD_DESCRIPTION = "Removes smokes effects from Stations",
MODIFICATIONS= 
	{
		{
			MBIN_CHANGE_TABLE = 
			{ 
				{
					MBIN_FILE_SOURCE = {	

					-- NEXUS
					"MODELS\EFFECTS\NEXUS\BRIDGEROOMVOLUMELIGHT.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\BRIDGEROOMVOLUMELIGHTTOP.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\BRIDGEVOLUMELIGHTSHAFTS.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\CENTRALPOINTVENTSMOKE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\CENTRALPOINTVOLUMELIGHT.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\EGGMACHINEDRIPS.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\EGGMACHINESTEAM.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\GALAXYBURST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\GALAXYCAPSULEBASE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\GALAXYCAPSULEBURST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\GALAXYCAPSULEOPEN.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\HALLWAYVOLUMELIGHTSHAFTS.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LEFTROOMCORRIDORLIGHTMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LEFTROOMCORRIDORMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LEFTROOMFLOORMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LEFTROOMLIGHTVOLUME.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LEFTROOMLOWMISTGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LEFTROOMWALKWAY.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LEFTSIDEGROUNDMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LEFTSIDEMINIPILLARGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LIGHTCOLUMNSMOKE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\MAINROOMGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSCHIMNEYS.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSCLOUDS.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSCLOUDSCLOSE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSCOOKINGSTEAM.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSCOOKINGSTEAM.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSENTRANCEGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSGALAXY.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSGALAXYBURST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\NEXUSLANDINGTUNNELGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\PIPESTEAM.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\RIGHTSIDEFOG.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\RIGHTSIDEGREENGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\RIGHTSIDEGROUNDMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\RIGHTSIDEORANGEGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\RINGEMBERS.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\SMALLLIGHTSMOKE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\SPECIALSHOPVOLUMELIGHT.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\SPIDEREYE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\SPIDERGROUNDMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\SPIDERPROPSBARRELMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\SPIDERPROPSGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\SPIDERPROPSMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\SUPPORTLIGHTMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\TOWERBACKINGGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\TOWERCHIMNEYS.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\TOWERFALLINGMIST.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\TOWERTOPGLOW.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\VENTSMOKE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\WHITELIGHTSMOKE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\WHITESMOKE.SCENE.MBIN",
					"MODELS\EFFECTS\NEXUS\LANDINGBAYMIST.SCENE.MBIN", -- Nexus ship landing pads smoke

					--STATIONS
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONCORRIDORMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONELEC.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONEXTERIORDAMAGEMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONFLOORMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDSTATIONTUNNELMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ABANDONEDVOLUMELIGHT.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/PIRATECENTRALORBEMBERS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/PIRATECENTRALORBMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/PIRATEFLOORMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/PIRATEFRIGATEHANGERVOLUMELIGHT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/PIRATEROOFMIST.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/CENTRALORBBEAMSPARKS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/CENTRALORBCOOLANT.MBIN",
					--"MODELS/EFFECTS/STATION/CENTRALORBCOOLANT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/CENTRALORBDUSTSPARKS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/CENTRALORBFOG.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ORBEYE.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ORBLOWERMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/ORBVOLUMELIGHT.SCENE.MBIN",
									
					--"MODELS/EFFECTS/STATION/STATIONBILLBOARDGLOW.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONCLOUDS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONEXHAUSTVENT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONEXTERIORLIGHTGLOW.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/ENTRANCESMOKE.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LANDINGPADSMOKEBURST.SCENE.MBIN",
				    --"MODELS/EFFECTS/STATION/GENERALFLOATINGSMOKE.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LANDINGPADSMOKELOOP.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LAUNCHTUBEFILLMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LAUNCHTUBEPIPESTEAM.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/LAUNCHTUBESTEAM.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/STATIONGLOWLINEMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONGROUNDMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONMIST.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONTOWERCLOUDS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONTUNNELFOG.SCENE.MBIN",		
					--"MODELS/EFFECTS/STATION/STATIONLARGEVOLUMELIGHT.SCENE.MBIN",
					
					--"MODELS/EFFECTS/STATION/STATIONPADVOLUMELIGHT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONPITVOLUMELIGHT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/STATIONSTAIRGLOW.SCENE.MBIN",					
					--"MODELS/EFFECTS/STATION/STATIONVOLUMELIGHT.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/TOWERLIGHTGLOW.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/WATERDRIPS.SCENE.MBIN",
					--"MODELS/EFFECTS/STATION/WATERSPLASH.SCENE.MBIN",
					
					"MODELS/EFFECTS/STATION/STATIONORBVENTMIST.SCENE.MBIN",		-- orb lateral steam vents
					--"MODELS/EFFECTS/STATION/STATIONORBTOP.SCENE.MBIN",  -- orb top blue rings
					"MODELS/EFFECTS/STATION/STATIONORBPITMIST.SCENE.MBIN",  --mist at the bottom of the orb pit
				    "MODELS/EFFECTS/STATION/STATIONLARGEFOG.SCENE.MBIN", --big white mist on top of the orb pit							
					"MODELS/EFFECTS/STATION/STATIONORBLARGEFOG.SCENE.MBIN",  --big white glow around the orb
					"MODELS/EFFECTS/STATION/STATIONORBMIST.SCENE.MBIN",  --mist folling from the orb
					"MODELS/EFFECTS/STATION/STATIONAREAMIST.SCENE.MBIN",  --Containers treatment smoke
					"MODELS/EFFECTS/STATION/STATIONORBEYE.SCENE.MBIN",  --eye streak effect			
					--"MODELS/EFFECTS/STATION/STATIONENERGYBEAM.SCENE.MBIN",  --energy beam smoke trail + electric effect
					--"MODELS/EFFECTS/STATION/STATIONENERGYBEAMSTART.SCENE.MBIN",  --blue energy ball
							
					"MODELS/EFFECTS/STATION/STATIONLIGHTGLOW.SCENE.MBIN",  --Whole station haze
					"MODELS/EFFECTS/STATION/STATIONLIGHTGLOWSMALL.SCENE.MBIN",	--Floor0 light haze
					"MODELS/EFFECTS/STATION/STATIONLAUNCHTUBELIGHTGLOW.SCENE.MBIN",  -- entry distance panels big white billboards
					"MODELS/EFFECTS/STATION/STATIONGRILLGLOW.SCENE.MBIN",  -- landing area vertical white lights
					"MODELS/EFFECTS/STATION/STATIONLANDPADBURST.SCENE.MBIN",  --landing pad smoke when poping in or out
					"MODELS/EFFECTS/STATION/STATIONLANDPADSMOKELOOP.SCENE.MBIN",  --landing pad ship smoke
					"MODELS/EFFECTS/STATION/STATIONVENTMIST.SCENE.MBIN",  --Smoke raising from every wall corner
					"MODELS/EFFECTS/STATION/STATIONVENTMISTLARGE.SCENE.MBIN",  -- falling smoke from ceiling large vents
					"MODELS/EFFECTS/STATION/STATIONFLOORMIST.SCENE.MBIN",  -- Floor0 mist
					"MODELS/EFFECTS/STATION/STATIONTOPFLOORMIST.SCENE.MBIN",  -- 1st floor mist
					
					"MODELS/EFFECTS/STATION/BIGGSORANGEVOLUMELIGHT.SCENE.MBIN",  -- corvette pads orange lights
					"MODELS/EFFECTS/STATION/LARGEPADMIST.SCENE.MBIN",			 -- corvette pads mist		
					},
					MXML_CHANGE_TABLE = 
					{
						{
							PKW = "Children",
							REMOVE = "SECTION",
						},
					}
				},
			}
		}
	}
}