----------------------------------------------------------------------------------------------------
-- mod description
----------------------------------------------------------------------------------------------------

METADATA_MOD_NAME       = "BetterPassiveLootFromFrigates"
METADATA_MOD_AUTHOR     = "FriendlyFirePL"
METADATA_LUA_AUTHOR     = "FriendlyFirePL"
METADATA_NMS_VERSION    = "450"
METADATA_MOD_DESC       = "This mod changes the passive loot generated by different frigate types to items better suited for mid- and late gameplay."



----------------------------------------------------------------------------------------------------
-- loot data
----------------------------------------------------------------------------------------------------

-- loot data structure
--
-- FT - frigate type
-- LI - loot item
-- LC - loot category
-- PN - parameter acting as nominator
-- PD - parameter acting as denominator
--
-- formula:
-- [Loot in single instace] = [Floor Of ( [Frigate Stat Score] * [PN] / [PD] )]

function CHANGE_LOOT(_FT,_LI,_LC,_PN,_PD)
return        
{
    ["SKW"] = {_FT,"GcPassiveFrigateIncome.xml",},
    ["VCT"] = 
    {
        {"IncomeId",_LI},
        {"InventoryType",_LC},
        {"AmountOfIncomeRewarded",_PN},
        {"ForEveryXAmountOfTheStat",_PD},
    },
}
end

INDUSTRIAL_LOOT = CHANGE_LOOT("Mining","BP_SALVAGE","Product",1,5)
INDUSTRIAL_GET = "%CAP_RACE%, the crew have been busy recovering the technology modules from planetary excavations. We will deposit the &lt;DARK_TECH&gt;Salvaged Data&lt;&gt; in your cargo inventory."
INDUSTRIAL_WAIT = "Welcome aboard %CAP_RACE%. The planetary scavenging crew are currently deployed on mission. I hope to receive news of a successful operation very soon."

TRADING_LOOT = CHANGE_LOOT("Diplomacy","AF_METAL","Substance",2,5)
TRADING_GET = "Welcome aboard %CAP_RACE%. I am pleased to report local trade scouts have secured favourable deals across the system. The collected &lt;RARE&gt;Tainted Metal&lt;&gt; will be transfered to your storage."
TRADING_WAIT = "Welcome, %CAP_RACE%. The scouts are currently deployed on trade missions across the local system. I shall report any profitable news as I have it."

SUPPORT_LOOT = CHANGE_LOOT("Support","HYPERFUEL1","Product",1,10)
SUPPORT_GET = "A status report, %CAP_RACE%. The generator units are at optimal load and the supply tanks are full. We have prepared the surplus &lt;FUEL&gt;Warp Cells&lt;&gt; for your own personal use."
SUPPORT_WAIT = "Warp fuel generators are running at maximum efficiency, %CAP_RACE%! The supply tanks will soon be full, ready for deployment to your fleet."



----------------------------------------------------------------------------------------------------
-- script data
----------------------------------------------------------------------------------------------------

-- file to be changed
PATH_FRIGATES = "GCFLEETGLOBALS.GLOBAL.MBIN"
PATH_LANGUAGE = "LANGUAGE\\NMS_LOC4_ENGLISH.MBIN"

-- time to generate loot instance in seconds
TIME = 600

-- new text on the button to collect loot
TEXT_COLLECT = "Collect Items"

-- array of text data to be changed
LIST_TEXT =
{
    FLEET_LOOT_MINING_LANG = INDUSTRIAL_GET,
    FLEET_LOOT_TRADE_LANG = TRADING_GET,
    FLEET_LOOT_FUEL_LANG = SUPPORT_GET,
    FLEET_LOOT_MINING_WAIT_LANG = INDUSTRIAL_WAIT,
    FLEET_LOOT_TRADE_WAIT_LANG = TRADING_WAIT,
    FLEET_LOOT_FUEL_WAIT_LANG = SUPPORT_WAIT,
    FLEET_LOOT_COLLECT_OPT_A = TEXT_COLLECT,
    FLEET_LOOT_COLLECT_UNITS_OPT_A = TEXT_COLLECT,
}



----------------------------------------------------------------------------------------------------
-- mod container
----------------------------------------------------------------------------------------------------

NMS_MOD_DEFINITION_CONTAINER = 
{
    ["MOD_FILENAME"] 	    = "FF_"..METADATA_MOD_NAME.."_"..METADATA_NMS_VERSION..".pak", 
    ["MOD_AUTHOR"]		    = METADATA_MOD_AUTHOR,
    ["LUA_AUTHOR"]		    = METADATA_LUA_AUTHOR,
    ["NMS_VERSION"]		    = METADATA_NMS_VERSION,
    ["MOD_DESCRIPTION"]     = METADATA_MOD_DESC,
    
    ["MODIFICATIONS"]   =
    {
        {
            ["MBIN_CHANGE_TABLE"] =
            {
                {
                    ["MBIN_FILE_SOURCE"] = PATH_FRIGATES,
                    ["EXML_CHANGE_TABLE"] = {{["VCT"] = {{"TimeBetweenPassiveIncomeTicks",TIME,},}},}
                },

                {
                    ["MBIN_FILE_SOURCE"] = PATH_LANGUAGE,
                    ["EXML_CHANGE_TABLE"] = {},
                }
            }
        }
    }
}



----------------------------------------------------------------------------------------------------
-- functions to modify the files (definetely do not change)
----------------------------------------------------------------------------------------------------

local EXML_LOOT = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][1]["EXML_CHANGE_TABLE"]
local EXML_TEXT = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][2]["EXML_CHANGE_TABLE"]

function MODIFY_LOOT(_change,_exml)
    if _change~=nil and _exml~=nil then _exml[#_exml+1] = _change end
end

function MODIFY_TEXT(_data,_exml)
    if _data~=nil and _exml~=nil then
        for id,value in next,_data do
            local change = {["SKW"] = {"Id",id,},["VCT"] = {{"Value",value},},}
            _exml[#_exml+1] = change
        end
    end
end

MODIFY_LOOT(INDUSTRIAL_LOOT,EXML_LOOT)
MODIFY_LOOT(TRADING_LOOT,EXML_LOOT)
MODIFY_LOOT(SUPPORT_LOOT,EXML_LOOT)
MODIFY_TEXT(LIST_TEXT,EXML_TEXT)



----------------------------------------------------------------------------------------------------
-- end of file
----------------------------------------------------------------------------------------------------