-- FORCED DISABLED FEATURES 
--  MBINCOMPILER ISSUES OR UNDER MAINTENANCE FEATURES
CAVE_BIOMES_FEATURE = "OFF" -- under maintenance
--------------------------------------------------------
MINING_SPEED = "1" -- MBINCOMPILER ISSUE
NEWGAME_BONUSES = "OFF" -- MBINCOMPILER ISSUE
GIANT_MECHS_BETA_FEATURE = "OFF " -- MBINCOMPILER ISSUE
NEW_INTERACTIONS_FEATURE = "OFF" -- MBINCOMPILER ISSUE