CATEGORY = {"NPC", "CREATURES", "VEHICLE", "SPACE", "BUILDINGS1", "BUILDINGS2", "COOKING", "CRYSTAL+ROCK", "ROCKS+LAVA", "PLANTS", "EXTRA", "SEASTUFF", "WEIRD"}

ENABLE_PHYSICS_EXTENDER = false

CATEGORY_ICON = {
    ["NPC"]="TEXTURES/UI/HUD/ICONS/TIPSCREENSHOTS/NPCS.DDS",
    ["CREATURES"]="TEXTURES/UI/HUD/EYE.CREATURE.DDS",
    ["VEHICLE"]="TEXTURES/UI/HUD/MENUS/ICON.SHIP.DDS",
    ["SPACE"]="TEXTURES/UI/HUD/ICONS/TIPSCREENSHOTS/SPACESTATION.DDS",
    ["BUILDINGS1"]="TEXTURES/UI/FRONTEND/ICONS/BANNERICONS/BANNERICON.PORTAL.DDS",
    ["BUILDINGS2"]="TEXTURES/UI/FRONTEND/ICONS/NOTIFICATIONS/ICON.BUILDING.DDS",
    ["COOKING"]="TEXTURES/UI/FRONTEND/ICONS/WIKI/WIKI.COOKING.ON.DDS",
    ["CRYSTAL+ROCK"]="TEXTURES/UI/FRONTEND/ICONS/PRODUCTS/PRODUCT.ELEMENT.CRYSTAL1.DDS",
    ["ROCKS+LAVA"]="TEXTURES/UI/FRONTEND/ICONS/U4PRODUCTS/PRODUCT.FUELPROD.DDS",
    ["PLANTS"]="TEXTURES/UI/HUD/ICONS/MISSIONS/TREESCAN.DDS",
    ["EXTRA"]="TEXTURES/UI/FRONTEND/ICONS/GAMEMODE/STAR.DDS",
    ["SEASTUFF"]="TEXTURES/UI/FRONTEND/ICONS/MISSIONS/MISSION.WATER.ON.DDS",
    ["WEIRD"]="TEXTURES/UI/FRONTEND/ICONS/MISSIONS/MISSION.MISSINGPERSON.ON.DDS"
}

CATEGORY_OFFSET = {
    ["NPC"]="0",
    ["CREATURES"]="0.5",
    ["VEHICLE"]="0",
    ["SPACE"]="400",
    ["BUILDINGS1"]="0",
    ["BUILDINGS2"]="0",
    ["COOKING"]="0",
    ["CRYSTAL+ROCK"]="0",
    ["ROCKS+LAVA"]="0",
    ["PLANTS"]="0",
    ["EXTRA"]="0",
    ["SEASTUFF"]="0",
    ["WEIRD"]="0"
}

BUILDABLE_OBJECT_TABLE =
{
["NPC"] =
{
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCFIFTH.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCFOURTH.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCGEK.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCKORVAX.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCNADA.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCPOLO.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCSPECIALSHOP.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCVYKEEN.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/PLAYERCHARACTER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/EXPLORER/ANOMALYEXPLORER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/EXPLORER/EXPLORER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/EXPLORER/EXPLORERSTAND.SCENE.MBIN",
"MODELS/PLANETS/NPCS/FOURTHRACE/FOURTHRACE.SCENE.MBIN",
"MODELS/PLANETS/NPCS/FOURTHRACE/HOLOEXPLORER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/FOURTHRACE/HOLONOONE.SCENE.MBIN",
"MODELS/PLANETS/NPCS/FOURTHRACE/HOLOSCEPTIC.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/ANOMALYLOWERORDER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDERBODY.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDERIPAD.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDERSIT.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDERSTAND.SCENE.MBIN",
"MODELS/PLANETS/NPCS/WARRIOR/WARRIOR.SCENE.MBIN",
"MODELS/PLANETS/NPCS/WARRIOR/WARRIORSTAND.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/COMPUTER/ANOMALY_HOLOEXPLORER.SCENE.MBIN"
},

["CREATURES"] =
{
"MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPEROBOT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPETWOLEGS.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BEETLERIG/BEETLE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BLOBRIG/BLOB.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BLOBRIG/BLOBTERRARIUM.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLY.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLYFLOCK.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BUTTERFLYRIG/LARGEBUTTERFLY.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/CATRIG/BONECAT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/CATRIG/CAT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/CATRIG/SIXLEGCAT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/COWRIG/COW.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/COWRIG/COWHINDLEGS.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/COWRIG/COWSWIM.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/COWRIG/SIXLEGGEDCOW.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/CLAM.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/FISHFIEND.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/FISHFIENDSMALL.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/FISHFLOCK.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/FREIGHTERJELLYFISH.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/GRABBYPLANT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/JELLYFISH.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/PROC_JELLYFISH.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/SMALLFISH.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/SPACEJELLYFISH.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/SPACEJELLYFISHPOS.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/PARTS/GRABBYPLANTEYE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FLYINGLIZARDRIG/FLYINGLIZARD.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FLYINGSNAKE/FLYINGSNAKE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/GRUNTRIG/GRUNT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/RODENTRIG/RODENT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/RODENTRIG/RODENTSWIM.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SEASNAKE/SEASNAKE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SHARKRIG/SHARK.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SLUG/SLUG.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SMALLBIRD/BIRD.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SMALLBIRD/BIRDFLOCK.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SMALLBIRD/SMALLBIRD.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/FIEND.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/FREIGHTERFIEND.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/ROCKCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/ROCKSPIDER.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/SPIDER.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/SPIDERFLOAT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/STRIDERRIG/STRIDER.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/TREXRIG/TREX.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/TRICERATOPSRIG/TRICERATOPS.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/CRYSTALCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/DIGGER.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/DRILL.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/FLOATERCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/GEMCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/GROUNDCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/PLOW.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/ROLLERCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/WEIRDBUTTERFLY.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/WEIRDDIGGER.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/WEIRDFLOCK.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIGGROUND.SCENE.MBIN",
--"MODELS/PLANETS/BIOMES/CAVE/SMALLCREATURE/SUNBEETLE/SUNBEETLE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/FLYINGLIZARD/FLYINGLIZARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMCREATURE/ANTELOPE/ANTELOPE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMCREATURE/ANTELOPE/ANTELOPEALT01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMCREATURE/ANTELOPE/ANTELOPEALT02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLCREATURE/BUTTERFLY/BUTTERFLY.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLCREATURE/RODENT/RODENT.SCENE.MBIN"
--"MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/DIPLODOCUS/DIPLODOCUS.SCENE.MBIN"
},

["VEHICLE"] =
{
"MODELS/COMMON/SPACECRAFT/FIGHTERS/FIGHTER_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/SCIENTIFIC/SCIENTIFIC_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/DROPSHIPS/DROPSHIP_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/SHUTTLE/SHUTTLE_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/S-CLASS/S-CLASS_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/S-CLASS/BIOPARTS/BIOSHIP_PROC.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/MECH_SUIT/MECH_SUIT.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/BIKE/BIKE.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/BUGGY/BUGGY.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/HOVER/HOVERCRAFT.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/ROVER/ROVER.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/SUBMARINE/SUBMARINE.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/WHEELEDBIKE/WHEELEDBIKE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/POLICE/POLICESHIP.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/DRONE/DRONESHIP.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/DRONE/HISTORY/DRONESHIP.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/CORRUPTEDDRONE.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/DRONE.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/DRONEARMOURED.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/QUADRUPED.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/WALKER.SCENE.MBIN",
"MODELS/COMMON/HMD/HMDDRONE.SCENE.MBIN"
},

["SPACE"] =
{
"MODELS/SPACE/ANOMALY/ANOMALY.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/ATLASSTATION.SCENE.MBIN",
"MODELS/SPACE/NEXUS/NEXUS.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/SPACESTATION.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/SPACESTATION_ABANDONED.SCENE.MBIN",
"MODELS/SPACE/BLACKHOLE/BLACKHOLE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CAPITALFREIGHTER_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTERSMALL_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTERTINY_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTER_A.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTER_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTSHIP01.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/SMALLTRANSPORT2.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLOCOMBAT.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLODIPLOMATIC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLOINDUSTRIAL.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLOSCIENCE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLOSUPPORT.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/SUPPORTFRIGATELOD0.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/DIPLOMATICFRIGATELOD0.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/INDUSTRIALFRIGATELOD0.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/SCIENCEFRIGATELOD0.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/POLICE/POLICEFREIGHTER.SCENE.MBIN",
"MODELS/SPACE/ASTEROIDS/ASTEROIDXL.SCENE.MBIN",
"MODELS/SPACE/ASTEROIDS/GIANTASTEROID.SCENE.MBIN",
"MODELS/SPACE/ASTEROIDS/SMALLASTEROID.SCENE.MBIN",
"MODELS/SPACE/ASTEROIDS/DEBRIS/ASTEROIDDEBRIS01.SCENE.MBIN",
"MODELS/SPACE/ASTEROIDS/DESTRUCTIBLE/ASTEROID01.SCENE.MBIN",
"MODELS/SPACE/ASTEROIDS/DESTRUCTIBLE/ASTEROIDSUBSTANCE.SCENE.MBIN",
"MODELS/SPACE/ASTEROIDS/NONDESTRUCTIBLE/BIGASTEROID01.SCENE.MBIN",
"MODELS/SPACE/ASTEROIDS/NONDESTRUCTIBLE/BIGASTEROIDDEBRIS.SCENE.MBIN"
},

["EXTRA"] =
{
"MODELS/COMMON/WEAPONS/MULTITOOL/MULTITOOL.SCENE.MBIN",
"MODELS/UI/WORLD/BASEPROJECTOR.SCENE.MBIN",
"MODELS/COMMON/PLAYER/SPACEGRAVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLAYER/PLAYERGRAVE.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLACEMARKER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/SHIELD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/SERVERROOM/SERVER.SCENE.MBIN",
"MODELS/COMMON/PROJECTILES/CHARGEDENERGYBALL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLAYER/PLAYERGRAVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLAYER/PLAYERITEMDROP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/CAVE/EGGRESOURCE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/CAVE/METALCUBE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/BONEPILE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/FIENDEGG.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/GROUNDRESOURCE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/GROUNDWORM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/HAZARDSTEAM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/METALFORMATION.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/METALFORMATION_DESTROYED.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SPOREBAG.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SPOREBAGBASE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SPOREBAG_DESTROYED.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/UNDERGROUNDPROP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/FIENDEGGPARTS/FIENDEGGREWARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPCOREA.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPCOREB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPCOREC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULEA.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULEB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULEC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULED.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULEE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULEF.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULEG.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULEH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/SCRAPHEAPMODULES/SCRAPMODULEI.SCENE.MBIN"
},

["BUILDINGS1"] =
{
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PORTAL/PORTAL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PORTAL/PORTALTERMINAL.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/SHOPS/GUNSHOP.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/SHOPS/SHIPSHOP.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/SHOPS/SUITSHOP.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/SHOPS/VEHICLESHOP.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/TERMINALS/NEXUSBLUEPRINTANALYSER.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/TOWER/NEXUSTOWER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/TERMINAL/TERMINAL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/TERMINAL/TERMINAL_TADINGPOST.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/GUILDSHOP.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/MAPSHOP.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/MISSIONSHOP.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/SHIPSHOP.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/SPECIALSHOP.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/SUITSHOP.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/VEHICLESHOP.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/SHOPS/WEAPONSHOP.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/BRIDGE/LARGETERMINAL.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/CENTRALPOINT/SPECIALSHOP.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/CORE/MECHANICALCORE.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/PATHDISK.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/ATLASCORE/ATLASCORE.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ORBS/BLUEORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ORBS/GREENORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ORBS/REDORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ORBS/WHITEORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_1_INTERACTION/ENDING_1_INTERACTION.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_1_INTERACTION/INTERACTIONCORE.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/INTERACTIONCORE.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ENDING_2_INTERACTION.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/INTERACTIONSTONE/INTERACTIONSTONE_1.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/PATHORB/PATHORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_1_INTERACTION/ATLASSTONE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/THEREMIN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/COMMONPARTS/TELEPORTER_NEXUS.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/COMMONPARTS/SCENES/MAINBATTERY.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/MODULE_TURRET.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/MODULE_TURRET_R.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/MODULE_TURRET_L.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/TURRET/TURRETA.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/TURRET/TURRETB.SCENE.MBIN",
"MODELS/PLANETS/SNOW/WRECKS/OLDTURRET.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/MODULE_COOLINGTOWER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/MODULE_DISTRIBUTOR.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/MODULE_WINDTURBINE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/LANDINGPADCUSTOMISER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/SWITCH_TARGET.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/ADAPTOR.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/UTILITYPARTS/FENCE.SCENE"
},

["BUILDINGS2"] =
{
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/HOLOCOM/HOLOHUB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/HOLOCOM/HOLOCOM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/LANDINGPAD/LANDINGPADTRADER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/LUNAR/LUNARPROC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/LUNAR/PARTS/GENERATOR.SCENE.MBIN",
"MODELS/PLANETS/SNOW/WRECKS/GIANTWRECKEDSHIP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MONUMENTS/MONUMENT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MONUMENTS/STARGATEMAIN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/OBSERVATORY/OBSERVATORYSCIENTIFIC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/OBSERVATORY/OBSERVATORYTRADER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/COMMONPARTS/CRYOCHAMBER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/COMMONPARTS/OBSERVATORY/HOLOGRAM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/MONOLITH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/PLAQUE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/RUINS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/STANDINGSTONE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/STANDINGSTONE_A.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/STANDINGSTONE_B.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/STANDINGSTONE_C.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/STANDINGSTONE_D.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/RUINPARTS/WORDSTONE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/RADIOTOWER/RADIOTOWERSCIENTIFIC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/RADIOTOWER/RADIOTOWERTRADER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/RELIC/RELIC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/PROCRUINS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SHACK/SHACKWARRIOR_PARTS/SHACK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SHACK/SHACKSCIENTIFIC_PARTS/SHACK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SHACK/SHACKTRADER_PARTS/SHACK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SHACK/SHACKTRADER_PARTS/SHELTER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SHACK/SHACKTRADER_PARTS/WATERTOWER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/TRADINGPOST/TRADINGPOST.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/TRADINGPOST/TRADINGPOSTTRADER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/TRADINGPOST/TRADINGPOSTWARRIOR.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/TRADINGPOST/TRADINGPOSTSCIENTIFIC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MONOLITH/MONOLITH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/HEXMONOLITH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/MONOLITH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/SMALLMONOLITH.SCENE.MBIN"
},

["COOKING"] =
{
"MODELS/PLANETS/BIOMES/COMMON/COOKING/ALOEFLESH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/BLOODYORGAN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/CREATUREPELLETS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/ENZYMEFLUID.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/FERMENTEDFRUIT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/FIREBERRY.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/FIREFLIES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/FOODGROUNDMEAT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/FROZENTUBERS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/GRAHFRUIT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/HEPTAWHEAT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/HEXABERRY.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/IMPULSEBEANS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/JADEPEAS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/PHEROMONESACK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/PULPYROOTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/SCENTEDHERBS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/SWEETENEDCOMPOST.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/SWEETROOT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/COOKING/SYNTHETICWORMS.SCENE.MBIN"
},

["CRYSTAL+ROCK"] =
{
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/LARGE/CRYSTALCUBE_LARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/LARGE/CRYSTAL_LARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/LARGE/CRYSTAL_LARGE_CAVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/LARGE/CRYSTAL_LARGE_MOUNTAIN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/LARGE/CRYSTAL_LARGE_UNDERWATER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/MEDIUM/CRYSTALCUBE_MEDIUM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/MEDIUM/CRYSTAL_MEDIUM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/MEDIUM/CRYSTAL_MEDIUM_CAVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/MEDIUM/CRYSTAL_MEDIUM_MOUNTAIN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/MEDIUM/CRYSTAL_MEDIUM_UNDERWATER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTALCUBE_FRAGMENT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTALCUBE_SMALL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTAL_FRAGMENT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTAL_FRAGMENT_CAVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTAL_FRAGMENT_MOUNTAIN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTAL_FRAGMENT_UNDERWATER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTAL_SMALL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTAL_SMALL_CAVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTAL_SMALL_MOUNTAIN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/CRYSTALS/SMALL/CRYSTAL_SMALL_UNDERWATER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MINERALROCK/MINERALROCK_MEDIUM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MINERALROCK/MINERALROCK_MEDIUM_RARE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MINERALROCK/MINERALROCK_SMALL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/MINERALROCK/MINERALROCK_SMALL_RARE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/CRYSTALS/GEMCRYSTALS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/CRYSTALS/STORMCRYSTALS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/CRYSTALALTAR.SCENE.MBIN"
},
["ROCKS+LAVA"] =
{
"MODELS/PLANETS/BIOMES/BARREN/HQ/GROUNDREVEALROCK01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/LARGEARRANGEDROCK01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/LARGEARRANGEDROCK02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/LARGEMOUNTAINROCKCLOSED.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/LARGEPLAINSBOULDER02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/MEDIUMBOULDER01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/MEDIUMBOULDER02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/SMALLBOULDER05.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/SMALLROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/HQ/LARGEPROP/STALAGMITES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/LARGEPROP/LARGEBOULDER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/LARGEPROP/LARGEFUNGHI.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/LARGEPROP/LARGEROCKFORMATION.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/LARGEPROP/STALACTITES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/LARGEPROP/STALAGMITES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/MEDIUMPROP/MEDIUMROCKPOOL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/MEDIUMPROP/MEDIUMSTALAGTITES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/SMALLROCKS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/TINYROCKS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/LARGE/LARGESHARP01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/LARGE/LARGESLATE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/LARGE/RESOURCEROCKLARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/LARGE/RESOURCEROCKSHARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/MEDIUMSHARP01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/MEDIUMSHARP02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/MEDIUMSLATE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/RESOURCEROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/FRAGMENTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/RESOURCEFRAGMENTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/RESOURCESMALL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SLATEFRAGMENTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SMALLROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SMALLSHARP01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SMALLSHARP02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SMALLSHARP03.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SMALLSLATE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/TINYSLATE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/TINYSLATE02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/TINYSLATE03.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKSSHARDS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/LARGEPROPS/LARGEICEROCK_1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/LARGEPROPS/LARGEROCKSTACK_1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/LARGEPROPS/LARGEROCK_1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/MEDIUMPROPS/MEDIUMROCKS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/SMALLPROPS/ROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/SMALLPROPS/ROCKSCREE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/SMALLPROPS/SMALLROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/SMALLPROPS/SMALLROCKCLUMPS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/LARGEPROPS/MOUNTAINROCK_1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/MEDIUMPROPS/MEDIUMBOULDER01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/MEDIUMPROPS/MEDIUMBOULDER02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/SMALLPROPS/SMALLBOULDER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/SMALLPROPS/SMALLROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/LARGEPROPS/LARGEVOLCANO.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/MEDIUMPROPS/COMET01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/MEDIUMPROPS/LAVACRYSTALS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/LARGEPROPS/LARGESHARD01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/LARGEPROPS/LARGESHARDINACTIVE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/LARGEPROPS/LARGESHARDINACTIVE02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/MEDIUMPROPS/MEDIUMDEADTREE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/MEDIUMPROPS/VOLCANODEBRIS01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/SMALLPROPS/LAVACLUMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/SMALLPROPS/LAVAGEMS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/SMALLPROPS/SMALLCOMET01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPROP/MEDIUMROCK1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPROP/MEDIUMWATERROCK1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPROP/SMALLROCK1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPROP/TINYROCK01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPROP/TINYROCK02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPROP/TINYROCK03.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SCORCHED/LARGE/LARGEROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SCORCHED/MEDIUM/MEDIUMROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SCORCHED/SMALL/SMALLROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SCORCHED/SMALL/SMALLSPIRE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/SMALLPROP/SWAMPROCK01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/MEDIUM/MEDIUMROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/SMALL/BLOBFRAGMENTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/SMALL/SMALLROCK.SCENE.MBIN",
"MODELS/PLANETS/DESERT/ROCKS/FLATROCK01.SCENE.MBIN",
"MODELS/PLANETS/DESERT/ROCKS/LARGEROCK01.SCENE.MBIN",
"MODELS/PLANETS/DESERT/ROCKS/LARGEROCK02.SCENE.MBIN",
"MODELS/PLANETS/DESERT/ROCKS/MEDIUMROCK01.SCENE.MBIN",
"MODELS/PLANETS/DESERT/ROCKS/MEDIUMROCK02.SCENE.MBIN",
"MODELS/PLANETS/DESERT/ROCKS/SMALLROCK01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGERING/HUGERINGTREE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGERING/HUGEROCKRING.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGEROCK/HUGEPLATFORMROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGEROCK/HUGESPIKEROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGESCORCHED/HUGESPIRE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGESCORCHED/PARTS/HUGESPIRE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGESCORCHED/PARTS/HUGESPIRE02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGESCORCHED/PARTS/HUGESPIRE03.SCENE.MBIN"
},

["PLANTS"] =
{
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/BERRYPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/COMMODITYPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/COMMODITYPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/COMMODITYPLANT2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/EXPLODEPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMALBUMEN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMBARREN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMDEADCREATURE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMGRAVITINO.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMLUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMNIP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMPOOP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMRADIOACTIVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMSCORCHED.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMSNOW.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMTOXIC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FARMVENOMSAC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FLOATINGPLANTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUELPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUELPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUELPLANT2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUELPLANTSTARTSCENE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARDPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARDPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARDPLANT2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTHPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTHPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTHPLANT2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/PROXIMITYPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/ROLLINGPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHIELDPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHIELDPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHIELDPLANT2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TECHPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TECHPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TECHPLANT2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TENTACLEPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/VENUSFLYTRAP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/BIOMESPECPLANTS/BARRENPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/BIOMESPECPLANTS/LUSHPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/BIOMESPECPLANTS/RADIOACTIVEPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/BIOMESPECPLANTS/SCORCHEDPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/BIOMESPECPLANTS/SNOWPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/BIOMESPECPLANTS/TOXICPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALIEN/LARGEPLANT/BENDYTREE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALIEN/LARGEPLANT/LARGETREE02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALIEN/MEDIUMPLANT/MEDIUMPLANT01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALIEN/MEDIUMPLANT/MEDIUMPLANT02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALIEN/MEDIUMPROP/MEDIUMPROP01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALIEN/SMALLPLANT/SMALLPLANT01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALIEN/SMALLPLANT/SMALLPLANT02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/LARGEPLANT/LARGEFIR01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/LARGEPLANT/LARGESPRUCE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/LARGEPLANT/MEDIUMDEADTREE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/LARGEPLANT/MEDIUMSPRUCE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/LARGEPLANT/MEDIUMUMBRELLA01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/LARGEPLANT/SMALLCEDAR01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/LARGEPLANT/SMALLSPRUCE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/MEDIUMPLANT/MEDIUMBUSH01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/MEDIUMPLANT/MEDIUMBUSH02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/MEDIUMPLANT/MEDIUMFIRN01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/MEDIUMPLANT/MEDIUMPLANT01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/MEDIUMPLANT/MEDIUMWEED01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/SMALLPLANT/SMALLBUSH01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/SMALLPLANT/SMALLFIRN01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/SMALLPLANT/SMALLSCRUB01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/SMALLPLANT/SMALLWEED01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/ALPINE/SMALLPLANT/SMALLWEED02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/BARRENGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/BARRENGRASSLARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/BARRENGRASSSMALL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/GROUNDFLOWER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/POOFBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/YUKKA.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/YUKKA02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/TREES/CACTUSMED.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/HQ/TREES/CACTUSSML.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/LARGEPROPS/LARGEFLAG.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/LARGEPROPS/LARGEFLAGPARTS/LARGEFLAG.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/LARGEPROPS/LARGEFLAGPARTS/LARGEFLAGMIDDLE_A.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/LARGEPROPS/LARGEFLAGPARTS/LARGEFLAGTOPBLANK_A.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/LARGEPROPS/LARGEFLAGPARTS/LARGEFLAGTOP_A.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/LARGEPROPS/LARGEFLAGPARTS/SMALLFLAG.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/CROSSGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/FLUFFBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/GRASSBILLBOARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/GROUNDFLOWER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/SCRUBBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/SMALLCACTUS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/TRUNK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/BARREN/PLANTS/VOLUMEBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/MEDIUMPROP/HANGINGPLANTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/MEDIUMPROP/MEDIUMPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPLANT/CAVEGROUNDLEAVES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPLANT/DUDLEYA.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPLANT/DUDLEYAVARIANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPLANT/SMALLCAVEBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/GROUNDFOG.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/HEAVYAIRGLOW.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/SMALLCAVEBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/SMALLCIELINGPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/SMALLGLOWPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/SMALLPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CAVE/SMALLPROP/SMALLSHRUB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/PLANTS/LARGEPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/PLANTS/MEDIUMPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/PLANTS/SMALLPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/FLOWERS/BUTTERCUP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/FLOWERS/SCABIOUS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/FLOWERS/YARROW.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/BLOBBYGRASS01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/CHEESEPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/CLOVER01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/CROSSGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/GRASSBILLBOARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/GRASSCLUMP01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/GRASSLUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/GRASSVARIATION01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWCROSSGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWLUSHGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWPROCGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWSCRUBGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/PROCGRASSCLUMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/TALLGRASSBILLBOARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/THINGRASS01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/WILDGRASS01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/GRASS/WILDGRASS02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/INTERACTIVE/SPOREVENT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/FERN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/FLOATER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/LARGEPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/MEDIUMBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/MEDIUMPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/MONSTERPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/MYRTLEBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/SMALLFLOWERS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/SMALLPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLANTS/SPRIGBUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/INAIR/FLOATINGGASBAGS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/INAIR/FLOATINGGASBAGS_DESTROYED.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/INAIR/GASBAGPARTS/FLOATINGRESOURCE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/LARGEPROP/LARGELUMP1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/LARGEPROP/SCALLOPSHELL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/LARGEPROP/SHELLSPIKES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/LARGEPROP/SPIKEYSHELL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/MEDIUMPROP/CORALDISC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/MEDIUMPROP/SHELLSPIKES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/SMALLPROP/SMALLBLOB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/SMALLPROP/SMALLDISC.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CORAL/SMALLPROP/SMALLSPIKES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/LARGEPLANT/STRANDBASE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/LARGEPROP/GIANTCUBE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/LARGEPROP/GIANTSPIKE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/LARGEPROP/PILLAR1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/LARGEPROP/SQUATPILLAR1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/SMALLPROP/ANIMATED_CUBES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/SMALLPROP/BASE1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/SMALLPROP/FRAGMENTS1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/CRYSTAL/SMALLPROP/TINYCUBES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMICEDRIFTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLICEFORMATION.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SNOWFRAGMENTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/GLOWING/LARGEPLANT/MEDGLOWINGTREE1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/GLOWING/LARGEPLANT/SMALLGLOWINGTREE1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/GLOWING/MEDIUMPLANT/MEDGLOWINGBUSH1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/GLOWING/SMALLPLANT/GRASSSCRUB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/GLOWING/SMALLPROP/SMALLBLOBFRAGMENT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/FOLIAGE/FROZENBUSHYGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/FOLIAGE/FROZENGRASSLARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/FOLIAGE/LARGETREEBARE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/FOLIAGE/STALKBRANCH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/LARGEPROPS/ICEDECAL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/SMALLPROPS/SMALLSNOWCLUMPS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/SMALLPROPS/SNOWCLUMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/TREES/HEROPINE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/TREES/SKINNYPINE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQFROZEN/TREES/TALLPINE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE03.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE04.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE05.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE06.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE07.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE08.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE09.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE10.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE11.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE12.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE13.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE14.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE15.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE16.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE17.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE18.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE19.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE20.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE21.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE22.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE23.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE24.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE25.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE26.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE27.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE28.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE29.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE30.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE31.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE32.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE33.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE34.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE35.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE36.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE37.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE38.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE39.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE40.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE41.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE42.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE43.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE44.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE45.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE46.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE47.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE48.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE49.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE50.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE51.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE52.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE53.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE54.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE55.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE56.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE57.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE58.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE59.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE60.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE61.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE62.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE63.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE64.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE65.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE66.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE67.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE68.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE69.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE70.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE71.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE72.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE73.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE74.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE75.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGETOXIC/HUGEFUNGUS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGETOXIC/HUGETENDRIL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGETOXIC/PARTS/FUNGALTREE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGETOXIC/PARTS/HUGETENDRIL01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGETOXIC/PARTS/HUGETENDRIL02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGEUW/HUGESTRANDS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGEUW/HUGESWIRLPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/LARGEPROPS/DEADTREE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LAVA/LARGEPROPS/DEADTREEFLAMING.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/COLOURFANSHROOM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/LARGEBLUESHROOM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/LARGEBLUESHROOMSINGLE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/LARGEFANSHROOM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/LARGEFANSHROOMSINGLE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/MEDIUMBLUESHROOM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/MEDIUMSHROOM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/SMALLBLUESHROOMS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/LUSHROOM/SMALLSHROOMCLUSTER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPLANTS/DEADTREE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPLANTS/DEADTREE02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPLANTS/DEADTREE03.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPLANTS/LARGEBUSH1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPLANTS/LARGEPLANT01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPLANTS/LARGEPLANT02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPLANTS/LARGEPLANT03.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPROP/LARGEMINERAL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/LARGEPROP/LARGEPYRAMID.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/MEDIUMPLANTS/MEDIUMPLANT01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/MEDIUMPLANTS/MEDIUMPLANT03.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/SMALLPLANTS/SMALLBUSH01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/SMALLPLANTS/SMALLCACTUS01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/SMALLPLANTS/SMALLPLANT01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/SMALLPLANTS/SMALLSHRUB01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/NEVADA/SMALLPLANTS/SMALLSHRUB02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/CURVEDMEDIUM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMSTEAMER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RADIOACTIVE/SMALL/CURVEDSMALL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RADIOACTIVE/SMALL/CURVEFRAGMENT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/GRASS/GRASSLUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/GRASS/GRASSSPIKE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/LARGEBUSH1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/LARGEMANGROVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/LARGEPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/LARGETREE1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/MEDIUMTREE1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/MEDIUMTREE1SHAKE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/MEDIUMTREE2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/MEDIUMTREE3.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE1BASE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE1BENT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE1SHAKE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE3.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE4.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/TREEVARIANTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/IMPOSTERS/LARGETREE1IMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/IMPOSTERS/MEDIUMTREE1IMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/IMPOSTERS/MEDIUMTREE2IMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/IMPOSTERS/SMALLTREE1IMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/IMPOSTERS/SMALLTREE2IMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMBUSH1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMBUSH2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMFALLENTREE1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMFALLENTREE2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT3.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT4.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT5.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT6.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT7.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/LILYPAD01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLCOLOUREDFLOWER01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLFLOWER01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLPLANT1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLPLANT2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLPLANT3.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLWEED01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLWEED02.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/WATERREED.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SCORCHED/MEDIUM/VOLCANICPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SCORCHED/SMALL/LEAFDROPLET.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SCORCHED/SMALL/SMALLFLOWER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPLANT/MANGROVELARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPLANT/ROOTBASE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPLANT/STRAIGHTTREELARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPLANT/STRAIGHTTREEMEDIUM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPLANT/STRAIGHTTREESMALL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPLANT/TANGLEDVINES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPLANT/VINETREELARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPROP/SWAMPBOULDER1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/LARGEPROP/SWAMPBOULDER2.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/MEDIUMPLANT/FALLENTREE01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/MEDIUMPLANT/MEDIUMSWAMPGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/MEDIUMPLANT/MEDIUMTRUNK01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/SWAMP/SMALLPLANT/SMALLTWIGS01.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/LARGE/FUNGALTREE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/LARGE/LARGEBLOB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/LARGE/SPONGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/LARGE/TENDRIL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/MEDIUM/BLOB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/TOXIC/SMALL/TOXICGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WOODLAND/LARGEPLANT/LARGEOAK1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WOODLAND/LARGEPLANT/MEDIUMOAK1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WOODLAND/LARGEPLANT/SMALLOAK1.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WOODLAND/MEDIUMPLANT/PLANT1.SCENE.MBIN",
"MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG01.SCENE.MBIN",
"MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG02.SCENE.MBIN",
"MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG03.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/CLIFFSHRUB.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/FERN01.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/FERN02.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP01.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP02.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP04.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP05.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP06.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP07.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP08.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/SHRUB01.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/WEED01.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/WEED02.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/WEED03.SCENE.MBIN",
"MODELS/PLANETS/COMMON/SHRUBS/WEED04.SCENE.MBIN",
"MODELS/PLANETS/DESERT/CACTUS/CACTUSMEDIUM.SCENE.MBIN",
"MODELS/PLANETS/DESERT/CACTUS/CACTUSSMALL.SCENE.MBIN",
"MODELS/PLANETS/DESERT/CACTUS/CACTUSTALL.SCENE.MBIN",
"MODELS/PLANETS/DESERT/TREES/SMALLTREE.SCENE.MBIN",
"MODELS/PLANETS/DESERT/TREES/TWISTEDTREE.SCENE.MBIN",
"MODELS/PLANETS/SKY/RAINBOWPLANE.SCENE.MBIN",
"MODELS/PLANETS/SKY/SKYSPHERE.SCENE.MBIN",
"MODELS/PLANETS/SNOW/CLUMPS/SNOWCLUMP01.SCENE.MBIN",
"MODELS/PLANETS/SNOW/CLUMPS/SNOWCLUMP02.SCENE.MBIN",
"MODELS/PLANETS/SNOW/CLUMPS/SNOWCLUMP03.SCENE.MBIN",
"MODELS/PLANETS/SNOW/CLUMPS/SNOWCLUMP04.SCENE.MBIN",
"MODELS/PLANETS/SNOW/CONSTRUCTS/CONSTRUCT01.SCENE.MBIN",
"MODELS/PLANETS/SNOW/FOLIAGE/SNOWGRASS.SCENE.MBIN"
},

["SEASTUFF"] =
{
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/GROUND/CLAMSHELL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/UNDERWATER/METALSPHERE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/RARERESOURCE/UNDERWATER/SEAURCHIN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/INTERACTIVE/FISHFIENDROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/INTERACTIVE/STEAMVENT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/INTERACTIVE/FISHFIENDROCKPARTS/FIENDROCKNEST.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/LARGEPLANTS/LARGESTRANDS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/LARGEPLANTS/UNDERWATERTREE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGELUMP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGEPLATFORMROCK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGEPROP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGESWIRLPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/LARGEPROP/UNDERWATERBOULDER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANTS/FLOATPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANTS/MEDIUIMGLOWPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANTS/MEDIUMSEAPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/MEDIUMPROP/MEDIUMGROWTHS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/MEDIUMPROP/MEDIUMLUMPS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/MEDIUMPROP/SEAURCHIN.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/SMALLPLANTS/SEABUSH.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/ANENOMESHAPE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/CORALLIGHT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/CORALLIGHTINST.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/CORALTRUMPET.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/CRYSTALSSHAPE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/CRYSTALSSHAPELARGE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/CUCUMBERSHAPE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/CURVECORAL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/GASBAGS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/LAMPSHAPE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/SAILPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/TALLKELP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/UNDERWATERCONTOURPOD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/UNDERWATERSHELLWHITE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/UNDERWATER/UPDATEPROPS/UNDERWATERSPORE.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/BUSHES/SEABUSH1.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/BUSHES/SEABUSH2.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/BUSHES/SEATREE01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/CORALTREE01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALBIG01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALBIG02.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALBRAIN01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALDISC01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALFINGERS01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALLUMP01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALLUMP02.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALLUMP03.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALLUMP04.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/CORAL/PARTS/CORALVASE01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/ROCKS/OCEANROCK01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/ROCKS/OCEANROCK02.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/LONGSTRANDS01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/SEAFLOWER01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/SEAFUNGI01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/SEAFUNGI02.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/SEAURCHIN01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/SEAURCHIN02.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/SEAWEED01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/SEAWEEDBUSH01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/TALLPLANT01.SCENE.MBIN",
"MODELS/PLANETS/OCEAN/SHRUBS/TALLSEAWEED01.SCENE.MBIN"
},

["WEIRD"] =
{
"MODELS/PLANETS/BIOMES/WEIRD/BEAMSTONE/BEAMSTONE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/BEAMSTONE/HOVERING.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/BEAMSTONE/HUGEBEAM.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/BEAMSTONE/SMALLSTONE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/BONESPIRE/BONEBLOBS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/BONESPIRE/BONEFRUIT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/BONESPIRE/BONEGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/BONESPIRE/BONESPINE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/CONTOUR/CONTOURDETAIL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/CONTOUR/CONTOUROBJECT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/CONTOUR/CONTOURPOD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/ELBUBBLE/DEADBUBBLE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/ELBUBBLE/DETAILBUBBLE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/ELBUBBLE/ELBUBBLE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/ELBUBBLE/SMALLBUBBLE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/FRACTALCUBE/CYLINDER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/FRACTALCUBE/FLAP.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/FRACTALCUBE/SHAPE1FLOAT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HEXAGON/DETAILSHAPE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HEXAGON/DETAILSHAPEB.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HEXAGON/HOVERINGDETAIL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HEXAGON/ROTATINGDETAIL.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/HYDROGARDENMASTER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/HYDROPOD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/HYDROPODDEAD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/HYDROPODFLOAT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/HYDROPODFLOATDEAD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/HYDROPODGROWING.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/HYDROPODGROWINGDEAD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/HYDROPODOFF.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/HYDROGARDEN/WEIRDLUSHGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/IRRISHELLS/SHELLCRYSTALSLICES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/IRRISHELLS/SHELLFLY.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/IRRISHELLS/SHELLFLYPLANT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/IRRISHELLS/SHELLGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/IRRISHELLS/SHELLHUSK.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/IRRISHELLS/SHELLSHELF.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/IRRISHELLS/SHELLWHITE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/MSTRUCTURES/SINGLEJOINT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/MSTRUCTURES/SMALLJOINT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/SHARDS/FLOORPIECES.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/SHARDS/FLOORSHARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/SHARDS/SHARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/SHARDS/SHARDALT.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/SHARDS/SINGLESHARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/SHARDS/TALLSHARD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/WIRECELLS/WIRECELLFLOATCUBE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/WIRECELLS/WIRECELLFRAGMENTS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/WIRECELLS/WIRECELLGRASS.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/WEIRD/WIRECELLS/WIRECELLSMALLBUSH.SCENE.MBIN"
}
}

ADD_FILES_TABLE = {}

function AddToBuildmenu(BUILDABLE_OBJECT, CATEGORY)
ID_NAME_ = GetObjectID(BUILDABLE_OBJECT)
ID_NAME = "#" .. ID_NAME_
BUILDABLE_OBJECT_ = BUILDABLE_OBJECT
BUILDABLE_OBJECT_EXTENDER = [[MODELS/CUSTOM/]] .. ID_NAME_ .. ".SCENE.MBIN"
if ENABLE_PHYSICS_EXTENDER then BUILDABLE_OBJECT = BUILDABLE_OBJECT_EXTENDER end

BASEBUILDINGTABLE_ADDING =
[[
    <Property value="GcBaseBuildingEntry.xml">
      <Property name="ID" value="]] .. ID_NAME .. [[" />
      <Property name="HasProduct" value="True" />
      <Property name="IsTemporary" value="False" />
      <Property name="IsFromModFolder" value="True" />
      <Property name="SnapPoints" value="TkModelResource.xml">
        <Property name="Filename" value="" />
      </Property>
      <Property name="Model" value="TkModelResource.xml">
        <Property name="Filename" value="]] .. BUILDABLE_OBJECT .. [[" />
      </Property>
      <Property name="InactiveModel" value="TkModelResource.xml">
        <Property name="Filename" value="]] .. BUILDABLE_OBJECT .. [[" />
      </Property>
      <Property name="DecorationType" value="GcBaseBuildingObjectDecorationTypes.xml">
        <Property name="BaseBuildingDecorationType" value="Normal" />
      </Property>
      <Property name="IsPlaceable" value="True" />
      <Property name="IsDecoration" value="False" />
      <Property name="IsConnection" value="False" />
      <Property name="PlacementNormalOffset" value="]] .. OFFSET .. [[" />
      <Property name="Biome" value="GcBiomeType.xml">
        <Property name="Biome" value="All" />
      </Property>
      <Property name="BuildableOnPlanetBase" value="True" />
      <Property name="BuildableOnSpaceBase" value="True" />
      <Property name="BuildableOnFreighter" value="True" />
      <Property name="BuildableOnPlanet" value="True" />
      <Property name="BuildableOnPlanetWithProduct" value="True" />
      <Property name="BuildableUnderwater" value="True" />
      <Property name="BuildableAboveWater" value="True" />
      <Property name="PlanetLimit" value="0" />
      <Property name="RegionLimit" value="0" />
      <Property name="PlanetBaseLimit" value="0" />
      <Property name="FreighterBaseLimit" value="0" />
      <Property name="CheckPlaceholderCollision" value="False" />
      <Property name="CollisionScale" value="0.9" />
      <Property name="EnableCollision" value="True" />
      <Property name="CanPlaceOnItself" value="True" />
      <Property name="CanRotate3D" value="True" />
      <Property name="CanScale" value="True" />
      <Property name="Groups">
        <Property value="NMSString0x10.xml">
          <Property name="Value" value="]] .. CATEGORY .. [[" />
        </Property>
      </Property>
      <Property name="StorageContainerIndex" value="-1" />
      <Property name="CanChangeColour" value="True" />
      <Property name="CanChangeMaterial" value="True" />
      <Property name="CanPickUp" value="False" />
      <Property name="ScanRadius" value="0" />
      <Property name="RemovesAttachedDecoration" value="True" />
      <Property name="EditsTerrain" value="False" />
      <Property name="BaseTerrainEditShape" value="Cube" />
      <Property name="TerrainEditBaseYOffset" value="0" />
      <Property name="TerrainEditTopYOffset" value="0" />
      <Property name="TerrainEditBoundsScalar" value="1" />
      <Property name="IsSealed" value="False" />
      <Property name="CloseMenuAfterBuild" value="False" />
      <Property name="LinkGridData" value="GcBaseLinkGridData.xml">
        <Property name="Connection" value="GcBaseLinkGridConnectionData.xml">
          <Property name="Network" value="GcLinkNetworkTypes.xml">
            <Property name="LinkNetworkType" value="Power" />
          </Property>
          <Property name="NetworkSubGroup" value="0" />
          <Property name="NetworkMask" value="0" />
          <Property name="ConnectionDistance" value="0.1" />
          <Property name="UseMinDistance" value="False" />
          <Property name="LinkSocketPositions" />
          <Property name="LinkSocketSubGroups" />
        </Property>
        <Property name="Rate" value="0" />
        <Property name="Storage" value="0" />
        <Property name="DependsOnEnvironment" value="None" />
        <Property name="DependsOnHotspots" value="None" />
        <Property name="DependentConnections" />
      </Property>
      <Property name="GhostsCountOverride" value="0" />
      <Property name="SnappingDistanceOverride" value="0" />
      <Property name="RegionSpawnLOD" value="1" />
    </Property>
]]

PRODUCT =
[[
    <Property value="GcProductData.xml">
      <Property name="Id" value="]] .. ID_NAME .. [[" />
      <Property name="Name" value="]] .. ID_NAME_ .. [[" />
      <Property name="NameLower" value="]] .. ID_NAME_ .. [[" />
      <Property name="Subtitle" value="VariableSizeString.xml">
        <Property name="Value" value="" />
      </Property>
      <Property name="Description" value="VariableSizeString.xml">
        <Property name="Value" value="" />
      </Property>
      <Property name="Hint" value="" />
      <Property name="GroupID" value="" />
      <Property name="DebrisFile" value="TkModelResource.xml">
        <Property name="Filename" value="MODELS/EFFECTS/DEBRIS/TERRAINDEBRIS/TERRAINDEBRIS4.SCENE.MBIN" />
      </Property>
      <Property name="BaseValue" value="1" />
      <Property name="Level" value="0" />
      <Property name="Icon" value="TkTextureResource.xml">
        <Property name="Filename" value="TEXTURES/UI/FRONTEND/ICONS/BUILDABLE/BUILDABLE.CUBEROOM.DDS" />
      </Property>
      <Property name="HeroIcon" value="TkTextureResource.xml">
        <Property name="Filename" value="" />
      </Property>
      <Property name="Colour" value="Colour.xml">
        <Property name="R" value="0.172549" />
        <Property name="G" value="0.4862745" />
        <Property name="B" value="0.6235294" />
        <Property name="A" value="1" />
      </Property>
      <Property name="Category" value="GcRealitySubstanceCategory.xml">
        <Property name="SubstanceCategory" value="BuildingPart" />
      </Property>
      <Property name="Type" value="GcProductCategory.xml">
        <Property name="ProductCategory" value="BuildingPart" />
      </Property>
      <Property name="Rarity" value="GcRarity.xml">
        <Property name="Rarity" value="Common" />
      </Property>
      <Property name="Legality" value="GcLegality.xml">
        <Property name="Legality" value="Legal" />
      </Property>
      <Property name="Consumable" value="False" />
      <Property name="ChargeValue" value="0" />
      <Property name="StackMultiplier" value="0" />
      <Property name="DefaultCraftAmount" value="1" />
      <Property name="CraftAmountStepSize" value="1" />
      <Property name="CraftAmountMultiplier" value="1" />
      <Property name="Requirements">
        <Property value="GcTechnologyRequirement.xml">
          <Property name="ID" value="LAND2" />
          <Property name="InventoryType" value="GcInventoryType.xml">
            <Property name="InventoryType" value="Substance" />
          </Property>
          <Property name="Amount" value="50" />
        </Property>
      </Property>
      <Property name="AltRequirements" />
      <Property name="Cost" value="GcItemPriceModifiers.xml">
        <Property name="SpaceStationMarkup" value="0" />
        <Property name="LowPriceMod" value="0" />
        <Property name="HighPriceMod" value="0" />
        <Property name="BuyBaseMarkup" value="0" />
        <Property name="BuyMarkupMod" value="0" />
      </Property>
      <Property name="RecipeCost" value="2" />
      <Property name="SpecificChargeOnly" value="False" />
      <Property name="NormalisedValueOnWorld" value="0" />
      <Property name="NormalisedValueOffWorld" value="0" />
      <Property name="TradeCategory" value="GcTradeCategory.xml">
        <Property name="TradeCategory" value="None" />
      </Property>
      <Property name="WikiCategory" value="Construction" />
      <Property name="IsCraftable" value="True" />
      <Property name="DeploysInto" value="" />
      <Property name="EconomyInfluenceMultiplier" value="0" />
      <Property name="PinObjective" value="" />
      <Property name="PinObjectiveTip" value="" />
      <Property name="CookingIngredient" value="False" />
      <Property name="CookingValue" value="0" />
      <Property name="GoodForSelling" value="False" />
      <Property name="GiveRewardOnSpecialPurchase" value="" />
      <Property name="EggModifierIngredient" value="True" />
    </Property>
]]

DEFAULTSAVEDATA_KNOWNPRODUCT =
[[
      <Property value="NMSString0x10.xml">
        <Property name="Value" value="]] .. ID_NAME .. [[" />
      </Property>
]]

PHYICS_ENTITY =
[[
<?xml version="1.0" encoding="utf-8"?>
<Data template="TkAttachmentData">
  <Property name="Components">
    <Property value="TkPhysicsComponentData.xml">
      <Property name="Data" value="TkPhysicsData.xml">
        <Property name="Mass" value="0" />
        <Property name="Friction" value="0.5" />
        <Property name="RollingFriction" value="0.2" />
        <Property name="AngularDamping" value="0.2" />
        <Property name="LinearDamping" value="0.1" />
        <Property name="Gravity" value="20" />
      </Property>
      <Property name="VolumeTriggerType" value="TkVolumeTriggerType.xml">
        <Property name="VolumeTriggerType" value="Open" />
      </Property>
      <Property name="SurfaceProperties" value="None" />
      <Property name="TriggerVolume" value="False" />
      <Property name="Climbable" value="False" />
      <Property name="IgnoreModelOwner" value="False" />
      <Property name="NoVehicleCollide" value="False" />
      <Property name="NoPlayerCollide" value="False" />
      <Property name="CameraInvisible" value="False" />
      <Property name="InvisibleForInteraction" value="False" />
      <Property name="AllowTeleporter" value="False" />
      <Property name="BlockTeleporter" value="False" />
    </Property>
    <Property value="GcColouriseComponentData.xml">
      <Property name="PrimaryColour" value="Colour.xml">
        <Property name="R" value="0.607" />
        <Property name="G" value="0.603" />
        <Property name="B" value="0.566" />
        <Property name="A" value="0" />
      </Property>
      <Property name="SecondaryColour" value="Colour.xml">
        <Property name="R" value="0.66" />
        <Property name="G" value="0.507" />
        <Property name="B" value="0.235" />
        <Property name="A" value="0" />
      </Property>
    </Property>
  </Property>
  <Property name="LodDistances">
    <Property value="0" />
    <Property value="50" />
    <Property value="80" />
    <Property value="150" />
    <Property value="500" />
  </Property>
</Data>
]]

PHYSICS_EXTENDER_SCENE =
[[
<?xml version="1.0" encoding="utf-8"?>
<Data template="TkSceneNodeData">
  <Property name="Name" value="MODELS//CUSTOM//]] .. ID_NAME_ .. [[" />
  <Property name="NameHash" value="0" />
  <Property name="Type" value="MODEL" />
  <Property name="Transform" value="TkTransformData.xml">
    <Property name="TransX" value="0" />
    <Property name="TransY" value="0" />
    <Property name="TransZ" value="0" />
    <Property name="RotX" value="0" />
    <Property name="RotY" value="0" />
    <Property name="RotZ" value="0" />
    <Property name="ScaleX" value="1" />
    <Property name="ScaleY" value="1" />
    <Property name="ScaleZ" value="1" />
  </Property>
  <Property name="Attributes">
    <Property value="TkSceneNodeAttributeData.xml">
      <Property name="Name" value="GEOMETRY" />
      <Property name="AltID" value="" />
      <Property name="Value" value="MODELS//SPACE//ATLASSTATION//MODULARPARTS//INTERIOR//ENDING_1_INTERACTION//ATLASSTONE.GEOMETRY.MBIN" />
    </Property>
    <Property value="TkSceneNodeAttributeData.xml">
      <Property name="Name" value="NUMLODS" />
      <Property name="AltID" value="" />
      <Property name="Value" value="1" />
    </Property>
  </Property>
  <Property name="Children">
    <Property value="TkSceneNodeData.xml">
      <Property name="Name" value="PhysicsExtender" />
      <Property name="NameHash" value="0" />
      <Property name="Type" value="LOCATOR" />
      <Property name="Transform" value="TkTransformData.xml">
        <Property name="TransX" value="0" />
        <Property name="TransY" value="0" />
        <Property name="TransZ" value="0" />
        <Property name="RotX" value="0" />
        <Property name="RotY" value="0" />
        <Property name="RotZ" value="0" />
        <Property name="ScaleX" value="1" />
        <Property name="ScaleY" value="1" />
        <Property name="ScaleZ" value="1" />
      </Property>
      <Property name="Attributes">
        <Property value="TkSceneNodeAttributeData.xml">
          <Property name="Name" value="ATTACHMENT" />
          <Property name="AltID" value="" />
          <Property name="Value" value="MODELS//PLANETS//BIOMES//COMMON//BUILDINGS//PARTS//ENTITIES//STATICPHYSICSCOLOURED01.ENTITY.MBIN" />
        </Property>
      </Property>
      <Property name="Children">
        <Property value="TkSceneNodeData.xml">
          <Property name="Name" value="MODELS//CUSTOM//]] .. ID_NAME_ .. [[" />
          <Property name="NameHash" value="0" />
          <Property name="Type" value="COLLISION" />
          <Property name="Transform" value="TkTransformData.xml">
            <Property name="TransX" value="0" />
            <Property name="TransY" value="0" />
            <Property name="TransZ" value="0" />
            <Property name="RotX" value="0" />
            <Property name="RotY" value="0" />
            <Property name="RotZ" value="0" />
            <Property name="ScaleX" value="1" />
            <Property name="ScaleY" value="1" />
            <Property name="ScaleZ" value="1" />
          </Property>
          <Property name="Attributes">
            <Property value="TkSceneNodeAttributeData.xml">
              <Property name="Name" value="TYPE" />
              <Property name="AltID" value="" />
              <Property name="Value" value="Sphere" />
            </Property>
            <Property value="TkSceneNodeAttributeData.xml">
              <Property name="Name" value="RADIUS" />
              <Property name="AltID" value="" />
              <Property name="Value" value="0.5" />
            </Property>
          </Property>
          <Property name="Children" />
        </Property>
        <Property value="TkSceneNodeData.xml">
          <Property name="Name" value="MODELS//CUSTOM//]] .. ID_NAME_ .. "_REF" .. [[" />
          <Property name="NameHash" value="0" />
          <Property name="Type" value="REFERENCE" />
          <Property name="Transform" value="TkTransformData.xml">
            <Property name="TransX" value="0" />
            <Property name="TransY" value="0" />
            <Property name="TransZ" value="0" />
            <Property name="RotX" value="0" />
            <Property name="RotY" value="0" />
            <Property name="RotZ" value="0" />
            <Property name="ScaleX" value="1" />
            <Property name="ScaleY" value="1" />
            <Property name="ScaleZ" value="1" />
          </Property>
          <Property name="Attributes">
            <Property value="TkSceneNodeAttributeData.xml">
              <Property name="Name" value="SCENEGRAPH" />
              <Property name="AltID" value="" />
              <Property name="Value" value="]] .. string.gsub(BUILDABLE_OBJECT_, [[/]], string.char(92)) .. [[" />
            </Property>
          </Property>
          <Property name="Children" />
        </Property>
      </Property>
    </Property>
  </Property>
</Data>
]]

PHYSICS_EXTENDER_SCENE = string.gsub(PHYSICS_EXTENDER_SCENE, [[//]], string.char(92))

PHYSICS_EXTENDER_SCENE_REF =
{
    ["FILE_DESTINATION"] = [[MODELS\CUSTOM\]] .. ID_NAME_ .. [[.SCENE.EXML]],
    ["FILE_CONTENT"] = PHYSICS_EXTENDER_SCENE
}
if ENABLE_PHYSICS_EXTENDER then table.insert(ADD_FILES_TABLE, PHYSICS_EXTENDER_SCENE_REF) end
end

function GetObjectID(SCENEPATH)
    --return string.gsub(string.match(string.match(SCENEPATH, "^.+/(.+)$"), "(.+)%.(.+)"), ".SCENE", "") .. "_" .. math.random(9999)
    return string.gsub(string.match(string.match(SCENEPATH, "^.+/(.+)$"), "(.+)%.(.+)"), ".SCENE", "")
end

GROUPS_ALL = ""

function AddGroup(NEW_BUILD_GROUP, DEFAULT_ITEM, PARENT_GROUP, ICON)
if PARENT_GROUP == nil then PARENT_GROUP = "MOD" end
if ICON == nil or ICON == "" then ICON = "TEXTURES/UI/FRONTEND/ICONS/RANK/RANK.DISTANCEWARPED.DDS" end
GROUP =
[[
    <Property value="GcBaseBuildingGroup.xml">
      <Property name="ID" value="]] .. NEW_BUILD_GROUP .. [[" />
      <Property name="ParentGroup" value="]] .. PARENT_GROUP .. [[" />
      <Property name="Name" value="]] .. NEW_BUILD_GROUP .. [[" />
      <Property name="Icon" value="TkTextureResource.xml">
        <Property name="Filename" value="]] .. ICON .. [[" />
      </Property>
      <Property name="DefaultColourIdx" value="0" />
      <Property name="DefaultItem" value="]] .. DEFAULT_ITEM .. [[" />
    </Property>
]]
GROUPS_ALL = GROUPS_ALL .. GROUP
end

AddGroup("MOD", CATEGORY[1], "")

BASEBUILDINGTABLE_ADDING_ALL = ""
DEFAULTSAVEDATA_KNOWNPRODUCT_ALL = ""
PRODUCT_ALL = ""
OFFSET = "0"

for i=1,#CATEGORY,1 do
    AddGroup(CATEGORY[i], BUILDABLE_OBJECT_TABLE[CATEGORY[i]][1], "MOD", CATEGORY_ICON[CATEGORY[i]])
    if CATEGORY_OFFSET[CATEGORY[i]] == nil or CATEGORY_OFFSET[CATEGORY[i]] == "" then
        OFFSET = "0"
    else
        OFFSET = CATEGORY_OFFSET[CATEGORY[i]]
    end
    for j=1,#BUILDABLE_OBJECT_TABLE[CATEGORY[i]],1 do
        AddToBuildmenu(BUILDABLE_OBJECT_TABLE[CATEGORY[i]][j], CATEGORY[i])
        BASEBUILDINGTABLE_ADDING_ALL = BASEBUILDINGTABLE_ADDING_ALL .. BASEBUILDINGTABLE_ADDING
        DEFAULTSAVEDATA_KNOWNPRODUCT_ALL = DEFAULTSAVEDATA_KNOWNPRODUCT_ALL .. DEFAULTSAVEDATA_KNOWNPRODUCT
        PRODUCT_ALL = PRODUCT_ALL .. PRODUCT
    end
end

NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]            = "0-UltraBaseBuilding+UnlimitedBaseBuilding.pak",
["MOD_AUTHOR"]              = "Mjjstral",
["Maintainer"]              = "Babscoole",
["Contributor"]             = "GhostRick",
["NMS_VERSION"]             = "3.53b",
["MODIFICATIONS"]           =
    {
        {
            ["MBIN_CHANGE_TABLE"]   =
            {
                {
                    ["MBIN_FILE_SOURCE"]    = "METADATA\REALITY\TABLES\BASEBUILDINGTABLE.MBIN",
                    ["EXML_CHANGE_TABLE"]   =
                    {
                        {
                            ["REPLACE_TYPE"]        = "ALL",
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"BuildableOnPlanetBase",        "True"},
                                {"BuildableOnSpaceBase",         "True"},
                                {"BuildableOnFreighter",         "True"},
                                {"BuildableOnPlanet",            "True"},
                                {"BuildableOnPlanetWithProduct", "True"},
                                {"BuildableUnderwater",          "True"},
                                {"BuildableAboveWater",          "True"},
                                {"GlobalLimit",                     "0"},
                                {"SystemLimit",                     "0"},
                                {"PlanetLimit",                     "0"},
                                {"RegionLimit",                     "0"},
                                {"PlanetBaseLimit",                 "0"},
                                {"FreighterBaseLimit",              "0"},
                                {"CheckPlaceholderCollision",   "False"},
                                --{"EnableCollision",               "False"},
                                {"CanPlaceOnItself",            "True"},
                                {"CanRotate3D",                 "True"},
                                {"CanScale",                    "True"},
                                --{"BaseBuildingDecorationType", "Normal"},
                                --{"IsDecoration",              "False"},
                            }
                        },
                        {
                            ["PRECEDING_KEY_WORDS"] = {"Objects"},
                            ["LINE_OFFSET"]         = "+0",
                            ["ADD"]                 = BASEBUILDINGTABLE_ADDING_ALL
                        },
                        {
                            ["PRECEDING_KEY_WORDS"] = {"GcBaseBuildingGroup.xml"},
                            ["LINE_OFFSET"]         = "-1",
                            ["ADD"]                 = GROUPS_ALL
                        },
                        {--Naming Collision Patch
                            ["SPECIAL_KEY_WORDS"] = {"Filename", "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SHACK/SHACKTRADER_PARTS/SHACK.SCENE.MBIN"},
                            ["SECTION_UP"]      = 1,
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"ID", "SHACK_TRADER",}
                            },
                        },
                                                {
                            ["SPECIAL_KEY_WORDS"] = {"Filename", "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SHACK/SHACKSCIENTIFIC_PARTS/SHACK.SCENE.MBIN"},
                            ["SECTION_UP"]      = 1,
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"ID", "SHACK_SCIENTIFIC",}
                            },
                        },
                                                {
                            ["SPECIAL_KEY_WORDS"] = {"Filename", "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/SHACK/SHACKWARRIOR_PARTS/SHACK.SCENE.MBIN"},
                            ["SECTION_UP"]      = 1,
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"ID", "SHACK_WARRIOR",}
                            }
                        }
                    }
                },
                {
                    ["MBIN_FILE_SOURCE"]    = "METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN",
                    ["EXML_CHANGE_TABLE"]   =
                    {
                        {
                            ["PRECEDING_KEY_WORDS"] = {"Table"}, --"GcProductTable"
                            ["LINE_OFFSET"]         = "+0",
                            ["ADD"]                 = PRODUCT_ALL
                        }
                    }
                }
            }
        },
        {
            ["MBIN_CHANGE_TABLE"]   =
            {
                {
                    ["MBIN_FILE_SOURCE"]    = "METADATA\GAMESTATE\DEFAULTSAVEDATACREATIVE.MBIN",
                    ["EXML_CHANGE_TABLE"]   =
                    {
                        {
                            ["PRECEDING_KEY_WORDS"] = {"KnownProducts"},
                            ["LINE_OFFSET"]         = "+0",
                            ["ADD"]                 = DEFAULTSAVEDATA_KNOWNPRODUCT_ALL
                        }
                    }
                },
                {
                    ["MBIN_FILE_SOURCE"]    = "METADATA\GAMESTATE\DEFAULTSAVEDATA.MBIN",
                    ["EXML_CHANGE_TABLE"]   =
                    {
                        {
                            ["PRECEDING_KEY_WORDS"] = {"KnownProducts"},
                            ["LINE_OFFSET"]         = "+0",
                            ["ADD"]                 = DEFAULTSAVEDATA_KNOWNPRODUCT_ALL
                        }
                    }
                }
            }
        },
        {
            ["MBIN_CHANGE_TABLE"]   =
            {
                {
                    ["MBIN_FILE_SOURCE"]    = "GCDEBUGOPTIONS.GLOBAL.MBIN",
                    ["EXML_CHANGE_TABLE"]   =
                    {
                        {
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                --{"DisableLimits",                 "True"},
                                {"DisableBaseBuildingLimits",       "True"},
                                {"BaseBuildingPartsRequirePower",   "False"},
                                {"BaseDownloadTimeout",             "120"}, --ORIGINAL 40
                            }
                        }
                    }
                },
                {
                    ["MBIN_FILE_SOURCE"]    = "GCPLAYERGLOBALS.GLOBAL.MBIN",
                    ["EXML_CHANGE_TABLE"]   =
                    {
                        {
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"MaxBuildHeight", "1024"} --ORIGINAL 64
                            }
                        }
                    }
                }
            }
        }
    },
["ADD_FILES"] = ADD_FILES_TABLE
}