--DO NOT USE "REMOVE" TAGS WHEN COPYING FILES
--This script is intended for use with OpenBiomeExtender and will not work without it.
--Place the OpenBiomeExtender.pak into your ModScript folder when you run this script

MODEL_REPLACEMENT = {[[MODELS/PLANETS/BIOMES/COMMON/PLANTS/MEDIUMPLANT.SCENE.MBIN]],[[CUSTOMMODELS/CODENAMEAWESOME/BIOMES/COMMON/PLANTS/MEDIUM/MEDIUMPLANTPROC.SCENE.MBIN]]}

USER_FOLDER = "CODENAMEAWESOME"
SUFFIX = "MEDIUMPLANTPROC"

HAS_COMMON_PLANT = {
	{--Barren & HugeRock
		["BIOMES"] = {
			"OPENBE/BIOMEFILES/VANILLA/BARREN/BARRENBIOME.MBIN",
		},
		["OBJECTS"] = {
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/BARREN/BARRENBIGPROPSOBJECTSFULL.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/HUGEPROPS/HUGEROCK/HUGEROCKOBJECTSFULL.MBIN",
		},
	},
	{--Frozen
		["BIOMES"] = {"OPENBE/BIOMEFILES/VANILLA/FROZEN/FROZENBIOME.MBIN",},
		["OBJECTS"] = {"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/FROZEN/FROZENBIGPROPSOBJECTSFULL.MBIN"},
	},
	{--Toxic
		["BIOMES"] = {
		"OPENBE/BIOMEFILES/VANILLA/TOXIC/TOXICBIOME.MBIN",
		"OPENBE/BIOMEFILES/VANILLA/HUGEPROPS/HUGETOXIC/HUGETOXICBIOME.MBIN",
		},
		["OBJECTS"] = {
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/TOXIC/TOXICBIGPROPSOBJECTSFULL.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/HUGEPROPS/HUGETOXIC/HUGETOXICOBJECTSFULL.MBIN",
		},
	},
	{--Lush
		["BIOMES"] = {
		"OPENBE/BIOMEFILES/VANILLA/LUSH/LUSHBIOME.MBIN",
		"OPENBE/BIOMEFILES/VANILLA/HUGEPROPS/HUGELUSH/HUGELUSHBIOME.MBIN"
		},
		["OBJECTS"] = {
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/HUGEPROPS/HUGERING/HUGERINGOBJECTSFULL.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/LUSH/LUSHBIGPROPSOBJECTSFULL.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/LUSH/LUSHOBJECTSDEAD.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/LUSH/LUSHOBJECTSFULL.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/LUSH/LUSHOBJECTSLOW.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/LUSH/LUSHOBJECTSMID.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/OBJECTS/LUSH/LUSHROCKYOBJECTS.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/OBJECTS/LUSH/LUSHROCKYWEIRDOBJECTS.MBIN",			
		},
	},
	{--Scorched
		["BIOMES"] = {},
		["OBJECTS"] = {
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/HUGEPROPS/HUGESCORCHED/HUGESCORCHOBJECTSFULL.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/SCORCHED/SCORCHBIGPROPSOBJECTSFULL.MBIN",
		},
	},
	{--Radioactive and HugeUW
		["BIOMES"] = {
			"OPENBE/BIOMEFILES/VANILLA/HUGEPROPS/HUGEUWPLANT/HUGEUVWPLANTBIOME.MBIN",
			"OPENBE/BIOMEFILES/VANILLA/RADIOACTIVE/RADIOACTIVEBIOME.MBIN",
		},
		["OBJECTS"] = {
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/HUGEPROPS/HUGEUWPLANT/HUGEUWPLANTOBJECTS.MBIN",
			"OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/RADIOACTIVE/RADIOBIGPROPSOBJECTS.MBIN",
		},
	},
}

function generate_mbin_change_table(HAS_MODEL)
	mbin_change_table = {}
	
	for _, entry in pairs(HAS_MODEL) do
		for _, objects_file in pairs(entry["OBJECTS"]) do
			new_objects_file = string.gsub(objects_file,"/VANILLA/","/"..USER_FOLDER.."/")
			new_objects_file = string.gsub(new_objects_file,".MBIN",SUFFIX..".MBIN")
			
			layer_name = string.match(objects_file,"OBJECTFILES/VANILLA/(%a+)/")
			
			copy_table = {
				["MBIN_FILE_SOURCE"] = {{objects_file,new_objects_file}}
			}
			table.insert(mbin_change_table,copy_table)
			
			model_replace_table = {
				["MBIN_FILE_SOURCE"] = {new_objects_file},
				["EXML_CHANGE_TABLE"] = {
					{
						["REPLACE_TYPE"] = "RAW",
						["VALUE_CHANGE_TABLE"] = {MODEL_REPLACEMENT}
					}
				},
			}
			table.insert(mbin_change_table,model_replace_table)
			
			biome_add_table = {
				["MBIN_FILE_SOURCE"] = entry["BIOMES"],
				["EXML_CHANGE_TABLE"] = {
					{
						["SPECIAL_KEY_WORDS"] = {"Name",layer_name},
						["PRECEDING_KEY_WORDS"] = {"Options"},
						["ADD"] =
[[        <Property value="NMSString0x80.xml">
          <Property name="Value" value="]]..new_objects_file..[[" />
        </Property>]],
					},
				},
			}
			table.insert(mbin_change_table,biome_add_table)
			
		end
	end
	
	return mbin_change_table
end

NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_BATCHNAME"] 			= "zzOpenBiomeExtender-MergedModules.pak",
  ["MOD_FILENAME"] 			= "Error - You forgot to put OpenBE pak in ModScript.pak", --MOD_FILENAME will never be used if scripts are used properly (as batch patches)
  ["MOD_DESCRIPTION"]		= "Adds cave DetailObjects to mountains",
  ["MOD_AUTHOR"]				= "CodenameAwesome",
  ["NMS_VERSION"]				= "",
  ["MODIFICATIONS"] 		= 
	{
		{
			["MBIN_CHANGE_TABLE"] = generate_mbin_change_table(HAS_COMMON_PLANT)
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE