NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= "Logo Replacement",
["MOD_DESCRIPTION"]	= "Replaces the boot logo",
["MOD_AUTHOR"]		= "FBI",
["NMS_VERSION"]		= "3.15",

["ADD_FILES"] = {
	{
		["FILE_DESTINATION"] 		= "CUSTOMTEXTURES/UI/LOADING/HGLOGOBLACKBGSMALL.DDS",
		["EXTERNAL_FILE_SOURCE"] 	= "HGLOGOBLACKBGSMALL.DDS",
	},
},

["MODIFICATIONS"]	= {{
["MBIN_CHANGE_TABLE"] = {

{["MBIN_FILE_SOURCE"] = "METADATA\UI\BOOTLOGOPC.MBIN",
["EXML_CHANGE_TABLE"] = {
	{["VALUE_CHANGE_TABLE"] = {
		{"Texture1", "CUSTOMTEXTURES/UI/LOADING/HGLOGOBLACKBGSMALL.DDS"}
	}},
}
},

}},}}