NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= "Incinerator 314a.pak",
["MOD_DESCRIPTION"]	= "Changes incinerator appearance",
["MOD_AUTHOR"]		= "Gumsk",
["NMS_VERSION"]		= "314",
["MODIFICATIONS"]	= {{
	["MBIN_CHANGE_TABLE"] = {{
		["MBIN_FILE_SOURCE"] = "MODELS\COMMON\PROJECTILES\MULTITOOL_FLAMETHROWER\FIREPARTICLE_MAT.MATERIAL.MBIN",
		["EXML_CHANGE_TABLE"] = {{
			["PRECEDING_KEY_WORDS"] = {"Samplers"},
			["VALUE_CHANGE_TABLE"] = {
				{"Map", "TEXTURES/EFFECTS/WEAPONS/PLASMAFLASH.DDS"}}
}}},}}}}