NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Lush Always Have Water",
["MOD_AUTHOR"]      = "Grouch",
["LUA_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "7.05",
["MOD_DESCRIPTION"] = "Makes it so that lush worlds never lack water/oceans (unless they are moons in non-purple systems of course)",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FLORAL\FLORALBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\HUGEPROPS\HUGELUSH\HUGELUSHBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\JUNGLE\JUNGLEBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBIGPROPSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLESBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQTENTACLEBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROCKYWEIRDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMABIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHRUINSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHULTRABIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\ROCKY\ROCKBIOME.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"Terrain", "GcTerrainControls"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"WaterActiveFrequency", "1.000000"},
              }
            },
          }
        },
      }
    }
  }
}