NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Offline Mode",
["MOD_AUTHOR"]      = "GrouchTheGreat",
["LUA_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "6.45",
["MOD_DESCRIPTION"] = "Disables ODS, Cloud Saves and Exped downloads. Multiplayer is still accessible and mostly functional",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] = "GCDEBUGOPTIONS.GLOBAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"SimulateNoNetworkConnection", "true"},
              }
            },
          }
        },
      }
    }
  },
["ADD_FILES"] =
  {
    {
      ["FILE_DESTINATION"] = "LocTable.MXML",
      ["FILE_CONTENT"] =
[[
<?xml version="1.0" encoding="utf-8"?>
<Data template="cTkLocalisationTable">
  <Property name="Table">
    <Property name="Table" value="TkLocalisationEntry" _id="UI_EXPED_START_INV_BODY">
      <Property name="Id" value="UI_EXPED_START_INV_BODY" />
      <Property name="English" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="French" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Italian" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="German" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Spanish" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Russian" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Polish" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Dutch" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Portuguese" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="LatinAmericanSpanish" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="BrazilianPortuguese" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="SimplifiedChinese" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="TraditionalChinese" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="TencentChinese" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Korean" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Japanese" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="USEnglish" value="You may choose &lt;COMMODITY&gt;extra items&lt;&gt; to assist you with this expedition. Reach this terminus during the expedition to retrieve this equipment, or to &lt;STELLAR&gt;create a copy&lt;&gt; of your &lt;TECHNOLOGY&gt;starship&lt;&gt; and &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt;.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
    </Property>
    <Property name="Table" value="TkLocalisationEntry" _id="UI_EXPED_CONFIRM_BUTTON">
      <Property name="Id" value="UI_EXPED_CONFIRM_BUTTON" />
      <Property name="English" value="Start Expedition Offline" />
      <Property name="French" value="Start Expedition Offline" />
      <Property name="Italian" value="Start Expedition Offline" />
      <Property name="German" value="Start Expedition Offline" />
      <Property name="Spanish" value="Start Expedition Offline" />
      <Property name="Russian" value="Start Expedition Offline" />
      <Property name="Polish" value="Start Expedition Offline" />
      <Property name="Dutch" value="Start Expedition Offline" />
      <Property name="Portuguese" value="Start Expedition Offline" />
      <Property name="LatinAmericanSpanish" value="Start Expedition Offline" />
      <Property name="BrazilianPortuguese" value="Start Expedition Offline" />
      <Property name="SimplifiedChinese" value="Start Expedition Offline" />
      <Property name="TraditionalChinese" value="Start Expedition Offline" />
      <Property name="TencentChinese" value="Start Expedition Offline" />
      <Property name="Korean" value="Start Expedition Offline" />
      <Property name="Japanese" value="Start Expedition Offline" />
      <Property name="USEnglish" value="Start Expedition Offline" />
    </Property>
    <Property name="Table" value="TkLocalisationEntry" _id="UI_EXPED_FINISHED_INV_BODY">
      <Property name="Id" value="UI_EXPED_FINISHED_INV_BODY" />
      <Property name="English" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="French" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Italian" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="German" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Spanish" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Russian" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Polish" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Dutch" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Portuguese" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="LatinAmericanSpanish" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="BrazilianPortuguese" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="SimplifiedChinese" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="TraditionalChinese" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="TencentChinese" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Korean" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Japanese" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="USEnglish" value="The expedition has &lt;COMMODITY&gt;finished&lt;&gt;.&#xA;&#xA;Collect your stored items from the cache below.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
    </Property>
    <Property name="Table" value="TkLocalisationEntry" _id="UI_S21_START_INV_BODY">
      <Property name="Id" value="UI_S21_START_INV_BODY" />
      <Property name="English" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="French" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Italian" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="German" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Spanish" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Russian" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Polish" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Dutch" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Portuguese" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="LatinAmericanSpanish" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="BrazilianPortuguese" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="SimplifiedChinese" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="TraditionalChinese" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="TencentChinese" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Korean" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="Japanese" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
      <Property name="USEnglish" value="This expedition takes place on a &lt;STELLAR&gt;single planet&lt;&gt;. Starship travel is &lt;FUEL&gt;unavailable&lt;&gt;, and this terminus will not be reachable for equipment transfer until the expedition is complete.&#xA;&#xA;&lt;STELLAR&gt;Offline Mode&lt;&gt; is &lt;FUEL&gt;Enabled&lt;&gt;. Current expedition data download is &lt;FUEL&gt;prevented&lt;&gt;. Delete GAMEDATA/MODS/OfflineMode and restart to download &lt;STELLAR&gt;current Community Expedition data&lt;&gt;." />
    </Property>
    <Property name="Table" value="TkLocalisationEntry" _id="UI_EXPED_AVAILABLE">
      <Property name="Id" value="UI_EXPED_AVAILABLE" />
      <Property name="English" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="French" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="Italian" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="German" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="Spanish" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="Russian" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="Polish" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="Dutch" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="Portuguese" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="LatinAmericanSpanish" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="BrazilianPortuguese" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="SimplifiedChinese" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="TraditionalChinese" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="TencentChinese" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="Korean" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="Japanese" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
      <Property name="USEnglish" value="&quot;Offline Mode&quot; mod enabled, Expedition download prevented." />
    </Property>
  </Property>
</Data>
]]
    },
  }
}