NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Waterless Hot n Dry Planets-DesertAlmostNoWater",
["MOD_AUTHOR"]      = "Grouch",
["LUA_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "7.05",
["MOD_DESCRIPTION"] = "Makes it so desert/barren worlds only have oceans 5% of the time",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENBIGPROPSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENCORALBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHIVESBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENINFESTEDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENOCEANBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENPEACOCKBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENROCKYBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENROCKYWEIRDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENRUINSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DESOLATE\DESOLATEBIOME.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"Terrain", "GcTerrainControls"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"WaterActiveFrequency", "0.050000"},
              }
            },
          }
        },
      }
    }
  }
}