NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Waterless Hot n Dry Planets-HotNoWater",
["MOD_AUTHOR"]      = "Grouch",
["LUA_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "7.05",
["MOD_DESCRIPTION"] = "Makes it so that Scorched worlds do not ever have oceans",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BURNT\BURNTBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BURNT\BURNTREMIX\BURNTREMIXBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LAVA\LAVABIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHBIGPROPSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHCORALBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDRUINSBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHEDSHIELDTREEBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHINFESTEDBIOME.MBIN",
            "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHOCEANBIOME.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"Terrain", "GcTerrainControls"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"WaterActiveFrequency", "0.000000"},
              }
            },
          }
        },
      }
    }
  }
}