NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= "GSound 302a Teleporter Nexus.pak",
["MOD_DESCRIPTION"]	= "Silence Nexus Teleporter decoration",
["MOD_AUTHOR"]		= "Gumsk",
["NMS_VERSION"]		= "3.02",
["MODIFICATIONS"]	= {{
	["MBIN_CHANGE_TABLE"] = {{
	["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\COMMONPARTS\TELEPORTER_NEXUS\ENTITIES\TELEPORTERNEXUSINTERACTION.ENTITY.MBIN",
	["EXML_CHANGE_TABLE"] = {{
		["VALUE_CHANGE_TABLE"] = {
			{"Ambient", ""}
}}}},}}}}