NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= "GSound 302a Battery.pak",
["MOD_DESCRIPTION"]	= "Silence battery",
["MOD_AUTHOR"]		= "Gumsk",
["NMS_VERSION"]		= "3.02",
["MODIFICATIONS"]	= {{
	["MBIN_CHANGE_TABLE"] = {{
	["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\UTILITYPARTS\MODULE_BATTERYS\ENTITIES\BATTERY.ENTITY.MBIN",
	["EXML_CHANGE_TABLE"] = {{
		["REPLACE_TYPE"] = "ALL",
		["VALUE_CHANGE_TABLE"] = {
			{"Sound", ""}
}}}},}}}}