NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= "GSound 302a Health.pak",
["MOD_DESCRIPTION"]	= "Silence health station",
["MOD_AUTHOR"]		= "Gumsk",
["NMS_VERSION"]		= "3.02",
["MODIFICATIONS"]	= {{
	["MBIN_CHANGE_TABLE"] = {{
	["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\TECH\HEALTHSTATION\ENTITIES\HEALTHSTATION.ENTITY.MBIN",
	["EXML_CHANGE_TABLE"] = {{
		["REPLACE_TYPE"] = "ALL",
		["VALUE_CHANGE_TABLE"] = {
			{"Sound", ""}
}}}},}}}}