NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= "GSound 302a Audiolargedesk.pak",
["MOD_DESCRIPTION"]	= "Silence Large Desk decoration",
["MOD_AUTHOR"]		= "Gumsk",
["NMS_VERSION"]		= "3.02",
["MODIFICATIONS"]	= {{
	["MBIN_CHANGE_TABLE"] = {{
	["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\LARGEDESK\ENTITIES\AUDIOLARGEDESK.ENTITY.MBIN",
	["EXML_CHANGE_TABLE"] = {{
		["VALUE_CHANGE_TABLE"] = {
			{"Ambient", ""}
}}}},}}}}