OBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="OBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DEAD/OBJECTS/DEADOBJECTSDEAD.MBIN" />
		</Property>
	  </Property>
	</Property>]]
DETAILOBJECTS = [[	<Property value="GcExternalObjectListOptions.xml">
	  <Property name="Name" value="DETAILOBJECTS" />
	  <Property name="ResourceHint" value="" />
	  <Property name="ResourceHintIcon" value="" />
	  <Property name="Probability" value="1" />
	  <Property name="TileType" value="GcTerrainTileType.xml">
		<Property name="TileType" value="Base" />
	  </Property>
	  <Property name="AllowLimiting" value="True" />
	  <Property name="ChooseUsingLifeLevel" value="False" />
	  <Property name="Options">
		<Property value="NMSString0x80.xml">
		  <Property name="Value" value="METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DEAD/DETAILOBJECTS/DEADOBJECTSDEAD.MBIN" />
		</Property>
	  </Property>
	</Property>]]
NMS_MOD_DEFINITION_CONTAINER = --WARNING: Most, if not all, biomes in this mod are co-dependent (They use object lists generated by other biomes). These scripts won't work unless all of them are used together.
{
["MOD_FILENAME"] 			= "_CodenameAwesome.MishMashBiomes-DEAD.pak",
["MOD_AUTHOR"]				= "CodenameAwesome",
["NMS_VERSION"]				= "",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
				{
					{
						["MBIN_FILE_SOURCE"] = {
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DEADOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\OBJECTS\DEADOBJECTSDEAD.MBIN"},
							{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DEADOBJECTSDEAD.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DETAILOBJECTS\DEADOBJECTSDEAD.MBIN","REMOVE"},
						},
					},
					{--Fix up Objects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\OBJECTS\DEADOBJECTSDEAD.MBIN"
						},
		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>Objects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","DetailObjects",},
								["REMOVE"] 	= "SECTION"
							}
						}
					},
					{--Fix up DetailObjects files
						["MBIN_FILE_SOURCE"] 	= {
							"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DETAILOBJECTS\DEADOBJECTSDEAD.MBIN"
						},
		   
						["EXML_CHANGE_TABLE"] 	= -- Remove everything but Objects>DetailObjects
						{
							{
								["PRECEDING_KEY_WORDS"] = {"Objects","Objects",},
								["REMOVE"] 	= "SECTION"
							}
						}
					},
					{--Create Mish Mash DEAD Biome File
						["MBIN_FILE_SOURCE"] 	= {{"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DEADBIOME.MBIN","METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\MISHMASHDEADBIOME.MBIN","REMOVE"}}
					},
					{--Update Object Lists
						["MBIN_FILE_SOURCE"] 	= {"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\MISHMASHDEADBIOME.MBIN"},
						["EXML_CHANGE_TABLE"] 	= -- Remove MAIN
						{
							{ --Remove the Crystals. We're going to start handling this from the BIOMEFILENAMES.MBIN since all biomes have the same crystals.
								["SPECIAL_KEY_WORDS"] = {"Name","CRYSTALS"},
								["REMOVE"] = "SECTION"
	
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = DETAILOBJECTS,
							},
							{
								["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists"},
								["ADD"] = OBJECTS,
							},
							{
								["SPECIAL_KEY_WORDS"] = {"Name","MAIN"},
								["REMOVE"] = "SECTION"
	
							},
						}
					},
				}
		}
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE