--see also StandardSchemeExtended.lua
MATCHGROUND_MATERIALFLAG = [[    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F56_MATCH_GROUND" />
    </Property>
]]
NMS_MOD_DEFINITION_CONTAINER =
{
  ["MOD_FILENAME"] 			= "zzAssets_ScrubGrassMatchGround.pak",     --the name of the pak created (if not combined) - REQUIRED
  ["MOD_DESCRIPTION"]		= "",         --optional, for reference
  ["MOD_AUTHOR"]				= "",         --optional, for reference
  ["NMS_VERSION"]				= "2.0",     --optional, for reference
  ["MODIFICATIONS"] 		=             --REQUIRED SECTION
	{
		{
			["MBIN_CHANGE_TABLE"] =
			{
				{
					["MBIN_FILE_SOURCE"] 	= {
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS.SCENE.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS.DESCRIPTOR.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS.GEOMETRY.MBIN.PC","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS.GEOMETRY.DATA.MBIN.PC","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS\SCRUBGRASS3MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS3MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS\SCRUBGRASS4MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS4MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS\SCRUBGRASS5MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS5MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS\SCRUBGRASS6MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS6MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS\SCRUBGRASS7MAT.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS7MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS\SCRUBGRASSMAT1.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASSMAT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS\SCRUBGRASSMAT2.MATERIAL.MBIN","MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASSMAT2.MATERIAL.MBIN","REMOVE"},
					},
				},
				{
					["MBIN_FILE_SOURCE"] = {"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] =
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] 	=
							{
								{[[\SCRUBGRASS\]],	[[\SCRUBGRASS_MATCHGROUND\]]},
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS3MAT.MATERIAL.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS4MAT.MATERIAL.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS5MAT.MATERIAL.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS6MAT.MATERIAL.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASS7MAT.MATERIAL.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASSMAT1.MATERIAL.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SCRUBGRASS_MATCHGROUND\SCRUBGRASSMAT2.MATERIAL.MBIN"
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["PRECEDING_KEY_WORDS"] = {"TkMaterialFlags.xml"},
							["REMOVE"] = "SECTION",
							["REPLACE_TYPE"] = "ALL"
						},
						{
							["PRECEDING_KEY_WORDS"] = {"Flags"},
							["ADD"] = [[    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F01_DIFFUSEMAP" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F03_NORMALMAP" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F11_ALPHACUTOUT" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F19_BILLBOARD" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F25_ROUGHNESS_MASK" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F40_SUBSURFACE_MASK" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F56_MATCH_GROUND" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F57_DETAIL_OVERLAY" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F58_USE_CENTRAL_NORMAL" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F59_SCREENSPACE_FADE" />
    </Property>
    <Property value="TkMaterialFlags.xml">
      <Property name="MaterialFlag" value="_F61_CLAMP_AMBIENT" />
    </Property>]]
						}
					}
				}
			}
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE
