
RADIUS_MULTIPLIER = 2
SCALE_MULTIPLIER = 2

NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] 			= "HeavyAirImprovements.pak",
  ["MOD_DESCRIPTION"]		= "",
  ["MOD_AUTHOR"]				= "CodenameAwesome",
  ["MODIFICATIONS"] 		=
	{
		{
			["MBIN_CHANGE_TABLE"] = 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= {
						"MODELS/EFFECTS/HEAVYAIR/FIRESTORM/FIRESTORMGAS.HEAVYAIR.MBIN",
						"MODELS/EFFECTS/HEAVYAIR/GRAVITYSTORM/GRAVITYSTORMGAS.HEAVYAIR.MBIN",
						"MODELS/EFFECTS/HEAVYAIR/MARS/MARS.HEAVYAIR.MBIN",
						"MODELS/EFFECTS/HEAVYAIR/RADIOACTIVE/RADIOACTIVEGAS.HEAVYAIR.MBIN",
						"MODELS/EFFECTS/HEAVYAIR/SCORCHED/SCORCHEDGAS.HEAVYAIR.MBIN",
						"MODELS/EFFECTS/HEAVYAIR/SNOW/SNOW2.HEAVYAIR.MBIN",
						"MODELS/EFFECTS/HEAVYAIR/TOXIC/TOXICGAS.HEAVYAIR.MBIN",
					},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["MATH_OPERATION"] = "*",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Radius",	RADIUS_MULTIPLIER},
							}	
						},
						{
							["PRECEDING_KEY_WORDS"] = {"ScaleRange"},
							["MATH_OPERATION"] = "*",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"x",	SCALE_MULTIPLIER},
								{"y",	SCALE_MULTIPLIER},
							}	
						},
					}
				},
			}
		},
	}
}