--[[┎──────────────────────────────────────────
	┃ 		ALWAYS EXCLUDED FROM BATCH
	┠──────────────────────────────────────────
	┃ 			LOD levels increase
────┸──────────────────────────────────────--]]
local Mult = { near=1.6, far=1.4 }
local path = 'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/'

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '_META LOD increase.pak',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= '3.53',
	MOD_BATCHNAME		= '_META ~@~collection.pak',
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE	= {
			path..'BARREN/BARRENBIGPROPSOBJECTSFULL.MBIN',
			path..'BARREN/BARRENCORALOBJECTS.MBIN',
			path..'BARREN/BARRENHIVESOBJECTS.MBIN',
			path..'BARREN/BARRENHQOBJECTSFULL.MBIN',
			path..'BARREN/BARRENINFESTEDOBJECTS.MBIN',
			path..'BARREN/BARRENOBJECTSDEAD.MBIN',
			path..'BARREN/BARRENOBJECTSFULL.MBIN',
			path..'BARREN/BARRENOBJECTSLOW.MBIN',
			path..'BARREN/BARRENOBJECTSMID.MBIN',
			path..'BARREN/BARRENROCKYOBJECTS.MBIN',
			path..'BARREN/BARRENROCKYWEIRDOBJECTS.MBIN',

			path..'CAVE/CAVEBIOMEDEAD.MBIN',
			path..'CAVE/CAVEBIOMEEMPTY.MBIN',
			path..'CAVE/CAVEBIOMEFULL.MBIN',
			path..'CAVE/CAVEBIOMEGRASSBUSHES.MBIN',
			path..'CAVE/CAVEBIOMEMID.MBIN',
			path..'CAVE/CAVEBIOMESPARSETOXIC.MBIN',

			path..'DEAD/DEADBIGPROPSOBJECTSFULL.MBIN',
			path..'DEAD/DEADBIGPROPSOBJECTSVAR1.MBIN',
			path..'DEAD/DEADBIGPROPSOBJECTSVAR2.MBIN',
			path..'DEAD/DEADBIGPROPSOBJECTSVAR3.MBIN',
			path..'DEAD/DEADOBJECTSDEAD.MBIN',
			path..'DEAD/FROZENDEADOBJECTS.MBIN',
			path..'DEAD/FROZENDEADWEIRDOBJECTS.MBIN',

			path..'FROZEN/FROZENALIENOBJECTS.MBIN',
			path..'FROZEN/FROZENBIGPROPSOBJECTSFULL.MBIN',
			path..'FROZEN/FROZENHQOBJECTSMID.MBIN',
			path..'FROZEN/FROZENOBJECTSDEAD.MBIN',
			path..'FROZEN/FROZENOBJECTSFULL.MBIN',
			path..'FROZEN/FROZENOBJECTSLOW.MBIN',
			path..'FROZEN/FROZENOBJECTSMID.MBIN',
			path..'FROZEN/FROZENPILLAROBJECTS.MBIN',
			path..'FROZEN/FROZENROCKYOBJECTS.MBIN',
			path..'FROZEN/FROZENROCKYWEIRDOBJECTS.MBIN',

			path..'HUGEPROPS/HUGELUSH/HUGELUSHOBJECTSFULL.MBIN',
			path..'HUGEPROPS/HUGERING/HUGERINGOBJECTSFULL.MBIN',
			path..'HUGEPROPS/HUGEROCK/HUGEROCKOBJECTSFULL.MBIN',
			path..'HUGEPROPS/HUGESCORCHED/HUGESCORCHOBJECTSFULL.MBIN',
			path..'HUGEPROPS/HUGETOXIC/HUGETOXICOBJECTSFULL.MBIN',
			path..'HUGEPROPS/HUGEUWPLANT/HUGEUWPLANTOBJECTS.MBIN',

			path..'LAVA/LAVAOBJECTSFULL.MBIN',

			path..'LUSH/LUSHBIGPROPSOBJECTSFULL.MBIN',
			path..'LUSH/LUSHBUBBLEOBJECTS.MBIN',
			path..'LUSH/LUSHHQOBJECTSFULL.MBIN',
			path..'LUSH/LUSHHQTENTACLEOBJECTSFULL.MBIN',
			path..'LUSH/LUSHINFESTEDOBJECTS.MBIN',
			path..'LUSH/LUSHOBJECTSDEAD.MBIN',
			path..'LUSH/LUSHOBJECTSFULL.MBIN',
			path..'LUSH/LUSHOBJECTSLOW.MBIN',
			path..'LUSH/LUSHOBJECTSMID.MBIN',
			path..'LUSH/LUSHROCKYOBJECTS.MBIN',
			path..'LUSH/LUSHROCKYWEIRDOBJECTS.MBIN',
			path..'LUSH/LUSHROOMAOBJECTS.MBIN',
			path..'LUSH/LUSHROOMBOBJECTS.MBIN',
			path..'LUSH/LUSHULTRAOBJECTS.MBIN',
			path..'LUSH/ULTRAEXTERNALOBJECTS.MBIN',

			path..'RADIOACTIVE/RADIOACTIVEALIENOBJECTS.MBIN',
			path..'RADIOACTIVE/RADIOACTIVEGLOWOBJECTS.MBIN',
			path..'RADIOACTIVE/RADIOACTIVEOBJECTSDEAD.MBIN',
			path..'RADIOACTIVE/RADIOACTIVEOBJECTSFULL.MBIN',
			path..'RADIOACTIVE/RADIOACTIVEOBJECTSLOW.MBIN',
			path..'RADIOACTIVE/RADIOACTIVEOBJECTSMID.MBIN',
			path..'RADIOACTIVE/RADIOBIGPROPSOBJECTS.MBIN',
			path..'RADIOACTIVE/RADIOSPIKECRYSTALSOBJECTS.MBIN',
			path..'RADIOACTIVE/RADIOSPIKEPOTATOOBJECTS.MBIN',

			path..'SCORCHED/SCORCHBIGPROPSOBJECTSFULL.MBIN',
			path..'SCORCHED/SCORCHCORALOBJECTS.MBIN',
			path..'SCORCHED/SCORCHEDALIENOBJECTS.MBIN',
			path..'SCORCHED/SCORCHEDOBJECTSDEAD.MBIN',
			path..'SCORCHED/SCORCHEDOBJECTSFULL.MBIN',
			path..'SCORCHED/SCORCHEDOBJECTSLOW.MBIN',
			path..'SCORCHED/SCORCHEDOBJECTSMID.MBIN',
			path..'SCORCHED/SCORCHEDSHIELDTREEOBJECTS.MBIN',

			path..'SWAMP/SWAMPOBJECTSFULL.MBIN',

			path..'TOXIC/TOXICBIGPROPSOBJECTSFULL.MBIN',
			path..'TOXIC/TOXICEGGSMOONOBJECTS.MBIN',
			path..'TOXIC/TOXICEGGSOBJECTS.MBIN',
			path..'TOXIC/TOXICINFESTEDOBJECTS.MBIN',
			path..'TOXIC/TOXICOBJECTSDEAD.MBIN',
			path..'TOXIC/TOXICOBJECTSFULL.MBIN',
			path..'TOXIC/TOXICOBJECTSLOW.MBIN',
			path..'TOXIC/TOXICOBJECTSMID.MBIN',
			path..'TOXIC/TOXICSPORESOBJECTS.MBIN',
			path..'TOXIC/TOXICTENTACLESOBJECTS.MBIN',

			path..'UNDERWATER/UNDERWATERCRYSTALS.MBIN',
			path..'UNDERWATER/UNDERWATERCUCUMBERLIGHTS.MBIN',
			path..'UNDERWATER/UNDERWATERCURVECORAL.MBIN',
			path..'UNDERWATER/UNDERWATERDEAD.MBIN',
			path..'UNDERWATER/UNDERWATERFULL.MBIN',
			path..'UNDERWATER/UNDERWATERGASBAGS.MBIN',
			path..'UNDERWATER/UNDERWATERMID.MBIN',
			path..'UNDERWATER/UNDERWATERMONOLITHS.MBIN',
			path..'UNDERWATER/UNDERWATERPLANT.MBIN',

			path..'WEIRD/BEAMSTONE/BEAMSOBJECTSDEAD.MBIN',
			path..'WEIRD/BONESPIRE/BONESPIREOBJECTSDEAD.MBIN',
			path..'WEIRD/CONTOUR/CONTOUROBJECTSDEAD.MBIN',
			path..'WEIRD/ELBUBBLE/ELBUBBLEOBJECTSDEAD.MBIN',
			path..'WEIRD/FRACTALCUBE/FRACTCUBEOBJECTSDEAD.MBIN',
			path..'WEIRD/HEXAGON/HEXAGONOBJECTSDEAD.MBIN',
			path..'WEIRD/HYDROGARDEN/HYDROGARDENOBJECTSDEAD.MBIN',
			path..'WEIRD/IRRISHELLS/IRRISHELLSOBJECTSDEAD.MBIN',
			path..'WEIRD/MSTRUCTURES/MSTRUCTOBJECTSDEAD.MBIN',
			path..'WEIRD/SHARDS/SHARDSOBJECTSDEAD.MBIN',
			path..'WEIRD/WIRECELLS/WIRECELLSOBJECTSDEAD.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH			= 200,
				VALUE_MATCH_OPTIONS = '<',
				MATH_OPERATION 		= '*',
				PRECEDING_KEY_WORDS = 'LodDistances',
				VALUE_CHANGE_TABLE 	= {
					{'IGNORE',		Mult.near}
				}
			},
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH			= 460,
				VALUE_MATCH_OPTIONS = '>',
				MATH_OPERATION 		= '*',
				PRECEDING_KEY_WORDS = 'LodDistances',
				VALUE_CHANGE_TABLE 	= {
					{'IGNORE',		Mult.far}
				}
			},
			-- {
			-- 	REPLACE_TYPE 		= 'ALL',
			-- 	VALUE_MATCH			= 8,
			-- 	VALUE_MATCH_OPTIONS = '<',
			-- 	MATH_OPERATION 		= '+',
			-- 	VALUE_CHANGE_TABLE 	= {
			-- 		{'MaxRegionRadius',	2} -- not found in ~30 of the files. Results in warnings
			-- 	}
			-- },
			-- {
			-- 	REPLACE_TYPE 		= 'ALL',
			-- 	VALUE_MATCH			= 9000,
			-- 	VALUE_MATCH_OPTIONS = '<',
			-- 	MATH_OPERATION 		= '*',
			-- 	VALUE_CHANGE_TABLE 	= {
			-- 		{'FadeInStartDistance',		1.5}, -- 2
			-- 		{'FadeInEndDistance',		1.5},
			-- 		{'FadeOutStartDistance',	1.5},
			-- 		{'FadeOutEndDistance',		1.5}
			-- 	}
			-- }
		}
	}
}}}}
