-- enable for SHips too
-- change emote mnenu icon + name
-- LinkedSpecialID
-- "SPEC_XOHELMET"
--creature detector button
-- "GenericReward" via Interaction instead of TriggerAxction


NUMBER_OF_SHIP_SEEDS =
{
	["FIGHTER"]		=	0,
	["DROPSHIP"] 	=	0,
	["SCIENTIFIC"]	= 	0,
	["SHUTTLE"]		=   528,
	["ROYAL"]		=   0
}

ENABLE_USER_SHIP_SEEDS = false

CUSTOM_SHIPS = true
OTHER_OPTIONS = false

FULL_VERSION = true --Use false for non cheat version
FORCE_ALL_ACTION = false
ENABLE_SHIELD_MOD = false
ENABLE_SPAWNERS = true
ADD_MORE_EMOTES = true
SPAWN_OFFSET_FRONT = 0

ACTION_SELECTION_FULL =
{
"TELEPORT_BASE",
"R_ENABLENEXUS",
"MIXER_AMMO",
"MIXER_WARPFUEL",
"MIXER_SHIPFUEL",
"MIXER_HEAL",
"MIXER_SPACEHELP",
"MIXER_JETPACK",
"MIXER_MONEY",
"MIXER_TECH_1",
"MIXER_TECH_2",
"MIXER_TECH_3",
"MIXER_SCAN",
--"MIXER_BREAKTECH",
"MIXER_STORM",
"MIXER_PIRATES",
"MIXER_WANTED",
"ENT_BOLTCASTER",
"ENT_PHOCORE",
"ENT_SHIP",
"ENT_CHARISMA",
"ENT_UNITS",
"ENT_REZOSUZ",
"ENT_SHIP_PC",
"ENT_XO_HELMET",
"ENT_XO_GUN_DIG",
"ENT_XO_GUN_RET",
"ENT_XO_UNIT_DIG",
"ENT_XO_UNIT_RET",

"Save", 
"Portal",

-- "Teleporter_Station", 
-- "CustomiseCharacter", 
-- "CustomiseShip", 
-- "CustomiseWeapon", 
-- "CustomiseVehicle", 
-- "ClaimBaseAnywhere", 
-- "NexusDailyMission", 
-- "BuildingShop", 
-- "SpecialsShop", 
-- "MissionGiver", 
-- "ExoticExtra1", 
-- "ExoticExtra2", 
-- "ExoticExtra3", 
-- "ExoticExtra4", 
-- "ExoticExtra5",
-- "ExoticExtra6", 
-- "AtlasPlinth", 
-- "Epilogue", 
-- "ManageFleet",

-- "GcRewardCommunityContribution", 
-- "GcRewardTimeWarp",
-- "GcRewardScanEventOutcome",
-- "GcRewardDeactivateFiends",
-- "GcRewardUploadBase",
-- "GcRewardNetworkPlayer"

"GcCameraShakeAction",
"GcFrigateInteractionAction",
"GcScareCreaturesAction",
"GcWarpAction"

-- "Ambient_CameraAmbient_Planet",
-- "Ambient_System",
-- "Ambient_Photo",
-- "Ambient_NxtSong",
-- "Ambient_Spawn",
-- "TogglePause",
-- "TogglePlanet",
-- "Suicide",
-- "Reset",
-- "AddLastToolbox",
-- "AddLastToolboxAtPos",
-- "TerrainInvalidate",
-- "TogglePipeline",
-- "TakeScreenshot",
-- "TakeExrScreenshot",
-- "ToggleDebugStats",
-- "ToggleDebugSubpage",
-- "DumpNodeStats",
-- "ToggleTaa",
-- "DebugDropMeasurementAnchor",
-- "QuickWarp",
-- "DumpStats",
-- "DiscoverOwnBase",
-- "ClearTerrainEdits",
-- "SelectRegion",
-- "SwitchRegionRow",
-- "SwitchRegionAxis",
-- "OpenLog",
-- "DumpVertStats",
-- "Player_TagMarker"
}

SPAWN_TABLE =
{
"MODELS/COMMON/SPACECRAFT/FIGHTERS/FIGHTER_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/SCIENTIFIC/SCIENTIFIC_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/DROPSHIPS/DROPSHIP_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/SHUTTLE/SHUTTLE_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/S-CLASS/S-CLASS_PROC.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/DRONE.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/DRONEARMOURED.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/QUADRUPED.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/WALKER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/PARTS/OBJECTSPAWNER/BALL.SCENE.MBIN"
}

GENERIC_ANIMATION_FILE = "MODELS/COMMON/PLAYER/PLAYERCHARACTER/ANIMS/EMOTES/0H_EMOTE_MIND_BLOWN.ANIM.MBIN"
GENERIC_BUTTON_ICON = "TEXTURES/UI/FRONTEND/COMPONENTS/STAR.DDS"

SimpleInteractionType = --NMS 2.09
{
"Interact", "Treasure", "Beacon", "Scan", "Save", "CallShip", "CallVehicle", "Word", "Tech", "GenericReward", 
"Feed", "Ladder", "ClaimBase", "TeleportStartPoint", "TeleportEndPoint", "Portal", "Chest", "ResourceHarvester", 
"BaseCapsule", "Hologram", "NPCTerminalMessage", "VehicleBoot", "BiomeHarvester", "FreighterGalacticMap", "FreighterChest",
"Collectable", "Chair", "BaseTreasureChest", "SpawnObject", "NoiseBox" 
}

InteractionType = --NMS 2.09
{
"None", "Shop", "NPC", "NPC_Secondary", "NPC_Anomaly", "NPC_Anomaly_Secondary", "Ship", "Outpost", "SpaceStation", "RadioTower", "Monolith", "Factory",
"AbandonedShip", "Harvester", "Observatory", "TradingPost", "DistressBeacon", "Portal", "Plaque", "AtlasStation", "AbandonedBuildings", "WeaponTerminal", "SuitTerminal", "SignalScanner",
"Teleporter_Base", "Teleporter_Station", "ClaimBase", "NPC_Freighter_Captain", "NPC_HIRE_Weapons", "NPC_HIRE_Weapons_Wait", "NPC_HIRE_Farmer", "NPC_HIRE_Farmer_Wait", "NPC_HIRE_Builder",
"NPC_HIRE_Builder_Wait", "NPC_HIRE_Vehicles", "NPC_HIRE_Vehicles_Wait", "MessageBeacon", "NPC_HIRE_Scientist", "NPC_HIRE_Scientist_Wait", "NPC_Recruit", "NPC_Freighter_Captain_Secondary",
"NPC_Recruit_Secondary", "Vehicle", "MessageModule", "TechShop", "VehicleRaceStart", "BuildingShop", "MissionGiver", "HoloHub", "HoloExplorer", "HoloSceptic", "HoloNoone", "PortalRuneEntry",
"PortalActivate", "CrashedFreighter", "GraveInCave", "GlitchyStoryBox", "NetworkPlayer", "NetworkMonument", "AnomalyComputer", "AtlasPlinth", "Epilogue", "GuildEnvoy", "ManageFleet",
"ManageExpeditions", "Frigate", "CustomiseCharacter", "CustomiseShip", "CustomiseWeapon", "CustomiseVehicle", "ClaimBaseAnywhere", "FleetNavigator", "FleetCommandPost", "StoryUtility",
"MPMissionGiver", "SpecialsShop", "WaterRuin", "LocationScanner", "ByteBeat", "NPC_CrashSite", "NPC_Scavenger", "BaseGridPart", "NPC_Freighter_Crew", "NPC_Freighter_Crew_Owned",
"AbandonedShip_With_NPC", "ShipPilot", "NexusMilestones", "NexusDailyMission", "CreatureFeeder", "ExoticExtra1", "ExoticExtra2", "ExoticExtra3", "ExoticExtra4", "ExoticExtra5",
"ExoticExtra6", "MapShop", "NPC_Closure", "StorageContainer", "Teleporter_Nexus" 
}

REWARD_TYPE = --NMS 2.09
{
"GcRewardAdvancePortalState", "GcRewardAssessCookedProduct", "GcRewardAtlasPathProgress", "GcRewardCargo", "GcRewardChangeGlobalMission", 
"GcRewardClosePortal", "GcRewardCrashSiteFly", "GcRewardCrashSiteRepair", "GcRewardDamage", "GcRewardDamageTech", "GcRewardDiscoverRune", 
"GcRewardDisguisedProduct", "GcRewardEnergy", "GcRewardFactionStanding", "GcRewardFrigateDamageResponse", "GcRewardHazard", 
"GcRewardHealth", "GcRewardIncrementInteractionIndex", "GcRewardInterventionResponse", "GcRewardJetpackBoost", "GcRewardJourneyThroughCentre", 
"GcRewardMission", "GcRewardMissionMessage", "GcRewardMissionMessageSeeded", "GcRewardMissionSeeded", "GcRewardModifyStat", "GcRewardMoney", 
"GcRewardMultiSpecificProductRecipes", "GcRewardMultiSpecificProducts", "GcRewardNexus", "GcRewardOpenPage", "GcRewardOpenUnlockTree", 
"GcRewardPirateAttack", "GcRewardPirateProbeSignal", "GcRewardProceduralProduct", "GcRewardProceduralProductFromBiome", 
"GcRewardProceduralTechnology", "GcRewardProcTechProduct", "GcRewardProduct", "GcRewardProductRecipe", "GcRewardRefreshHazProt", 
"GcRewardRepairTech", "GcRewardScan", "GcRewardScanEvent", "GcRewardScanEventNearestBuilding", "GcRewardSecondaryInteractionOptions", 
"GcRewardSecondarySubstance", "GcRewardShield", "GcRewardShipAssistance", "GcRewardShipMessage", "GcRewardShowBlackHoles", 
"GcRewardSignalScan", "GcRewardSpecificProduct", "GcRewardSpecificProductRecipe", "GcRewardSpecificProductRecipeFromList", "GcRewardSpecificShip", 
"GcRewardSpecificSpecial", "GcRewardSpecificSubstance", "GcRewardSpecificTech", "GcRewardSpecificTechFromList", "GcRewardSpecificWeapon", 
"GcRewardStanding", "GcRewardStartPurchase", "GcRewardStatDiff", "GcRewardSubstance", "GcRewardTeachWord", "GcRewardTechRecipe", 
"GcRewardTeleport", "GcRewardTrigger", "GcRewardTriggerStorm", "GcRewardUpgradeBase", "GcRewardWantedLevel", "GcRewardWeapon", 
"GcRewardWikiTopic", "GcRewardWorker",
"GcRewardCommunityContribution", "GcRewardScanEventOutcome", "GcRewardCustomExpeditionLogEntry", "GcRewardCompleteMission", 
"GcRewardStatCompareAndSet", "GcRewardDisplayTechWindow", "GcRewardDeactivateFiends", "GcRewardMissionOverride", 
"GcRewardDestructTable", "GcRewardUploadBase", "GcRewardNetworkPlayer", "GcRewardSendChatMessage", "GcRewardTimeWarp"
}

QuickMenuActions = --NMS 2.09 --HotActionMenuTypesEnum: OnFoot, InShip, InExocraft
{ 
"None", "CallFreighter", "SummonNexus", "CallShip", "SummonVehicleSubMenu", "SummonBuggy", "SummonBike", "SummonTruck", "SummonWheeledBike",
"SummonHovercraft", "SummonSubmarine", "VehicleScan", "VehicleScanSelect", "VehicleRestartRace", "Torch", "GalaxyMap", "PhotoMode", "ChargeMenu", "Charge", "ChargeSubMenu",
"Repair", "BuildItem", "BuildChangeGroup", "BuildDelete", "BuildColour", "BuildMaterial", "BuildWireConnection", "BuildColourGroup", "BuildMaterialGroup", "BuildRotateScale",
"CommunicatorReceive", "CommunicatorInitiate", "ThirdPersonCharacter", "ThirdPersonShip", "EconomyScan", "EmoteMenu", "Emote", "UtilitySubMenu", "SummonSubMenu", "SummonShipSubMenu",
"ChangeSecondaryWeaponMenu", "ChangeSecondaryWeapon", "ChooseCreatureFoodMenu", "ChooseCreatureFood", "Invalid"
}

InputActions = --NMS 2.09
{ 
"Invalid", "Player_Forward", "Player_Back", "Player_Left", "Player_Right", "Player_SwimUp", "Player_SwimDown", "Player_Interact", "Player_Melee",
"Player_Scan", "Player_Torch", "Player_Binoculars", "Player_Zoom", "Player_ShowHUD", "Player_Jump", "Player_Run", "Player_Shoot", "Player_Grenade", "Player_Reload",
"Player_ChangeWeapon", "Player_Deconstruct", "Player_ChangeAltWeapon", "Player_PlaceMarker", "Quick_Menu", "Build_Menu", "Ship_Thrust", "Ship_Brake", "Ship_Boost",
"Ship_RollLeft", "Ship_RollRight", "Ship_Exit", "Ship_Land", "Ship_Shoot", "Ship_ChangeWeapon", "Ship_Scan", "Ship_PulseJump", "Ship_GalacticMap", "Ship_TurnLeft", "Ship_TurnRight",
"Ship_FreeLook", "Vehicle_Forward", "Vehicle_Reverse", "Vehicle_Left", "Vehicle_Right", "Vehicle_Brake", "Vehicle_Exit", "Vehicle_Shoot", "Vehicle_ChangeWeapon", "Vehicle_Scan",
"Vehicle_Boost", "Vehicle_Jump", "Vehicle_Horn", "Vehicle_AddCheckpoint", "Vehicle_DeleteCheckpoint", "Fe_Select", "Fe_AltSelect", "Fe_SelectX", "Fe_Back", "Fe_Alt1", "Fe_Alt1X",
"Fe_Transfer", "Fe_Destroy", "Gm_Select", "Gm_Restart", "UI_Left", "UI_Right", "UI_Left_Sub", "UI_Right_Sub", "UI_Down_Sub", "UI_Up_Sub", "UI_NetworkPageShortcut", "UI_StackSplitUp",
"UI_StackSplitDown", "Fe_ExitMenu", "Fe_Options", "Fe_Quit", "Fe_MsgSkip", "Quick_Left", "Quick_Right", "Quick_Action", "Quick_Back", "Quick_Up", "Quick_Down", "Build_Place", "Build_Rotate_Left",
"Build_Rotate_Right", "Build_AnalogRotateMode1", "Build_AnalogRotateMode2", "Build_AnalogRotateLeftY", "Build_AnalogRotateRightY", "Build_AnalogRotateY", "Build_AnalogRotateLeftZ",
"Build_AnalogRotateRightZ", "Build_AnalogRotateZ", "Build_ScaleUp", "Build_ScaleDown", "Build_AnalogueScale", "Build_SelectionMode", "Build_Camera", "Photo_Hide", "Photo_Sun", "Photo_Cam",
"Photo_Exit", "Photo_CamDown", "Photo_CamUp", "Photo_Capture", "Ambient_Camera", "Ambient_Planet", "Ambient_System", "Ambient_Photo", "Ambient_NxtSong", "Ambient_Spawn", "Terrain_Edit",
"Terrain_ModeBack", "Terrain_Menu", "Terrain_SizeUp", "Terrain_SizeDown", "Terrain_RotTerrainLeft", "Terrain_RotTerrainRight", "Terrain_ChangeShape", "Ship_NextTarget",
"Ship_PreviousTarget", "Ship_ClosestTarget", "CameraLook", "CameraLookX", "CameraLookY", "PlayerMove", "PlayerMoveX", "PlayerMoveY", "SpaceshipThrust", "SpaceshipBrake", "VehicleMove",
"VehicleSteer", "VehicleThrust", "VehicleBrake", "ShipStrafe", "ShipStrafeHorizontal", "ShipStrafeVertical", "HeldRotate", "HeldRotateLeft", "HeldRotateRight", "ShipSteer", "ShipTurn",
"ShipPitch", "ShipLook", "ShipLookX", "ShipLookY", "ShipLand", "ShipPulse", "PlayerSmoothTurnLeft", "PlayerSmoothTurnRight", "PlayerSnapTurnLeft", "PlayerSnapTurnRight", "PlayerSnapTurnAround",
"PlayerMoveAround", "TeleportDirection", "PlayerAutoWalk", "InteractLeft", "MeleeLeft", "HandCtrlHolster", "ShipUp", "ShipDown", "ShipLeft", "ShipRight", "ShipZoom", "Inventory",
"DiscoveryNetworkRetry", "QuitGame", "ReportBase", "GalacticMap_Select", "GalacticMap_Deselect", "GalacticMap_Exit", "GalacticMap_Scan", "GalacticMap_Home", "GalacticMap_PlanetBase",
"GalacticMap_Accelerate", "GalacticMap_ExpandMenu", "GalacticMap_ScreenshotToggle", "GalacticMap_ScanChooseNext", "GalacticMap_ToggleWaypoint", "GalacticMap_ClearAllWaypoints",
"GalacticMap_NextNavType", "GalacticMap_PreviousNavType", "GalacticMap_PreviousFilter", "GalacticMap_NextFilter", "GalacticMap_CameraLook", "GalacticMap_CameraLookX",
"GalacticMap_CameraLookY", "GalacticMap_PlayerMove", "GalacticMap_PlayerMoveX", "GalacticMap_PlayerMoveY", "GalacticMap_PlayerMoveForward", "GalacticMap_PlayerMoveBackward",
"GalacticMap_PlayerMoveLeft", "GalacticMap_PlayerMoveRight", "GalacticMap_Up", "GalacticMap_Down", "GalacticMap_Gesture", "UI_Cursor", "UI_CursorX", "UI_CursorY", "UI_Camera",
"UI_CameraX", "UI_CameraY", "UI_ViewPlayerInfo", "UI_NextInputControls", "UI_PrevInputControls", "UI_ToggleBuySell", "UI_ToggleTradeInventory", "CharacterCustomisation_ShowCharacter",
"UI_CharacterCustomisation_Camera", "UI_CharacterCustomisation_RotateCamera", "UI_CharacterCustomisation_PitchCamera", "GameMode_CancelDelete", "GameMode_TitleStart",
"GameMode_ChangeUser", "Binocs_NextMode", "Binocs_PrevMode", "BaseBuilding_PinRecipe", "BaseBuilding_SwitchBase", "PhotoMode_CatLeft", "PhotoMode_CatRight", "PhotoMode_ValueIncrease",
"PhotoMode_ValueDecrease", "PhotoMode_OptionUp", "PhotoMode_OptionDown", "PhotoMode_CameraRollLeft", "PhotoMode_CameraRollRight", "PhotoMode_PauseApplication", "PhotoMode_CopyLocation",
"PhotoMode_HideLocation", "HMD_Recenter", "HMD_Recenter2", "HMD_FEOpen", "TextChatOpenClose", "TextChatSend", "TextChatPasteHold", "TextChatPaste", "TextChatAutocomplete",
"TextChatAutocompleteModifier", "TextChatCursorLeft", "TextChatCursorRight", "TextChatCursorHome", "TextChatCursorEnd", "TextChatDelete", "Player_InteractSecondary", "TogglePause",
"TogglePlanet", "Suicide", "Reset", "AddLastToolbox", "AddLastToolboxAtPos", "TerrainInvalidate", "TogglePipeline", "TakeScreenshot", "TakeExrScreenshot", "ToggleDebugStats",
"ToggleDebugSubpage", "DumpNodeStats", "ToggleTaa", "DebugDropMeasurementAnchor", "QuickWarp", "DumpStats", "DiscoverOwnBase", "ClearTerrainEdits", "SelectRegion", "SwitchRegionRow",
"SwitchRegionAxis", "OpenLog", "DumpVertStats", "Player_TagMarker"
}

ACTION =
{
"GcBaseBuildingSettingsAction.xml",
"GcCameraShakeAction.xml",
"GcDestroyAction.xml",
"GcDisplayText.xml",
"GcFiendCrimeAction",
"GcFireSimpleInteractionAction.xml",
"GcFrigateInteractionAction.xml",
"GcGoToStateAction.xml",
"GcHazardAction.xml",
"GcNodeActivationAction.xml",
"GcPainAction.xml",
"GcParticleAction.xml",
"GcPlayAnimAction.xml",
"GcPlayAudioAction.xml",
"GcPowerStateAction.xml",
"GcResetSimpleInteractionAction",
"GcRewardAction.xml",
"GcScareCreaturesAction.xml",
"GcSpawnAction.xml",
"GcWarpAction.xml"
}
 
TRIGGER =
{ 
"GcAnimFrameEvent.xml",
"GcBeenShotEvent.xml",
"GcCreatureNearbyEvent",
"GcPlayerNearbyEvent.xml",
"GcStateTimeEvent.xml",
"GcStormEvent.xml"
}

REWARDS = 
{
"ENT_BOLTCASTER",
"ENT_PHOCORE",
"ENT_SHIP",
"ENT_CHARISMA",
"ENT_UNITS",
"ENT_REZOSUZ",
"ENT_SHIP_PC",
"ENT_XO_HELMET",
"ENT_XO_GUN_DIG",
"ENT_XO_GUN_RET",
"ENT_XO_UNIT_DIG",
"ENT_XO_UNIT_RET",
"SALVAGE_C",
"SALVAGE_B",
"SALVAGE_A",
"SALVAGE_S",
"VEHICLE_SCAN",
"WILD_BARREN",
"WILD_LUSH",
"WILD_RADIO",
"WILD_SNOW",
"WILD_SCORCHED",
"WILD_TOXIC",
"PROC_GUN",
"PROC_SUIT",
"CARGO_LOOT",
"DRONE_LOOT",
"QUAD_LOOT",
"WALKER_LOOT",
"POOPLOOT",
"SPECPOOP",
"DAMAGESMALL",
"DAMAGELARGE",
"DAMAGEENERGY",
"SHIELDSMALL",
"SHIELDLARGE",
"HAZARDSMALL",
"HAZARDLARGE",
"HEALTHSMALL",
"HEALTHLARGE",
"ENERGY",
"STANDING",
"CAPFRT_STAND",
"CAPFRT_LOOT",
"FREIGHT_STAND",
"FREIGHT_REWARD",
"PIRATELOOT",
"PIRAT_LOOT_EASY",
"PIRAT_LOOT_MED",
"PIRAT_LOOT_HARD",
"POLICELOOT",
"TRAD_LOOT_EASY",
"TRAD_LOOT_MED",
"TRAD_LOOT_HARD",
"INTERIORPLANTS",
"WORD",
"PIRATE_BATTLE",
"PIRATE_FIGHT",
"RANDOM",
"NOREWARD",
"HYPER",
"PIRATE_BOUNTY1",
"PIRATE_BOUNTY2",
"PIRATE_BOUNTY3",
"PLANT_COMMODITY",
"PLANT_TECH",
"PLANT_FUEL",
"PLANT_PEARL",
"PLANT_GRAV",
"PLANT_SACVENOM",
"PLANT_BARREN",
"PLANT_LUSH",
"PLANT_CREATURE",
"PLANT_POOP",
"PLANT_RADIO",
"PLANT_SCORCHED",
"PLANT_SNOW",
"PLANT_TOXIC",
"FREIGHTERLOOT",
"PLANTER_CARBON",
"HEALTHFULL",
"PLANT_NIP",
"TECHFRAG_L",
"TECHFRAG_M",
"TECHFRAG_S",
"MONEY",
"MONEY_S",
"MONEY_M",
"MONEY_L",
"TECHDEBRIS",
"KILLED_CIV",
"PROC_PRODUCT",
"BUY_FRIGATE",
"FRIGATE_STATUS",
"PROC_PROD_CHEST",
"PROC_PROD_BONES",
"PROC_PROD_SCRAP",
"SPOREVENT",
"FLYTRAP",
"CRT_WEIRD",
"COLL_WEIRDSHELL",
"COLL_WEIRDHYDRO",
"COLL_WEIRDCUBE",
"COLL_CONTOURPOD",
"COLL_BONESPIRE",
"COLL_WEIRDSHARD",
"COLL_WEIRDBEAM",
"COLL_WEIRDENGIN",
"COLL_WEIRDBUBL",
"COLL_WEIRDHEX",
"COLL_WEIRDJOINT",
"DE_GEODE_TUT",
"DE_GEODE_GOLD",
"DE_GEODE_SPACE",
"DE_GEODE_CRYST",
"DE_GEODE_LAND",
"DE_GEODE_CAVE",
"DE_SCRAP_PART",
"DE_STORMCRYSTAL",
"DE_SALVAGE",
"DE_EYEPLANT",
"DE_SEAHORROR",
"DE_EYEBALL",
"DE_CLAMPEARL",
"DE_FISHCORE",
"DE_FIENDCORE",
"DE_VENTGEM",
"DE_URCHIN",
"DE_JELLY",
"DE_DEPOT",
"DE_PLANT_SMALL",
"DE_PLANT_MED",
"DE_PLANT_LARGE",
"DE_WATERPLANT_A",
"DE_WATERPLANT_S",
"DE_WATERPLANT_M",
"DE_WATERPLANT_L",
"DE_ROCK_SMALL",
"DE_ROCK_MED",
"DE_ROCK_LARGE",
"DE_GEM_R_SMALL",
"DE_GEM_R_MED",
"DE_GEM_R_LARGE",
"DE_GEM_B_SMALL",
"DE_GEM_B_MED",
"DE_GEM_B_LARGE",
"DE_GEM_Y_SMALL",
"DE_GEM_Y_MED",
"DE_GEM_Y_LARGE",
"DE_CAVE_MED",
"DE_CAVE_LARGE",
"DE_WATER_MED",
"DE_WATER_LARGE",
"DE_PLANT_SECOND",
"DE_PLANT_TOXIC",
"DE_PLANT_RADIO",
"DE_PLANT_DUSTY",
"DE_PLANT_LUSH",
"DE_PLANT_HOT",
"DE_PLANT_COLD",
"DE_ROCK_COLD",
"DE_ROCK_LUSH",
"DE_ROCK_DUSTY",
"DE_ROCK_HOT",
"DE_ROCK_TOXIC",
"DE_ROCK_RADIO",
"DE_ROCK_DEAD",
"DE_GEM_SECOND",
"DE_WATER_SECOND",
"DE_WATER_L_SEC",
"DE_CAVE_SECOND",
"DE_CAVE_GAS1",
"DE_CAVE_GAS2",
"DE_CAVE_GAS3",
"DE_GAS_PLANT",
"DE_RARE_ROCK",
"DE_RARE_HOT",
"DE_RARE_RADIO",
"DE_RARE_COLD",
"DE_RARE_DUSTY",
"DE_RARE_GOLD",
"DE_RARE_WATER",
"DE_RARE_CAVE",
"DE_TENTACLE",
"DE_SPOREVENT",
"DE_FLYTRAP",
"DE_COOK_LUSH",
"DE_COOK_HOT",
"DE_COOK_COLD",
"DE_COOK_DUST",
"DE_COOK_TOX",
"DE_COOK_RAD",
"DE_COOK_WEIRD",
"DE_COOK_ALL1",
"DE_COOK_ALL2",
"DE_COOK_ALL3",
"R_CHEF_JUDGE",
"R_NEXUS_CASH",
"R_PROC_FOSSIL",
"R_BAIT_BASIC",
"R_AMMO",
"R_CARBON",
"R_RUST",
"R_LIVINGSLIME",
"R_LAUNCHFUEL",
"R_POWERCELL",
"R_PRODFUEL2",
"R_KORVAXCUBE",
"R_NAVDATA_ONLY",
"R_STORMCRYSTAL",
"R_ASTEROID_MINS",
"R_OXYGEN_50",
"R_DAGGER",
"R_CATAPROD3",
"R_FARMPROD5",
"DIRT",
"FACT_PROD",
"E_REQUESTPAGE1",
"E_REQUESTPAGE2",
"T_REQUESTPAGE1",
"T_REQUESTPAGE2",
"W_REQUESTPAGE1",
"W_REQUESTPAGE2",
"R_DIVEHELMET",
"R_SEACHEST",
"R_WATERRUIN",
"R_DIG_CLUE",
"EARLY_TECH_SUIT",
"PROC_TECH_ONLY",
"PROC_TECH_ALL",
"PROC_TECH_SHIP",
"PROC_TECH_SUIT",
"PROC_TECH_WEAP",
"PROC_SHIP_ONLY",
"PROC_SUIT_ONLY",
"PROC_WEAP_ONLY",
"WEAPON",
"R_A1S9_HOT",
"R_A1S9_COLD",
"R_A1S9_RAD",
"R_A1S9_TOX",
"NAVDATA_EXO",
"NAVDATA_RARE",
"NAVDATA",
"R_DROPSCAN",
"TUT_GOODS",
"JUNK",
"ARTIFACTKEY",
"USEFUL_PROD",
"USEFUL_SUB",
"RECIPE_LIST",
"R_CAVEGRAVE",
"R_A1S6_WAR",
"R_A1S6_TRA",
"R_A1S6_EXP",
"TRA_WORD",
"EXP_WORD",
"WAR_WORD",
"ANOMALYTECH1",
"ANOMALYTECH2",
"ANOMALYTECH3",
"ANOMALYTECH4",
"ANOMALYTECH5",
"ANOMALYTECH6",
"ANOMALYTECH7",
"ANOMALYTECH8",
"ANOMALYTECH9",
"ANOMALYTECH10",
"ANOMALYTECH11",
"ANOMALYTECH12",
"ANOMALYTECH13",
"ANOMALYTECH14",
"ANOMALYTECH15",
"ANOMALYTECH16",
"SHIPSUIT",
"STD_INC_EXP",
"STD_DEC_EXP",
"STD_INC_TRA",
"STD_DEC_TRA",
"STD_INC_WAR",
"STD_DEC_WAR",
"SUBST_COMMOD",
"SUBST_TECH",
"SUBST_FUEL",
"PROD_TECH",
"PROD_FUEL",
"PROD_CUR",
"RECIP_PROD_TRAD",
"RECIP_PROD_TECH",
"RECIP_PROD_FUEL",
"TECH_ALL",
"TECH_SUIT",
"TECH_WEAPON",
"TECH_SHIP",
"DISTRESSSCAN",
"DAMAGE_TECH",
"REPAIR_TECH",
"FUEL1_SM",
"AMMO1_SM",
"HACK1_SM",
"DRUGS1_SM",
"FUEL1_ME",
"AMMO1_ME",
"HACK1_ME",
"DRUGS1_ME",
"FUEL1_LA",
"AMMO1_LA",
"HACK1_LA",
"DRUGS1_LA",
"TEACHWORD_EXP",
"TEACHWORD_TRA",
"TEACHWORD_WAR",
"GIVE_HYPERDRIVE",
"GIVE_ANTI",
"RECIP_ANTI",
"RECIP_FLUID",
"ATLAS",
"SCAN_A1S5",
"SCAN_1",
"R_GEKRELIC",
"R_VYKEENEFFIGY",
"R_KORVAXCASING",
"C_NIGHTCRYSTALS",
"C_ATLASSTONE",
"D_ATLASPASSV1",
"D_ATLASPASSV2",
"D_ATLASPASSV3",
"TEACHWORD_ATLAS",
"P_HYPERFUEL1",
"P_HACK1",
"P_GRAVBALL",
"P_ALBUMENPEARL",
"T_ARMOUR1",
"T_ARMOUR2",
"T_ARMOUR3",
"D_HYPERDRIVE1",
"D_HYPERDRIVE2",
"D_HYPERDRIVE3",
"FREIGHTER_TRANS",
"BUILDING_VISIT",
"SEC_MONEY",
"SEC_STARMAP",
"SEC_CRASHEDSHIP",
"SEC_STDLOW_WAR",
"SEC_STDLOW_TRA",
"SEC_STDLOW_EXP",
"SEC_STDHIGH_WAR",
"SEC_STDHIGH_TRA",
"SEC_STDHIGH_EXP",
"RECIP_NEW_COMP",
"RECIP_NEW_GAS",
"RECIP_NEW_PROD",
"RECIP_RARE_PROD",
"SEC_SCN_OUTPOST",
"SEC_SCN_FACT",
"SEC_SCN_TOWER",
"SEC_SCN_OBS",
"SHOW_CRASHSITE",
"R_TECHMISSION",
"R_CURIO9",
"R_CURIO7",
"R_CAVECUBE",
"SEC_SCN_HARV",
"TRADER_FIGHT",
"TRADER_LEAVE",
"R_CURIO8",
"EXP_DELICACY",
"TRA_DELICACY",
"WAR_DELICACY",
"PIRATES_DELAY",
"PIRATES_INSTANT",
"TRADER_SUB",
"TRADER_THANKS",
"TRADER_REP",
"R_GUILD_TAX1",
"R_GUILD_TAX2",
"R_GUILD_TAX3",
"R_GUILD_TAX4",
"R_TGUILD_MISS",
"R_TGUILD_GIFT1",
"R_TGUILD_GIFT2",
"R_TGUILD_GIFT3",
"R_TGUILD_GIFT4",
"R_EGUILD_MISS",
"R_EGUILD_GIFT1",
"R_EGUILD_GIFT2",
"R_EGUILD_GIFT3",
"R_EGUILD_GIFT4",
"R_WGUILD_MISS",
"R_WGUILD_GIFT1",
"R_WGUILD_GIFT2",
"R_WGUILD_GIFT3",
"R_WGUILD_GIFT4",
"TRADER_DO_TRADE",
"PLANETPROC_MISS",
"PROC_MISS_EARLY",
"R_PP_BIOME_FARM",
"R_PP_SCN_ARTI",
"R_LSUPPORTLARGE",
"R_LUSH1",
"R_TOXIC1",
"R_HOT1",
"R_RADIO1",
"R_COLD1",
"R_DUSTY1",
"R_LAND1",
"R_ASTEROID2",
"TRA_WORD_DIRECT",
"TRA_WORD_HELP",
"TRA_WORD_TRADE",
"TRA_WORD_LORE",
"TRA_WORD_TECH",
"TRA_WORD_THREAT",
"TRA_WORD_MISC",
"EXP_WORD_DIRECT",
"EXP_WORD_HELP",
"EXP_WORD_TRADE",
"EXP_WORD_LORE",
"EXP_WORD_TECH",
"EXP_WORD_THREAT",
"EXP_WORD_MISC",
"WAR_WORD_DIRECT",
"WAR_WORD_HELP",
"WAR_WORD_TRADE",
"WAR_WORD_LORE",
"WAR_WORD_TECH",
"WAR_WORD_THREAT",
"WAR_WORD_MISC",
"NPC_BUILD_GOTO",
"NPC_BUILD7",
"NPC_BUILD5",
"NPC_SCI_GOTO",
"NPC_SCI_GOTO1",
"NPC_VEHIC_GOTO",
"NPC_FARM_GOTO",
"NPC_WEAPON_GOTO",
"NPC_WEAPON1",
"NPC_WEAPON2",
"NPC_WEAPON3",
"NPC_WEAPON4",
"NPC_WEAPON5",
"NPC_WEAPON6",
"NPC_WEAPON7",
"NPC_WEAPON8",
"NPC_WEAPON9",
"NPC_WEAPON10",
"NPC_VEHICLE16S",
"NPC_VEHICLE16",
"NPC_VEHICLE15",
"NPC_VEHICLE14",
"NPC_VEHICLE13",
"NPC_VEHICLE12",
"NPC_VEHICLE11S",
"NPC_VEHICLE11",
"NPC_VEHICLE10",
"NPC_VEHICLE9",
"NPC_VEHICLE8",
"NPC_VEHICLE7",
"NPC_VEHICLE6",
"NPC_VEHICLE5S",
"NPC_VEHICLE5",
"NPC_VEHICLE4",
"NPC_VEHICLE3",
"NPC_VEHICLE2",
"NPC_VEHICLE1",
"NPC_FARM1",
"NPC_FARM2",
"NPC_FARM3",
"NPC_FARM4",
"NPC_FARM5",
"NPC_FARM6",
"NPC_FARM7",
"NPC_FARM8",
"NPC_FARM9",
"NPC_FARM10",
"NPC_SCIENCE1",
"NPC_SCIENCE2",
"NPC_SCIENCE3",
"NPC_SCIENCE4",
"NPC_SCIENCE5",
"NPC_SCIENCE6",
"NPC_SCIENCE7",
"NPC_SCIENCE8",
"NPC_SCIENCE9",
"NPC_SCIENCE10",
"NPC_BUILD1",
"NPC_BUILD2",
"NPC_BUILD3",
"NPC_BUILD4",
"NPC_BUILD6",
"NPC_BUILD8",
"NPC_BUILD9",
"NPC_BUILD10",
"HIRE_BUILDER",
"HIRE_WEAPONS",
"HIRE_FARMER",
"HIRE_VEHICLES",
"HIRE_SCIENTIST",
"NPC_BUILD11",
"RECIP_PROD_COMM",
"PROD_COMMOD",
"R_EXOTIC1",
"R_EXOTIC2",
"R_EXOTIC3",
"R_EXOTIC4",
"R_EXOTIC5",
"R_A1S6_GIVEMAP",
"TREE_BASICS",
"TREE_TECHBASICS",
"TREE_BASE",
"TREE_SPEC_BASE",
"TREE_SUIT",
"TREE_SHIP",
"TREE_WEAP",
"TREE_EXO",
"TREE_CRAFT",
"TREE_FRIGATE",
"R_CRASHSITE_REP",
"R_CRASHSITE_FLY",
"R_ENABLENEXUS",
"R_WAYPOINT",
"R_MONOLITH",
"R_UTECH_TOXIC",
"R_UTECH_HOT",
"R_UTECH_RADIO",
"R_UTECH_SNOW",
"R_SEEDS_LUSH",
"R_SEEDS_TOXIC",
"R_SEEDS_HOT",
"R_SEEDS_RADIO",
"R_SEEDS_SNOW",
"R_SEEDS_DUST",
"R_COMM4_FOUND",
"R_POLO_LINK",
"STARSEED",
"OPEN_BASE_SHOP",
"UPGRADE_BASE",
"R_NADA_PROGRESS",
"R_POLO_PROGRESS",
"R_NADA_JM",
"R_POLO_ACCEPT",
"R_POLO_DONE",
"BEACON_DUMMY",
"TUT_INGREDS",
"TUT_CRASH_SCAN",
"JETPACK_BOOST",
"REFRESH_HAZ",
"REFRESH_O2",
"SEC_DIRECTIONS",
"NEAR_SCAN",
"RANDOM_SCAN_A",
"RANDOM_SCAN_B",
"RANDOM_SCAN_C",
"RANDOM_SCAN_D",
"R_MSG_NEAR_SCAN",
"R_STARCHART_A",
"R_STARCHART_B",
"R_STARCHART_C",
"R_STARCHART_D",
"R_A1S6_MAP",
"REVEAL_TREASURE",
"TRIG_AP_10",
"TRIGGER_ACTIVE",
"R_A2S5_ARTDEAD",
"R_A2S5_ARTSIM",
"R_FACTHARD_WIN",
"R_FACTMED_WIN",
"REV_ATLAS_STA",
"REV_BLACK_HOLE",
"REV_ALL_BH",
"INC_ATLAS_PATH",
"FREE_EXPLORE",
"RUINSCAN",
"TELEPORT_BASE",
"TELEPORT_0",
"TELEPORT_1",
"TELEPORT_2",
"TELEPORT_3",
"START_PURCHASE",
"BEGIN_SALVAGE",
"CENTREJOURNEY1",
"CENTREJOURNEY2",
"CENTREJOURNEY3",
"CENTREJOURNEY4",
"PORTALRUNE1",
"PORTALRUNE2",
"PORTALRUNE3",
"PORTALRUNE4",
"PORTALRUNE5",
"PORTALRUNE6",
"PORTALRUNE7",
"PORTALRUNE8",
"PORTALRUNE9",
"PORTALRUNE10",
"PORTALRUNE11",
"PORTALRUNE12",
"PORTALRUNE13",
"PORTALRUNE14",
"PORTALRUNE15",
"PORTALRUNE16",
"C_ATLASSTONE1",
"C_ATLASSTONE2",
"C_ATLASSTONE3",
"C_ATLASSTONE4",
"C_ATLASSTONE5",
"C_ATLASSTONE6",
"C_ATLASSTONE7",
"C_ATLASSTONE8",
"C_ATLASSTONE9",
"C_ATLASSTONE10",
"PIRATE_APPEASE",
"PIRATE_REJECT",
"PIRATE_POLICE",
"ADVANCE_PORTAL",
"RESET_PORTAL",
"REVEAL_RUNES",
"REVEAL_PORTAL",
"REPAIR_COMPLETE",
"STORM",
"BASE_FLAG",
"BASE_PARTS",
"BASE_RAND_FLAG",
"BASE_RAND_LIGHT",
"BP_ACCESS",
"BP_BASE_TECH",
"BP_BASIC",
"BP_CUBES",
"BP_DECALS",
"BP_EXT_DECOR",
"BP_FARMING",
"BP_FRAMES",
"BP_GLASS",
"BP_INT_DECOR",
"BP_LIGHTS",
"BP_PLANET_TECH",
"BP_ROOMS",
"BP_STORAGE",
"BP_ALL",
"BP_FIRST_TECH",
"BP_SALVAGE_ONLY",
"BP_SALVAGE",
"EFIRST_WORD",
"TFIRST_WORD",
"WFIRST_WORD",
"SOLVE_MYSTERY",
"ADV_MYSTERY",
"BP_FIRST_MSG",
"R_COMM_UG_EASY",
"R_COMM_UG_HARD",
"CRASHCONT_M",
"CRASHCONT_S",
"CRASHCONT_A2S8",
"MB_STAND_GUILD",
"MB_STAND_HIGH",
"MB_STAND_MED",
"MB_STAND_LOW",
"MB_STAND_NEG",
"R_MB_LOW",
"R_MB_MED",
"R_MB_HIGH",
"R_MB_MEGA",
"FLEET_LOOT_SCAN",
"FLEET_HOLO_CAP",
"FLEET_HOLO_DMG",
"FLEET_NEXTDMG",
"FLEET_CONTINUE",
"FLEET_COMEHOME",
"FLEET_DAMAGED",
"FLEET_STATUS",
"FLEET_DEBRIEF",
"SHOW_ROUTES",
"AVOID_INTERVENE",
"INTERVN_SUCCESS",
"INTERVN_FAILURE",
"FLT_COMBAT_1",
"FLT_COMBAT_2",
"FLT_COMBAT_3",
"FLT_COMBAT_4",
"FLT_COMBAT_5",
"FLT_COMBAT_6",
"FLT_COMBAT_7",
"FLT_COMBAT_8",
"FLT_COMBAT_9",
"FLT_COMBAT_10",
"FLT_COMBAT_11",
"FLT_COMBAT_12",
"FLT_COMBAT_13",
"FLT_COMBAT_14",
"FLT_COMBAT_15",
"FLT_COMBAT_16",
"FLT_COMBAT_17",
"FLT_COMBAT_18",
"FLT_COMBAT_19",
"FLT_COMBAT_20",
"FLT_MINING_1",
"FLT_MINING_2",
"FLT_MINING_3",
"FLT_MINING_4",
"FLT_MINING_5",
"FLT_MINING_6",
"FLT_MINING_7",
"FLT_MINING_8",
"FLT_MINING_9",
"FLT_MINING_10",
"FLT_MINING_11",
"FLT_MINING_12",
"FLT_MINING_13",
"FLT_MINING_14",
"FLT_MINING_15",
"FLT_MINING_16",
"FLT_MINING_17",
"FLT_MINING_18",
"FLT_MINING_19",
"FLT_MINING_20",
"FLT_TRADE_1",
"FLT_TRADE_2",
"FLT_TRADE_3",
"FLT_TRADE_4",
"FLT_TRADE_5",
"FLT_TRADE_6",
"FLT_TRADE_7",
"FLT_TRADE_8",
"FLT_TRADE_9",
"FLT_TRADE_10",
"FLT_TRADE_11",
"FLT_TRADE_12",
"FLT_TRADE_13",
"FLT_TRADE_14",
"FLT_TRADE_15",
"FLT_TRADE_16",
"FLT_TRADE_17",
"FLT_TRADE_18",
"FLT_TRADE_19",
"FLT_TRADE_20",
"FLT_EXPLORE_1",
"FLT_EXPLORE_2",
"FLT_EXPLORE_3",
"FLT_EXPLORE_4",
"FLT_EXPLORE_5",
"FLT_EXPLORE_6",
"FLT_EXPLORE_7",
"FLT_EXPLORE_8",
"FLT_EXPLORE_9",
"FLT_EXPLORE_10",
"FLT_EXPLORE_11",
"FLT_EXPLORE_12",
"FLT_EXPLORE_13",
"FLT_EXPLORE_14",
"FLT_EXPLORE_15",
"FLT_EXPLORE_16",
"FLT_EXPLORE_17",
"FLT_EXPLORE_18",
"FLT_EXPLORE_19",
"FLT_EXPLORE_20",
"R_WIKI_1",
"R_WIKI_2",
"R_WIKI_3",
"R_WIKI_4",
"R_WIKI_5",
"R_WIKI_6",
"R_WIKI_7",
"R_WIKI_8",
"R_WIKI_9",
"R_WIKI_10",
"R_WIKI_11",
"R_WIKI_12",
"R_WIKI_13",
"R_WIKI_14",
"R_WIKI_15",
"R_WIKI_16",
"R_WIKI_17",
"R_WIKI_18",
"R_WIKI_19",
"R_WIKI_20",
"R_WIKI_21",
"R_WIKI_22",
"R_WIKI_23",
"R_WIKI_24",
"R_WIKI_25",
"R_WIKI_26",
"R_WIKI_27",
"R_WIKI_28",
"R_WIKI_29",
"R_WIKI_30",
"R_WIKI_31",
"R_WIKI_32",
"R_WIKI_33",
"R_WIKI_34",
"R_WIKI_35",
"R_WIKI_36",
"DEADDRONE",
"RARE_SPHERE",
"RARE_OBJECT",
"CRATE",
"BARREL",
"DROPPOD",
"DEBRIS",
"SENTINEL",
"MIXER_AMMO",
"MIXER_WARPFUEL",
"MIXER_SHIPFUEL",
"MIXER_HEAL",
"MIXER_SPACEHELP",
"MIXER_JETPACK",
"MIXER_MONEY",
"MIXER_TECH_1",
"MIXER_TECH_2",
"MIXER_TECH_3",
"MIXER_SCAN",
"MIXER_BREAKTECH",
"MIXER_STORM",
"MIXER_PIRATES",
"MIXER_WANTED",
"R_PP_CS_DIG",
"R_PP_CS_COMMS",
"R_PP_CS_RAID",
"R_PP_CS_BOUNTY",
"R_TRA_OBS_1",
"R_TRA_OBS_D_A_1",
"R_TRA_OBS_D_B_1",
"R_TRA_CS_1",
"R_TRA_CS_D_1",
"R_TRA_CS_3",
"R_TRA_CS_D_A_3",
"R_TRA_CS_D_B_3",
"R_TRA_CS_5_WEAP",
"R_TRA_CS_6",
"R_TRA_CS_D_6",
"R_TRA_CS_7",
"R_TRA_CS_D_A_7",
"R_TRA_CS_D_B_7",
"R_WAR_CS_2",
"R_WAR_CS_D_A_2",
"R_WAR_CS_D_B_2",
"R_WAR_CS_3",
"R_WAR_CS_D_3",
"R_WAR_CS_4",
"R_WAR_CS_D_A_4",
"R_WAR_CS_D_B_4",
"R_WAR_CS_5",
"R_WAR_CS_D_A_5",
"R_WAR_CS_D_B_5",
"R_WAR_CS_6",
"R_WAR_CS_D_6",
"R_WAR_CS_7",
"R_WAR_CS_D_A_7",
"R_WAR_CS_D_B_7",
"R_WAR_CS_8",
"R_WAR_CS_D_8",
"R_EXP_CS_2",
"R_EXP_CS_D_A_2",
"R_EXP_CS_D_B_2",
"R_EXP_CS_3",
"R_EXP_CS_D_3",
"R_EXP_CS_4",
"R_EXP_CS_D_4",
"R_EXP_CS_7",
"R_EXP_CS_D_7",
"R_EXP_CS_8",
"R_EXP_CS_D_A_8",
"R_EXP_CS_D_B_8",
"R_TRA_DEB_4",
"R_TRA_DEB_D_4",
"R_TRA_DEB_7",
"R_WAR_DEB_4",
"R_WAR_DEB_D_4",
"R_EXP_DEB_4",
"R_EXP_DEB_D_4",
"R_EXP_DEB_ST_8"
}

CATEGORY = {"NPC", "VEHICLE", "EXTRA", "NPC", "CREATURES", "VEHICLE", "SPACE", "BUILDINGS1", "BUILDINGS2", "COOKING", "CRYSTAL+ROCK", "NATURE", "EXTRA"}
SELECTED_CATEGORY = {"NPC", "VEHICLE", "EXTRA", "NPC", "CREATURES", "VEHICLE", "SPACE", "BUILDINGS1" }--, "BUILDINGS2", "COOKING", "CRYSTAL+ROCK", "NATURE", "EXTRA"}

SPAWN_TABLE_EXTENDED = 
{
["NPC"] =
{
"MODELS/TESTS/PHYSICSMESH.SCENE.MBIN",
"MODELS/TESTS/CHARACTERTESTS/ASTRO.SCENE.MBIN",
"MODELS/TESTS/COMBATTESTS/TARGET.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCFIFTH.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCFOURTH.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCGEK.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCKORVAX.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCNADA.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCPOLO.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCSPECIALSHOP.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCVYKEEN.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLAYERCHARACTER/PLAYERCHARACTER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/EXPLORER/ANOMALYEXPLORER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/EXPLORER/EXPLORER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/EXPLORER/EXPLORERIPAD.SCENE.MBIN",
"MODELS/PLANETS/NPCS/EXPLORER/EXPLORERSTAND.SCENE.MBIN",
"MODELS/PLANETS/NPCS/FOURTHRACE/FOURTHRACE.SCENE.MBIN",
"MODELS/PLANETS/NPCS/FOURTHRACE/HOLOEXPLORER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/FOURTHRACE/HOLONOONE.SCENE.MBIN",
"MODELS/PLANETS/NPCS/FOURTHRACE/HOLOSCEPTIC.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/ANOMALYLOWERORDER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDER.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDERBODY.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDERIPAD.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDERSIT.SCENE.MBIN",
"MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDERSTAND.SCENE.MBIN",
"MODELS/PLANETS/NPCS/WARRIOR/WARRIOR.SCENE.MBIN",
"MODELS/PLANETS/NPCS/WARRIOR/WARRIORSTAND.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/COMPUTER/ANOMALY_HOLOEXPLORER.SCENE.MBIN"
},

["CREATURES"] =
{
"MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPETWOLEGS.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/ANTELOPERIG/ACCESSORIES/CREATUREACCS.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BLOBRIG/BLOB.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BLOBRIG/BLOBTERRARIUM.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLY.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/CATRIG/CAT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/CATRIG/SIXLEGCAT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/COWRIG/COW.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/COWRIG/COWHINDLEGS.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/COWRIG/COWSWIM.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/COWRIG/SIXLEGGEDCOW.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/CLAM.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/FISHFIEND.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/FISHFIENDSMALL.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/GRABBYPLANT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/JELLYFISH.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/PROC_JELLYFISH.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/SMALLFISH.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FISH/PARTS/GRABBYPLANTEYE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FLYINGLIZARDRIG/FLYINGLIZARD.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/FLYINGSNAKE/FLYINGSNAKE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/GRUNTRIG/GRUNT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/RODENTRIG/RODENT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/RODENTRIG/RODENTSWIM.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SHARKRIG/SHARK.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SMALLBIRD/BIRD.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/FIEND.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/ROCKCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/ROCKSPIDER.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/SPIDER.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/SPIDERRIG/SPIDERFLOAT.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/STRIDERRIG/STRIDER.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/TREXRIG/TREX.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/TRICERATOPSRIG/TRICERATOPS.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/CRYSTALCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/GEMCREATURE.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/WEIRDBUTTERFLY.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG.SCENE.MBIN",
"MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIGGROUND.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/DIPLODOCUS/DIPLODOCUS.SCENE.MBIN"
},


["VEHICLE"] =
{
"MODELS/COMMON/SPACECRAFT/FIGHTERS/FIGHTER_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/SCIENTIFIC/SCIENTIFIC_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/DROPSHIPS/DROPSHIP_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/SHUTTLE/SHUTTLE_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/S-CLASS/S-CLASS_PROC.SCENE.MBIN",
"MODELS/TESTS/MATERIALTESTS/DECALPROJECTOR.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/BIKE/BIKE.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/BUGGY/BUGGY.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/HOVER/HOVERCRAFT.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/ROVER/ROVER.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/SUBMARINE/SUBMARINE.SCENE.MBIN",
"MODELS/COMMON/VEHICLES/WHEELEDBIKE/WHEELEDBIKE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/POLICE/POLICESHIP.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/DRONE/DRONESHIP.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/DRONE/HISTORY/DRONESHIP.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/CORRUPTEDDRONE.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/DRONE.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/DRONEARMOURED.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/QUADRUPED.SCENE.MBIN",
"MODELS/COMMON/ROBOTS/WALKER.SCENE.MBIN",
"MODELS/COMMON/HMD/HMDDRONE.SCENE.MBIN"
},

["SPACE"] =
{
"MODELS/SPACE/ANOMALY/ANOMALY.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/ATLASSTATION.SCENE.MBIN",
"MODELS/SPACE/NEXUS/NEXUS.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/SPACESTATION.SCENE.MBIN",
"MODELS/SPACE/SPACESTATION/SPACESTATION_ABANDONED.SCENE.MBIN",
"MODELS/SPACE/BLACKHOLE/BLACKHOLE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/CAPITALFREIGHTER_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTERSMALL_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTERTINY_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTER_A.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/FREIGHTER_PROC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/COMBATFRIGATE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/DIPLOMATICFRIGATE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/INDUSTRIALFRIGATE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/SCIENCEFRIGATE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/SUPPORTFRIGATE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLOCOMBAT.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLODIPLOMATIC.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLOINDUSTRIAL.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLOSCIENCE.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/FRIGATES/HOLOGRAMFRIGATES/HOLOSUPPORT.SCENE.MBIN",
"MODELS/COMMON/SPACECRAFT/POLICE/POLICEFREIGHTER.SCENE.MBIN"
},

["EXTRA"] =
{
"MODELS/COMMON/WEAPONS/MULTITOOL/MULTITOOL.SCENE.MBIN",
"MODELS/COMMON/HMD/TOUCH/TOUCHCONTROLLER_LEFT.SCENE.MBIN",
"MODELS/COMMON/HMD/TOUCH/TOUCHCONTROLLER_RIGHT.SCENE.MBIN",
"MODELS/UI/WORLD/BASEPROJECTOR.SCENE.MBIN",
"MODELS/COMMON/PLAYER/SPACEGRAVE.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/PLAYER/PLAYERGRAVE.SCENE.MBIN",
"MODELS/COMMON/PLAYER/PLACEMARKER.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/TECH/SHIELD.SCENE.MBIN",
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/SERVERROOM/SERVER.SCENE.MBIN",
"MODELS/COMMON/PROJECTILES/CHARGEDENERGYBALL.SCENE.MBIN",
"MODELS/SPACE/NEXUS/PARTS/CORE/MECHANICALCORE.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/PATHDISK.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/ATLASCORE/ATLASCORE.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ORBS/BLUEORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ORBS/GREENORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ORBS/REDORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ORBS/WHITEORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_1_INTERACTION/ENDING_1_INTERACTION.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_1_INTERACTION/INTERACTIONCORE.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/INTERACTIONCORE.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_2_INTERACTION/ENDING_2_INTERACTION.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/INTERACTIONSTONE/INTERACTIONSTONE_1.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/PATHORB/PATHORB.SCENE.MBIN",
"MODELS/SPACE/ATLASSTATION/MODULARPARTS/INTERIOR/ENDING_1_INTERACTION/ATLASSTONE.SCENE.MBIN"
},

["BUILDINGS1"] =
{
"MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PORTAL/PORTAL.SCENE.MBIN",
},

["BUILDINGS2"] =
{
},

["COOKING"] =
{
},

["CRYSTAL+ROCK"] =
{
},

["NATURE"] =
{
}
}

GcFrigateInteractionAction 	= { "Repair", "UpdateDamagedComponents", "CargoPhoneCall"}
NodeActiveState 			= {"Activate", "Deactivate", "Toggle", "Add", "Remove", "RemoveChildren"}
InteractionAction 			= {"PressButton", "HoldButton", "Shoot"}
PlayerNearbyEventType 		= {"None", "Fire", "InShip", "OnFoot", "OnFootOutside", "Upload"}

ANIM_TEMPLATE_ALL = ""
QUICK_ACTION_BUTTON_ALL = ""
ACTION_TRIGGER_COMPONENT = ""
NEW_EMOTES_ALL = ""
ACTION_TRIGGER_ALL = ""

ADD_FILES_TABLE = {}
SPAWN_ENTITY_ATTACHMENTS = ""
ENTITY_ATTACHMENT_ALL = ""
SCENE_REF_FOR_SIMPLEINTERACTION = ""

ACTION_TRIGGER_HARD_LIMIT = 528 --32(32+1)/2
ACTION_TRIGGER_LIMIT = 32

EMOTE_GENERIC_ICON = "TEXTURES/UI/FRONTEND/ICONS/QUICKMENU/EMOTES/WONDER.DDS"
EMOTE_GENERIC_ICON_HAPPY = "TEXTURES/UI/FRONTEND/ICONS/QUICKMENU/EMOTES/LAUGH.DDS"
EMOTE_GENERIC_ICON_ANGRY = "TEXTURES/UI/FRONTEND/ICONS/QUICKMENU/EMOTES/NEGATIVE.DDS"
EMOTE_GENERIC_ICON_GREET = "TEXTURES/UI/FRONTEND/ICONS/QUICKMENU/EMOTES/WAVE.DDS"
NEW_EMOTE_TABLE =
{
	{ ["TITLE"]="Fake Death", ["ANIM"]="0H_DEATH", ["ICON"]="TEXTURES/UI/FRONTEND/ICONS/WIKI/COMBATHEADER.DDS" },
	{ ["TITLE"]="PANIC!", ["ANIM"]="0H_FALL_PANIC", ["ICON"]=EMOTE_GENERIC_ICON },
	{ ["TITLE"]="Happy 1", ["ANIM"]="0H_HAPPY_01", ["ICON"]=EMOTE_GENERIC_ICON_HAPPY },
	{ ["TITLE"]="Happy 2", ["ANIM"]="0H_HAPPY_02", ["ICON"]=EMOTE_GENERIC_ICON_HAPPY },
	{ ["TITLE"]="Happy 3", ["ANIM"]="0H_HAPPY_03", ["ICON"]=EMOTE_GENERIC_ICON_HAPPY },
	{ ["TITLE"]="Happy 4", ["ANIM"]="0H_HAPPY_04", ["ICON"]=EMOTE_GENERIC_ICON_HAPPY },
	{ ["TITLE"]="Happy 5", ["ANIM"]="0H_HAPPY_05", ["ICON"]=EMOTE_GENERIC_ICON_HAPPY },
	{ ["TITLE"]="Happy 6", ["ANIM"]="0H_HAPPY_06", ["ICON"]=EMOTE_GENERIC_ICON_HAPPY },
	{ ["TITLE"]="Happy 7", ["ANIM"]="0H_HAPPY_07", ["ICON"]=EMOTE_GENERIC_ICON_HAPPY },
	{ ["TITLE"]="Happy 8", ["ANIM"]="0H_HAPPY_08", ["ICON"]=EMOTE_GENERIC_ICON_HAPPY },
	{ ["TITLE"]="Angry 1", ["ANIM"]="0H_ANGRY_01", ["ICON"]=EMOTE_GENERIC_ICON_ANGRY },
	{ ["TITLE"]="Angry 2", ["ANIM"]="0H_ANGRY_02", ["ICON"]=EMOTE_GENERIC_ICON_ANGRY },
	{ ["TITLE"]="Angry 3", ["ANIM"]="0H_ANGRY_03", ["ICON"]=EMOTE_GENERIC_ICON_ANGRY },
	{ ["TITLE"]="Angry 4", ["ANIM"]="0H_ANGRY_04", ["ICON"]=EMOTE_GENERIC_ICON_ANGRY },
	{ ["TITLE"]="Greet 1", ["ANIM"]="0H_GREET_01", ["ICON"]=EMOTE_GENERIC_ICON_GREET },
	{ ["TITLE"]="Greet 2", ["ANIM"]="0H_GREET_02", ["ICON"]=EMOTE_GENERIC_ICON_GREET },
	{ ["TITLE"]="Greet 3", ["ANIM"]="0H_GREET_03", ["ICON"]=EMOTE_GENERIC_ICON_GREET },
	{ ["TITLE"]="Greet 4", ["ANIM"]="0H_GREET_04", ["ICON"]=EMOTE_GENERIC_ICON_GREET },
	{ ["TITLE"]="Greet 5", ["ANIM"]="0H_GREET_05", ["ICON"]=EMOTE_GENERIC_ICON_GREET },
	{ ["TITLE"]="Greet 6", ["ANIM"]="0H_GREET_06", ["ICON"]=EMOTE_GENERIC_ICON_GREET },
	{ ["TITLE"]="Greet 7", ["ANIM"]="0H_GREET_07", ["ICON"]=EMOTE_GENERIC_ICON_GREET },
	{ ["TITLE"]="Slide", ["ANIM"]="0H_SLIDE_F", ["ICON"]=EMOTE_GENERIC_ICON },
	{ ["TITLE"]="Land Float", ["ANIM"]="0H_SWIM_IDLE", ["ICON"]=EMOTE_GENERIC_ICON },
	{ ["TITLE"]="Land Swim", ["ANIM"]="0H_SWIM_F", ["ICON"]=EMOTE_GENERIC_ICON },
	{ ["TITLE"]="Interact With Console", ["ANIM"]="0H_INT_CNSL_IN", ["ICON"]="TEXTURES/UI/FRONTEND/ICONS/QUICKMENU/EMOTES/POINT.DDS" },
	{ ["TITLE"]="Gather", ["ANIM"]="0H_INT_GATH_IN", ["ICON"]=EMOTE_GENERIC_ICON },
}

ACTION_SELECTION_LIGHT = --QOL version of the mod
{
"TELEPORT_BASE",
"R_ENABLENEXUS",
"MIXER_SPACEHELP",
"MIXER_SCAN"	
}

ACTION_TABLE =
{
	["TELEPORT_BASE"] = 
	{ 
		["TITLE"] = "Teleport to Base", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/BANNERICONS/BANNERICON.WARP.DDS"
	},
	["R_ENABLENEXUS"] = 
	{ 
		["TITLE"] = "Enable Nexus", 
		["ICON"] = "TEXTURES/UI/HUD/ICONS/BUILDINGS/NEXUS.DDS" 
	},
	["MIXER_STORM"] = 
	{ 
		["TITLE"] = "Trigger Storm", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/DISCOVERY/PLANETDATA.WEATHER.DDS" 
	},
	["ENT_SHIP"] = 
	{ 
		["TITLE"] = "Custom Ship Exchange", 
		["ICON"] = "TEXTURES/UI/HUD/MENUS/ICON.SHIP.DDS" 
	},
	["ENT_SHIP_PC"] = 
	{ 
		["TITLE"] = "Custom Ship Exchange", 
		["ICON"] = "TEXTURES/UI/HUD/MENUS/ICON.SHIP.DDS" 
	},
	["MIXER_AMMO"] = 
	{ 
		["TITLE"] = "Ammo", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/U4PRODUCTS/PRODUCT.AMMO.DDS"
	},
	["MIXER_WARPFUEL"] = 
	{ 
		["TITLE"] = "Warp Fuel", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/VEHICLEFUEL.DDS"
	},
	["MIXER_SHIPFUEL"] = 
	{ 
		["TITLE"] = "Ship Fuel", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/TECHNOLOGY/VEHICLEFUEL.DDS"
	},
	["MIXER_HEAL"] = 
	{ 
		["TITLE"] = "Heal", 
		["ICON"] = "TEXTURES/UI/HUD/HEALTHICON.DDS"
	},
	["MIXER_SPACEHELP"] = 
	{ 
		["TITLE"] = "Space Help", 
		["ICON"] = "TEXTURES/UI/HUD/SPACESHIP/INCASSIST.DDS"
	},
	["MIXER_JETPACK"] = 
	{ 
		["TITLE"] = "Jetpack Boost", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/STATS/STATS.WEAPON.JETPACK.DDS"
	},
	["MIXER_MONEY"] = 	
	{ 
		["TITLE"] = "Money", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/RANK/RANK.MONEY.DDS"
	},
	["MIXER_TECH_1"] = 	
	{ 
		["TITLE"] = "Tech 1", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/CATEGORIES/UPGRADECAT.GENERIC.DDS"
	},
	["MIXER_TECH_2"] = 	
	{ 
		["TITLE"] = "Tech 2", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/CATEGORIES/UPGRADECAT.GENERIC.DDS"
	},
	["MIXER_TECH_3"] = 
	{ 
		["TITLE"] = "Tech 3", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/CATEGORIES/UPGRADECAT.GENERIC.DDS"
	},
	["MIXER_SCAN"] = 	
	{ 
		["TITLE"] = "Scan near Building", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/STATS/STATS.SHIP.SCAN.DDS "
	},
	["MIXER_PIRATES"] = 	
	{ 
		["TITLE"] = "Pirates", 
		["ICON"] = "TEXTURES/UI/HUD/ICONS/PIRATE.SKULL.DDS"
	},
	["MIXER_WANTED"] = 	
	{ 
		["TITLE"] = "Wanted Level", 
		["ICON"] = "TEXTURES/UI/HUD/WANTEDICON.DDS"
	},
	["Save"] = 
	{ 
		["TITLE"] = "Save", 
		["ICON"] = "TEXTURES/UI/HUD/ICONS/PLAYER/SAVE.DDS" 
	},
	["Portal"] = 
	{ 
		["TITLE"] = "Portal", 
		["ICON"] = "TEXTURES/UI/FRONTEND/ICONS/BANNERICONS/BANNERICON.PORTAL.DDS"
	},
	["GcCameraShakeAction"] = 
	{ 
		["TITLE"] = "Earthquake", 
		["ICON"] = GENERIC_BUTTON_ICON 
	},
	["GcScareCreaturesAction"] = 
	{ 
		["TITLE"] = "Scare Creatures", 
		["ICON"] = "TEXTURES/UI/HUD/EYE.CREATURE.DDS"
	},
	["GcWarpAction"] = 
	{ 
		["TITLE"] = "Black Hole Warp", 
		["ICON"] = "TEXTURES/UI/HUD/ICONS/MISSIONS/MISSION.BLACKHOLE.DDS"
	},
	["GcFrigateInteractionAction"] = 
	{ 
		["TITLE"] = "Frigate Interaction", 
		["ICON"] = GENERIC_BUTTON_ICON
	},
	["GENERIC"] = 
	{ 
		["TITLE"] = "", 
		["ICON"] = GENERIC_BUTTON_ICON 
	},
	["GENERIC"] = 
	{ 
		["TITLE"] = "", 
		["ICON"] = GENERIC_BUTTON_ICON 
	},
	["GENERIC"] = 
	{ 
		["TITLE"] = "", 
		["ICON"] = GENERIC_BUTTON_ICON 
	}
	--[""] = { ["TITLE"] = "", ["ICON"] = GENERIC_BUTTON_ICON }
}

-- ACTION_TABLE =
-- {
-- TEXTURES/UI/FRONTEND/COMPONENTS/POWERSYMBOL.DDS
-- TEXTURES/UI/FRONTEND/ICONS/STATS/STATS.SUIT.PROTECTION.DDS
-- TEXTURES/UI/FRONTEND/COMPONENTS/STAR.DDS
-- TEXTURES/UI/FRONTEND/ICONS/ENERGY.DDS
-- TEXTURES/UI/FRONTEND/ICONS/STAR.DDS
-- TEXTURES/UI/FRONTEND/ICONS/BANNERICONS/BANNERICON.SHIELD.DDS
-- }
	-- ["NPC"]="TEXTURES/UI/HUD/ICONS/TIPSCREENSHOTS/NPCS.DDS", 
	-- ["CREATURES"]="TEXTURES/UI/HUD/EYE.CREATURE.DDS", 
	-- ["VEHICLE"]="TEXTURES/UI/HUD/MENUS/ICON.SHIP.DDS",
	-- ["SPACE"]="TEXTURES/UI/HUD/ICONS/TIPSCREENSHOTS/SPACESTATION.DDS", 
	-- ["BUILDINGS1"]="TEXTURES/UI/FRONTEND/ICONS/BANNERICONS/BANNERICON.PORTAL.DDS", 
	-- ["BUILDINGS2"]="TEXTURES/UI/FRONTEND/ICONS/NOTIFICATIONS/ICON.BUILDING.DDS",
	-- ["COOKING"]="TEXTURES/UI/FRONTEND/ICONS/WIKI/WIKI.COOKING.ON.DDS",
	-- ["CRYSTAL+ROCK"]="TEXTURES/UI/FRONTEND/ICONS/PRODUCTS/PRODUCT.ELEMENT.CRYSTAL1.DDS",
	-- ["NATURE"]="TEXTURES/UI/HUD/ICONS/MISSIONS/TREESCAN.DDS",
	-- ["EXTRA"]="TEXTURES/UI/FRONTEND/ICONS/GAMEMODE/STAR.DDS"

ACTION_TYPE = {"REWARD", "CUSTOM_REWARD", "SIMPLE_INTERACTION", "INTERACTION", "ENTITY_ACTION", "QUICK_MENU_ACTION", "INPUT_ACTION"} --InputActions
ACTION_TABLES = 
{
	["REWARD"]=REWARDS, 
	["CUSTOM_REWARD"]=REWARD_TYPE, 
	["SIMPLE_INTERACTION"]=SimpleInteractionType, 
	["INTERACTION"]=InteractionType, 
	["ENTITY_ACTION"]=ACTION, 
	["QUICK_MENU_ACTION"]=QuickMenuActions,
	["INPUT_ACTION"]=QuickMenuActions
}

function RequestActionType(ID)
	if string.find(ID, "/") then return "SPAWNER" end
	for i=1,#ACTION_TYPE,1 do
		for j=1,#ACTION_TABLES[ACTION_TYPE[i]],1 do
			if ID == ACTION_TABLES[ACTION_TYPE[i]][j] then 
				return ACTION_TYPE[i]
			end
		end
	end
end

function CreateQuickActionMenuEntry(BUTTON_TITLE, ANIM_ID, ICON)
QUICK_ACTION_BUTTON_TEMPLATE =
[[
    <Property value="GcPlayerEmote.xml">
      <Property name="Title" value="]] .. BUTTON_TITLE .. [[" />
      <Property name="ChatText" value="" />
      <Property name="ChatUsesPrefix" value="False" />
      <Property name="AnimationName" value="]] .. ANIM_ID .. [[" />
      <Property name="Icon" value="TkTextureResource.xml">
        <Property name="Filename" value="]] .. ICON .. [[" />
      </Property>
      <Property name="LinkedSpecialID" value="" />
      <Property name="LoopAnimUntilMov" value="" />
      <Property name="CloseMenuOnSelect" value="False" />
      <Property name="GekAnimationName" value="" />
      <Property name="GekLoopAnimUntilMove" value="" />
      <Property name="AvailableUnderwater" value="False" />
      <Property name="RidingAnimationName" value="" />
    </Property>
    <Property value="GcPlayerEmote.xml">
      <Property name="Title" value="]] .. BUTTON_TITLE .. [[" />
      <Property name="ChatText" value="" />
      <Property name="ChatUsesPrefix" value="False" />
      <Property name="AnimationName" value="]] .. ANIM_ID .. [[" />
      <Property name="Icon" value="TkTextureResource.xml">
        <Property name="Filename" value="]] .. ICON .. [[" />
      </Property>
      <Property name="LinkedSpecialID" value="" />
      <Property name="LoopAnimUntilMov" value="" />
      <Property name="CloseMenuOnSelect" value="False" />
      <Property name="GekAnimationName" value="" />
      <Property name="GekLoopAnimUntilMove" value="" />
      <Property name="AvailableUnderwater" value="True" />
      <Property name="RidingAnimationName" value="" />
    </Property>	
]]
return QUICK_ACTION_BUTTON_TEMPLATE
end

-------------CUSTOM SHIP-------------------------------

CUSTOM_GENERICREWARD_ALL = ""

function CreateCustomShipRewardEntry(REWARD_ID, SHIP_SEED, SHIPTYPE)
local GENERIC_REWARD_ENTRY =
[[
    <Property value="GcGenericRewardTableEntry.xml">
      <Property name="Id" value="]] .. REWARD_ID .. [[" />
      <Property name="Common" value="GcRewardTableItemList.xml">
        <Property name="RewardChoice" value="GiveAll" />
        <Property name="OverrideZeroSeed" value="False" />
        <Property name="List">
          <Property value="GcRewardTableItem.xml">
            <Property name="PercentageChance" value="100" />
			  <Property name="Reward" value="GcRewardSpecificShip.xml">
				<Property name="ShipResource" value="GcResourceElement.xml">
				  <Property name="Filename" value="]] .. SHIPTYPE .. [[" />
				  <Property name="Seed" value="GcSeed.xml">
					<Property name="Seed" value="]] .. SHIP_SEED .. [[" />
					<Property name="UseSeedValue" value="True" />
				  </Property>
				  <Property name="AltId" value="" />
				  <Property name="ProceduralTexture" value="TkProceduralTextureChosenOptionList.xml">
					<Property name="Samplers" />
				  </Property>
				</Property>
				<Property name="ShipLayout" value="GcInventoryLayout.xml">
				  <Property name="Slots" value="48" />
				  <Property name="Seed" value="GcSeed.xml">
					<Property name="Seed" value="1" />
					<Property name="UseSeedValue" value="True" />
				  </Property>
				  <Property name="Level" value="1" />
				</Property>
				<Property name="ShipInventory" value="GcInventoryContainer.xml">
				  <Property name="Slots">
					<Property value="GcInventoryElement.xml">
					  <Property name="Type" value="GcInventoryType.xml">
						<Property name="InventoryType" value="Technology" />
					  </Property>
					  <Property name="Id" value="LAUNCHER" />
					  <Property name="Amount" value="0" />
					  <Property name="MaxAmount" value="300" />
					  <Property name="DamageFactor" value="0" />
					  <Property name="FullyInstalled" value="True" />
					  <Property name="Index" value="GcInventoryIndex.xml">
						<Property name="X" value="-1" />
						<Property name="Y" value="-1" />
					  </Property>
					</Property>
					<Property value="GcInventoryElement.xml">
					  <Property name="Type" value="GcInventoryType.xml">
						<Property name="InventoryType" value="Technology" />
					  </Property>
					  <Property name="Id" value="SHIPJUMP1" />
					  <Property name="Amount" value="0" />
					  <Property name="MaxAmount" value="100" />
					  <Property name="DamageFactor" value="0" />
					  <Property name="FullyInstalled" value="True" />
					  <Property name="Index" value="GcInventoryIndex.xml">
						<Property name="X" value="-1" />
						<Property name="Y" value="-1" />
					  </Property>
					</Property>
					<Property value="GcInventoryElement.xml">
					  <Property name="Type" value="GcInventoryType.xml">
						<Property name="InventoryType" value="Technology" />
					  </Property>
					  <Property name="Id" value="SHIPSHIELD" />
					  <Property name="Amount" value="200" />
					  <Property name="MaxAmount" value="200" />
					  <Property name="DamageFactor" value="0" />
					  <Property name="FullyInstalled" value="True" />
					  <Property name="Index" value="GcInventoryIndex.xml">
						<Property name="X" value="-1" />
						<Property name="Y" value="-1" />
					  </Property>
					</Property>
					<Property value="GcInventoryElement.xml">
					  <Property name="Type" value="GcInventoryType.xml">
						<Property name="InventoryType" value="Technology" />
					  </Property>
					  <Property name="Id" value="SHIPGUN1" />
					  <Property name="Amount" value="1000" />
					  <Property name="MaxAmount" value="1000" />
					  <Property name="DamageFactor" value="0" />
					  <Property name="FullyInstalled" value="True" />
					  <Property name="Index" value="GcInventoryIndex.xml">
						<Property name="X" value="-1" />
						<Property name="Y" value="-1" />
					  </Property>
					</Property>
					<Property value="GcInventoryElement.xml">
					  <Property name="Type" value="GcInventoryType.xml">
						<Property name="InventoryType" value="Technology" />
					  </Property>
					  <Property name="Id" value="HYPERDRIVE" />
					  <Property name="Amount" value="24" />
					  <Property name="MaxAmount" value="120" />
					  <Property name="DamageFactor" value="0" />
					  <Property name="FullyInstalled" value="True" />
					  <Property name="Index" value="GcInventoryIndex.xml">
						<Property name="X" value="-1" />
						<Property name="Y" value="-1" />
					  </Property>
					</Property>
					<Property value="GcInventoryElement.xml">
					  <Property name="Type" value="GcInventoryType.xml">
						<Property name="InventoryType" value="Technology" />
					  </Property>
					  <Property name="Id" value="SHIPLAS1" />
					  <Property name="Amount" value="1000" />
					  <Property name="MaxAmount" value="1000" />
					  <Property name="DamageFactor" value="0" />
					  <Property name="FullyInstalled" value="True" />
					  <Property name="Index" value="GcInventoryIndex.xml">
						<Property name="X" value="-1" />
						<Property name="Y" value="-1" />
					  </Property>
					</Property>
				  </Property>
				  <Property name="ValidSlotIndices" />
				  <Property name="Class" value="GcInventoryClass.xml">
					<Property name="InventoryClass" value="S" />
				  </Property>
				  <Property name="SubstanceMaxStorageMultiplier" value="0" />
				  <Property name="ProductMaxStorageMultiplier" value="0" />
				  <Property name="BaseStatValues" />
				  <Property name="SpecialSlots" />
				  <Property name="Width" value="0" />
				  <Property name="Height" value="0" />
				  <Property name="IsCool" value="False" />
				  <Property name="Version" value="0" />
				</Property>
			  </Property>
            <Property name="LabelID" value="" />
          </Property>
        </Property>
      </Property>
    </Property> 
]]
return GENERIC_REWARD_ENTRY
end

RANDOMSEED_INIT = false
function GetSeed()
	local SEED = "0x"
	local HEX = {"0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"}
	if not RANDOMSEED_INIT then
		math.randomseed(77*os.time())
		math.random() math.random() math.random()
		RANDOMSEED_INIT = true
	end
	for i=1,16,1 do
		SEED = SEED .. HEX[math.random(1, #HEX)]
	end
	return SEED
end

function HexToDec(number)
	if type(number) == "number" then return number
	elseif string.find(tostring(number),"0x") then return tonumber(number)
	else return tonumber(number,16) end
end

SHIP_TYPE = { "FIGHTER", "DROPSHIP", "SCIENTIFIC", "SHUTTLE", "ROYAL" }

SHIP_TYPE_PATH = 
{
	["FIGHTER"]="MODELS/COMMON/SPACECRAFT/FIGHTERS/FIGHTER_PROC.SCENE.MBIN",
	["DROPSHIP"]="MODELS/COMMON/SPACECRAFT/DROPSHIPS/DROPSHIP_PROC.SCENE.MBIN",
	["SCIENTIFIC"]="MODELS/COMMON/SPACECRAFT/SCIENTIFIC/SCIENTIFIC_PROC.SCENE.MBIN",
	["SHUTTLE"]="MODELS/COMMON/SPACECRAFT/SHUTTLE/SHUTTLE_PROC.SCENE.MBIN",
	["ROYAL"]="MODELS/COMMON/SPACECRAFT/S-CLASS/S-CLASS_PROC.SCENE.MBIN"
}

NUMBER_OF_SHIP_SEEDS_DEFAULT =
{
	["FIGHTER"]		=	3,
	["DROPSHIP"] 	=	3,
	["SCIENTIFIC"]	= 	3,
	["SHUTTLE"]		=   3,
	["ROYAL"]		=   3
}

SHIP_SEED_LIST = --Add your own seeds here, 200 additional random seeds per ship type get generated too
{
	["FIGHTER"] =
	{
		"-4266666232903262234", --HORIZOSHIP
		"-8174559354674307366" 	--ALPHAVSHIP
		
	}, 
	["DROPSHIP"] =
	{
	
	},
	["SCIENTIFIC"] =
	{
		
	},
	["SHUTTLE"] =
	{
		
	}, 
	["ROYAL"] =
	{
		
	}
}

MY_SHIP_SEED_LIST =
{
	["FIGHTER"] =
	{
		"0x8E12667E612EC1A8",
		"0x0469079B58527FAC",
		"0x2ed0b7e8773e6959",
		"0x5243aac12ced95a2",
		"0x646abde861bb4790",
		"0x6672cffd8aeb2da8",
		"0x8B368967CED50C9C",
		"0xc82dbd4a5f1f4191",
		"0xdc4f7dfc3db6cc3b",
		"0xe9a6ce92bacc8b3a",
		"0xef22a881f0d6f86e",
		"0xb88d1d41ebd70b00"
	}, 
	["DROPSHIP"] =
	{
		"0x000000000000001b",
		"0x3ce7f4403f778b7e",
		"0x3ec3bea6ab51b0d",
		"0x62DE31604ECF844",
		"0xae09769f089b0309",
		"0xD27D6CC673D4FE4C",
		"0x890ecf651b18ee1e",
		"0xD70BF9B7144DA9BF"
	},
	["SCIENTIFIC"] =
	{
		
	},
	["SHUTTLE"] =
	{
		
	}, 
	["ROYAL"] =
	{
		"0x14a83398853af22f",
		"0x66c2ba46dcfbf4c3",
		"0xc688372a1012811b",
		"0xca47d32074d80110",
		"0xea7a77aa96f8b7df",
		"0xfe3ec7be5c555923"		
	}
}

SHIP_SEED_LIST = MY_SHIP_SEED_LIST
ACTION_TRIGGER_SEGMENTS = {}
ACTION_TRIGGER_SEGMENT_COUNT = 1

ACTION_TRIGGER_HARD_LIMIT 	= 528 --32(32+1)/2
ACTION_TRIGGER_LIMIT 	= 32
SHIP_REWARD_COUNT_LIMIT_REF = 1

function AddShipsRewardsToQuickActionMenu()
	local SHIP_REWARD_COUNT = 1
	local SHIP_REWARD_ID = ""
	local Seed = ""
	for i=1,#SHIP_TYPE,1 do
		if ENABLE_USER_SHIP_SEEDS then
			for j=1,#SHIP_SEED_LIST[SHIP_TYPE[i]],1 do
				if SHIP_REWARD_COUNT > ACTION_TRIGGER_HARD_LIMIT then break end
				Seed = SHIP_SEED_LIST[SHIP_TYPE[i]][j]
				if string.len(Seed)<16 or string.find(Seed,"0x") then Seed = HexToDec(Seed) end
				SHIP_REWARD_ID = "CUSTOM_SHIP_" .. SHIP_REWARD_COUNT
				CUSTOM_GENERICREWARD_ALL = CUSTOM_GENERICREWARD_ALL .. CreateCustomShipRewardEntry(SHIP_REWARD_ID, Seed, SHIP_TYPE_PATH[SHIP_TYPE[i]])
				ANIM_TEMPLATE_ALL = ANIM_TEMPLATE_ALL .. CreateAnimEntry(SHIP_REWARD_ID)
				ACTION_TRIGGER_ALL = ACTION_TRIGGER_ALL .. CreateActionTriggerRewardEntry(SHIP_REWARD_ID, SHIP_REWARD_ID)
				QUICK_ACTION_BUTTON_ALL = QUICK_ACTION_BUTTON_ALL .. CreateQuickActionMenuEntry(SHIP_REWARD_COUNT .. "." .. string.sub(SHIP_TYPE[i],1,7) .. ": " .. Seed, SHIP_REWARD_ID, "TEXTURES/UI/HUD/MENUS/ICON.SHIP.DDS")	
				if SHIP_REWARD_COUNT_LIMIT_REF >= ACTION_TRIGGER_LIMIT then 
					table.insert(ACTION_TRIGGER_SEGMENTS, ACTION_TRIGGER_ALL) 
					ACTION_TRIGGER_ALL = ""
					ACTION_TRIGGER_LIMIT = ACTION_TRIGGER_LIMIT - 1
					SHIP_REWARD_COUNT_LIMIT_REF = 0
				end
				SHIP_REWARD_COUNT = SHIP_REWARD_COUNT + 1
				SHIP_REWARD_COUNT_LIMIT_REF = SHIP_REWARD_COUNT_LIMIT_REF + 1
			end	
		end	
	end
	for i=1,#SHIP_TYPE,1 do
		for j=1,NUMBER_OF_SHIP_SEEDS[SHIP_TYPE[i]],1 do
			if SHIP_REWARD_COUNT > ACTION_TRIGGER_HARD_LIMIT then break end
			Seed = GetSeed()
			SHIP_REWARD_ID = "CUSTOM_SHIP_" .. SHIP_REWARD_COUNT
			CUSTOM_GENERICREWARD_ALL = CUSTOM_GENERICREWARD_ALL .. CreateCustomShipRewardEntry(SHIP_REWARD_ID, HexToDec(Seed), SHIP_TYPE_PATH[SHIP_TYPE[i]])
			ANIM_TEMPLATE_ALL = ANIM_TEMPLATE_ALL .. CreateAnimEntry(SHIP_REWARD_ID)
			ACTION_TRIGGER_ALL = ACTION_TRIGGER_ALL .. CreateActionTriggerRewardEntry(SHIP_REWARD_ID, SHIP_REWARD_ID)
			QUICK_ACTION_BUTTON_ALL = QUICK_ACTION_BUTTON_ALL .. CreateQuickActionMenuEntry(SHIP_REWARD_COUNT .. "." .. string.sub(SHIP_TYPE[i],1,7) .. ": " .. Seed, SHIP_REWARD_ID, "TEXTURES/UI/HUD/MENUS/ICON.SHIP.DDS")
			if SHIP_REWARD_COUNT_LIMIT_REF >= ACTION_TRIGGER_LIMIT then 
				table.insert(ACTION_TRIGGER_SEGMENTS, ACTION_TRIGGER_ALL) 
				ACTION_TRIGGER_ALL = ""
				ACTION_TRIGGER_LIMIT = ACTION_TRIGGER_LIMIT - 1
				SHIP_REWARD_COUNT_LIMIT_REF = 0
			end
			SHIP_REWARD_COUNT = SHIP_REWARD_COUNT + 1
			SHIP_REWARD_COUNT_LIMIT_REF = SHIP_REWARD_COUNT_LIMIT_REF + 1
		end
	end
	for i=1,#ACTION_TRIGGER_SEGMENTS,1 do
		ACTION_TRIGGER_COMPONENT = ACTION_TRIGGER_COMPONENT .. CreateActionTriggerComponent(ACTION_TRIGGER_SEGMENTS[i])	
	end
end


--------------------------------------------------------------------------

function CreateSpawner(ID, SCENE_TO_SPAWN)
SPAWNER_TEMPLATE =
[[
<?xml version="1.0" encoding="utf-8"?>
<!--File created using MBINCompiler version (2.0.9)-->
<Data template="TkAttachmentData">
  <Property name="Components">
    <Property value="GcSimpleInteractionComponentData.xml">
      <Property name="SimpleInteractionType" value="]] .. "SpawnObject" .. [[" />
      <Property name="InteractDistance" value="0" />
      <Property name="Id" value="" />
      <Property name="Rarity" value="GcRarity.xml">
        <Property name="Rarity" value="Common" />
      </Property>
      <Property name="Size" value="GcSizeIndicator.xml">
        <Property name="SizeIndicator" value="Medium" />
      </Property>
      <Property name="TriggerAction" value="]] .. "BOOT" .. [[" />
      <Property name="TriggerActionToggle" value="" />
      <Property name="BroadcastTriggerAction" value="True" />
      <Property name="Delay" value="0" />
      <Property name="HideContents" value="True" />
      <Property name="InteractIsCrime" value="False" />
      <Property name="InteractFiendCrimeType" value="GcFiendCrime.xml">
        <Property name="FiendCrime" value="None" />
      </Property>
      <Property name="InteractCrimeLevel" value="0" />
      <Property name="ActivationCost" value="GcInteractionActivationCost.xml">
        <Property name="SubstanceId" value="" />
        <Property name="AltIds" />
        <Property name="Cost" value="0" />
        <Property name="Repeat" value="False" />
        <Property name="RequiredTech" value="" />
      </Property>
      <Property name="StatToTrack" value="GcStatsEnum.xml">
        <Property name="Stat" value="None" />
      </Property>
      <Property name="StartsBuried" value="False" />
      <Property name="MustBeVisibleToInteract" value="False" />
      <Property name="NeedsStorm" value="False" />
      <Property name="Name" value="" />
      <Property name="VRInteractMessage" value="" />
      <Property name="TerminalMessage" value="" />
      <Property name="ScanType" value="" />
      <Property name="ScanData" value="" />
      <Property name="ScanIcon" value="GcDiscoveryTypes.xml">
        <Property name="DiscoveryType" value="Unknown" />
      </Property>
      <Property name="ActivateLocatorsFromRarity" value="False" />
      <Property name="RarityLocators">
        <Property value="NMSString0x10.xml">
          <Property name="Value" value="" />
        </Property>
        <Property value="NMSString0x10.xml">
          <Property name="Value" value="" />
        </Property>
        <Property value="NMSString0x10.xml">
          <Property name="Value" value="" />
        </Property>
      </Property>
      <Property name="BaseBuildingTriggerActions" />
      <Property name="RewardOverrideTable" />
      <Property name="UsePersonalPersistentBuffer" value="False" />
      <Property name="ReseedOnRewardSuccess" value="False" />
    </Property>
    <Property value="TkPhysicsComponentData.xml">
      <Property name="Data" value="TkPhysicsData.xml">
        <Property name="Mass" value="0" />
        <Property name="Friction" value="0.5" />
        <Property name="RollingFriction" value="0.2" />
        <Property name="AngularDamping" value="0.2" />
        <Property name="LinearDamping" value="0.1" />
        <Property name="Gravity" value="20" />
      </Property>
      <Property name="VolumeTriggerType" value="TkVolumeTriggerType.xml">
        <Property name="VolumeTriggerType" value="Open" />
      </Property>
      <Property name="SurfaceProperties" value="None" />
      <Property name="TriggerVolume" value="False" />
      <Property name="Climbable" value="False" />
      <Property name="IgnoreModelOwner" value="False" />
      <Property name="NoVehicleCollide" value="True" />
      <Property name="NoPlayerCollide" value="True" />
      <Property name="CameraInvisible" value="True" />
      <Property name="InvisibleForInteraction" value="True" />
      <Property name="AllowTeleporter" value="True" />
      <Property name="BlockTeleporter" value="False" />
    </Property>
    <Property value="GcTriggerActionComponentData.xml">
      <Property name="HideModel" value="False" />
      <Property name="StartInactive" value="False" />
      <Property name="States">
        <Property value="GcActionTriggerState.xml">
          <Property name="StateID" value="BOOT" />
          <Property name="Triggers" />
        </Property>
        <Property value="GcActionTriggerState.xml">
          <Property name="StateID" value="]] .. ID .. [[" />
          <Property name="Triggers">
            <Property value="GcActionTrigger.xml">
              <Property name="Trigger" value="GcStateTimeEvent.xml">
                <Property name="Seconds" value="0" />
                <Property name="RandomSeconds" value="0" />
              </Property>
              <Property name="Action">
                <Property value="GcFireSimpleInteractionAction.xml" />
<!--                 <Property value="GcGoToStateAction.xml">
                  <Property name="State" value="]] .. "BOOT" .. [[" />
                  <Property name="Broadcast" value="True" />
                  <Property name="BroadcastLevel" value="Scene" />
                </Property>	 -->				
              </Property>
            </Property>
          </Property>
        </Property>
      </Property>
      <Property name="Persistent" value="False" />
      <Property name="PersistentState" value="" />
      <Property name="ResetShotTimeOnStateChange" value="False" />
      <Property name="LinkStateToBaseGrid" value="False" />
    </Property>
    <Property value="GcObjectSpawnerComponentData.xml">
      <Property name="Object" value="TkTextureResource.xml">
        <Property name="Filename" value="]] .. SCENE_TO_SPAWN .. [[" />
      </Property>
      <Property name="SpawnPowerCost" value="0" />
      <Property name="SpawnCooldown" value="0" />
    </Property>
  </Property>
  <Property name="LodDistances">
    <Property value="0" />
    <Property value="50" />
    <Property value="80" />
    <Property value="150" />
    <Property value="500" />
  </Property>
</Data>
]]
return SPAWNER_TEMPLATE
end

function CreateSimpleInteractionEntity(ACTION, ID)
INTERACTION_ENTITY_TEMPLATE =
[[
<?xml version="1.0" encoding="utf-8"?>
<!--File created using MBINCompiler version (2.0.9)-->
<Data template="TkAttachmentData">
  <Property name="Components">
    <Property value="GcSimpleInteractionComponentData.xml">
      <Property name="SimpleInteractionType" value="]] .. ACTION .. [[" />
      <Property name="InteractDistance" value="0" />
      <Property name="Id" value="" />
      <Property name="Rarity" value="GcRarity.xml">
        <Property name="Rarity" value="Common" />
      </Property>
      <Property name="Size" value="GcSizeIndicator.xml">
        <Property name="SizeIndicator" value="Medium" />
      </Property>
      <Property name="TriggerAction" value="]] .. "BOOT" .. [[" />
      <Property name="TriggerActionToggle" value="" />
      <Property name="BroadcastTriggerAction" value="True" />
      <Property name="Delay" value="0" />
      <Property name="HideContents" value="True" />
      <Property name="InteractIsCrime" value="False" />
      <Property name="InteractFiendCrimeType" value="GcFiendCrime.xml">
        <Property name="FiendCrime" value="None" />
      </Property>
      <Property name="InteractCrimeLevel" value="0" />
      <Property name="ActivationCost" value="GcInteractionActivationCost.xml">
        <Property name="SubstanceId" value="" />
        <Property name="AltIds" />
        <Property name="Cost" value="0" />
        <Property name="Repeat" value="False" />
        <Property name="RequiredTech" value="" />
      </Property>
      <Property name="StatToTrack" value="GcStatsEnum.xml">
        <Property name="Stat" value="None" />
      </Property>
      <Property name="StartsBuried" value="False" />
      <Property name="MustBeVisibleToInteract" value="False" />
      <Property name="NeedsStorm" value="False" />
      <Property name="Name" value="" />
      <Property name="VRInteractMessage" value="" />
      <Property name="TerminalMessage" value="" />
      <Property name="ScanType" value="" />
      <Property name="ScanData" value="" />
      <Property name="ScanIcon" value="GcDiscoveryTypes.xml">
        <Property name="DiscoveryType" value="Unknown" />
      </Property>
      <Property name="ActivateLocatorsFromRarity" value="False" />
      <Property name="RarityLocators">
        <Property value="NMSString0x10.xml">
          <Property name="Value" value="" />
        </Property>
        <Property value="NMSString0x10.xml">
          <Property name="Value" value="" />
        </Property>
        <Property value="NMSString0x10.xml">
          <Property name="Value" value="" />
        </Property>
      </Property>
      <Property name="BaseBuildingTriggerActions" />
      <Property name="RewardOverrideTable" />
      <Property name="UsePersonalPersistentBuffer" value="False" />
      <Property name="ReseedOnRewardSuccess" value="False" />
    </Property>
    <Property value="TkPhysicsComponentData.xml">
      <Property name="Data" value="TkPhysicsData.xml">
        <Property name="Mass" value="0" />
        <Property name="Friction" value="0.5" />
        <Property name="RollingFriction" value="0.2" />
        <Property name="AngularDamping" value="0.2" />
        <Property name="LinearDamping" value="0.1" />
        <Property name="Gravity" value="20" />
      </Property>
      <Property name="VolumeTriggerType" value="TkVolumeTriggerType.xml">
        <Property name="VolumeTriggerType" value="Open" />
      </Property>
      <Property name="SurfaceProperties" value="None" />
      <Property name="TriggerVolume" value="False" />
      <Property name="Climbable" value="False" />
      <Property name="IgnoreModelOwner" value="False" />
      <Property name="NoVehicleCollide" value="True" />
      <Property name="NoPlayerCollide" value="True" />
      <Property name="CameraInvisible" value="True" />
      <Property name="InvisibleForInteraction" value="True" />
      <Property name="AllowTeleporter" value="True" />
      <Property name="BlockTeleporter" value="False" />
    </Property>
    <Property value="GcTriggerActionComponentData.xml">
      <Property name="HideModel" value="False" />
      <Property name="StartInactive" value="False" />
      <Property name="States">
        <Property value="GcActionTriggerState.xml">
          <Property name="StateID" value="BOOT" />
          <Property name="Triggers" />
        </Property>
        <Property value="GcActionTriggerState.xml">
          <Property name="StateID" value="]] .. ID .. [[" />
          <Property name="Triggers">
            <Property value="GcActionTrigger.xml">
              <Property name="Trigger" value="GcStateTimeEvent.xml">
                <Property name="Seconds" value="0" />
                <Property name="RandomSeconds" value="0" />
              </Property>
              <Property name="Action">
                <Property value="GcFireSimpleInteractionAction.xml" />				
              </Property>
            </Property>
          </Property>
        </Property>
      </Property>
      <Property name="Persistent" value="False" />
      <Property name="PersistentState" value="" />
      <Property name="ResetShotTimeOnStateChange" value="False" />
      <Property name="LinkStateToBaseGrid" value="False" />
    </Property>
  </Property>
  <Property name="LodDistances">
    <Property value="0" />
    <Property value="50" />
    <Property value="80" />
    <Property value="150" />
    <Property value="500" />
  </Property>
</Data>
]]
return INTERACTION_ENTITY_TEMPLATE
end

function CreateAnimEntry(ANIM_ID)
ANIM_TEMPLATE =
[[
		<Property value="TkAnimationData.xml">
			<Property name="Anim" value="]] .. ANIM_ID .. [[" />
		  <Property name="Filename" value="]] .. GENERIC_ANIMATION_FILE .. [[" />
		  <Property name="AnimType" value="OneShot" />
		  <Property name="FrameStart" value="0" />
		  <Property name="FrameEnd" value="0" />
		  <Property name="StartNode" value="" />
		  <Property name="ExtraStartNodes" />
		  <Property name="Priority" value="0" />
		  <Property name="LoopOffsetMin" value="0" />
		  <Property name="LoopOffsetMax" value="0" />
		  <Property name="Delay" value="0" />
		  <Property name="Speed" value="1" />
		  <Property name="ActionFrameStart" value="0" />
		  <Property name="ActionFrame" value="-1" />
		  <Property name="ControlCreatureSize" value="AllSizes" />
		  <Property name="Additive" value="False" />
		  <Property name="Mirrored" value="False" />
		  <Property name="Active" value="True" />
		  <Property name="AdditiveBaseAnim" value="" />
		  <Property name="AdditiveBaseFrame" value="0" />
		  <Property name="GameData" value="TkAnimationGameData.xml">
			<Property name="RootMotionEnabled" value="True" />
			<Property name="BlockPlayerMovement" value="False" />
			<Property name="BlockPlayerWeapon" value="Unblocked" />
		  </Property>
		</Property>	
]]
return ANIM_TEMPLATE
end

function CreateActionTriggerRewardEntry(ANIM_ID, REWARD)
ACTION_TRIGGER_ENTRY =
[[
            <Property value="GcActionTrigger.xml">
              <Property name="Trigger" value="GcAnimFrameEvent.xml">
                <Property name="Anim" value="]] .. ANIM_ID .. [[" />
                <Property name="FrameStart" value="0" />
                <Property name="StartFromEnd" value="False" />
              </Property>			  
              <Property name="Action">
                <Property value="GcRewardAction.xml">
                  <Property name="Reward" value="]] .. REWARD .. [[" />
                </Property>		
              </Property>
            </Property>			
]]
return ACTION_TRIGGER_ENTRY
end

function CreateActionTriggerSpawnerEntry(ANIM_ID)
ACTION_TRIGGER_ENTRY =
[[
            <Property value="GcActionTrigger.xml">
              <Property name="Trigger" value="GcAnimFrameEvent.xml">
                <Property name="Anim" value="]] .. ANIM_ID .. [[" />
                <Property name="FrameStart" value="0" />
                <Property name="StartFromEnd" value="False" />
              </Property>			  
              <Property name="Action">
                <Property value="GcGoToStateAction.xml">
                  <Property name="State" value="]] .. ANIM_ID .. [[" />
                  <Property name="Broadcast" value="True" />
                  <Property name="BroadcastLevel" value="Scene" />
                </Property>		
              </Property>
            </Property>			
]]
return ACTION_TRIGGER_ENTRY
end

function CreateActionTriggerComponent(ACTION_TRIGGER_LIST_)
local ACTION_TRIGGER_COMPONENT =
[[
    <Property value="GcTriggerActionComponentData.xml">
      <Property name="HideModel" value="False" />
      <Property name="StartInactive" value="False" />
      <Property name="States">
        <Property value="GcActionTriggerState.xml">
          <Property name="StateID" value="BOOT" />
          <Property name="Triggers">
]] .. ACTION_TRIGGER_LIST_ .. [[
          </Property>
        </Property>
      </Property>
      <Property name="Persistent" value="False" />
      <Property name="PersistentState" value="" />
      <Property name="ResetShotTimeOnStateChange" value="False" />
      <Property name="LinkStateToBaseGrid" value="False" />
    </Property>
]]
return ACTION_TRIGGER_COMPONENT
end

function FormatPath(FILEPATH)
	return string.gsub(FILEPATH, string.char(92) .. string.char(92), string.char(92))	
end

function CreateAnimEntry(ANIM_ID)
ANIM_TEMPLATE =
[[
		<Property value="TkAnimationData.xml">
			<Property name="Anim" value="]] .. ANIM_ID .. [[" />
		  <Property name="Filename" value="]] .. GENERIC_ANIMATION_FILE .. [[" />
		  <Property name="AnimType" value="OneShot" />
		  <Property name="FrameStart" value="0" />
		  <Property name="FrameEnd" value="0" />
		  <Property name="StartNode" value="" />
		  <Property name="ExtraStartNodes" />
		  <Property name="Priority" value="0" />
		  <Property name="LoopOffsetMin" value="0" />
		  <Property name="LoopOffsetMax" value="0" />
		  <Property name="Delay" value="0" />
		  <Property name="Speed" value="1" />
		  <Property name="ActionFrameStart" value="0" />
		  <Property name="ActionFrame" value="-1" />
		  <Property name="ControlCreatureSize" value="AllSizes" />
		  <Property name="Additive" value="False" />
		  <Property name="Mirrored" value="False" />
		  <Property name="Active" value="True" />
		  <Property name="AdditiveBaseAnim" value="" />
		  <Property name="AdditiveBaseFrame" value="0" />
		  <Property name="GameData" value="TkAnimationGameData.xml">
			<Property name="RootMotionEnabled" value="True" />
			<Property name="BlockPlayerMovement" value="False" />
			<Property name="BlockPlayerWeapon" value="Unblocked" />
		  </Property>
		</Property>	
]]
return ANIM_TEMPLATE
end

function CreateEntityAttachment(FILEPATH)
ENTITY_ATTACHMENT =
[[
		<Property value="TkSceneNodeAttributeData.xml">
		  <Property name="Name" value="ATTACHMENT" />
		  <Property name="AltID" value="" />
		  <Property name="Value" value="]] .. FormatPath(FILEPATH) .. [[" />
		</Property>
]]
return ENTITY_ATTACHMENT
end

function CreateSpawnEntityContainerRef(ATTACHMENTS)
SCENE_REF =
[[
   <Property value="TkSceneNodeData.xml">
	  <Property name="Name" value="INERACT_SPAWN" />
	  <Property name="NameHash" value="0" />
	  <Property name="Type" value="LOCATOR" />
	  <Property name="Transform" value="TkTransformData.xml">
		<Property name="TransX" value="0" />
		<Property name="TransY" value="0" />
		<Property name="TransZ" value="0" />
		<Property name="RotX" value="0" />
		<Property name="RotY" value="0" />
		<Property name="RotZ" value="0" />
		<Property name="ScaleX" value="1" />
		<Property name="ScaleY" value="1" />
		<Property name="ScaleZ" value="1" />
	  </Property>
	  <Property name="Attributes">
]] .. ATTACHMENTS .. [[
	  </Property>
	  <Property name="Children" />
	</Property>	
]]
return SCENE_REF
end

function GetObjectID(SCENEPATH)
	return string.gsub(string.match(string.match(SCENEPATH, "^.+/(.+)$"), "(.+)%.(.+)"), ".SCENE", "")
end

function HandleActionType(Action)
	local ButtonTitle = ""
	local Icon = ""
	local CurrentActionType = RequestActionType(Action)
	if not ACTION_TABLE[Action] then 
		ButtonTitle = Action 
		Icon = GENERIC_BUTTON_ICON
	else
		ButtonTitle = ACTION_TABLE[Action]["TITLE"]
		Icon = ACTION_TABLE[Action]["ICON"]
	end
	ANIM_TEMPLATE_ALL = ANIM_TEMPLATE_ALL .. CreateAnimEntry(Action)
	QUICK_ACTION_BUTTON_ALL = QUICK_ACTION_BUTTON_ALL .. CreateQuickActionMenuEntry(ButtonTitle, Action, Icon)
	if CurrentActionType == "REWARD" then
		ACTION_TRIGGER_ALL = ACTION_TRIGGER_ALL .. CreateActionTriggerRewardEntry(Action, Action)
	elseif CurrentActionType == "SIMPLE_INTERACTION" or CurrentActionType == "QUICK_MENU_ACTION" then
		ADD_ENTITY_FILE =
		{
			["FILE_DESTINATION"] = [[MODELS\CUSTOM\]] .. "S_INTERACTION_" .. Action .. [[.ENTITY.EXML]],
			["FILE_CONTENT"] 	 = CreateSimpleInteractionEntity(Action, Action)
		}
		table.insert(ADD_FILES_TABLE, ADD_ENTITY_FILE)
		ENTITY_ATTACHMENT_ALL = ENTITY_ATTACHMENT_ALL .. CreateEntityAttachment(ADD_ENTITY_FILE["FILE_DESTINATION"])
		ACTION_TRIGGER_ALL = ACTION_TRIGGER_ALL .. CreateActionTriggerSpawnerEntry(Action, Action)
	elseif CurrentActionType == "ENTITY_ACTION" then
	elseif CurrentActionType == "CUSTOM_REWARD" then
	elseif CurrentActionType == "INTERACTION" then
	elseif CurrentActionType == "REWARD" then
	elseif CurrentActionType == "INPUT_ACTION" then
	elseif CurrentActionType == "SPAWNER" then
		ACTION_TRIGGER_ALL = ACTION_TRIGGER_ALL .. CreateActionTriggerSpawnerEntry(Action, Action)
	end
end

function CreateModContent()
	if not FORCE_ALL_ACTION then
		if FULL_VERSION then
			for i=1,#ACTION_SELECTION_FULL,1 do
				HandleActionType(ACTION_SELECTION_FULL[i])				
			end
		else
			for i=1,#ACTION_SELECTION_LIGHT,1 do
				HandleActionType(ACTION_SELECTION_LIGHT[i])					
			end	
		end
	else
		for i=1,#REWARDS,1 do
			HandleActionType(REWARDS[i])		
		end
	end
	if ENABLE_SPAWNERS then
		local ID = ""
		for i=1,#SPAWN_TABLE,1 do
			ID = GetObjectID(SPAWN_TABLE[i])
			HandleActionType(ID)
			ADD_ENTITY_FILE =
			{
				["FILE_DESTINATION"] = [[MODELS\CUSTOM\]] .. "SPAWNER_" .. ID .. [[.ENTITY.EXML]],
				["FILE_CONTENT"] 	 = CreateSpawner(ID, SPAWN_TABLE[i])
			}
			table.insert(ADD_FILES_TABLE, ADD_ENTITY_FILE)
			ENTITY_ATTACHMENT_ALL = ENTITY_ATTACHMENT_ALL .. CreateEntityAttachment(ADD_ENTITY_FILE["FILE_DESTINATION"])
		end
	end
	if ADD_MORE_EMOTES then
		for i=1,#NEW_EMOTE_TABLE,1 do
			NEW_EMOTES_ALL = NEW_EMOTES_ALL .. CreateQuickActionMenuEntry(NEW_EMOTE_TABLE[i]["TITLE"], NEW_EMOTE_TABLE[i]["ANIM"], NEW_EMOTE_TABLE[i]["ICON"])
		end		
	end	
	SCENE_REF_FOR_SIMPLEINTERACTION = CreateSpawnEntityContainerRef(ENTITY_ATTACHMENT_ALL)
	ACTION_TRIGGER_COMPONENT = CreateActionTriggerComponent(ACTION_TRIGGER_ALL)
end

if CUSTOM_SHIPS then AddShipsRewardsToQuickActionMenu() end
if OTHER_OPTIONS then CreateModContent() end	






MOD_DEF_CON_ALL = 
{
["MOD_FILENAME"] 			= "MetaModByMjjstral.pak",
["MOD_AUTHOR"]				= "Mjjstral",
["MOD_DESCRIPTION"]			= "Adds many new quick action menu options",
["NMS_VERSION"]				= "2.0+",
["MODIFICATIONS"] 			= 
	{
		{
			["PAK_FILE_SOURCE"] 	= "NMSARC.515F1D3.pak",
			["MBIN_CHANGE_TABLE"] 	= 
			{  
				{
					["MBIN_FILE_SOURCE"] 	= "MODELS\COMMON\PLAYER\PLAYERCHARACTER\PLAYERCHARACTER\ENTITIES\PLAYERCHARACTER.ENTITY.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = {"Anims"}, 
							["LINE_OFFSET"] 		= "+0",
							["ADD"] 				= ANIM_TEMPLATE_ALL
						},
						{
							["PRECEDING_KEY_WORDS"] = {"LodDistances"}, 
							["LINE_OFFSET"] 		= "-2",
							["ADD"] 				= ACTION_TRIGGER_COMPONENT
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= "METADATA\UI\EMOTEMENU.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = {"Emotes"}, 
							["LINE_OFFSET"] 		= "+0",
							["ADD"] 				= QUICK_ACTION_BUTTON_ALL
						},
						{
							["SPECIAL_KEY_WORDS"] 	= {"Title", "EMOTE_KNEES"},
							["LINE_OFFSET"] 		= "+14",
							["ADD"] 				= NEW_EMOTES_ALL
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= "METADATA\REALITY\TABLES\REWARDTABLE.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = {"GenericTable"}, 
							["LINE_OFFSET"] 		= "+0",
							["ADD"] 				= CUSTOM_GENERICREWARD_ALL
						}
					}
				}
			}
		},
		{
			["PAK_FILE_SOURCE"] 	= "NMSARC.4C482859.pak",
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= "MODELS\COMMON\PLAYER\PLAYERCHARACTER\PLAYERCHARACTER.SCENE.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = { "Name", "SUB9Backpack_1"},
							--["PRECEDING_KEY_WORDS"] = {"SUB9Backpack_1"},
							["LINE_OFFSET"] 		= "+128",
							["ADD"] 				= SCENE_REF_FOR_SIMPLEINTERACTION
						}
					}
				}
			}
		}
	},
["ADD_FILES"] = ADD_FILES_TABLE
}


--Only add custom ships
NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "MetaModByMjjstral.pak",
["MOD_AUTHOR"]				= "Mjjstral",
["MOD_DESCRIPTION"]			= "Adds many new quick action menu options",
["NMS_VERSION"]				= "2.0+",
["MODIFICATIONS"] 			= 
	{
		{
			["PAK_FILE_SOURCE"] 	= "NMSARC.515F1D3.pak",
			["MBIN_CHANGE_TABLE"] 	= 
			{  
				{
					["MBIN_FILE_SOURCE"] 	= "MODELS\COMMON\PLAYER\PLAYERCHARACTER\PLAYERCHARACTER\ENTITIES\PLAYERCHARACTER.ENTITY.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = {"Anims"}, 
							["LINE_OFFSET"] 		= "+0",
							["ADD"] 				= ANIM_TEMPLATE_ALL
						},
						{
							["PRECEDING_KEY_WORDS"] = {"LodDistances"}, 
							["LINE_OFFSET"] 		= "-2",
							["ADD"] 				= ACTION_TRIGGER_COMPONENT
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= "METADATA\UI\EMOTEMENU.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = {"Emotes"}, 
							["LINE_OFFSET"] 		= "+0",
							["ADD"] 				= QUICK_ACTION_BUTTON_ALL
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= "METADATA\REALITY\TABLES\REWARDTABLE.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = {"GenericTable"}, 
							["LINE_OFFSET"] 		= "+0",
							["ADD"] 				= CUSTOM_GENERICREWARD_ALL
						}
					}
				}
			}
		}
	}
}

