NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "NoObjectGlowOnFocus.pak", 
["MOD_AUTHOR"]				= "Mjjstral",
["NMS_VERSION"]				= "2.24",
["MOD_DESCRIPTION"]			= "Remove white glow around objects when focusing it (especially for VR immersion)",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= 
					{
						-- "MODELS\COMMON\PLAYER\PLAYERCHARACTER\NPCFIFTH\ENTITIES\NPCFIFTHDATA.ENTITY.MBIN",
						-- "MODELS\COMMON\PLAYER\PLAYERCHARACTER\NPCFOURTH\ENTITIES\NPCFOURTHDATA.ENTITY.MBIN",
						-- "MODELS\COMMON\PLAYER\PLAYERCHARACTER\NPCGEK\ENTITIES\NPCGEKDATA.ENTITY.MBIN",
						-- "MODELS\COMMON\PLAYER\PLAYERCHARACTER\NPCKORVAX\ENTITIES\NPCKORVAXDATA.ENTITY.MBIN",
						-- "MODELS\COMMON\PLAYER\PLAYERCHARACTER\NPCSPECIALSHOP\ENTITIES\NPCSPECIALDATA.ENTITY.MBIN",
						"MODELS\COMMON\PLAYER\PLAYERCHARACTER\NPCVYKEEN\ENTITIES\NPCVYKEENDATA.ENTITY.MBIN",
						
						-- "MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPIT_A\COCKPITA\ENTITIES\COCKPIT_A.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPIT_B\COCKPITB\ENTITIES\COCKPIT_B.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPIT_D\COCKPITD\ENTITIES\COCKPITD.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPIT_E\COCKPIT_E\ENTITIES\COCKPTE.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPIT_F\COCKPTF\ENTITIES\COCKPITF.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\DROPSHIPS\COCKPIT\COCKPITA\ENTITIES\COCKPIT_A.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\DROPSHIPS\COCKPIT\COCKPITB\ENTITIES\COCKPIT_B.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\SCIENTIFIC\ACCESSORIES\LANDINGGEAR\LANDINGGEAR_POD\ENTITIES\LANDINGGEAR.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\SHUTTLE\ACCESSORIES\LANDINGGEAR_LEG\ENTITIES\LANDINGGEAR.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\SHUTTLE\INTERIORS\CANOPYA_INTERIOR\ENTITIES\CANOPYA.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\S-CLASS\INTERIORS\CANOPYA_INTERIOR\ENTITIES\COCKPIT.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\S-CLASS\ROYALPARTS\LANDINGGEAR\LANDINGGEAR_A\ENTITIES\S_CLASS_LANDINGGEAR_A.ENTITY.MBIN",
						-- "MODELS\COMMON\SPACECRAFT\S-CLASS\SQUIDPARTS\LANDINGGEAR\LANDINGGEAR_A\ENTITIES\LANDINGGEAR_A.ENTITY.MBIN",	
					},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["REPLACE_TYPE"]		= "ALL",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"UsePlayerCameraInHmd",						"False"},
								{"UseSensibleCameraFocusNodeIsNowOffsetNode",	"True"},
								{"FocusType",									"DiscoveryView"},
								{"UseInteractCamera",							"False"},		
								{"IgnoreModelOwner",							"True"},	
								{"CameraInvisible",								"True"},	
								{"InvisibleForInteraction",						"True"},	
							}
						}
					}
				}
			}
		}
	}	
}