SPECIAL_LIST =
{
	{
		["ShopNumber"] = "110",
		["Table"] =  
		{
			{ ["ID"] = "B_DECO_Q_0",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "B_DECO_R",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "B_DECO_S",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "B_DECO_T",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "B_SHL_E",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "B_STR_AA_N",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "B_WNG_P",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "B_WNG_Q",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "B_WNG_R",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER20",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL20",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER20A",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER20B",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER20C",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE20",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			-- { ["ID"] = "F_BOSS_JELLY",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			-- { ["ID"] = "S20_LOG1",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			-- { ["ID"] = "S20_LOG2",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			-- { ["ID"] = "S20_LOG3",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			-- { ["ID"] = "S20_LOG4",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			-- { ["ID"] = "S20_LOG5",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "SHIP_ATLAS",	["IsConsumable"] = "false", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "106",
		["Table"] =  
		{
			{ ["ID"] = "B_TUR_B",	["IsConsumable"] = "false", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER19",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL19",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_19",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER19A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER19B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER19C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE19",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "JETS_RUIN",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "S19_TP",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "SHIP_PLASMA",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW11A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW11B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW11C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW11D",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW11E",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN25",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN26",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN27",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET23",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET24",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP51",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP52",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP53",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP54",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP55",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRFIGHT1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRFIGHT2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRFIGHT3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRFIGHT4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRMINE1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRMINE2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRMINE3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRMINE4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRSCI1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRSCI2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRSCI3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRSCI4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRTRADE1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRTRADE2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRTRADE3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_CRTRADE4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "WORLDSMB_SOUL",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "103",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_POSTER18A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER18B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER18C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE18",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL18",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER18",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_18",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_STAFF_18",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_STONE_PACK",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "STONE_HAT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "STONE_ARMOUR",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "STONE_TORSO",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "STONE_GLOVES",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "STONE_LEGS",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "STONE_BOOTS",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_CAPE17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER17A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER17B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER17C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_SHIP17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_SHIPMAT17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_STAFF_17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_BOB1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_BOB2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_BOB3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_BOB4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_BOB5",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_BOB6",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_HAT1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_HAT2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_HAT3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_HAT4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_HAT5",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_FISH_HAT6",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW10A",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW10B",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW10C",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW10D",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW10E",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN22",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN23",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN24",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET21",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET22",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP46",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP47",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP48",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP49",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP50",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TGA_SHIP01",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "101",
		["Table"] =  
		{
			-- { ["ID"] = "SPOOK_JUICE",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "PORTAL_JUICE",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "MESSAGE_JUICE",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "BOSS_JUICE",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "MESSAGE_JUICE1",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "MESSAGE_JUICE2",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "MESSAGE_JUICE3",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "MESSAGE_JUICE4",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_SHIP16",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "JETS_SQUID",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_S16_HAT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_16",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER16A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER16B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER16C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE16",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL16",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER16",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "S16_HEATER",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "92",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_POSTER15A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER15B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER15C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FISH_PACK",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_S15_ARMOUR",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_S15_HAT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_S15_LEGS",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_S15_BOOTS",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE15",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL15",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER15",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_S15_LASER",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BOBBLE_OCTO",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPED_BUG_ARMOR",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPED_BUG_GLOVE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPED_BUG_BOOTS",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPED_BUG_HAT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPED_BUG_PACK",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_14",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_BUGHEAD1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_BUGHEAD2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_BUGHEAD3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_BUGHEAD4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_BUGHEAD5",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER14A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER14B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER14C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "BUGMECH_ARML",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "BUGMECH_ARMR",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "BUGMECH_LEGS",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "BUGMECH_HEAD",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE14",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL14",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER14",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP41",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP42",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP43",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP44",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP45",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET20",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN19",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN20",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN21",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "U_MECHFLAME2",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "U_MECHFLAME3",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "U_MECHFLAME4",	["IsConsumable"] = "True", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "91",
		["Table"] =  
		{
			{ ["ID"] = "DROPS_COCKS13",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "DROPS_ENGIS13",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "DROPS_WINGS13",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER13A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER13B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER13C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_SHIPBREAK1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_SHIPBREAK2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_SHIPBREAK3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_SHIPBREAK4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_SHIPBREAK5",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_SHIPMAT13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_SHIP_METAL",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_GHOSTFRIG",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_SHIP13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "88",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_SHIP12",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_ATLASHELM",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_ATLASSTAFF",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_ATLASPACK",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER12A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER12B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER12C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE12",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL12",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER12",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP36",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP37",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP38",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP39",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP40",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET18",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET19",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN16",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN18",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "SPEC_FIREWORK07",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "SPEC_FIREWORK08",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "SPEC_FIREWORK09",	["IsConsumable"] = "True", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "79",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_POSTER11A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER11B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER11C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "JETS_ELECTRIC",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_PETCUST11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_BUI_HAND",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_BUI_HEAD",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_BUI_TENT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_5",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_6",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_7",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_8",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_9",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_10",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_12",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_14",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_HEAD_15",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_ARMOUR_1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_ARMOUR_2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_ARMOUR_3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_ARMOUR_4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_CLOTH_1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_CLOTH_2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BUI_CLOTH_3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_PART_A",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_CORE1",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_CORE2",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_CORE3",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_CORE4",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_CORE5",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_CORE6",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_PART_B",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_HEAD1",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_HEAD2",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_HEAD3",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_HEAD4A",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_HEAD4B",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_HEAD5",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_HEAD6",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_PART_C",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_POLE1",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_POLE2",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_POLE3",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_POLE4",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_POLE5",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "STAFF_POLE6",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP31",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP32",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP33",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP34",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP35",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN14",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN15",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW07A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW07B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW07C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW07D",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW07E",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER10A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER10B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER10C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_CRYS_SENT0",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_CRYS_SENT1",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_CRYS_DRONE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_ROCKETHAT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE10",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL10",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER10",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "FREI_TRAIL_RED",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "JETS_CORRUPT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "S10_PART1A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "S10_PART1B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "S10_PART2",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "S10_PART3",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "S10_PART4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "S10_PART5",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "75",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_SHIP09",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER09",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL09",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE09",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_09",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_BUCKETHELM",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_HOLOGEK",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER09C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER09B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER09A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP26",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP27",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP28",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP29",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP30",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET15",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET16",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN12",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW06A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW06B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW06C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW06D",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW06E",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "71",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_EGG_08",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TECHBOX",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "INVBOX",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			-- { ["ID"] = "ACCESS4",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_DECRYPT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_KEYPIECE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_KEY",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_SCIENCETREE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_WEAPONTREE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_FARMTREE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_EXOCRAFTTREE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_SHIPTREE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "S9_BUILDERTREE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SWITCH_SHIP01",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SWITCH_GUN01",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP21",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP22",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP23",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP24",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP25",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET14",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN09",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN10",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW05A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW05B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW05C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW05D",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_FIREW05E",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "66",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_BANNER08",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL08",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE08",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_DATASIGN",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_FIREPIT",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_MAPTUBE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_CAPE08",	["IsConsumable"] = "False", ["IsCape"] = "True"},
			{ ["ID"] = "FREI_TRAIL_GRAV",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER08C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER08B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER08A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET12",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP16",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP17",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP18",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP19",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP20",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN06",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN07",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN08",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "62",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_POSTER07A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER07B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER07C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SHIP_ROGUE",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_CAPE07",	["IsConsumable"] = "False", ["IsCape"] = "True"},
			{ ["ID"] = "BLD_MINI_BIOFRI",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE07",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL07",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER07",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BIOFRIG",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "60",
		["Table"] =  
		{
			{ ["ID"] = "SHIP_PIRATE",	["IsConsumable"] = "False", ["IsCape"] = "False", ["Display"] = "-1"},
			{ ["ID"] = "EXPD_CAPE06",	["IsConsumable"] = "False", ["IsCape"] = "True"},
			{ ["ID"] = "SPEC_HOOD01",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_CUBE_06",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE06",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL06",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER06",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FLAG_06A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FLAG_06B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FLAG_06C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FLAG_06D",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FLAG_06E",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER06A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER06B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER06C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET06",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET07",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET08",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET09",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET10",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP11",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP12",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP13",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP14",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP15",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW03A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW03B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW03C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW03D",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			-- { ["ID"] = "TWITCH_FIREW03E",	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "59",
		["Table"] =  
		{
			{ ["ID"] = "JETS_SENT",			["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER05A",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER05B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_POSTER05C",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_PETCUST05",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BACKPACK05",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE05",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL05",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER05",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_05",		["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "56",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_FIREWORK04",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE04",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL04",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER04",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_WORMHAT",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_SKULL",			["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_EGG_04",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "JETS_WORM",			["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET05",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET04",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET03",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET02",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_PET01",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP10",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP09",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP08B",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP07",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP06",		["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "55",
		["Table"] =  
		{
			{ ["ID"] = "EXPD_EGG_03",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE03",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL03",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER03",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BASE_CAVE1",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BASE_CAVE2",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BASE_CAVE3",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BASE_CAVE4",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BASE_CAVE5",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_FLYJAR",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_PLANET_HOLO",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "JETS_BUBBLE",		["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "52",
		["Table"] =  
		{
			--{ ["ID"] = "EXPD_FIREPACK01",	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_SPEC02",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			--{ ["ID"] = "MYSTERY_TRACKER",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE02A",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE02B",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL02",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER02",		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FIREWORK01",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FIREWORK02",	["IsConsumable"] = "True", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_FIREWORK03",	["IsConsumable"] = "True", ["IsCape"] = "False"},
		}
	},
	{
		["ShopNumber"] = "49",
		["Table"] =  
		{
			{ ["ID"] = "SPEC_SPOOKYHEAD", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "SPEC_XOHELMET", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "BLD_EXPD_BASE01", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_HELMET01", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BACKPACK01", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_BANNER01", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_DECAL01", 		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_TITLE01", 		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "EXPD_SHIP01", 		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP01", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP02", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP03", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP04", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_SHIP05", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN01", 		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN02", 		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN03", 		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN04", 		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUN05", 		["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUNUP01A", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUNUP01B", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUNUP01C", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUNUP01D", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
			{ ["ID"] = "TWITCH_GUNUP01E", 	["IsConsumable"] = "False", ["IsCape"] = "False"},
		}
	},
}

UNLOCK_ALL =
{
	-- ["PRECEDING_KEY_WORDS"] = "",
	["REPLACE_TYPE"] 	= "ALL",
	["VALUE_CHANGE_TABLE"] 	= 
	{
		{"ShopNumber", "1"},
		{"MissionTier", "-1"} -- Original numbers other than -1 and are capitalist scum
	},
}

SET_OVERWRITE_FLAG =
{
	["PKW"] = {"Table"},
	["EXML_FLAGS"]  = "OVERWRITE", 
}

function GetNewSpecial(ID, REPEAT, DISPLAY)
	FINISHED_EXPORT = [[    <Property value="GcPurchaseableSpecial" _id="]] .. ID .. [["]]
	if DISPLAY then FINISHED_EXPORT = FINISHED_EXPORT .. [[ _display="WTP"]] end
	FINISHED_EXPORT = FINISHED_EXPORT .. [[>
      <Property name="ID" value="]] .. ID .. [[" />
      <Property name="ShopNumber" value="1" />
      <Property name="MissionTier" value="-1" />
      <Property name="IsConsumable" value="]] .. REPEAT .. [[" />
    </Property>
]]
return FINISHED_EXPORT
end

NEW_SPECIAL = {}
ID_EXPORT = {}
for _i,j in pairs(SPECIAL_LIST) do
	SHOP_LIST_TEMP = {}
	SPECIAL_EXPORT = {}
	for _k,l in ipairs(j["Table"]) do
		local ExportDisplay = false; if l["Display"] ~= nil then ExportDisplay = true end
		table.insert(SHOP_LIST_TEMP, GetNewSpecial(l["ID"], l["IsConsumable"], ExportDisplay))
		-- table.insert(ID_EXPORT, l["ID"]..string.char(10))
	end
	SPECIAL_EXPORT =
	{
		["SKW"] = {"ShopNumber", j["ShopNumber"]},
		["ADD_OPTION"] = "ADDbeforeSECTION",
		-- ["LINE_OFFSET"] = "-4",
		["ADD"] = table.concat(SHOP_LIST_TEMP)
	}
	table.insert(NEW_SPECIAL, SPECIAL_EXPORT)
end
table.insert(NEW_SPECIAL, UNLOCK_ALL)
table.insert(NEW_SPECIAL, SET_OVERWRITE_FLAG)
--[[table.insert(NEW_SPECIAL,
{
	["SEC_EMPTY"] = "ID_HANDOVER",
})
table.insert(NEW_SPECIAL,
{
	["SEC_EDIT"] = "ID_HANDOVER",
	["REPLACE_TYPE"] = "RAW",
	["VCT"] = {{"<EMPTY>", table.concat(ID_EXPORT)}},
	["SEC_KEEP"] = "TRUE",
})]]

NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "~Consumerism",
["MOD_AUTHOR"]				= "WinderTP",
["NMS_VERSION"]				= "1.1.6",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= { "METADATA\REALITY\TABLES\PURCHASEABLESPECIALS.MBIN"},
					["MXML_CHANGE_TABLE"] 	= NEW_SPECIAL
				},
			}
		},
	}	
}