NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 		= "+Windrex_Materials",
["MOD_AUTHOR"]			= "WinderTP",
["MODIFICATIONS"] 		= 
	{
		{
			["MBIN_CHANGE_TABLE"] =
			{
				{
					["MBIN_FILE_SOURCE"] 	= 
	{
	[[MODELS\COMMON\SPACECRAFT\DROPSHIPS\COCKPIT\COCKPITA_INTERIOR\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\DROPSHIPS\COCKPIT\COCKPITA_INTERIOR\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\DROPSHIPS\COCKPIT\COCKPITB_INTERIOR\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\DROPSHIPS\COCKPIT\COCKPITB_INTERIOR\GLASS_MAT1.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPITA_INTERIOR\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPITA_INTERIOR\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPITB_INTERIOR\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPITB_INTERIOR\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\FIGHTERS\COCKPIT\COCKPITCOMMON_INTERIOR\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SAILSHIP\SAILSHIPPARTS\COCKPIT\SAILSHIPCOCKPITA_INTERIOR\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SAILSHIP\SAILSHIPPARTS\COCKPIT\SAILSHIPCOCKPITA_INTERIOR\SAILSHIPGLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SCIENTIFIC\INTERIORS\CANOPYA_INTERIOR\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SCIENTIFIC\INTERIORS\CANOPYA_INTERIOR\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SENTINELSHIP\SENTINELCOCKPIT\GLASSTRIMBMAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SENTINELSHIP\SENTINELCOCKPIT\GLASSTRIM_MAT2.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SENTINELSHIP\SENTINELCOCKPIT\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SHUTTLE\INTERIORS\CANOPYA_INTERIOR\CANOPYA_INTERIOR\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\SPACECRAFT\SHUTTLE\INTERIORS\CANOPYA_INTERIOR\CANOPYA_INTERIOR\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\BIKE\BIKECOCKPIT\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\BUGGY\BUGGYCOCKPIT\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\MECH_SUIT\MECH_SUIT_COCKPIT\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\MECH_SUIT\MECH_SUIT_COCKPIT\RAIL12_PASTED__PASTED__GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\ROVER\ROVERCOCKPIT\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\SHARED\INTERIOR\COCKPITCHAIR\GLASS_MAT1.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\SHARED\INTERIOR\COCKPITCHAIRSUB\GLASS_MAT1.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\SHARED\INTERIOR\SCREENS\SCREEN1_L\GLASS_MAT1.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\SHARED\INTERIOR\SCREENS\SCREEN1_R\GLASS_MAT1.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\SUBMARINE\SUBMARINECOCKPIT\GLASSTRIM_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\VEHICLES\SUBMARINE\SUBMARINECOCKPIT\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\WEAPONS\MULTITOOL\ATLASMTPARTS\ATLASMTARTEMIS\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\WEAPONS\MULTITOOL\ATLASMTPARTS\ATLASMTATLAS\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\WEAPONS\MULTITOOL\ATLASMTPARTS\ATLASMTMONOLITH\GLASS_MAT.MATERIAL.MBIN]],
	[[MODELS\COMMON\WEAPONS\MULTITOOL\ATLASMTPARTS\ATLASMTMONOLITH\GLASS_MAT1.MATERIAL.MBIN]],
	},
					["EXML_CHANGE_TABLE"]	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = {"Samplers"},
							["WISS"] =
							{
								{ "Map", [[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASS.MASKS.DDS]]},
							},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{[[Map]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASS.MASKS.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.MASKS.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.MASKS.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.REFRACTION.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.REFRACTION.DDS"	},		
							}
						},
						{
							["PRECEDING_KEY_WORDS"] = {"Samplers"},
							["WISS"] =
							{
								{ "Map", [[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.DDS]]},
							},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASS.MASKS.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASS.MASKS.DDS"	},		
								{[[Map]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.MASKS.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.MASKS.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.REFRACTION.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.REFRACTION.DDS"	},		
							}
						},
						{
							["PRECEDING_KEY_WORDS"] = {"Samplers"},
							["WISS"] =
							{
								{ "Map", [[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.MASKS.DDS]]},
							},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASS.MASKS.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASS.MASKS.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.DDS"	},		
								{[[Map]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.MASKS.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.REFRACTION.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.REFRACTION.DDS"	},		
							}
						},
						{
							["PRECEDING_KEY_WORDS"] = {"Samplers"},
							["WISS"] =
							{
								{ "Map", [[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.REFRACTION.DDS]]},
							},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASS.MASKS.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASS.MASKS.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.DDS"	},		
								-- {[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/GLASSTRIM.MASKS.DDS]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.MASKS.DDS"	},		
								{[[Map]],	 "CUSTOMMODELS/COCKPITINTERIORS/GLASSTRIM.REFRACTION.DDS"	},		
							}
						},
					},
				}
			}
		}
	}
}