winget install Microsoft.DotNet.SDK.5

xcopy AMUMSS\INSTALL\AMUMSS-4.0.3.0W\ ENGINE\ /q /s /y
copy STEP_1_ENTER_NMS_FOLDER_HERE_BEFORE_INSTALL.txt ENGINE\NMS_FOLDER.txt
copy AMUMSS\INSTALL\BUILDMOD_AUTO.bat ENGINE\BUILDMOD_AUTO.bat
COPY /V /B RGOG\ALL_PRESETS\EUPHORIA.lua+RGOG\MAIN.lua RGOG\REDMAS_MODS_BUILDER.lua
cd RGOG
copy REDMAS_MODS_BUILDER.lua ..\ENGINE\ModScript\REDMAS_MODS_BUILDER.lua
cd ..
cd ENGINE
BUILDMOD_AUTO.bat