xcopy _ENGINE\RGOG\INSTALL\AMUMSS\AMUMSS-4.0.3.0W\ _ENGINE\AMUMSS\ /q /s /y
copy STEP_1_ENTER_NMS_FOLDER_HERE_BEFORE_INSTALL.txt _ENGINE\AMUMSS\NMS_FOLDER.txt
copy _ENGINE\RGOG\INSTALL\AMUMSS\BUILDMOD_AUTO.bat _ENGINE\AMUMSS\BUILDMOD_AUTO.bat
If NOT exist _ENGINE\RGOG\USERPARAMS\ADVANCED_PARAMS.lua (
xcopy _ENGINE\RGOG\SRC\REDMASPARAMS\ _ENGINE\RGOG\USERPARAMS\ /q /s /y
)
cd _ENGINE\AMUMSS\
BUILDMOD_AUTO.bat