NEW_TEX_DIR = [[CUSTOMTEXTURES/CODENAMEAWESOME/PLANETS/BIOMES/UNFROZEN/]]
NEW_MODEL_DIR = [[CUSTOMMODELS/CODENAMEAWESOME/PLANETS/BIOMES/UNFROZEN/]]

MBIN_CHANGE_TABLE = {}


TEXTURES = {--All Frozen texture MBINs that have "Palette" value="Snow"
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/BARKSNOWDECAL.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/FROSTLEAF.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/HANGINGICICLES.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ICEROCK.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ICETILING.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/PINELEAF.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ROCKTILING.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SMOOTHROCKTILING.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWBILLLEAF.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWFROND.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWTILING.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWTREEBASE2.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TILINGROCKA.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TREEBASE.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/FROZENLEAF_1.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK_1.TEXTURE.MBIN",
	"TEXTURES/PLANETS/BIOMES/FROZEN/SMALLPROPS/ICEFORMATION.TEXTURE.MBIN",
}

MATERIALS = {--All Frozen material files.
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/FROZENLARGETREE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/FROZENLEAF1_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/ICE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/IMPOSTER_IMPOSTERMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/LAMBERT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/LARGETILINGROCK_A.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/MEDIUMPLANT_FROZENLARGETREE_MAT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/SMALLPLANT_FROZENLEAF1_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS/SMOOTHROCKTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREEBARE/FROZENLARGETREE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREEBARE/HANGINGICESOLID_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREEBARE/HANGINGICE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREEBARE/IMPOSTERMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREEBARE/LAMBERT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREEBARE/SNOWTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE/BARK.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE/BARK1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE/BILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE/FROZENFRONDMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE/FROZENLARGETREE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE/IMPOSTERMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE/LAMBERT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE/SNOWTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/BONEFORM6_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/COLLISIONMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/COLLISIONMAT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/CONTOUR2MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/CONTOUR3MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/CONTOUR4MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/CONTOURSNOWBLENDMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/LAMBERT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/SNOWBLENDSHAPEMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/SNOWBONEGLOW_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/SNOWBONEINNER_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/SNOWCORELIGHT_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP/SNOWJOINT_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMICEDRIFTS/ICE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMICEDRIFTS/SNOWTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMPLANT/BARK2.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMPLANT/FROND2.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMPLANT/FROZENLARGETREE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMPLANT/FROZENLEAF1_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMPLANT/IMPOSTERMAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMPLANT/LAMBERT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK/FLATROCKS_SNOWTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK/FROZENLARGETREE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK/FROZENLEAF1_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK/FROZENMEDROCK_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK/LAMBERT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK/LARGEROCKS_FROZENLEAF1_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK/ROCKTEMPLATWE_SMOOTHROCKTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK/TILINGROCKFROZEN_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLICEFORMATION/ICEFORMATION_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT/FLOWERHEAD_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT/FROZENLEAF1_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT/LAMBERT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT/LEAVESB_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT/LEAVES_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT/MEDIUMPLANT_FROZENLARGETREE_MAT2.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKSSHARDS/SMALLROCKBASE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKSSHARDS/SMALLROCKS_SNOWTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKSSHARDS/SNOWTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKS/ICE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKS/LAMBERT1.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKS/ROCKBASE_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKS/SNOWTILING_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKS/TILINGROCKFROZEN_MAT.MATERIAL.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SNOWFRAGMENTS/TINYSLATEMAT.MATERIAL.MBIN",
}

MODELS = {--All Frozen model files.
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREEBARE.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWCOVEREDWEIRDPROP.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMICEDRIFTS.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMPLANT.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLICEFORMATION.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKS.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKSSHARDS.SCENE.MBIN",
	"MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SNOWFRAGMENTS.SCENE.MBIN",
}

ADD_FILES = {}

TEXTURE_REPLACEMENT_TABLE = {
	{[[<?]],[[<?]]},
	{[[.BASE.1.DDS]],[[.DDS]]}
}
for _, texture_mbin in ipairs(TEXTURES) do
	new_texture_mbin = texture_mbin:gsub("TEXTURES/PLANETS/BIOMES/FROZEN/",NEW_TEX_DIR)
	texture = texture_mbin:gsub(".TEXTURE.MBIN",".DDS")
	new_texture = new_texture_mbin:gsub(".TEXTURE.MBIN",".DDS")
	
	table.insert(TEXTURE_REPLACEMENT_TABLE,{texture,new_texture})
	
	table.insert(ADD_FILES,{
		["INTERNAL_FILE_SOURCE"] = texture,
		["FILE_DESTINATION"] = new_texture
	})
	
	table.insert(MBIN_CHANGE_TABLE,{
		["MBIN_FILE_SOURCE"] = {{texture_mbin,new_texture_mbin}}
	})
	table.insert(MBIN_CHANGE_TABLE,{
		["MBIN_FILE_SOURCE"] = {new_texture_mbin},
		["EXML_CHANGE_TABLE"] = {
			{--Remove snow layer
				["SPECIAL_KEY_WORDS"] = {"Palette", "Snow"},
				["SECTION_UP"] = 1,
				["REPLACE_TYPE"] = "ALL",
				["REMOVE"] = "SECTION"
			}
		}
	})
end

for _, material_mbin in ipairs(MATERIALS) do
	new_material_mbin = material_mbin:gsub("MODELS/PLANETS/BIOMES/FROZEN/",NEW_MODEL_DIR)
	table.insert(MBIN_CHANGE_TABLE,{
		["MBIN_FILE_SOURCE"] = {{material_mbin,new_material_mbin}}
	})
	
	table.insert(MBIN_CHANGE_TABLE,{
		["MBIN_FILE_SOURCE"] = {new_material_mbin},
		["EXML_CHANGE_TABLE"] = {
			{
				["REPLACE_TYPE"] = "RAW",
				["NOTICE_OFF"] = "TRUE",
				["VALUE_CHANGE_TABLE"] = TEXTURE_REPLACEMENT_TABLE
			}
		}
	})
	
end

for _, model_mbin in ipairs(MODELS) do
	new_model_mbin = model_mbin:gsub("MODELS/PLANETS/BIOMES/FROZEN/",NEW_MODEL_DIR)
	backslash_model_dir = NEW_MODEL_DIR:gsub([[/]],[[\]])
	table.insert(MBIN_CHANGE_TABLE,{
		["MBIN_FILE_SOURCE"] = {
			{model_mbin,new_model_mbin},
			{model_mbin:gsub(".SCENE.",".DESCRIPTOR."),new_model_mbin:gsub(".SCENE.",".DESCRIPTOR.")},
		}
	})
	table.insert(MBIN_CHANGE_TABLE,{
		["MBIN_FILE_SOURCE"] = {new_model_mbin},
		["EXML_CHANGE_TABLE"] = {
			{
				["REPLACE_TYPE"] = "RAW",
				["NOTICE_OFF"] = "TRUE",
				["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
				["VALUE_CHANGE_TABLE"] = {
					{[[MODELS\PLANETS\BIOMES\FROZEN\]], backslash_model_dir}
				}
			}
		}
	})
end

--Special rules
table.insert(MBIN_CHANGE_TABLE,{
	["MBIN_FILE_SOURCE"] = {NEW_MODEL_DIR.."LARGEPROPS/LARGETREE.SCENE.MBIN"},
	["EXML_CHANGE_TABLE"] = {
		{
			["SPECIAL_KEY_WORDS"] = {"Value", string.gsub(NEW_MODEL_DIR,[[/]],[[\]]).."LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN"},
			["SECTION_UP"] = 2,
			["REMOVE"] = "SECTION",
			["REPLACE_TYPE"] = "ALL"
		}
	}
})

table.insert(MBIN_CHANGE_TABLE,{
	["MBIN_FILE_SOURCE"] = {NEW_MODEL_DIR.."LARGEPROPS/LARGETREEBARE.SCENE.MBIN"},
	["EXML_CHANGE_TABLE"] = {
		{
			["SPECIAL_KEY_WORDS"] = {"Value", string.gsub(NEW_MODEL_DIR,[[/]],[[\]]).."LARGEPROPS\LARGETREEBARE\HANGINGICESOLID_MAT.MATERIAL.MBIN"},
			["SECTION_UP"] = 2,
			["REMOVE"] = "SECTION",
			["REPLACE_TYPE"] = "ALL"
		},
		{
			["SPECIAL_KEY_WORDS"] = {"Value", string.gsub(NEW_MODEL_DIR,[[/]],[[\]]).."LARGEPROPS\LARGETREEBARE\SNOWTILING_MAT.MATERIAL.MBIN"},
			["SECTION_UP"] = 2,
			["REMOVE"] = "SECTION",
			["REPLACE_TYPE"] = "ALL"
		},
	}
})

NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] = "AlpinModels.pak",
  ["MOD_BATCHNAME"] = "Spacefarer-Biomes-RequiredAssets.pak",
  ["MOD_AUTHOR"] = "CodenameAwesome",
  ["ADD_FILES"] = ADD_FILES,
  ["MODIFICATIONS"] =
	{
		{
			["MBIN_CHANGE_TABLE"] =  MBIN_CHANGE_TABLE
		}
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE