NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] = "LushRadioTreesModels.pak",
  ["MOD_BATCHNAME"] = "Spacefarer-Biomes-RequiredAssets.pak",
  ["MOD_AUTHOR"] = "CodenameAwesome",
  ["MODIFICATIONS"] =
	{
		{
			["MBIN_CHANGE_TABLE"] =  {
				{
					["MBIN_FILE_SOURCE"] = {"MODELS/PLANETS/BIOMES/COMMON/TREES/MEDIUMTREE1/FRONDMAT.MATERIAL.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name", "gDiffuseMap"},
							["VALUE_CHANGE_TABLE"] = {
								{"Map","TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/FRONDS/FROND.BASE.1.DDS"}
							}
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"MODELS/PLANETS/BIOMES/COMMON/TREES/MEDIUMTREE1/FRONDMAT.MATERIAL.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name", "gMasksMap"},
							["VALUE_CHANGE_TABLE"] = {
								{"Map","TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/FRONDS/FROND.BASE.1.MASKS.DDS"}
							}
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"MODELS/PLANETS/BIOMES/COMMON/TREES/MEDIUMTREE1/FRONDMAT.MATERIAL.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name", "gNormalMap"},
							["VALUE_CHANGE_TABLE"] = {
								{"Map","TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/FRONDS/FROND.BASE.1.NORMAL.DDS"}
							}
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/FRONDS/FROND.TEXTURE.MBIN",},
					["EXML_CHANGE_TABLE"] = 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Name","OVERLAY"},
							["INTEGER_TO_FLOAT"] = "FORCE",
							["VALUE_CHANGE_TABLE"] = {
								{"Probability",0.5}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","1"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND1.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND1.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND1.BASE.MASKS.DDS"},
							}	
						},
						--no equivalent for frond 2
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","3"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND3.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND3.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND3.BASE.MASKS.DDS"},
							}	
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","4"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND4.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND4.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND4.BASE.MASKS.DDS"},
							}	
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","4"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND4.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND4.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND4.BASE.MASKS.DDS"},
							}	
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","5"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND5.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND5.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND5.BASE.MASKS.DDS"},
							}	
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","6"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND6.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND6.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND6.BASE.MASKS.DDS"},
							}	
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","7"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND7.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND7.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND7.BASE.MASKS.DDS"},
							}	
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","8"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND8.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND8.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND8.BASE.MASKS.DDS"},
							}	
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","9"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND9.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND9.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND9.BASE.MASKS.DDS"},
							}	
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","BASE","Name","10"},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Diffuse",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND10.BASE.DDS"},
								{"Normal",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND10.BASE.NORMAL.DDS"},
								{"Mask",	"TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQFROND10.BASE.MASKS.DDS"},
							}	
						},
						--no equivalent for frond 11
						--no equivalent for frond 12
					}
				},
			}
		}
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE