ModName = "PTSd UI Description Adjustments"
GameVersion = "5_12"
Description = "Changes the UI display for things like Settlement Production rate, Crop Growth time (in the construction menu), Tech descriptions, etc. to match the adjusted PTSd rates"

AnalysisVisorDesc =
[[Specialist &lt;TECHNOLOGY&gt;Discovery&lt;&gt; and &lt;TECHNOLOGY&gt;Survey&lt;&gt; unit.&#xA;&#xA;Augments standard &lt;TECHNOLOGY&gt;Scanner&lt;&gt; capabilities by projecting detailed environmental data directly over the user's visor. Allows the identification of &lt;STELLAR&gt;distant points of interest&lt;&gt;.&#xA;&#xA;The Visor will generate &lt;COMMODITY&gt;valuable data&lt;&gt; when used to study &lt;TRADEABLE&gt;flora&lt;&gt;, &lt;FUEL&gt;fauna&lt;&gt; and &lt;TECHNOLOGY&gt;minerals&lt;&gt;.&#xA;This data's value is further boosted by the &lt;TECHNOLOGY&gt;Scanning&lt;&gt; stat bonus for your Multi-Tool's type.&#xA;&#xA;Hold &lt;IMG&gt;AIM&lt;&gt; to operate. Press &lt;IMG&gt;ZOOM&lt;&gt; to zoom.]]

AnalysisVisorDescVR =
[[Specialist &lt;TECHNOLOGY&gt;Discovery&lt;&gt; and &lt;TECHNOLOGY&gt;Survey&lt;&gt; unit.&#xA;Augments standard &lt;TECHNOLOGY&gt;Scanner&lt;&gt; capabilities by projecting detailed environmental data directly over the user's visor. Allows the identification of &lt;STELLAR&gt;distant points of interest&lt;&gt;.&#xA;&#xA;The Visor will generate &lt;COMMODITY&gt;valuable data&lt;&gt; when used to study &lt;TRADEABLE&gt;flora&lt;&gt;, &lt;FUEL&gt;fauna&lt;&gt; and &lt;TECHNOLOGY&gt;minerals&lt;&gt;.&#xA;This data's value is further boosted by the &lt;TECHNOLOGY&gt;Scanning&lt;&gt; stat bonus for your Multi-Tool's type.&#xA;&#xA;Hold &lt;IMG&gt;AIM&lt;&gt; to operate.]]

MiningBeamDesc =
[[Multi-Tool &lt;TECHNOLOGY&gt;Mining Beam&lt;&gt; powered by &lt;FUEL&gt;Carbon-based Elements&lt;&gt;. Fire the beam with &lt;IMG&gt;ATTACK&lt;&gt;.&#xA;&#xA;Installs focusing optics within the Multi-Tool, allowing it to emit a &lt;STELLAR&gt;high-energy beam&lt;&gt;. The beam is calibrated to excite molecules within common &lt;STELLAR&gt;organic or geological objects&lt;&gt;, allowing it to operate as a highly effective mining device.&#xA;The substance yield is further boosted by the &lt;TECHNOLOGY&gt;Mining&lt;&gt; stat bonus for your Multi-Tool's type.&#xA;&#xA;&lt;FUEL&gt;WARNING&lt;&gt;: Destruction of flora, fauna or minerals may attract Sentinel attention.]]

HijackedLaserDesc =
[[&lt;FUEL&gt;NOTE&lt;&gt;: To be used &lt;STELLAR&gt;instead of&lt;&gt; the default Mining Beam, not in addition to it.&#xA;This Multi-Tool is made with material and methods known to no conventional manufacturer, its core a unfathomable array of impossible optics and glassy foam. Nonetheless, there is a layer of recogniseable technology. It shows signs of having been &lt;STELLAR&gt;tampered with&lt;&gt; by an unknown craftsman, who has repurposed its scanner array into a &lt;TECHNOLOGY&gt;high-powered mining laser&lt;&gt;.&#xA;The substance yield is further boosted by the &lt;TECHNOLOGY&gt;Mining&lt;&gt; stat bonus for your Multi-Tool's type.&#xA;&#xA;Powered by &lt;FUEL&gt;Carbon-based Elements&lt;&gt;. Fire the beam with &lt;IMG&gt;ATTACK&lt;&gt;.]]

RunicLensDesc =
[[&lt;FUEL&gt;NOTE&lt;&gt;: To be used &lt;STELLAR&gt;instead of&lt;&gt; the default Mining Beam, not in addition to it.&#xA;The geometric heart of this ancient weapon is the &lt;TECHNOLOGY&gt;Runic Lens&lt;&gt;. Its impossible geometry not only concentrates light into a high-powered &lt;TECHNOLOGY&gt;Mining Laser&lt;&gt;, but can also warp the local electromagnetic field so as to render the user &lt;STELLAR&gt;invisible&lt;&gt;.&#xA;The substance yield is further boosted by the &lt;TECHNOLOGY&gt;Mining&lt;&gt; stat bonus for your Multi-Tool's type.&#xA;&#xA;Powered by &lt;FUEL&gt;Carbon-based Elements&lt;&gt;. Fire the beam with &lt;IMG&gt;ATTACK&lt;&gt;. Select its secondary cloaking function with &lt;IMG&gt;CYCLEALTWEAPON&lt;&gt; and hold &lt;IMG&gt;ALTATTACK&lt;&gt; to activate. ]]

AnimusBeamDesc =
[[A unique overload to the Multi-Tool's standard mining laser. Beam frequency is modulated precisely in a feedback loop with the delta-waves generated by the impact target.&#xA;&#xA;Recordings of the target's experiences are thus etched into tiny fragments of metal and rendered as &lt;STELLAR&gt;Fragmented Qualia&lt;&gt;. Readability of collected fragments is not guaranteed.&#xA;The substance yield is further boosted by the &lt;TECHNOLOGY&gt;Mining&lt;&gt; stat bonus for your Multi-Tool's type.]]

VesperSailDesc =
[[A high-performance &lt;STELLAR&gt;solar sail&lt;&gt;, deployed automatically during flight. This advanced &lt;TECHNOLOGY&gt;propulsion device&lt;&gt; generates an electric field within the sails themselves, allowing the starship to build momentum from the solar wind.&#xA;&#xA;Offers substantial gains in &lt;STELLAR&gt;fuel efficiency&lt;&gt; and &lt;STELLAR&gt;Pulse Jump speed&lt;&gt; performance over conventional engine systems, as well as the photovoltaic cells enabling more &lt;STELLAR&gt;efficient&lt;&gt; use of the starship's &lt;TECHNOLOGY&gt;launch systems&lt;&gt;.]]

LargeRocketTubesDesc =
[[Expands the loading chamber of the starship &lt;TECHNOLOGY&gt;Rocket Launcher&lt;&gt;, improving payload size and allowing for significantly higher &lt;STELLAR&gt;damage&lt;&gt;.]]

PhaseBeamDesc =
[[A &lt;TECHNOLOGY&gt;high-energy beam weapon&lt;&gt; for ship-to-ship combat. &#xA;&#xA;Though vulnerable to &lt;FUEL&gt;overheating&lt;&gt;, these highly accurate laser weapons can &lt;STELLAR&gt;recharge the users's shields&lt;&gt; by leeching energy from target shield systems. Shield leech effect is relatively &lt;STELLAR&gt;stronger&lt;&gt; the higher the user's &lt;STELLAR&gt;maximum shield capacity&lt;&gt; is.&#xA;&#xA;Use &lt;IMG&gt;CYCLEWEAPON&lt;&gt; to change weapon mode. Press &lt;IMG&gt;SHIPFIRE&lt;&gt; to fire.]]

GraftedEyesDesc =
[[A complex arrangement of membranes and lens, fused atop a high-energy laser array. Incineration awaits those that meet their stare.&#xA;Press &lt;IMG&gt;SHIPFIRE&lt;&gt; request the eyes gaze upon nearby targets and &lt;STELLAR&gt;recharge its own shields&lt;&gt; by leeching energy from target shield systems. Shield leech effect is relatively &lt;STELLAR&gt;stronger&lt;&gt; the higher the user's &lt;STELLAR&gt;maximum shield capacity&lt;&gt; is.]]

PhotonCannonDesc =
[[A destructive &lt;TECHNOLOGY&gt;starship projectile launcher&lt;&gt; with a high &lt;STELLAR&gt;critical hit&lt;&gt; damage multiplier, the weapons system of choice for the interstellar trader and pirate alike.&#xA;&#xA;Use &lt;IMG&gt;CYCLEWEAPON&lt;&gt; to change weapon mode. Press &lt;IMG&gt;SHIPFIRE&lt;&gt; to fire.]]

PositronEjectorDesc =
[[A powerful starship weapon, capable of delivering &lt;STELLAR&gt;extreme destruction&lt;&gt; at &lt;TECHNOLOGY&gt;close range&lt;&gt;. Recovers from heat buildup faster by &lt;FUEL&gt;overheating&lt;&gt; rather than allowing to cool normally. &#xA;&#xA;Note: these particles show &lt;TITLE&gt;decreased effectiveness&lt;&gt; against shielded targets.&#xA;&#xA;Use &lt;IMG&gt;CYCLEWEAPON&lt;&gt; to change weapon mode. Press &lt;IMG&gt;SHIPFIRE&lt;&gt; to fire.]]

BoltcasterDesc =
[[Generalist weapon attachment for the &lt;TECHNOLOGY&gt;Multi-Tool&lt;&gt; with a high &lt;STELLAR&gt;critical hit&lt;&gt; damage multiplier. Access fire mode by pressing &lt;IMG&gt;CYCLEWEAPON&lt;&gt; and fire weapon with &lt;IMG&gt;ATTACK&lt;&gt;.&#xA;&#xA;The &lt;TECHNOLOLY&gt;Boltcaster&lt;&gt; reconfigures the Multi-Tool to supercharge &lt;EARTH&gt;Metallic Elements&lt;&gt;, firing them as &lt;STELLAR&gt;high-velocity projectiles&lt;&gt; capable of causing extreme damage.]]

CargoScanDefDesc =
[[A specially tuned resonance jammer, designed to interfere with the remote &lt;STELLAR&gt;cargo scans&lt;&gt; deployed by system authorities in the search for &lt;SPECIAL&gt;smuggled goods&lt;&gt;, or by &lt;FUEL&gt;pirates&lt;&gt; searching for valuable cargo.&#xA;&#xA;Deploy from the &lt;TECHNOLOGY&gt;Quick Menu&lt;&gt; (&lt;IMG&gt;QUICK_MENU&lt;&gt;) while a scan is in progress to deflect the probe. Note: jamming is not 100% effective.&#xA;&#xA;Can be useful to bind to a hotkey to activate quickly, multiple times per scan attempt.]]

NeuralShieldDesc =
[[A beautiful living weave of nanotubes, laced through the vessel's neural assembly. This structure can be energised as the ship deems fit, creating a field that &lt;STELLER&gt;blocks&lt;&gt; hostile &lt;STELLAR&gt;cargo probes&lt;&gt; by either system authorities or &lt;FUEL&gt;pirates&lt;&gt;.&#xA;&#xA;Use the &lt;TECHNOLOGY&gt;Quick Menu&lt;&gt; (&lt;IMG&gt;QUICK_MENU&lt;&gt;) while a scan is in progress to ask that the ship might block the scan.&#xA;&#xA;Can be useful to bind to a hotkey to activate quickly, multiple times per scan attempt.]]

TeleportReceiver =
[[A device that modulates standard starship communication signals to &lt;TECHNOLOGY&gt;enable the transport of matter&lt;&gt; as well as data.&#xA;&#xA;Starships fitted with such a device can send and receive products and substances to a user's exosuit over a &lt;VAL_ON&gt;long distance&lt;&gt;, up to &lt;STELLAR&gt;800u&lt;&gt; away.]]

EmerilDriveDesc =
[[Upgrades the hyperdrive's shield integrity, preventing reality glitches when attempting to reach rare-class &lt;TRADEABLE&gt;green&lt;&gt; or &lt;FUEL&gt;red&lt;&gt; &lt;TRADEABLE&gt;stellar bodies&lt;&gt;.&#xA;&#xA;User is advised to access Hyperdrive systems via the &lt;VAL_ON&gt;Galactic Map&lt;&gt;.]]

IndiumDriveDesc =
[[Upgrades the hyperdrive's computational matrix,  preventing temporal anomalies when attempting to reach rare-class &lt;TECHNOLOGY&gt;blue&lt;&gt;, &lt;TRADEABLE&gt;green&lt;&gt;, or &lt;FUEL&gt;red&lt;&gt; &lt;TECHNOLOGY&gt;stellar bodies&lt;&gt;.&#xA;&#xA;User is advised to access Hyperdrive systems via the &lt;VAL_ON&gt;Galactic Map&lt;&gt;.]]

DreamsDeep3Msg4 =
[[Purchase the &lt;TECHNOLOGY&gt;High-Power Sonar&lt;&gt; blueprints from aboard the &lt;SPECIAL&gt;Space Anomaly&lt;&gt;, then install it in the Nautilon.&#xA;Access the Nautilon's inventory and craft in an empty slot with &lt;IMG&gt;TECHMENU&lt;&gt;&#xA;Pin the blueprint recipe for detailed instructions with &lt;IMG&gt;PIN&lt;&gt;]]

DreamsDeep3Obj3Tip =
[[The abandoned radio structure only contained blueprints for a &lt;TECHNOLOGY&gt;Basic Sonar&lt;&gt;.&#xA;Purchase the &lt;TECHNOLOGY&gt;High-Power Sonar&lt;&gt; blueprints from aboard the &lt;SPECIAL&gt;Space Anomaly&lt;&gt;, then install it in the Nautilon.&#xA;Access the Nautilon's inventory and craft in an empty slot with &lt;IMG&gt;TECHMENU&lt;&gt;.&#xA;Pin the blueprint recipe for detailed instructions with &lt;IMG&gt;PIN&lt;&gt;.]]

SonarQuickMenu =
[[Use Sonar]]

SonarQuickMenuFail =
[[No Sonar Installed]]

Sonar =
[[Sonar]]

BasicSonarDesc =
[[A high-detail sonar device, capable of upgrading the scanner technology aboard a Nautilon-class submarine to Analysis Visor levels.&#xA;Press &lt;IMG&gt;SCAN&lt;&gt; to activate the Basic Sonar.]]

AMUDesc =
[[An &lt;TECHNOLOGY&gt;automated harvester&lt;&gt; for the mining of resources. Once activated, the AMU extracts minerals for up to &lt;TECHNOLOGY&gt;10 minutes&lt;&gt; before collecting and &lt;FUEL&gt;refueling&lt;&gt;.&#xA;&#xA;&lt;FUEL&gt;NOTE&lt;&gt;: It is recommended to remain in the &lt;TECHNOLOGY&gt;same system&lt;&gt; during operation and to &lt;STELLAR&gt;delete and rebuild&lt;&gt; this unit before refueling it to reduce the chances of a &lt;HIGHLIGHT&gt;vanilla glitch&lt;&gt; clearing its contents.]]

OxygenHarvesterDesc =
[[An &lt;TECHNOLOGY&gt;autonomous atmosphere extractor&lt;&gt;, this device can be left to collect and purify &lt;STELLAR&gt;oxygen&lt;&gt; from the air for up to &lt;TECHNOLOGY&gt;10 minutes&lt;&gt; before collecting and &lt;FUEL&gt;refueling&lt;&gt;.&#xA;&#xA;The resulting gas is compressed and processed, ready for use in all standard &lt;FUEL&gt;life support systems&lt;&gt;.&#xA;&#xA;&lt;FUEL&gt;NOTE&lt;&gt;: It is recommended to remain in the &lt;TECHNOLOGY&gt;same system&lt;&gt; during operation and to &lt;STELLAR&gt;delete and rebuild&lt;&gt; this unit before refueling it to reduce the chances of a &lt;HIGHLIGHT&gt;vanilla glitch&lt;&gt; clearing its contents.]]

AtmosphereHarvesterDesc =
[[An &lt;TECHNOLOGY&gt;automated siphon unit&lt;&gt; for the collection of valuable gases. Once activated, the harvester condenses and compresses substances from the air for up to &lt;TECHNOLOGY&gt;10 minutes&lt;&gt; before collecting and &lt;FUEL&gt;refueling&lt;&gt;. Compressed gas is then stored safely until collected.&#xA;&#xA;&lt;FUEL&gt;NOTE&lt;&gt;: It is recommended to remain in the &lt;TECHNOLOGY&gt;same system&lt;&gt; during operation and to &lt;STELLAR&gt;delete and rebuild&lt;&gt; this unit before refueling it to reduce the chances of a &lt;HIGHLIGHT&gt;vanilla glitch&lt;&gt; clearing its contents.]]

AntimatterReactorDesc =
[[An &lt;TECHNOLOGY&gt;autonomous baryogenesis reactor&lt;&gt;, this device can be left to harvest reality paradoxes and convert them into usable &lt;FUEL&gt;antimatter&lt;&gt; for up to &lt;TECHNOLOGY&gt;10 minutes&lt;&gt; before collecting and &lt;FUEL&gt;refueling&lt;&gt;.&#xA;&#xA;The resulting antimatter is safely contained, ready for use in all standard &lt;FUEL&gt;hyperspace power units&lt;&gt;.]]

ScannerRoomDesc =
[[Advanced integrated freighter equipment. By consuming some &lt;STELLAR&gt;Navigation Data&lt;&gt; to orient itself, this &lt;TECHNOLOGY&gt;planetary scanner&lt;&gt; probes all celestial bodies in the local solar system. This module is placed as an &lt;STELLAR&gt;entire room&lt;&gt; and comes with its functional units pre-installed.&#xA;&#xA;Scanned moons and planets are &lt;STELLAR&gt;Discovered&lt;&gt;, and sensors collect high-level data such as weather conditions and prominent resources.]]

ConsciousnessBridgeMissionHint =
[[The Void Egg requires a &lt;TECHNOLOGY&gt;Consciousness Bridge&lt;&gt;&#xA;Gather %ITEM% to craft Consciousness Bridge: %CURRENT%/%AMOUNT%&#xA;%ITEM% can be mined on planets in &lt;TRADEABLE&gt;green star systems&lt;&gt;]]

ESSDesc =
[[A &lt;STELLAR&gt;single-use&lt;&gt; receiver that scans for distress signals on &lt;TECHNOLOGY&gt;freighter frequencies&lt;&gt;. Derelict or abandoned freighters often contain &lt;STELLAR&gt;high-value salvage&lt;&gt; and &lt;HIGHLIGHT&gt;large amounts of nanites&lt;&gt;.&#xA;&#xA;Select the Receiver and use Tune Signal (&lt;IMG&gt;FE_ALT1&lt;&gt;) to begin the location process.]]

DerelictLootTip =
[[The &lt;STELLAR&gt;Space Station&lt;&gt; offers several opportunities to profit from salvage.&#xA;Both &lt;TECHNOLOGY&gt;Scrap Dealers&lt;&gt; and &lt;TRADEABLE&gt;Guild Envoys&lt;&gt; may be interested in acquiring data from the derelict freighter.&#xA;&#xA;&lt;TECHNOLOGY&gt;Scrap Dealers&lt;&gt; offer &lt;SPECIAL&gt;Tainted Metal&lt;&gt; while &lt;TRADEABLE&gt;Guild Envoys&lt;&gt; offer &lt;TRADE&gt;Units&lt;&gt; and &lt;STELLAR&gt;Standing&lt;&gt;]]

DerelictCrewPopup =
[[Offload the &lt;STELLAR&gt;Crew Manifest&lt;&gt;&#xA;&lt;TECHNOLOGY&gt;Scrap Dealers&lt;&gt; offer &lt;SPECIAL&gt;Tainted Metal&lt;&gt; while &lt;TRADEABLE&gt;Guild Envoys&lt;&gt; offer &lt;TRADE&gt;Units&lt;&gt; and &lt;STELLAR&gt;Standing&lt;&gt;]]

DerelictLogPopup =
[[Offload the &lt;STELLAR&gt;Captain's Log&lt;&gt;&#xA;&lt;TECHNOLOGY&gt;Scrap Dealers&lt;&gt; offer &lt;SPECIAL&gt;Tainted Metal&lt;&gt; while &lt;TRADEABLE&gt;Guild Envoys&lt;&gt; offer &lt;TRADE&gt;Units&lt;&gt; and &lt;STELLAR&gt;Standing&lt;&gt;]]

ReinforcedDoor =
[[Reinforced Door (Destroy nearby &lt;SPECIAL&gt;sentinels&lt;&gt;)]]

CargoPod =
[[Cargo Pod - Contents &lt;SPECIAL&gt;Unknown&lt;&gt;]]

ReleaseFish =
[[RELEASE FISH FOR &lt;STELLAR&gt;NANITES&lt;&gt;]]

ReleaseFishDesc =
[[Return your catch to the water for &lt;STELLAR&gt;nanites&lt;&gt; based on its &lt;HIGHLIGHT&gt;rarity&lt;&gt;]]

SentPillarLeftPane =
[[WARNING: [ &lt;SPECIAL&gt;BOUNDARY NODE EXPOSED&lt;&gt; ]&#xA;BOUNDARY ARCHIVE STATUS: [ &lt;SPECIAL&gt;VULNERABLE&lt;&gt; ]&#xA;&#xA;Destroy nearby &lt;FUEL&gt;Sentinel Mech&lt;&gt; to earn the right to use this terminal &lt;STELLAR&gt;honourably&lt;&gt;]]

BuyNewSlot =
[[Select any empty space in Cargo or Technology with &lt;IMG&gt;FE_SELECT&lt;&gt; to install new slot&#xA;&#xA;For the default PTSd experience, only increase &lt;METAL&gt;Exosuit&lt;&gt; slots to &lt;STELLAR&gt;40&lt;&gt; &lt;TECHNOLOGY&gt;Technology&lt;&gt; and &lt;STELLAR&gt;40&lt;&gt; &lt;COMMODITY&gt;Cargo&lt;&gt;]]

BuyNewSlotMP =
[[Select any empty space in Cargo or Technology with &lt;IMG&gt;FE_SELECT&lt;&gt; to install new slot (%NUM% available)&#xA;&#xA;For the default PTSd experience, only increase &lt;METAL&gt;Exosuit&lt;&gt; slots to &lt;STELLAR&gt;40&lt;&gt; &lt;TECHNOLOGY&gt;Technology&lt;&gt; and &lt;STELLAR&gt;40&lt;&gt; &lt;COMMODITY&gt;Cargo&lt;&gt;]]

FreeFreighterOffer =
[[The Captain looks at me happily, almost relieved. Perhaps the burden of command had become too much for them?&#xA;Their ship and its crew is could be at my disposal, as well as command of the freighter's &lt;STELLAR&gt;Support Frigates&lt;&gt;...&#xA;But perhaps I might regret accepting such an overly generous offer.&#xA;&#xA;&lt;FUEL&gt;NOTE:&lt;&gt; For the default PTSd experience, it's recommended to decline this free rescued freighter and instead purchase your first one yourself]]

FreeFreighterSelect =
[[Give in to temptation and inspect &lt;STELLAR&gt;free&lt;&gt; freighter]]

DreadnoughtCaptain =
[[The pirate commander begs for mercy. I can demand a share of the plunder, or earn the loyalty of this vessel's crew with a show of enough units.&#xA;&#xA;&lt;FUEL&gt;WARNING:&lt;&gt; The full price must be paid &lt;HIGHLIGHT&gt;each time&lt;&gt; you select the inspect option to the right, &lt;HIGHLIGHT&gt;before&lt;&gt; confirming to exchange freighers.&#xA;&#xA;Before proceeding with this purchase, first use your Analysis Visor to view the details of this Dreadnought, and potentially summon your Freighter to uninstall any technology]]

DreadnoughtSeize =
[[&lt;HIGHLIGHT&gt;Pay&lt;&gt; to inspect Dreadnought]]

DreadnoughtTribute =
[[Demand tribute of units, nanites, and goods]]

PirateFrigate =
[[Pirate Frigate - Dreadnought will summon to keep &lt;HIGHLIGHT&gt;at least 2&lt;&gt;]]

DreadnoughtHUDHint =
[[Fly beneath shields to destroy Dreadnought &lt;STELLAR&gt;shield generators&lt;&gt;, can also take out up to &lt;FUEL&gt;6 Pirate Frigates&lt;&gt;]]

DreadnoughtSurrenderFull =
[[The Dreadnought has &lt;TRADEABLE&gt;surrendered&lt;&gt;&#xA;Board the ship to negotiate terms&#xA;Or, destroy the ship for a chance at &lt;STELLAR&gt;minor salvage&lt;&gt;&#xA;Approach &lt;TECHNOLOGY&gt;pirate frigates&lt;&gt; to recruit survivors]]

DreadnoughtBoardDestroy =
[[Board to negotiate terms &lt;IMG&gt;SLASH&lt;&gt; Destroy for a chance at &lt;STELLAR&gt;minor salvage&lt;&gt;]]

AntiFreightCannon =
[[Anti-Freighter Cannon - &lt;HIGHLIGHT&gt;Heavy Armour&lt;&gt;]]

FreightWarpDrives =
[[Freighter Warp Drives - &lt;STELLAR&gt;Medium Armour&lt;&gt;]]

FreighterShieldGen =
[[&lt;CATALYST&gt;Freighter Shield Generator - Shielded&lt;&gt;]]

DerelictEndDesc =
[[Engineering Control Panel Accessed...&#xA;Generator failure detected. Fabricators on &lt;AUDIO&gt;TXT_RadioNoise&lt;&gt;&lt;FUEL&gt;emergency power&lt;&gt;.&#xA;The &lt;HIGHLIGHT&gt;Class&lt;&gt; of &lt;STELLAR&gt;Fabricated Tech Upgrades&lt;&gt; will be truly &lt;SPECIAL&gt;randomized&lt;&gt; each time. Construct component?]]

DerelictTech =
[[Fabricate &lt;SPECIAL&gt;Random&lt;&gt; Tech Upgrade]]

DerelictNanites =
[[Extract approx. &lt;STELLAR&gt;1,500&lt;&gt; Nanites]]

ManufacturingFacNanites =
[[Extract approx. &lt;STELLAR&gt;400&lt;&gt; Nanites]]

LeapDark3rdMonolith =
[[The Atlas told the Traveller they were the first of their kind. That a multitude would follow. Each would be endowed with the same noble soul, each able to travel from planet to planet in eternal solitude.&#xA;&#xA;The First Traveller rejected the gift of the Atlas. This was not what they hoped for. What was the purpose of infinity if you could not see it all? If you were alone? If you would one day die?&#xA;&#xA;The First Traveller cursed the Atlas, and claimed that they would find a way to survive no matter the cost.&#xA;&#xA;All of these worlds, all of time itself, it will be for the Travellers to witness.&#xA;&#xA;After inspecting so many Monoliths, I now have the ability to access &lt;SPECIAL&gt;secret terminals&lt;&gt; at Monoliths in &lt;TECHNOLOGY&gt;Korvax systems&lt;&gt;.]]

LeapDarkAfter3rdMonolithTip =
[[The ancient monuments have supplied a series of glyphs. Perhaps they hold the key to opening a portal...&#xA;&#xA;Also, after inspecting so many Monoliths, I now have the ability to access &lt;SPECIAL&gt;secret terminals&lt;&gt; at Monoliths in &lt;TECHNOLOGY&gt;Korvax systems&lt;&gt;.]]

BasaltDesc =
[[Local mineral extract, typically found in large deposits or extracted from common minerals after inspection with an &lt;TECHNOLOGY&gt;Analysis Visor&lt;&gt;.&#xA;&#xA;Typically found on planets with a &lt;FUEL&gt;volcanic environment&lt;&gt;.&#xA;&#xA;Can be processed into &lt;STELLAR&gt;Silicate Powder&lt;&gt; in a refiner.]]

AtlasPass2Desc =
[[Security and permissions pass granted to specific travellers by many primary galactic species.&#xA; &#xA;Provides access to mid-tier or lower restricted areas and outpost systems.]]

AtlasPass3Desc =
[[Security and permissions pass granted to specific travellers by many primary galactic species.&#xA; &#xA;Provides access to high level or lower restricted areas and outpost systems.]]

PearlDesc =
[[Gemstone formed over the course of centuries within the egg of a super-incubatory species. Highly ornamental, these gems are themselves living seeds, lucent grains of potential life.&#xA;&#xA;Can be sold at a &lt;TECHNOLOGY&gt;Galactic Trade Terminal&lt;&gt;, or &lt;FUEL&gt;refined together&lt;&gt; with &lt;STELLAR&gt;Gravitino Balls&lt;&gt; to extract the &lt;TECHNOLOGY&gt;Di-Hydrogen&lt;&gt; within them.]]

GravDesc =
[[A supersymmetric particle cluster created by divergent super-gravitational forces. A &lt;STELLAR&gt;micro-rift&lt;&gt; is created as they form, and extraction of the orb prompts a localised reality weakening. &lt;FUEL&gt;Sentinel forces&lt;&gt; will respond to stablise any such anomaly.&#xA;&#xA;Can be sold at a &lt;TECHNOLOGY&gt;Galactic Trade Terminal&lt;&gt;, or &lt;FUEL&gt;refined together&lt;&gt; with &lt;STELLAR&gt;Albumen Pearls&lt;&gt; or &lt;STELLAR&gt;Sac Venom&lt;&gt; to extract useful substances from them.]]

VenomDesc =
[[A stabilised poison gland extracted from a terrestrial urchin. The host-urchin is actually a colony of smaller proto-creatures, a formation built on years of slow growth and cooperation.&#xA;&#xA;Of use both medicinally and as a delicacy in some riskier cuisines.&#xA;&#xA;Can be sold at a &lt;TECHNOLOGY&gt;Galactic Trade Terminal&lt;&gt;, or &lt;FUEL&gt;refined together&lt;&gt; with &lt;STELLAR&gt;Gravitino Balls&lt;&gt; to extract the &lt;TECHNOLOGY&gt;Tritium&lt;&gt; within them.]]

PearlTime =
[[A medium-sized, farmable Crystal Orb that yields an occasional harvest of valuable Albumen Pearls, as well as &lt;STELLAR&gt;nanites&lt;&gt;.&#xA;&#xA;Suitable for hydroponic indoor planting. Cannot be planted outdoors.&#xA;&#xA;Approximate growing time: &lt;TECHNOLOGY&gt;1 hour&lt;&gt;&#xA;&#xA;Very high &lt;TECHNOLOGY&gt;units/hour&lt;&gt; but low &lt;TECHNOLOGY&gt;units/harvest&lt;&gt; and low &lt;STELLAR&gt;nanites/hour&lt;&gt;]]

GravTime =
[[A strange, potentially parasitic plant that yields an occasional harvest of the highly tradable commodity, Gravitino Balls, as well as &lt;STELLAR&gt;nanites&lt;&gt;.&#xA;&#xA;Suitable for hydroponic indoor planting. Cannot be planted outdoors.&#xA;&#xA;Approximate growing time: &lt;TECHNOLOGY&gt;4 hours&lt;&gt;&#xA;&#xA;Low &lt;TECHNOLOGY&gt;units/hour&lt;&gt; and low &lt;TECHNOLOGY&gt;units/harvest&lt;&gt; but high &lt;STELLAR&gt;nanites/hour&lt;&gt;]]

VenomTime =
[[A small, innocuous looking plant whose leaves periodically secrete a small amount of potent Sac Venom, a valuable trading commodity, as well as &lt;STELLAR&gt;nanites&lt;&gt;.&#xA;&#xA;Suitable for hydroponic indoor planting. Cannot be planted outdoors.&#xA;&#xA;Approximate growing time: &lt;TECHNOLOGY&gt;12 hours&lt;&gt;&#xA;&#xA;Low &lt;TECHNOLOGY&gt;units/hour&lt;&gt; and low &lt;STELLAR&gt;nanites/hour&lt;&gt;, but very high &lt;TECHNOLOGY&gt;units/harvest&lt;&gt;]]

NipNipTime =
[[This medicinal herb is known for its pungent buds, which are harvested to produce Gek Nip. NipNip thrives in dank environments, and often grows as a weed.&#xA;&#xA;Suitable for hydroponic planting indoors. Cannot be planted outdoors.&#xA;&#xA;Approximate growing time: &lt;TECHNOLOGY&gt;4 hours 20 mins&lt;&gt;&#xA;&#xA;High &lt;TECHNOLOGY&gt;units/hour&lt;&gt; and high &lt;TECHNOLOGY&gt;units/harvest&lt;&gt; but does not produce nanites]]

Mealworms =
[[A piece of specialist &lt;STELLAR&gt;bait&lt;&gt;, designed to improve the &lt;HIGHLIGHT&gt;rarity&lt;&gt; of your catch, with a slight improvement to &lt;STELLAR&gt;size&lt;&gt;.&#xA;&#xA;Locate your &lt;TECHNOLOGY&gt;Fishing Rig&lt;&gt; and begin bait application with &lt;IMG&gt;FE_ALT1&lt;&gt;.]]

SpicyChum =
[[A piece of specialist &lt;STELLAR&gt;bait&lt;&gt;, designed to greatly improve the &lt;HIGHLIGHT&gt;rarity&lt;&gt; of your catch, with a little improvement to &lt;STELLAR&gt;size&lt;&gt;.&#xA;&#xA;Locate your &lt;TECHNOLOGY&gt;Fishing Rig&lt;&gt; and begin bait application with &lt;IMG&gt;FE_ALT1&lt;&gt;.]]

BionicLure =
[[A specialist &lt;STELLAR&gt;lure&lt;&gt;, designed to vastly improve the &lt;HIGHLIGHT&gt;rarity&lt;&gt; of your catch, with a decent improvement to &lt;STELLAR&gt;size&lt;&gt;. Of particular interest to anglers seeking &lt;COMMODITY&gt;legendary fish&lt;&gt;.&#xA;&#xA;Locate your &lt;TECHNOLOGY&gt;Fishing Rig&lt;&gt; and begin bait application with &lt;IMG&gt;FE_ALT1&lt;&gt;.]]

DanglingOrb =
[[A specialist &lt;STELLAR&gt;lure&lt;&gt;, designed to greatly attract &lt;COMMODITY&gt;diurnal&lt;&gt; fish during the day, which are &lt;STELLAR&gt;slightly more valuable&lt;&gt; than normal fish.&#xA;Also improves the &lt;HIGHLIGHT&gt;rarity&lt;&gt; and &lt;STELLAR&gt;size&lt;&gt; of your catch only slightly less than Spicy Chum.&#xA;&#xA;Locate your &lt;TECHNOLOGY&gt;Fishing Rig&lt;&gt; and begin bait application with &lt;IMG&gt;FE_ALT1&lt;&gt;.]]

ShadowLure =
[[A specialist &lt;STELLAR&gt;lure&lt;&gt;, designed to greatly attract &lt;SPECIAL&gt;nocturnal&lt;&gt; fish at night, which are &lt;STELLAR&gt;slightly more valuable&lt;&gt; than normal fish.&#xA;Also improves the &lt;HIGHLIGHT&gt;rarity&lt;&gt; and &lt;STELLAR&gt;size&lt;&gt; of your catch only slightly less than Spicy Chum.&#xA;&#xA;Locate your &lt;TECHNOLOGY&gt;Fishing Rig&lt;&gt; and begin bait application with &lt;IMG&gt;FE_ALT1&lt;&gt;.]]

MagpulseLure =
[[A specialist &lt;STELLAR&gt;lure&lt;&gt;, designed to greatly attract fish that are only active during &lt;TECHNOLOGY&gt;storms&lt;&gt; while a storm is occuring, which are &lt;STELLAR&gt;more valuable&lt;&gt; than normal fish.&#xA;Also improves the &lt;HIGHLIGHT&gt;rarity&lt;&gt; and &lt;STELLAR&gt;size&lt;&gt; of your catch only slightly less than Spicy Chum.&#xA;&#xA;Locate your &lt;TECHNOLOGY&gt;Fishing Rig&lt;&gt; and begin bait application with &lt;IMG&gt;FE_ALT1&lt;&gt;.]]

AutoTrapDesc =
[[An autonomous fishing device, designed for long-term deployment in a wide-range of water conditions.&#xA;&#xA;Once activated, the system will lure and trap aquatic creatures from various depths &lt;STELLAR&gt;regardless of trap placement&lt;&gt; and store them for later retrieval.]]

AutoTrapAltDesc =
[[An autonomous fishing device, designed for long-term deployment in a wide-range of water conditions. Return later to collect trapped fish lured from various depths &lt;STELLAR&gt;regardless of trap placement&lt;&gt;.&#xA;&#xA;Trap cycle: &lt;TRADEABLE&gt;IN PROGRESS&lt;&gt;]]

SurvivalDiffDesc =
[[The Exosuit's &lt;CATALYST&gt;Hazard Protection&lt;&gt; protects explorers from environmental factors such as &lt;TECHNOLOGY&gt;extreme cold&lt;&gt; and &lt;TRADEABLE&gt;toxicity&lt;&gt;. Its &lt;FUEL&gt;Life Support&lt;&gt; unit provides breathable air and vital movement systems.&#xA;&#xA;This setting scales how quickly these systems are drained in challenging environments.&#xA;&#xA;&lt;TRADE&gt;Relaxed&lt;&gt;: 33% Hazard and 50% Life Support drain rate&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% Hazard and Life Support drain rate&#xA;&lt;FUEL&gt;Challenging&lt;&gt;: 150% Hazard and 150% Life Support drain rate]]

SprintingDesc =
[[&lt;STELLAR&gt;Standard&lt;&gt; sprinting places additional drain on the Exosuit's &lt;FUEL&gt;Life Support&lt;&gt; systems.&#xA;&#xA;&lt;STELLAR&gt;Relaxed&lt;&gt; sprinting removes this life support cost and increases the Sprint Stamina bar by 250%, but still requires occasional short breaks to recharge.&#xA;&#xA;&lt;STELLAR&gt;Infinite&lt;&gt; sprinting removes all restrictions and allows player to sprint forever.]]

NatResourcesDesc =
[[Mining and gathering materials such as &lt;TITLE&gt;minerals&lt;&gt;, &lt;TRADEABLE&gt;vegetation&lt;&gt;, &lt;STELLAR&gt;animal products&lt;&gt;, &lt;FUEL&gt;loot&lt;&gt;, and many other sources is essential for survival while exploring.&#xA;&#xA;This setting scales the abundance of Substance-type resources and how quickly they are gathered. Note that this actually affects the yield of most Substances collected while exploring Planets or Space, but does not apply to most automated sources such as player-planted crops, machines such as extractors or refiners, settlements, etc.&#xA;&#xA;&lt;TRADE&gt;Abundant&lt;&gt;: ~175% Substance yield&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% Substance yield&#xA;&lt;FUEL&gt;Scarce&lt;&gt;: ~63% Substance yield]]

FuelUsageDesc =
[[Technologies such as the &lt;TECHNOLOGY&gt;Mining Laser&lt;&gt; or the starship's &lt;TECHNOLOGY&gt;Launch Thrusters&lt;&gt; require regular recharging to remain functional.&#xA;&#xA;This setting scales the cost of recharging these technologies.&#xA;&#xA;&lt;TRADE&gt;Discounted&lt;&gt;: 25% Launch cost, 67% other fuel costs, refueling is 150% more efficient, Mining Laser and Terrain Manipulator consume no fuel&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% for all fuel costs and refueling efficiency&#xA;&lt;FUEL&gt;Expensive&lt;&gt;: 150% Launch cost, 133% other fuel costs, refueling is 75% as efficient]]

ScanRechargeDesc =
[[The Exosuit and starship &lt;TECHNOLOGY&gt;scanners&lt;&gt; assist with locating survival resources such as &lt;FUEL&gt;oxygen&lt;&gt; and &lt;CATALYST&gt;sodium&lt;&gt;, and can reveal additional information about planets from space. After a scan pulse, the scanner must be &lt;STELLAR&gt;recharged&lt;&gt; before it can be used again.&#xA;&#xA;This setting adjusts how quickly the scanner recharges after each scan pulse.&#xA;&#xA;&lt;HIGHLIGHT&gt;Very Fast&lt;&gt;: 500% Recharge rate&#xA;&lt;TRADE&gt;Fast&lt;&gt;: 200% Recharge rate&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% Recharge rate&#xA;&lt;FUEL&gt;Challenging&lt;&gt;: 67% Recharge rate]]

CurrencyCostDesc =
[[Items can be purchased on the &lt;VAL_ON&gt;Galactic Trade Network&lt;&gt; with &lt;COMMODITY&gt;Units&lt;&gt; (&lt;IMG&gt;UNITS&lt;&gt;). Technologies are usually purchased with &lt;TECHNOLOGY&gt;Nanites&lt;&gt; (&lt;IMG&gt;NANITE&lt;&gt;).&#xA;&#xA;This setting scales the prices of Unit and Nanite purchases across the galaxy. The &lt;STELLAR&gt;Free&lt;&gt; setting also bypasses many costs required for mission progress and other similar dialogue interactions.&#xA;&#xA;&lt;TRADE&gt;Discounted&lt;&gt;: ~50% Units and Nanites costs&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% Units and Nanites costs&#xA;&lt;FUEL&gt;Expensive&lt;&gt;: ~200% Units and ~150% Nanites costs]]

DamageLevelsDesc =
[[Hazardous environments, combat situations, or high-speed impact with the ground may all damage the Exosuit or starship.&#xA;&#xA;This setting scales the &lt;FUEL&gt;damage received&lt;&gt; in such events, as well as how many attacks an AI-piloted Minotaur exo-mech must be hit by before sustaining tech damage to a random installed tech.&#xA;&#xA;&lt;TRADE&gt;Minimal&lt;&gt;: 50% Damage received, AI-Minotaur takes 2x as many hits before being damaged&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% Damage received and standard number of hits before AI-Minotaur is damaged&#xA;&lt;FUEL&gt;Challenging&lt;&gt;: 133% Damage received, AI-Minotaur takes 0.5x as many hits before being damaged]]

EnemyStrengthDesc =
[[While exploring planets or deep space, you may occasionally encounter hostile creatures, planetary &lt;SPECIAL&gt;Sentinels&lt;&gt;, or armed &lt;FUEL&gt;pirates&lt;&gt;.&#xA;&#xA;This setting scales the difficulty of such combat encounters.&#xA;&#xA;&lt;TRADE&gt;Weak&lt;&gt;: 50% Enemy health&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% Enemy health&#xA;&lt;FUEL&gt;Challenging&lt;&gt;: 200% Enemy health]]

GroundCombatDesc =
[[While exploring on foot, explorers may be confronted by hostile forces such as &lt;SPECIAL&gt;Sentinels&lt;&gt; and &lt;SPECIAL&gt;alien monstrosities&lt;&gt;.&#xA;&#xA;This setting adjusts the frequency of such hostile encounters, particularly how soon &lt;SPECIAL&gt;Sentinel Drones&lt;&gt; spawn when loading onto a planet and the time between &lt;FUEL&gt;Planetary Pirate Raids&lt;&gt; in 2 or 3 star conflict systems.&#xA;&#xA;&lt;TRADE&gt;Minimal&lt;&gt;: 167% time for hostile spawn&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% time for hostile spawn&#xA;&lt;FUEL&gt;Hostile&lt;&gt;: 50% time for hostile spawn, and like in vanilla selecting this option will also increase the chances of some planets having &lt;FUEL&gt;Aggressive Sentinels&lt;&gt;, particularly &lt;GREEN&gt;Lush&lt;&gt; planets.]]

SpaceCombatDesc =
[[In space, explorers may be confronted by hostile forces such as &lt;FUEL&gt;pirates&lt;&gt; and vengeful &lt;FUEL&gt;system authorities&lt;&gt;.&#xA;&#xA;This setting adjusts the frequency of combat encounters in space, as well as their health.&#xA;&#xA;&lt;TRADE&gt;Minimal&lt;&gt;: 33% Random hostile encounter frequency and 80% Enemy health in space&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% Random hostile encounter frequency and Enemy health in space&#xA;&lt;FUEL&gt;Hostile&lt;&gt;: 150% Random hostile encounter frequency and 120% Enemy health in space]]

TechDamageDesc =
[[Installed &lt;TECHNOLOGY&gt;Technology Modules&lt;&gt; enhance and protect the Exosuit, Starship, and Exocraft. However, extreme environmental and combat conditions can cause these modules to become &lt;FUEL&gt;damaged&lt;&gt;.&#xA;&#xA;Your shield greatly reduces the chance of technology breaking while it remains active, and provides even better protection against tech breakage the closer it is to being full.&#xA;&#xA;This setting scales the probability of breakages to installed technology when receiving damage.&#xA;&#xA;&lt;TRADE&gt;Minimal&lt;&gt;: Low chance of tech damage&#xA;&lt;FUEL&gt;Challenging&lt;&gt;: 650% Higher chance of tech damage]]

DeathConsequencesDesc =
[[&lt;STELLAR&gt;No Item Loss&lt;&gt; will display the death screen, then resume play with no further consequences.&#xA;&#xA;&lt;STELLAR&gt;Standard&lt;&gt; will drop all carried inventory items (from your exosuit when on foot, or from your exocraft or starship if riding one) into a grave at the location of death. If the grave is reached before dying again or quitting, the items can be recovered.&#xA;&#xA;&lt;STELLAR&gt;Items Destroyed&lt;&gt; will permanently lose all carried inventory items (from your exosuit when on foot, or from your exocraft or starship if riding one).&#xA;&#xA;&lt;STELLAR&gt;Save Deleted&lt;&gt; is &lt;FUEL&gt;permadeath&lt;&gt; mode, where death will mean the end of your current journey. This option can only be selected when starting a new game, and cannot be changed later.&#xA;&lt;FUEL&gt;NOTE&lt;&gt;: Periodic backups recommended for PTSd in &lt;FUEL&gt;permadeath&lt;&gt; mode in case of unexpected deaths from mod-glitches]]

GoodsAvailableDesc =
[[&lt;TECHNOLOGY&gt;Trade Terminals&lt;&gt; in different star systems will stock a wide range and quantity of items.&#xA;&#xA;This setting scales the amount on offer, as well as restricting the purchase of some critical survival elements.&#xA;&#xA;In PTSd the purchase price of all these goods are &lt;STELLAR&gt;greatly increased&lt;&gt; on any setting, so even on the &lt;TRADE&gt;Abundant&lt;&gt; setting attempting to get most of your basic Substances or Consumables by purchasing them will cost a &lt;STELLAR&gt;significant&lt;&gt; amount of units.]]

InvStackLimitDesc =
[[Gathered resources are stored in your &lt;STELLAR&gt;Inventory&lt;&gt;, which has a limited number of slots. Multiple items of the same type can be stored in one slot.&#xA;&#xA;This setting scales the &lt;TECHNOLOGY&gt;capacity of individual inventory slots&lt;&gt;, allowing more items to be carried. For any setting, the stacksize of slots in various inventories will be as follows:&#xA;&#xA;&lt;HIGHLIGHT&gt;1x&lt;&gt;: Exosuit&#xA;~&lt;HIGHLIGHT&gt;1.5x&lt;&gt;: Exocraft&#xA;&lt;HIGHLIGHT&gt;2x&lt;&gt;: Refiners, Starships&#xA;&lt;HIGHLIGHT&gt;4x&lt;&gt;: Freighter, Storage Containers&#xA;&#xA;&lt;TRADE&gt;Spacious&lt;&gt;: Default stack of 1,000 Substances or 8 Products&#xA;&lt;TECHNOLOGY&gt;Restricted&lt;&gt;: Default stack of 500 Substances or 5 Products&#xA;&lt;FUEL&gt;Harsh&lt;&gt;: Default stack of 300 Substances or 3 Products&#xA;&#xA;&lt;FUEL&gt;NOTE&lt;&gt;: When changing from a larger to a smaller stacksize, you will lose some items in any stacks which are currently larger than the new stack limit]]

InvStackLimitEasy =
[[Spacious]]		--Standard

RepAndStandingDesc =
[[&lt;SPECIAL&gt;Standing&lt;&gt; is a measure of your reputation with the aliens factions that populate the galaxy. Higher standing will offer greater opportunities, such as available missions.&#xA;&#xA;This setting scales how quickly standing is gained by impressing a faction. It does not impact how quickly standing is lost.&#xA;&#xA;&lt;HIGHLIGHT&gt;Very Fast&lt;&gt;: 400% Standing and Reputation Gains&#xA;&lt;TRADE&gt;Fast&lt;&gt;: 200% Standing and Reputation Gains&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 100% Standing and Reputation Gains&#xA;&lt;FUEL&gt;Challenging&lt;&gt;: 50% Standing and Reputation Gains]]

FishTimingDesc =
[[This setting increases or decreases the length of time in which to react to a &lt;STELLAR&gt;fish biting on your line&lt;&gt;.&#xA;&#xA;&lt;HIGHLIGHT&gt;Auto-Catch&lt;&gt;: Will automatically snare any fish that bites without requiring any additional button presses or timing.&#xA;&lt;TRADE&gt;Relaxed&lt;&gt;: 3 second window.&#xA;&lt;TECHNOLOGY&gt;Standard&lt;&gt;: 1 second window.&#xA;&lt;FUEL&gt;Challenging&lt;&gt;: 0.67 second window.]]

SettlementRate =
[[%NUM% every 6 hours]]

SalvageConfirm =
[[&lt;FUEL&gt;WARNING:&lt;&gt; starship '&lt;STELLAR&gt;%SHIPNAME%&lt;&gt;' will be destroyed along with all cargo.&lt;NEWLINE&gt;Select desired &lt;TECHNOLOGY&gt;customisation module&lt;&gt; to confirm salvage operation...&lt;NEWLINE&gt;Does not work on &lt;FUEL&gt;Living&lt;&gt; or &lt;FUEL&gt;Interceptor&lt;&gt; starships]]

SalvageAttempt =
[[Attempt to extract Reactor]]

SalvageEngine =
[[Salvage Engines + Reactor]]

SalvageWings =
[[Salvage Wings + Reactor]]

SalvageLWing =
[[Salvage Left Wing + Reactor]]

SalvageRWing =
[[Salvage Right Wing + Reactor]]

SalvageHull =
[[Salvage Hull + Reactor]]

SalvageCockpit =
[[Salvage Cockpit + Reactor]]

SalvageSails =
[[Salvage Sails + Reactor]]

UI_DIFFICULTY_DIFFICULTY_DESC =
[[Most difficulty settings can be changed at any time, as often as you wish.&#xA;&#xA;Some settings can only be changed before starting a new game. Select &quot;Custom&quot; when choosing a new game to fully customise these settings.&#xA;&#xA;Note that difficulty cannot be changed while a multiplayer mission is active.&#xA;&#xA;&lt;HIGHLIGHT&gt;Survival&lt;&gt;: The default PTSd experience&#xA;&#xA;&lt;TECHNOLOGY&gt;Normal&lt;&gt;: PTSd Lite, with key things such as damage and hazards reduced&#xA;&#xA;&lt;TRADE&gt;Relaxed&lt;&gt;: Closer to the vanilla level of challenge but still with the PTSd rebalancing of rewards, starships, weapons, etc.&#xA;&#xA;&lt;FUEL&gt;Permadeath&lt;&gt;: Periodic backups recommended in case of unexpected deaths from mod-glitches]]

GAMEMODE_SURVIVAL_SUBTITLE =
[[A survival challenge: the default PTSd experience intended to be challenging but generally fair]]

GAMEMODE_SURVIVAL_SUB_SHORT =
[[A survival challenge: the default PTSd experience]]

GAMEMODE_NORMAL_SUBTITLE =
[[An infinite journey: PTSd Lite, with key things such as damage and hazard reduced. Explore and survive in a boundless universe]]

GAMEMODE_NORMAL_SUB_SHORT =
[[An infinite journey: PTSd Lite]]

GAMEMODE_RELAXED_SUBTITLE =
[[A streamlined experience: fewer systems to manage, lower costs, closer to the vanilla level of challenge but still with the PTSd rebalancing of rewards, etc.]]

GAMEMODE_PERMADEATH_SUBTITLE =
[[Extreme survival challenge: save is wiped upon death. Recommended to make periodic backups in case of deaths due to unexpected or glitched modded behavior]]

GAMEMODE_PERMADEATH_SUB_SHORT =
[[Extreme survival challenge: Periodic backups recommended]]

AresTradeItem4 = "Glowing Minerals"

AresTradeItem6 = "Pirate Transponders"

function AresTradeOffer (ItemName)
    return
[[Traveller hopes to make progress. Traveller tests themselves. I will help. An exchange. Progress for progress.&#xA;Or wealth, perhaps. Experience or materials. Both valid. Today... &lt;STELLAR&gt;]]..ItemName..[[&lt;&gt;.]]
end

function AppendText (Text)
    return
[[{:}]]..Text..[[]]
end

SettleExpedNote = [[ &lt;HIGHLIGHT&gt;NOTE&lt;&gt;: Expeditions usually &lt;TRADE&gt;increase&lt;&gt; settlement &lt;STELLAR&gt;population&lt;&gt; on average.]]

NaniteRefineItem = [[&#xA;&#xA;Can be processed into &lt;STELLAR&gt;nanites&lt;&gt; in a refiner]]

SalDataRefineItem = [[, or refined together with Microprocessors to create &lt;TECHNOLOGY&gt;Salvaged Data&lt;&gt;.]]

SpaceGunkRefineItem = [[&#xA;&#xA;Processing in a refiner could eventually result in something &lt;STELLAR&gt;more useful&lt;&gt;...]]

NaniteRefineItemDescs =
{
	{
		{1},		--"LANGUAGE\\NMS_LOC1_ENGLISH.MBIN",
		{"SUB_DEADDRONE_DESC", }
	},
	{
		{2},		--"LANGUAGE\\NMS_LOC4_ENGLISH.MBIN",
		{"BP_SALVAGE_DESC", "UI_QUAD_PROD_DESC", "UI_WALKER_PROD_DESC", "UI_ASTEROID3_DESC", "UI_FIENDCORE_DESC", "UI_FISHCORE_DESC", }
	},
	{
		{4},		--"LANGUAGE\\NMS_LOC6_ENGLISH.MBIN",
		{"UI_AF_METAL_DESC", }
	},
	{
		{5},		--"LANGUAGE\\NMS_LOC7_ENGLISH.MBIN",
		{"UI_MECH_PROD_DESC", "UI_WORMCORE_DESC", "UI_WORMPROD_DESC", }
	},
	{
		{6},		--"LANGUAGE\\NMS_LOC8_ENGLISH.MBIN",
		{"UI_SPIDER_PROD_DESC", "UI_DRONE_SALVAGE_DESC", "UI_DRONE_SHARD_DESC", "UI_SHIP_BRAIN_DESC", }
	},
	{
		{8},		--"LANGUAGE\\NMS_UPDATE3_ENGLISH.MBIN",
		{"UI_NAV_DATA_DESC", "UI_NAV_DROPPOD_DESC", "UI_MAINTAIN_SUB2_DESC", }
	},
}

SalDataRefineItemDescs =
{
	{
		{2},		--"LANGUAGE\\NMS_LOC4_ENGLISH.MBIN",
		{"UI_QUAD_PROD_DESC", "UI_WALKER_PROD_DESC", "UI_FIENDCORE_DESC", "UI_FISHCORE_DESC", }
	},
	{
		{4},		--"LANGUAGE\\NMS_LOC6_ENGLISH.MBIN",
		{"UI_AF_METAL_DESC", }
	},
	{
		{5},		--"LANGUAGE\\NMS_LOC7_ENGLISH.MBIN",
		{"UI_MECH_PROD_DESC", "UI_WORMCORE_DESC", "UI_WORMPROD_DESC", }
	},
	{
		{6},		--"LANGUAGE\\NMS_LOC8_ENGLISH.MBIN",
		{"UI_SPIDER_PROD_DESC", "UI_DRONE_SALVAGE_DESC", "UI_DRONE_SHARD_DESC", "UI_SHIP_BRAIN_DESC", }
	},
	{
		{8},		--"LANGUAGE\\NMS_UPDATE3_ENGLISH.MBIN",
		{"UI_NAV_DATA_DESC", "UI_NAV_DROPPOD_DESC", "UI_MAINTAIN_SUB2_DESC", }
	},
}

SpaceGunkRefineItemDescs =
{
	{
		{8},		--"LANGUAGE\\NMS_UPDATE3_ENGLISH.MBIN",
		{"UI_MAINTAIN_SUB1_DESC", "UI_MAINTAIN_SUB4_DESC", "UI_MAINTAIN_SUB5_DESC", "UI_MAINTAIN_SUB3_DESC", }
	},
}

NMS_MOD_DEFINITION_CONTAINER = 
{
	["MOD_FILENAME"]		= ModName..GameVersion..".pak",
	["MOD_DESCRIPTION"]		= Description,
	["MOD_AUTHOR"]			= "Xen0nex",
	["NMS_VERSION"]			= GameVersion,   
    ["MODIFICATIONS"] 		= 
    {
	    {
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= {"LANGUAGE\\NMS_LOC1_ENGLISH.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SCANBINOC1_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AnalysisVisorDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "LASER_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", MiningBeamDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SHIPLAS1_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", PhaseBeamDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SHIPGUN1_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", PhotonCannonDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SHIPSHOTGUN_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", PositronEjectorDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "BOLT_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", BoltcasterDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "ALL_FREIGHTER_RES_1"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", FreeFreighterOffer}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "ALL_FREIGHTER_OPT_1"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", FreeFreighterSelect}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "ALL_FAC_REWARD_OPT_A"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ManufacturingFacNanites}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "BLD_HARVESTER_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AMUDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "ACCESS2_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AtlasPass2Desc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "ACCESS3_DESCRIPTION"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AtlasPass3Desc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "NEWPROD14_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", PearlDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "NEWPROD13_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GravDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "NEWPROD12_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", VenomDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "PLANT_PEARL_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", PearlTime}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "PLANT_NIP_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", NipNipTime}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "GAMEMODE_SURVIVAL_SUBTITLE"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GAMEMODE_SURVIVAL_SUBTITLE}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "GAMEMODE_SURVIVAL_SUB_SHORT"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GAMEMODE_SURVIVAL_SUB_SHORT}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "GAMEMODE_NORMAL_SUBTITLE"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GAMEMODE_NORMAL_SUBTITLE}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "GAMEMODE_NORMAL_SUB_SHORT"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GAMEMODE_NORMAL_SUB_SHORT}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "GAMEMODE_PERMADEATH_SUBTITLE"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GAMEMODE_PERMADEATH_SUBTITLE}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "GAMEMODE_PERMADEATH_SUB_SHORT"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GAMEMODE_PERMADEATH_SUB_SHORT}
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"LANGUAGE\\NMS_LOC4_ENGLISH.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SUB_BINOCS_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", BasicSonarDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "VEHICLE_SUBSCAN"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", Sonar}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "QUICK_MENU_SUB_RADAR"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SonarQuickMenu}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "QUICK_MENU_SUB_RADAR_MISSING"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SonarQuickMenuFail}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_WATERMISSION3_MSG4"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DreamsDeep3Msg4}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_WATERMISSION3_OBJ3_TIP"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DreamsDeep3Obj3Tip}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "O2_HARVESTER_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", OxygenHarvesterDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "DOOR_ARMOUR"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ReinforcedDoor}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_CARGO_POD_NAME"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", CargoPod}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UT_ROCKETS_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", LargeRocketTubesDesc}
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"LANGUAGE\\NMS_LOC5_ENGLISH.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "BLD_ANTIMATTER_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AntimatterReactorDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "NPC_NEXUSMILES_LANG_4"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AresTradeOffer (AresTradeItem4)}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "NPC_NEXUSMILES_LANG_6"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AresTradeOffer (AresTradeItem6)}
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"LANGUAGE\\NMS_LOC6_ENGLISH.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_BIO_SHIP_MISSION1_MSG2B"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ConsciousnessBridgeMissionHint}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ABAND_LOCATOR_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ESSDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ABAND_FREIGHT_OBJ4_TIP"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DerelictLootTip}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ABAND_FREIGHT_MSG7"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DerelictCrewPopup}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ABAND_FREIGHT_MSG9"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DerelictLogPopup}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SHIPLAS1_ALIEN_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GraftedEyesDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SOUL_LASER_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AnimusBeamDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_LAVA1_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", BasaltDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ABAND_END_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DerelictEndDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ABAND_END_OPTA"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DerelictTech}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ABAND_END_OPTC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DerelictNanites}
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"LANGUAGE\\NMS_LOC7_ENGLISH.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_CARGO_S_ALIEN_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", NeuralShieldDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SCAN_BLOCKER_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", CargoScanDefDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "BLD_FRE_ROOM_SCAN_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ScannerRoomDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "MP_HIVE_LANG"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SentPillarLeftPane}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SENTINEL_HIVE_SETUP_LANG"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SentPillarLeftPane}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SETTLEMENT_PROD_RATE_NUM"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SettlementRate}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SOLAR_SAIL_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", VesperSailDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "HAZARD_DRAIN_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SurvivalDiffDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "RUNNING_DRAINS_STAMINA_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SprintingDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SUBSTANCE_COLLECTION_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", NatResourcesDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "CHARGING_REQUIREMENTS_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", FuelUsageDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SCANNER_RECHARGE_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ScanRechargeDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "CURRENCY_COST_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", CurrencyCostDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "DAMAGE_RECEIVED_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DamageLevelsDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "DAMAGE_GIVEN_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", EnemyStrengthDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "GROUND_COMBAT_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GroundCombatDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SPACE_COMBAT_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SpaceCombatDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "EXTRA_TECH_DAMAGE_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", TechDamageDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "DEATH_CONSEQUENCES_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DeathConsequencesDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "ITEM_SHOP_AVAILABILTY_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GoodsAvailableDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "INVENTORY_STACK_LIMITS_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", InvStackLimitDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "INV_SIZE_EASY"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", InvStackLimitEasy}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "REPUTATION_GAIN_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", RepAndStandingDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_DIFFICULTY_DIFFICULTY_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", UI_DIFFICULTY_DIFFICULTY_DESC}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "GAMEMODE_RELAXED_SUBTITLE"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GAMEMODE_RELAXED_SUBTITLE}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_JUDGEMENT_MISSION_DETAIL%d*"},
							["REPLACE_TYPE"] = "ALL",
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AppendText (SettleExpedNote)}
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"LANGUAGE\\NMS_LOC8_ENGLISH.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SENT_LASER_NAME_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", HijackedLaserDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ATLAS_LASER_NAME_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", RunicLensDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SCANBINOC1_DESCRIPTION_VR"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AnalysisVisorDescVR}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SLOT_PURCHASE_SUB"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", BuyNewSlot}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SLOT_PURCHASE_SUB_NUM"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", BuyNewSlotMP}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "FLEET_UI_PIRATE_SHIP_TITLE_C"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", PirateFrigate}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_BATTLE_BAR_SHIELD_HINT"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DreadnoughtHUDHint}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PIRATE_FREI_MSG7"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DreadnoughtSurrenderFull}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_BATTLE_BAR_DEFEAT_HINT"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DreadnoughtBoardDestroy}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PIRATE_FREI_BIG_TURRET"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AntiFreightCannon}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_ENGINE_TARGET_NAME"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", FreightWarpDrives}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SHIELD_GENERATOR_NAME"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", FreighterShieldGen}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PIR_SURRENDER_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DreadnoughtCaptain}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PIR_SURRENDER_OPT_A"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DreadnoughtSeize}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PIR_SURRENDER_OPT_B"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DreadnoughtTribute}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_SALVAGE_PROD_CONFIRM_LANG"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageConfirm}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_COST_NO_SALVAGE_PRODS"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageAttempt}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_COST_SALVAGE_PRODS_ENG"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageEngine}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_COST_SALVAGE_PRODS_WING"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageWings}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_COST_SALVAGE_PRODS_WING_L"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageLWing}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_COST_SALVAGE_PRODS_WING_R"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageRWing}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_COST_SALVAGE_PRODS_HULL"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageHull}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_COST_SALVAGE_PRODS_COCK"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageCockpit}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_COST_SALVAGE_PRODS_SAIL"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SalvageSails}
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"LANGUAGE\\NMS_LOC9_ENGLISH.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_RELEASE_FISH_LABEL"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ReleaseFish}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_RELEASE_FISH_LABEL_SUB"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ReleaseFishDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "FISHING_CATCH_WINDOW_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", FishTimingDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_FISH_BAIT_1_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", Mealworms}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_FISH_BAIT_2_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", SpicyChum}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_FISH_BAIT_3_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", BionicLure}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_FISH_BAIT_DAY_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", DanglingOrb}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_FISH_BAIT_NIGHT_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", ShadowLure}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_FISH_BAIT_STORM_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", MagpulseLure}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "BLD_SEAHARVESTER_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AutoTrapDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "BLD_SEAHARVESTER_DESC_ALT"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AutoTrapAltDesc}
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"LANGUAGE\\NMS_UPDATE3_ENGLISH.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "RGB_WARP_2_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", EmerilDriveDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "RGB_WARP_3_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", IndiumDriveDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "BLD_GASHARVESTER_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", AtmosphereHarvesterDesc}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PLANTPROD_NIP_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", NipNipTime}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PLANT_11_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", NipNipTime}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PLANT_12_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", VenomTime}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_PLANT_13_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", GravTime}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "SHIP_TELEPORT_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", TeleportReceiver}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "NPC_CORE_ACT1_15_DESC"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", LeapDark3rdMonolith}
							}
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Id", "UI_CORE_ACT1_STEP13_OBJ4_TIP"},
							["VALUE_CHANGE_TABLE"] 	=
							{
								{"English", LeapDarkAfter3rdMonolithTip}
							}
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {"UI\BUYSCREEN.MBIN"},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["SPECIAL_KEY_WORDS"] = {"ID", "BUY_SLOT_SUB"},
							["REPLACE_TYPE"] 		= "ALL",
							["SECTION_UP"] = 1,
							["VALUE_CHANGE_TABLE"] 	=
							{
								--{"AllowScroll", "False"},		--"True"
								{"IsParagraph", "True"},		--"False"
								{"AnimTime", "3"}				--"0.5"
							}
						},
					}
				},
            }
		}
    }
}

--local ChangesToLOC1 = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][1]["EXML_CHANGE_TABLE"]
--local ChangesToLOC4 = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][2]["EXML_CHANGE_TABLE"]
--local ChangesToLOC5 = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][3]["EXML_CHANGE_TABLE"]
--local ChangesToLOC6 = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][4]["EXML_CHANGE_TABLE"]
--local ChangesToLOC7 = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][5]["EXML_CHANGE_TABLE"]
--local ChangesToLOC8 = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][6]["EXML_CHANGE_TABLE"]
--local ChangesToLOC9 = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][7]["EXML_CHANGE_TABLE"]
--local ChangesToUPDATE3 = NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][8]["EXML_CHANGE_TABLE"]

for i = 1, #NaniteRefineItemDescs do
	local ChangeTableNum = NaniteRefineItemDescs[i][1][1]
	local Descs = NaniteRefineItemDescs[i][2]
			
		for j = 1, #Descs do
			DescId = Descs[j]
			Text = [[{:}]]..NaniteRefineItem..[[]]
		
			NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][ChangeTableNum]["EXML_CHANGE_TABLE"][#NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][ChangeTableNum]["EXML_CHANGE_TABLE"]+1] =
			{
				["SPECIAL_KEY_WORDS"] = {"Id", DescId},
				["VALUE_CHANGE_TABLE"] 	=
				{
					{"English", Text}
				}
			}
		end
end

for i = 1, #SalDataRefineItemDescs do
	local ChangeTableNum = SalDataRefineItemDescs[i][1][1]
	local Descs = SalDataRefineItemDescs[i][2]
			
		for j = 1, #Descs do
			DescId = Descs[j]
			Text = [[{:}]]..SalDataRefineItem..[[]]
		
			NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][ChangeTableNum]["EXML_CHANGE_TABLE"][#NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][ChangeTableNum]["EXML_CHANGE_TABLE"]+1] =
			{
				["SPECIAL_KEY_WORDS"] = {"Id", DescId},
				["VALUE_CHANGE_TABLE"] 	=
				{
					{"English", Text}
				}
			}
		end
end

for i = 1, #SpaceGunkRefineItemDescs do
	local ChangeTableNum = SpaceGunkRefineItemDescs[i][1][1]
	local Descs = SpaceGunkRefineItemDescs[i][2]
			
		for j = 1, #Descs do
			DescId = Descs[j]
			Text = [[{:}]]..SpaceGunkRefineItem..[[]]
		
			NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][ChangeTableNum]["EXML_CHANGE_TABLE"][#NMS_MOD_DEFINITION_CONTAINER["MODIFICATIONS"][1]["MBIN_CHANGE_TABLE"][ChangeTableNum]["EXML_CHANGE_TABLE"]+1] =
			{
				["SPECIAL_KEY_WORDS"] = {"Id", DescId},
				["VALUE_CHANGE_TABLE"] 	=
				{
					{"English", Text}
				}
			}
		end
end

