-- ************************************************************************************************************
-- If you only have that .lua file, download the RGOG at https://www.nexusmods.com/nomanssky/mods/2578 in order to update the mod
--
-- REDMAS GAME OVERHAUL BUILDER is a .lua script that allows to,
-- using AMUMSS created by Mjstral,
-- generate / update / modify easily, every single mod that i've done
-- + Easy to tweak at your own taste. -- If you use this tool to create your mods, credits will be highly appreciated.
-- It looks like it is lot of of works, but reality is x100000000 times worst.
-- ***********************************************************************************************************
-- -----------------------------------------------------------------------------------------------------------
-- -----------------------------------------------------------------------------------------------------------
-- ------------------You can configure the overhaul from the following VARs-------------------------------- --
--------------------------------------------------------------------------------------------------------------
-- -----------------------------------------------------------------------------------------------------------
-- Main Features enabler -- ----------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
DAY_ONE_MODE = "OFF"--( put "ON" the day one of a big vanilla update while mbincompiler is being updated to disable some features
PERFORMANCE_MODE = "OFF" --( Putting ON will reduce CPU-DEMANDING FEATURES )
MULTIPLAYER_MODE = "OFF" --( Put On if you play heavily in Multiplayer )
----------------------------------------------------------------------------------
-------------------------------------------------------------------------------------
INIT = "INSTANT_MINING_PRESET"
-- presets list ( make sure to edit the preset selected by the "INIT" var )
------------------------------------
-- EUPHORIA_PRESET
-- SCIFI_PRESET
-- SCIFI_FANTASY_PRESET
-------------------------------
-- CUSTOM_PRESET
-- TEST_PRESET
---------------------------------
-- REDMAS_CHALLENGE_MODE_PRESET
-- REDMAS_NEW_GAME_BONUSES_PRESET
-- REDMAS_START_AS_PRESET
-- REDMAS_SPACE_OVERHAUL_PRESET
-- REDMAS_SPACESHIPS_GENERATION_PRESET
-- REDMAS_E3PIC_FANTASY_PRESET
-- REDMAS_EASY_MODE_PRESET
-- REDMAS_SANDWORM_OVERHAUL_PRESET
-- REDMAS_SPAWNER_FOR_CONSTRUCTS_BY_MSSP_PRESET
-- REDMAS_EXTREME_FANTASY_TERRAIN_PRESET
-- REDMAS_VISUAL_OVERHAUL_PRESET
-- REDMAS_SUPER_VEHICLES_PRESET
-- REDMAS_CAMERA_OVERHAUL_PRESET
-- REDMAS_MENU_REVISION_PRESET
-- NEW_GAMEPLAY_MECHANICS_PRESET
-- PLAYER_GAMEPLAY_REVISION_PRESET
-- INSTANT_MINING_PRESET
-- METAL_SPACESHIPS_PRESET
-- DARKSPACE_COLORS_PRESET
-- REDMAS_PROCEDURAL_SPACE_CRASH_MISSION_PRESET