NMS_MOD_DEFINITION_CONTAINER = {
  MODIFICATIONS = {
    {
      MBIN_CHANGE_TABLE = {
        {
          MBIN_FILE_SOURCE = {
            'GCAISPACESHIPGLOBALS.GLOBAL.MBIN',
            'GCBUILDINGGLOBALS.GLOBAL.MBIN',
            'GCCAMERAGLOBALS.GLOBAL.MBIN',
            'GCCREATUREGLOBALS.MBIN',
            'GCDEBUGOPTIONS.GLOBAL.MBIN',
            'GCENVIRONMENTGLOBALS.GLOBAL.MBIN',
            'GCGALAXYGLOBALS.GLOBAL.MBIN',
            'GCGAMEPLAYGLOBALS.GLOBAL.MBIN',
            'GCPLAYERGLOBALS.GLOBAL.MBIN',
            'GCSKYGLOBALS.GLOBALS.MBIN',
            'GCSOLARGENERATIONGLOBALS.GLOBAL.MBIN',
            'GCSPACESHIPGLOBALS.GLOBAL.MBIN',
            'GCUIGLOBALS.GLOBAL.MBIN',
            'GCVEHICLEGLOBALS.GLOBAL.MBIN',
            'GCCHARACTERGLOBALS.GLOBAL.MBIN',
            'GCWATERGLOBALS.GLOBAL.MBIN',
          },
        },
      },
    },
  },
  MOD_DESCRIPTION = 'Testing used mbins compilation without value changes',
  MOD_FILENAME = 'Test used GLOBALS.pak',
}