NMS_MOD_DEFINITION_CONTAINER = {
  MODIFICATIONS = {
    {
      MBIN_CHANGE_TABLE = {
        {
          MBIN_FILE_SOURCE = {
            'METADATA/REALITY/TABLES/BASEBUILDINGPARTSTABLE.MBIN',
            'METADATA/REALITY/TABLES/BASEBUILDINGOBJECTSTABLE.MBIN',
            'METADATA/REALITY/TABLES/DAMAGETABLE.MBIN',
            'METADATA/PROJECTILES/PROJECTILETABLE.MBIN',
            'METADATA/REALITY/TABLES/NMS_DIALOG_GCALIENPUZZLETABLE.MBIN',
            'METADATA/REALITY/TABLES/NMS_REALITY_GCPROCEDURALTECHNOLOGYTABLE.MBIN',
            'METADATA/REALITY/TABLES/NMS_REALITY_GCPRODUCTTABLE.MBIN',
            'METADATA/REALITY/TABLES/NMS_REALITY_GCRECIPETABLE.MBIN',
            'METADATA/REALITY/TABLES/REWARDTABLE.MBIN',
            'METADATA/REALITY/TABLES/NMS_REALITY_GCTECHNOLOGYTABLE.MBIN',
            'METADATA/REALITY/TABLES/UNLOCKABLEITEMTREES.MBIN',
            'METADATA/REALITY/TABLES/CONSUMABLEITEMTABLE.MBIN',
            'METADATA/REALITY/TABLES/INVENTORYTABLE.MBIN',
            'METADATA/REALITY/TABLES/COSTTABLE.MBIN',
          },
        },
      },
    },
  },
  MOD_FILENAME = 'Test used TABLES.pak',
  MOD_DESCRIPTION = 'Testing used mbins compilation without value changes',
}