NMS_MOD_DEFINITION_CONTAINER = {
  MODIFICATIONS = {
    {
      MBIN_CHANGE_TABLE = {
        {
          MBIN_FILE_SOURCE = {
            'TEXTURES/COMMON/DECALS/RECTANGLE/RECTANGLE.TEXTURE.MBIN',
            'TEXTURES/SPACE/SPACESTATION/DECALS/NUMBER.TEXTURE.MBIN',
            'TEXTURES/COMMON/DECALS/LOGO/LOGO.TEXTURE.MBIN',
            'TEXTURES/COMMON/WEAPONS/MULTITOOL/MULTITOOLGLOW.TEXTURE.MBIN',
            'TEXTURES/COMMON/DECALS/SMALLSIGN/SMALLSIGN.TEXTURE.MBIN',
            'TEXTURES/COMMON/SPACECRAFT/S-CLASS/ROYALSCLASS_TRIM.TEXTURE.MBIN',
            'TEXTURES/COMMON/DECALS/LETTERING/LETTERING.TEXTURE.MBIN',
            'TEXTURES/COMMON/ROBOTS/SENTINELTRIM.TEXTURE.MBIN',
            'TEXTURES/SPACE/SPACESTATION/DECALS/LETTERING.TEXTURE.MBIN',
            'TEXTURES/COMMON/DECALS/NUMBER/NUMBER.TEXTURE.MBIN',
          },
        },
      },
    },
  },
  MOD_FILENAME = 'Test used TEXTURES.pak',
  MOD_DESCRIPTION = 'Testing used mbins compilation without value changes',
}