NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= "No Speed Lines 303a.pak",
["MOD_DESCRIPTION"]	= "LUA Update of Paletizma's Clean Space",
["MOD_AUTHOR"]		= "Paletizma",
["NMS_VERSION"]		= "303",
["MODIFICATIONS"]	= {{
["MBIN_CHANGE_TABLE"] = {
	{["MBIN_FILE_SOURCE"] = "MODELS\EFFECTS\LINES\SPEEDLINEMATERIAL.MATERIAL.MBIN",
	["EXML_CHANGE_TABLE"] = {
		{["VALUE_CHANGE_TABLE"] = {
			{"Class", ""},
			}},
	}},
	{["MBIN_FILE_SOURCE"] = "MODELS\EFFECTS\LINES\SPEEDLINE2MATERIAL.MATERIAL.MBIN",
	["EXML_CHANGE_TABLE"] = {
		{["VALUE_CHANGE_TABLE"] = {
			{"Class", ""},
			}},
	}},
	{["MBIN_FILE_SOURCE"] = "MODELS\EFFECTS\LINES\SPEEDLINE3MATERIAL.MATERIAL.MBIN",
	["EXML_CHANGE_TABLE"] = {
		{["VALUE_CHANGE_TABLE"] = {
			{"Class", ""},
			}},
	}},
}}}}