NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_FILENAME"] 			= "", --please leave EMPTY, so that no pak is created
  ["MOD_DESCRIPTION"]		= "",
  ["MOD_AUTHOR"]				= "",
  ["NMS_VERSION"]				= "ALL",
  ["MODIFICATIONS"] 		=
	{
		{
			["MBIN_CHANGE_TABLE"] = 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= --add / delete any MBIN file below to suit your requirements
          {
            "GCAISPACESHIPGLOBALS.GLOBAL.MBIN",
            "GCATLASGLOBALS.GLOBAL.MBIN",
            "GCAUDIOGLOBALS.GLOBAL.MBIN",
            "GCBUILDINGGLOBALS.GLOBAL.MBIN",
            "GCCAMERAGLOBALS.GLOBAL.MBIN",
            "GCCHARACTERGLOBALS.GLOBAL.MBIN",
            "GCCREATUREGLOBALS.MBIN",
            "GCDEBUGOPTIONS.GLOBAL.MBIN",
            "GCENVIRONMENTGLOBALS.GLOBAL.MBIN",
            "GCFLEETGLOBALS.GLOBAL.MBIN",
            "GCGALAXYGLOBALS.GLOBAL.MBIN",
            "GCGAMEPLAYGLOBALS.GLOBAL.MBIN",
            "GCGRAPHICSGLOBALS.GLOBAL.MBIN",
            "GCMULTIPLAYERGLOBALS.GLOBAL.MBIN",
            "GCPLACEMENTGLOBALS.MBIN",
            "GCPLAYERGLOBALS.GLOBAL.MBIN",
            "GCRICHPRESENCEGLOBALS.MBIN",
            "GCROBOTGLOBALS.MBIN",
            "GCSCENEOPTIONS.GLOBAL.MBIN",
            "GCSCRATCHPADGLOBALS.GLOBAL.MBIN",
            "GCSIMULATIONGLOBALS.GLOBAL.MBIN",
            "GCSKYGLOBALS.GLOBALS.MBIN",
            "GCSMOKETESTOPTIONS.GLOBAL.MBIN",
            "GCSOLARGENERATIONGLOBALS.GLOBAL.MBIN",
            "GCSPACESHIPGLOBALS.GLOBAL.MBIN",
            "GCTERRAINGLOBALS.GLOBAL.MBIN",
            "GCUIGLOBALS.GLOBAL.MBIN",
            "GCVEHICLEGLOBALS.GLOBAL.MBIN",
            "GCWATERGLOBALS.GLOBAL.MBIN",
          },
				},
			}
		}, --0 global replacements
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE