SPEED_MULTIPLIER = 2

NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "Faster Mining.pak",
["MOD_AUTHOR"]				= "TheVoidKnight",
["MODIFICATIONS"] 			= 
	{
		{
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= 
					{
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\LARGECACTUS\ENTITIES\LARGECACTUS.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\MEDIUMCACTUS\ENTITIES\MEDIUMCACTUS.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\SMALLCACTUS\ENTITIES\SMALLCACTUS.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\PLANTS\THINBUSHTREE\ENTITIES\_CAC_1.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\ROCKS\LARGEROCK\ENTITIES\LARGEBARRENROCK.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\BARREN\ROCKS\MEDIUMROCK\ENTITIES\MEDIUMROCKBARREN.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\CAVE\SMALLPROP\SMALLGLOWPLANT\ENTITIES\_MEDPLANT_B.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTAL_LARGE\ENTITIES\CRYSTAL_LARGE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTAL_LARGE_CAVE\ENTITIES\CRYSTAL_LARGE_CAVE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTAL_LARGE_MOUNTAIN\ENTITIES\CRYSTAL_LARGE_MOUNTAIN.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTAL_LARGE_UNDERWATER\ENTITIES\CRYSTAL_LARGE_UNDERWATER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\LARGE\CRYSTALCUBE_LARGE\ENTITIES\CRYSTALCUBE_LARGE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\MEDIUM\CRYSTAL_MEDIUM\ENTITIES\CRYSTAL_MEDIUM.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\MEDIUM\CRYSTAL_MEDIUM_CAVE\ENTITIES\CRYSTAL_MEDIUM_CAVE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\MEDIUM\CRYSTAL_MEDIUM_MOUNTAIN\ENTITIES\CRYSTAL_MEDIUM_MOUNTAIN.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\MEDIUM\CRYSTAL_MEDIUM_UNDERWATER\ENTITIES\CRYSTAL_MEDIUM_UNDERWATER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\MEDIUM\CRYSTALCUBE_MEDIUM\ENTITIES\CRYSTAL_MEDIUM.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\MEDIUM\CRYSTALCUBE_MEDIUM\ENTITIES\CRYSTALCUBE_MEDIUM.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTAL_FRAGMENT\ENTITIES\SHARDS.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTAL_FRAGMENT_CAVE\ENTITIES\SHARDS_CAVE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTAL_FRAGMENT_MOUNTAIN\ENTITIES\SHARDS_MOUNTAIN.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTAL_FRAGMENT_UNDERWATER\ENTITIES\SHARDS_UNDERWATER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTAL_SMALL\ENTITIES\CYSTAL_SMALL.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTAL_SMALL_CAVE\ENTITIES\CYSTAL_SMALL_CAVE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTAL_SMALL_MOUNTAIN\ENTITIES\CYSTAL_SMALL_MOUNTAIN.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTAL_SMALL_UNDERWATER\ENTITIES\CYSTAL_SMALL_UNDERWATER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\CRYSTALS\SMALL\CRYSTALCUBE_SMALL\ENTITIES\CYSTALCUBE_SMALL.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\PLANTS\LARGEPLANT\ENTITIES\LARGEPLANT.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\PLANTS\MEDIUMBUSH\ENTITIES\_MEDIUMBUSH.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\PLANTS\MEDIUMPLANT\ENTITIES\MEDIUMPLANT.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\PLANTS\SMALLFLOWERS\ENTITIES\SMALLFLOWER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\PLANTS\SMALLPLANT\ENTITIES\SMALLPLANT.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\LARGEROCK\ENTITIES\LARGEROCK.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\LARGEROCK\ENTITIES\LARGEROCKWATER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\PROCSHAPE1\ENTITIES\_BASE_1.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKLARGE\ENTITIES\RESOURCEROCKLARGE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\LARGE\RESOURCEROCKSHARD\ENTITIES\RESOURCEROCKSHARD.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\MEDIUMROCK\ENTITIES\MEDIUMROCKCAVE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\MEDIUMROCK\ENTITIES\MEDIUMROCKSCAN.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\MEDIUMROCK\ENTITIES\MEDIUMROCKWATER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\MEDIUMROCK\ENTITIES\ROCKMEDIUM1.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\MEDIUM\RESOURCEROCK\ENTITIES\RESOURCEROCK.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\RESOURCESMALL\ENTITIES\RESOURCEROCKSMALL.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\ROCKS\SMALL\SMALLROCK\ENTITIES\SMALLROCK.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\COMMON\TREES\MEDIUMTREE1\ENTITIES\MEDIUMTREE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\ENTITIES\_LARGEROCK_A.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_A2.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_C.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\ENTITIES\_TRUNK_C2.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\ENTITIES\_MEDPLANT_D.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\ENTITIES\_SMALLPLANT_A.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\SCORCHED\LARGE\LARGEROCK\ENTITIES\LARGESCORCHROCK.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\SCORCHED\LARGE\LARGESPIRE\ENTITIES\LARGESPIRE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\SCORCHED\MEDIUM\MEDIUMROCK\ENTITIES\MEDIUMSCORCHROCK.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\SCORCHED\MEDIUM\MEDIUMSPIRE\ENTITIES\MEDIUMSPIRE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\SCORCHED\MEDIUM\VOLCANICPLANT\ENTITIES\SCORCHEDPLANT.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\SCORCHED\SMALL\SMALLSPIRE\ENTITIES\SMALLSPIRE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\TOXIC\LARGE\FUNGALTREE\ENTITIES\FUNGALTREE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\TOXIC\LARGE\LARGEBLOB\ENTITIES\LARGEBLOB.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\TOXIC\LARGE\SPONGE\ENTITIES\SPONGE.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\TOXIC\LARGE\TENDRIL\ENTITIES\_TENDRIL_1.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\TOXIC\LARGE\TENDRIL\ENTITIES\TENDRIL.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\UNDERWATER\LARGEPLANTS\ENTITIES\LARGEPLANTWATER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\UNDERWATER\MEDIUMPLANTS\ENTITIES\MEDIUMPLANTWATER.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\UNDERWATER\MEDIUMPLANTS\MEDIUIMGLOWPLANT\ENTITIES\_BASE_1.ENTITY.MBIN",
						"MODELS\PLANETS\BIOMES\UNDERWATER\SMALLPLANTS\ENTITIES\SMALLPLANTWATER.ENTITY.MBIN"
					},
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = "",
							["MATH_OPERATION"] 		= "/",
							["REPLACE_TYPE"] 		= "ALL",
							["VALUE_MATCH"] 		= "", 
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{ "Health",	SPEED_MULTIPLIER }
							}
						}
					}
				}
			}
		}, --66 global replacements
	}	
}
--NOTE: ANYTHING DOWN HERE IS IGNORED
--ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE