-----------------------------------------------
local desc = [[
  Remove bloom glow flag:: base parts, plants
]]---------------------------------------------

local exo  = 'MODELS/COMMON/VEHICLES/'
local base = 'MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/'
local farm = 'MODELS/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/'

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '__MODEL remove bloom glow.pak',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= '4.08',
	MOD_DESCRIPTION		= desc,
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE	= {
			exo..'BIKE/BIKEPRES/LIGHTS_ENGINEGLOW_MAT.MATERIAL.MBIN',
			exo..'BUGGY/BUGGYPRES/ENGINEGLOW_MAT.MATERIAL.MBIN',
			exo..'ROVER/ROVERPRES/ENGINEGLOW_MAT1.MATERIAL.MBIN',

			base..'DECORATION/TABLE2/LIGHTS1_MAT.MATERIAL.MBIN',
			base..'FOLIAGE/BEAMSTONE/LIGHTBEAM_MAT3.MATERIAL.MBIN',
			base..'FOLIAGE/STARJOINT/MSTRUCTURE_MAT.MATERIAL.MBIN',
			base..'FOLIAGE/WEIRDCUBE/CELLSCOLOURISABLE1.MATERIAL.MBIN',
			base..'FOLIAGE/WEIRDCUBE/CELLSCOLOURISABLE2.MATERIAL.MBIN',

			farm..'FARMLUSH/STARBULB_MAT.MATERIAL.MBIN',
			farm..'FARMRADIOACTIVE/FRUITGLOW_MAT.MATERIAL.MBIN',
			farm..'FARMSCORCHED/FRUITYELLOW_MAT.MATERIAL.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'MaterialFlag', '_F34_GLOW'},
				REMOVE				= 'Section'
			}
		}
	},
	{
		MBIN_FILE_SOURCE	= {
			farm..'FARMRADIOACTIVE/FRUITGLOW_MAT.MATERIAL.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'MaterialFlag', '_F07_UNLIT'},
				REMOVE				= 'Section'
			}
		}
	}
}}}}
