NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME = [[Test used E:\MODZ_stuff\NoMansSky\AMUMss_Scripts\GLOBALS.pak]],
	MOD_DESCRIPTION = [[Testing used mbins compilation without value changes]],
	MODIFICATIONS = {
		{
			MBIN_CHANGE_TABLE = {
				{
					MBIN_FILE_SOURCE = {
						[[GCAISPACESHIPGLOBALS.GLOBAL.MBIN]],
						[[GCBUILDINGGLOBALS.GLOBAL.MBIN]],
						[[GCCAMERAGLOBALS.GLOBAL.MBIN]],
						[[GCCREATUREGLOBALS.MBIN]],
						[[GCDEBUGOPTIONS.GLOBAL.MBIN]],
						[[GCENVIRONMENTGLOBALS.GLOBAL.MBIN]],
						[[GCGALAXYGLOBALS.GLOBAL.MBIN]],
						[[GCGAMEPLAYGLOBALS.GLOBAL.MBIN]],
						[[GCPLAYERGLOBALS.GLOBAL.MBIN]],
						[[GCSKYGLOBALS.GLOBALS.MBIN]],
						[[GCSOLARGENERATIONGLOBALS.GLOBAL.MBIN]],
						[[GCSPACESHIPGLOBALS.GLOBAL.MBIN]],
						[[GCUIGLOBALS.GLOBAL.MBIN]],
						[[GCVEHICLEGLOBALS.GLOBAL.MBIN]],
						[[GCCHARACTERGLOBALS.GLOBAL.MBIN]],
						[[GCFREIGHTERBASEGLOBALS.GLOBAL.MBIN]],
						[[GCTERRAINGLOBALS.GLOBAL.MBIN]],
						[[GCGRAPHICSGLOBALS.GLOBAL.MBIN]],
						[[GCWATERGLOBALS.GLOBAL.MBIN]],
						[[GCSIMULATIONGLOBALS.GLOBAL.MBIN]],
						[[GCROBOTGLOBALS.MBIN]],
					},
				},
			},
		},
	},
}