NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME = [[Test used E:\MODZ_stuff\NoMansSky\AMUMss_Scripts\TEXTURES.pak]],
	MOD_DESCRIPTION = [[Testing used mbins compilation without value changes]],
	MODIFICATIONS = {
		{
			MBIN_CHANGE_TABLE = {
				{
					MBIN_FILE_SOURCE = {
						[[TEXTURES/COMMON/ROBOTS/SENTINELTRIM.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/SPACECRAFT/S-CLASS/ROYALSCLASS_TRIM.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/DECALS/NUMBER/NUMBER.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/DECALS/LOGO/LOGO.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/SPACECRAFT/S-CLASS/PULSELINEENGINE.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/WEAPONS/MULTITOOL/MULTITOOLGLOW.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/DECALS/LETTERING/LETTERING.TEXTURE.MBIN]],
						[[TEXTURES/SPACE/SPACESTATION/DECALS/NUMBER.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/SPACECRAFT/S-CLASS/PULSELINES.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/SPACECRAFT/SHARED/COCKPITINTERIORS/PLASTICGRAIN.TEXTURE.MBIN]],
						[[TEXTURES/SPACE/SPACESTATION/DECALS/LETTERING.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/DECALS/RECTANGLE/RECTANGLE.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/DECALS/SMALLSIGN/SMALLSIGN.TEXTURE.MBIN]],
						[[TEXTURES/COMMON/ROBOTS/SENTINELPROC.TEXTURE.MBIN]],
					},
				},
			},
		},
	},
}