NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME = [[Test used E:\MODZ_stuff\NoMansSky\AMUMss_Scripts\UI.pak]],
	MOD_DESCRIPTION = [[Testing used mbins compilation without value changes]],
	MODIFICATIONS = {
		{
			MBIN_CHANGE_TABLE = {
				{
					MBIN_FILE_SOURCE = {
						[[UI/HUD/HUDNOTIFICATIONPANEL.MBIN]],
						[[UI/COMPONENTS/INVENTORY/SQU_INV_BOXTECH.MBIN]],
						[[UI/BUYSCREEN.MBIN]],
						[[UI/INVENTORYPAGE.MBIN]],
						[[UI/COMPONENTS/PAGESELECTBARSIDE.MBIN]],
						[[UI/COMPONENTS/INVENTORY/SQU_INV_BOXREGULAR.MBIN]],
						[[UI/HUD/SHIP/SIDESCREENSOLARSYSTEM.MBIN]],
						[[UI/COMPONENTS/INTERACTION/CINEMATICBARS.MBIN]],
						[[UI/INTERACTIONDIALOGPAGE.MBIN]],
						[[UI/COMPONENTS/RESPONDBUTTONSCROLL.MBIN]],
						[[UI/COMPONENTS/USERBAR.MBIN]],
						[[UI/HUD/HUDBARS.MBIN]],
						[[UI/COMPONENTS/INVENTORY/SQU_SLOT_ITEM.MBIN]],
					},
				},
			},
		},
	},
}