------------------------------------
dofile('LIB/lua_2_exml.lua')
dofile('LIB/scene_tools.lua')
------------------------------------

-- MODELS/SPACE/NEXUS/PARTS/PROPS/BOOK_1.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/CANNISTER.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/CANNISTERLARGE.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/CIRCUITBOX.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/CRATE.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/HARDDRIVE_1.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/HOVERTROLLEY.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/HOVERTROLLEY_CANNISTERS.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/LARGECANNISTER.SCENE.MBIN

-- MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/ROOFMONITOR/ROOFMONITOR.SCENE.MBIN
-- MODELS/SPACE/NEXUS/PARTS/PROPS/CRATE.SCENE.MBIN
-- MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/WALLMONITORS/WALLMONITORA.SCENE.MBIN
-- MODELS/SPACE/SPACESTATION/MODULARPARTS/DOCK/PIRATES/COVEREDSILOS.SCENE.MBIN
-- MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/DECORATION/BAZAAR/CRATE1.SCENE.MBIN
-- MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/DECORATION/BAZAAR/MILKCRATE.SCENE.MBIN
-- MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/DECORATION/BUILDERHEAD.SCENE.MBIN

local ECT = {}
ECT[#ECT+1] = {
	PRECEDING_KEY_WORDS = 'Children',
	ADD					= ToExml({
		ScNode('RefAdd1More01', 'REFERENCE', {
			ScTransform({tx=1.0, ty=1.0, tz=1.0, rx=0, ry=0, rz=0, sx=1.0, sy=1.0, sz=1.0}),
			ScAttributes({
				{'SCENEGRAPH', 'MODELS/SPACE/NEXUS/PARTS/PROPS/HOVERTROLLEY.SCENE.MBIN'}
			})
		}),

	})
}

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 			= '___TEST 01 add to scene.pak',
	MOD_AUTHOR				= 'lMonk',
	NMS_VERSION				= '4.52',
	GLOBAL_INTEGER_TO_FLOAT = 'Force',
	MODIFICATIONS 			= {{
	MBIN_CHANGE_TABLE		= {
	{
		MBIN_FILE_SOURCE	= 'MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/DECORATION/SIMPLEDESK.SCENE.MBIN',
		EXML_CHANGE_TABLE	= ECT
	}
}}}}
