NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]  = "Better Easier Frigate Repair",
["MOD_AUTHOR"]    = "Democrity & Babscoole",
["NMS_VERSION"]   = "6.18",
["MODIFICATIONS"] =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] = 
          {
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\CARGOBAY\ENTITIES\CARGOBAY.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\CARGOCONTAINER\ENTITIES\MAINTENANCEINTERACTION.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\ENGINEREACTOR\ENTITIES\MAINTENANCEINTERACTION.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\MAINBATTERY\ENTITIES\MAINTENANCEINTERACTION.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\MAINTENANCEPOINT\ENTITIES\MAINTENANCEPOINT.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\TORPEDOCONTAINER\ENTITIES\MAINTENANCEINTERACTION.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\TORPEDOCONTFRONTL\ENTITIES\MAINTENANCEINTERACTION.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\TORPEDOCONTFRONTR\ENTITIES\MAINTENANCEINTERACTION.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\INTERACTIONS\TORPEDOCONTBACKR\ENTITIES\MAINTENANCEINTERACTION.ENTITY.MBIN",
            "MODELS\COMMON\SPACECRAFT\FRIGATES\COMMONPARTS\SCENES\MAINBATTERY\ENTITIES\TURRET.ENTITY.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"Components", "GcMaintenanceComponentData"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"DamageStatus",             "Repaired"},
                {"CompletionRequirement",    "NoRequirement"},
                {"CompletedTransitionDelay", "0.2"},
              }
            },
          }
        },
        -- {
          -- ["MBIN_FILE_SOURCE"] = "GCFLEETGLOBALS.GLOBAL.MBIN",
          -- ["MXML_CHANGE_TABLE"] =
          -- {
            -- {
              -- ["VALUE_CHANGE_TABLE"] =
              -- {
                -- {"TimeTakenForExpeditionEvent_Easy", 0}, -- Original 900
                -- {"TimeTakenForExpeditionEvent",      0}, -- Original 5400
              -- }
            -- },
          -- }
        -- },
      }
    },
  }
}
