NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Cheaper Multitool and Ship Slot Upgrades",
["MOD_AUTHOR"]      = "Reikokuu & Babscoole",
["MOD_DESCRIPTION"] = "Changes the unit prices for each storage slot in multitool and ship upgrade terminals",
["NMS_VERSION"]     = "6.16",
["MODIFICATIONS"]   =
    {
        {
            ["MBIN_CHANGE_TABLE"] =
            {
                {
                    ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\COSTTABLE.MBIN",
                    ["MXML_CHANGE_TABLE"] =
                    {
                        {
                            ["SPECIAL_KEY_WORDS"] =
                            {
                                {"Id", "C_INV_WEAP_C"},  -- add new multitool dialogue option display price
                                {"Id", "C_INV_WEAP_CR"}, -- add new multitool menu prices
                            },
                            ["PRECEDING_KEY_WORDS"] = {"Costs"},
                            ["REPLACE_TYPE"] = "ONCEINSIDE",
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"Costs", "50000"},
                                {"Costs", "60000"},
                                {"Costs", "70000"},
                                {"Costs", "80000"},
                                {"Costs", "90000"},
                                {"Costs", "100000"},
                                {"Costs", "110000"},
                                {"Costs", "120000"},
                                {"Costs", "130000"},
                                {"Costs", "140000"},
                                {"Costs", "150000"},
                                {"Costs", "200000"},
                                {"Costs", "250000"},
                                {"Costs", "300000"},
                                {"Costs", "350000"},
                                {"Costs", "400000"},
                                {"Costs", "450000"},
                                {"Costs", "500000"},
                                {"Costs", "600000"},
                                {"Costs", "700000"},
                                {"Costs", "800000"},
                                {"Costs", "900000"},
                                {"Costs", "1000000"},
                                {"Costs", "1250000"},
                                {"Costs", "1500000"},
                                {"Costs", "1750000"},
                                {"Costs", "2000000"},
                                {"Costs", "2250000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                                {"Costs", "2500000"},
                            }
                        },
                        {
                            ["SPECIAL_KEY_WORDS"] =
                            {
                                {"Id", "C_INV_SAL_CASH"},  -- add new ship dialogue option display price
                                {"Id", "C_INV_SAL_CASHR"}, -- add new ship menu prices
                            },
                            ["PRECEDING_KEY_WORDS"] = {"Costs"},
                            ["REPLACE_TYPE"] = "ONCEINSIDE",
                            ["VALUE_CHANGE_TABLE"] =
                            {
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "100000"},
                                {"Costs", "200000"},
                                {"Costs", "300000"},
                                {"Costs", "400000"},
                                {"Costs", "500000"},
                                {"Costs", "600000"},
                                {"Costs", "700000"},
                                {"Costs", "800000"},
                                {"Costs", "900000"},
                                {"Costs", "1000000"},
                                {"Costs", "2000000"},
                                {"Costs", "3000000"},
                                {"Costs", "4000000"},
                                {"Costs", "5000000"},
                                {"Costs", "6000000"},
                                {"Costs", "7000000"},
                                {"Costs", "8000000"},
                                {"Costs", "9000000"},
                                {"Costs", "10000000"},
                                {"Costs", "11000000"},
                                {"Costs", "12000000"},
                                {"Costs", "13000000"},
                                {"Costs", "14000000"},
                                {"Costs", "15000000"},
                                {"Costs", "16000000"},
                                {"Costs", "17000000"},
                                {"Costs", "18000000"},
                                {"Costs", "19000000"},
                                {"Costs", "20000000"},
                                {"Costs", "21000000"},
                                {"Costs", "22000000"},
                                {"Costs", "23000000"},
                                {"Costs", "24000000"},
                                {"Costs", "25000000"},
                                {"Costs", "25000000"},
                                {"Costs", "25000000"},
                                {"Costs", "25000000"},
                                {"Costs", "25000000"},
                                {"Costs", "25000000"},
                            }
                        },
                    }
                },
            }
        },
    }
}