NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Goop Begone Abandoned",
["MOD_DESCRIPTION"] = "Remove trypophobia triggers from Abandoned buildings.",
["MOD_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "6.10",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_BARAABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_NPC_ABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_UNDERWATER1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_BASE1_ABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_RIGHTROOMABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\FLOORLAYOUT_NPC_ABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_LEFTROOMABANDONED.SCENE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "AlienProps"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\EXTLAYOUT_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\EXTLAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\EXTLAYOUT_ABANDONED3.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\EXTLAYOUT_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\EXTLAYOUT_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\EXTLAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\EXTLAYOUT_ABANDONED3.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\EXTLAYOUT_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\EXTLAYOUT_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\EXTLAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\EXTLAYOUT_ABANDONED3.SCENE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "AlienProps1_DUP"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_ABANDONED5.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_ABANDONED5.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_ABANDONED5.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED5.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_LEFTROOMABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_LEFTROOMCABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUTSHOP_1_ABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_BARAABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED5.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_LEFTROOMABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_LEFTROOMBABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_LEFTROOMCABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_UNDERWATER1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED5.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_LEFTROOMCABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_LEFTROOMBABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_RIGHTROOMABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_UNDERWATER1.SCENE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "InfectionProps"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\EXTLAYOUT_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\EXTLAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\EXTLAYOUT_ABANDONED3.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\EXTLAYOUT_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\EXTLAYOUT_ABANDONED1.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\EXTLAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\EXTLAYOUT_ABANDONED3.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\EXTLAYOUT_ABANDONED4.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\EXTLAYOUT_ABANDONED1.SCENE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "InfectionProps1"},
                {"Name", "InfectionProps2_DUP"},
                {"Name", "InfectionProps3_DUP"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\EXTLAYOUT_ABANDONED2.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\EXTLAYOUT_ABANDONED3.SCENE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "InfectionProps1"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUTSHOP_1_ABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUTSHOP_3_ABANDONED.SCENE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "pasted__InfectionProps"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_ABANDONED3.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_ABANDONED3.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUTSHOP_2_ABANDONED.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED3.SCENE.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_GENERIC_ABANDONED3.SCENE.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "InfectedProps"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\SCIENTIFICPARTS\LAYOUTS\LAYOUTSHOP_3_ABANDONED.SCENE.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "pasted__InfectedProps"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\WARRIORPARTS\LAYOUTS\LAYOUT_BARAABANDONED.SCENE.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "InfectionProps1_DUP"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\TRADERPARTS\LAYOUTS\LAYOUT_ABANDONED3.SCENE.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "polySurface43"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\COMMONPARTS\ABANDONEDTERMINAL.SCENE.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] =
              {
                {"Name", "_Flesh_2"},
                {"Name", "_Flesh_1"},
              },
              ["REPLACE_TYPE"] = "ALL",
              ["REMOVE"] = "SECTION"
            },
          },
        },
      },
    },
  },
}
