NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "No Interstellar Teleporters",
["MOD_DESCRIPTION"] = "No Interstellar Teleporters",
["MOD_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "6.18",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\COMMONPARTS\TELEPORTER_STATION\ENTITIES\TELEPORTERSTATIONINTERACTION.ENTITY.MBIN",
            "MODELS\SPACE\SPACESTATION\MODULARPARTSTYPEB\DOCK\TELEPORTERTYPEB\ENTITIES\STATIONTELEPORTERB.ENTITY.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\FREIGHTERBASE\ROOMS\TELEPOROOM\ENTITIES\TELEPORTERINTERACTION.ENTITY.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\COMMONPARTS\TELEPORTER\ENTITIES\TELEPORTERINTERACTION.ENTITY.MBIN",
            "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\COMMONPARTS\TELEPORTER_NEXUS\ENTITIES\TELEPORTERNEXUSINTERACTION.ENTITY.MBIN",
          },
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"Components", "GcInteractionComponentData"},
              ["REMOVE"] = "SECTION"
            },
						-- {
						  -- ["VALUE_CHANGE_TABLE"] = 
						  -- {
							  -- {"InteractDistance", "0"}, 
						  -- }	
						-- },
          },
        },
      },
    },
  },
}
