-- REWARD_ID    = "RS_S22_S3M4_G"
-- REWARD_ICON  = "TEXTURES/UI/FRONTEND/ICONS/SPECIALSHOP/EXPEDITION.S22.TROPHYG.DDS"
-- REWARD_TITLE = "PRISMATIC_CORE_G"
-- REWARD_ABBR  = "PCG"

NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "Prismatic Cores Restored",
["MOD_AUTHOR"]      = "Babscoole",
["NMS_VERSION"]     = "7.00-Cosmos",
["MOD_DESCRIPTION"] = "Restore the Red and Green Prismatic Cores back to the game",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"] =
          {
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\DARK_MAT1.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\DARK_MAT1.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\DARK_MAT2.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\DARK_MAT2.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\FLOOR1_MAT1.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\FLOOR1_MAT1.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\PIPE1_MAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\PIPE1_MAT.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\SWARMDRONEMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\SWARMDRONEMAT.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\SWARMDRONETROPHY.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\SWARMDRONETROPHY.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\SWARMHIVEMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\SWARMHIVEMAT.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\SWARMHIVEMAT1.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\SWARMHIVEMAT1.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\TRIMSHEETMETAL_MAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\TRIMSHEETMETAL_MAT.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\TRIMSHEETMETAL_MAT1.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\TRIMSHEETMETAL_MAT1.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\BLUEPANNINGMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\GREENTEAMPANNINGMAT.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\BLUESHIMMERMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\GREENTEAMSHIMMERMAT.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\BLUESTATICMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\GREENTEAMSTATICMAT.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\HOLORINGBLUE_MAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\HOLORINGGREEN_MAT.MATERIAL.MBIN",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\HOLORINGGLOWBLUE_MAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\HOLORINGGREENGLOW_MAT.MATERIAL.MBIN",},            
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\DARK_MAT1.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\DARK_MAT1.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\DARK_MAT2.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\DARK_MAT2.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\FLOOR1_MAT1.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\FLOOR1_MAT1.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\PIPE1_MAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\PIPE1_MAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\SWARMDRONEMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\SWARMDRONEMAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\SWARMDRONETROPHY.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\SWARMDRONETROPHY.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\SWARMHIVEMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\SWARMHIVEMAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\SWARMHIVEMAT1.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\SWARMHIVEMAT1.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\TRIMSHEETMETAL_MAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\TRIMSHEETMETAL_MAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\TRIMSHEETMETAL_MAT1.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\TRIMSHEETMETAL_MAT1.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\BLUEPANNINGMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\REDTEAMPANNINGMAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\BLUESHIMMERMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\REDTEAMSHIMMERMAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\BLUESTATICMAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\REDTEAMSTATICMAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\HOLORINGBLUE_MAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\HOLORINGRED_MAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE\HOLORINGGLOWBLUE_MAT.MATERIAL.MBIN", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\HOLORINGGLOWRED_MAT.MATERIAL.MBIN", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE.GEOMETRY.DATA.MBIN.PC", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN.GEOMETRY.DATA.MBIN.PC",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE.GEOMETRY.MBIN.PC", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN.GEOMETRY.MBIN.PC",},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE.GEOMETRY.DATA.MBIN.PC", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED.GEOMETRY.DATA.MBIN.PC", "REMOVE"},
            {"MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_BLUE.GEOMETRY.MBIN.PC", "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED.GEOMETRY.MBIN.PC", "REMOVE"},
          },
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\GREENTEAMPANNINGMAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "GreenTeamPanningMat"},
                {"Map",  "TEXTURES/SPACE/NEXUS/GREENGLOWFADE.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\GREENTEAMSHIMMERMAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "GreenTeamShimmerMat"},
                {"Map",  "TEXTURES/SPACE/NEXUS/SCROLLINGEFFECTGREEN.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\GREENTEAMSTATICMAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "GreenTeamStaticMat"},
                {"Map",  "TEXTURES/SPACE/NEXUS/GREENGLOWFADE.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\HOLORINGGREEN_MAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "HoloRingGreen_Mat"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Name", "gDiffuseMap"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Map", "TEXTURES/SPACE/NEXUS/SWARMTROPHY/HOLORINGGREEN.BASE.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_GREEN\HOLORINGGREENGLOW_MAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name",          "HoloRingGreenGlow_Mat"},
                {"Metamaterial",  "Models/Space/Nexus/Parts/CentralPoint/Parts/CP_Trophy/Materials/HoloRing_Mat.metamaterial.mXml"},
                {"MaterialClass", "DoublesidedAdditive"},
              }
            },
            {
              ["PRECEDING_KEY_WORDS"] = {"Flags"},
              ["ADD_OPTION"] = "ADDendSECTION", 
              ["ADD"] =
[[
		<Property name="Flags" value="TkMaterialFlags" _index="3">
			<Property name="MaterialFlag" value="_F36_DOUBLESIDED" />
		</Property>
]]
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Name", "gMaterialParams2Vec4"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"X", "0.600000"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Name", "gDynamicFlags"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"X", "1056768"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Name", "gDiffuseMap"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Map", "TEXTURES/SPACE/NEXUS/SWARMTROPHY/HOLORINGGREENGLOW.BASE.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\REDTEAMPANNINGMAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "RedTeamPanningMat"},
                {"Map",  "TEXTURES/SPACE/NEXUS/REDGLOWFADE.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\REDTEAMSHIMMERMAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "RedTeamShimmerMat"},
                {"Map",  "TEXTURES/SPACE/NEXUS/SCROLLINGEFFECTRED.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\REDTEAMSTATICMAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "RedTeamStaticMat"},
                {"Map",  "TEXTURES/SPACE/NEXUS/REDGLOWFADE.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\HOLORINGRED_MAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "HoloRingRed_Mat"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Name", "gDiffuseMap"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Map", "TEXTURES/SPACE/NEXUS/SWARMTROPHY/HOLORINGRED.BASE.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\DECORATION\SWARMTROPHY_RED\HOLORINGGLOWRED_MAT.MATERIAL.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Name", "HoloRingGlowRed_Mat"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"Name", "gDiffuseMap"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Map", "TEXTURES/SPACE/NEXUS/SWARMTROPHY/HOLORINGREDGLOW.BASE.DDS"},
              }
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\BASEBUILDINGOBJECTSTABLE.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "SWARM_TROPHY_B"},
              ["SEC_SAVE_TO"] = "ADD_BBOBJECTS",
            },
            {
              ["SEC_EDIT"] =  {"ADD_BBOBJECTS"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"ID",           "SWARM_TROPHY_R"},
                {"SinglePartID", "_SWARM_TROPHY_R"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "SWARM_TROPHY_B"},
              ["ADD_OPTION"] = "ADDafterSECTION",
              ["SEC_ADD_NAMED"] = "ADD_BBOBJECTS"
            },
            {
              ["SEC_EDIT"] =  {"ADD_BBOBJECTS"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"ID",           "SWARM_TROPHY_G"},
                {"SinglePartID", "_SWARM_TROPHY_G"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "SWARM_TROPHY_B"},
              ["ADD_OPTION"] = "ADDafterSECTION",
              ["SEC_ADD_NAMED"] = "ADD_BBOBJECTS"
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\BASEBUILDINGPARTSTABLE.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "_SWARM_TROPHY_B"},
              ["SEC_SAVE_TO"] = "ADD_BBPARTS",
            },
            {
              ["SEC_EDIT"] =  {"ADD_BBPARTS"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"ID",       "_SWARM_TROPHY_R"},
                {"Filename", "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/DECORATION/SWARMTROPHY_RED.SCENE.MBIN"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "_SWARM_TROPHY_B"},
              ["ADD_OPTION"] = "ADDafterSECTION",
              ["SEC_ADD_NAMED"] = "ADD_BBPARTS"
            },
            {
              ["SEC_EDIT"] =  {"ADD_BBPARTS"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"ID",       "_SWARM_TROPHY_G"},
                {"Filename", "MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/DECORATION/SWARMTROPHY_GREEN.SCENE.MBIN"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "_SWARM_TROPHY_B"},
              ["ADD_OPTION"] = "ADDafterSECTION",
              ["SEC_ADD_NAMED"] = "ADD_BBPARTS"
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\BASEBUILDINGAUTOGENERATEDPARTSDATA.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"PartID", "_SWARM_TROPHY_B"},
              ["SEC_SAVE_TO"] = "ADD_BBAUTOGENPARTS",
            },
            {
              ["SEC_EDIT"] =  {"ADD_BBAUTOGENPARTS"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"PartID", "_SWARM_TROPHY_R"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"PartID", "_SWARM_TROPHY_B"},
              ["ADD_OPTION"] = "ADDafterSECTION",
              ["SEC_ADD_NAMED"] = "ADD_BBAUTOGENPARTS"
            },
            {
              ["SEC_EDIT"] =  {"ADD_BBAUTOGENPARTS"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"PartID", "_SWARM_TROPHY_G"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"PartID", "_SWARM_TROPHY_B"},
              ["ADD_OPTION"] = "ADDafterSECTION",
              ["SEC_ADD_NAMED"] = "ADD_BBAUTOGENPARTS"
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "SWARM_TROPHY_B"},
              ["SEC_SAVE_TO"] = "ADD_GCPROD",
            },
            {
              ["SEC_EDIT"] =  {"ADD_GCPROD"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"ID", "SWARM_TROPHY_R"},
              }
            },
            {
              ["SEC_EDIT"] =  {"ADD_GCPROD"},
              ["SPECIAL_KEY_WORDS"] = {"Icon", "TkTextureResource"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Filename", "TEXTURES/UI/FRONTEND/ICONS/SPECIALSHOP/EXPEDITION.S22.TROPHYR.DDS"},
              }
            },
            {
              ["SEC_EDIT"] =  {"ADD_GCPROD"},
              ["SPECIAL_KEY_WORDS"] = {"HeroIcon", "TkTextureResource"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Filename", "TEXTURES/UI/FRONTEND/ICONS/SPECIALSHOP/HERO.S22.TROPHYR.DDS"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "SWARM_TROPHY_B"},
              ["ADD_OPTION"] = "ADDafterSECTION",
              ["SEC_ADD_NAMED"] = "ADD_GCPROD"
            },
            {
              ["SEC_EDIT"] =  {"ADD_GCPROD"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"ID", "SWARM_TROPHY_G"},
              }
            },
            {
              ["SEC_EDIT"] =  {"ADD_GCPROD"},
              ["SPECIAL_KEY_WORDS"] = {"Icon", "TkTextureResource"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Filename", "TEXTURES/UI/FRONTEND/ICONS/SPECIALSHOP/EXPEDITION.S22.TROPHYG.DDS"},
              }
            },
            {
              ["SEC_EDIT"] =  {"ADD_GCPROD"},
              ["SPECIAL_KEY_WORDS"] = {"HeroIcon", "TkTextureResource"},
              ["VALUE_CHANGE_TABLE"] =
              {
                {"Filename", "TEXTURES/UI/FRONTEND/ICONS/SPECIALSHOP/HERO.S22.TROPHYG.DDS"},
              }
            },
            {
              ["SPECIAL_KEY_WORDS"] = {"ID", "SWARM_TROPHY_B"},
              ["ADD_OPTION"] = "ADDafterSECTION",
              ["SEC_ADD_NAMED"] = "ADD_GCPROD"
            },
          }
        },
        {
          ["MBIN_FILE_SOURCE"] = "METADATA\GAMESTATE\DEFAULTSAVEDATA.MBIN",
          ["MXML_CHANGE_TABLE"] =
          {
            {
              ["PRECEDING_KEY_WORDS"] = {"KnownProducts"},
              ["ADD_OPTION"] = "ADDendSECTION",
              ["ADD"] =
[[
        <Property name="KnownProducts" value="SWARM_TROPHY_G" />
        <Property name="KnownProducts" value="SWARM_TROPHY_R" />
]]
            }
          }
        },
      }
    }
  }
}